### ISSUE TITLE
Create an embeddable version for event webpages

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#100]
Most ticketing softwares provide a way to integrate the ticket shop into an existing event website. This is a very useful thing and we want to support that too. There are generally two ways this can be done.

* Using a ``<iframe>`` that contains the whole shop. This is how [Eventbrite](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_US) and XING Events do it.
* Using a javascript widget that is embedded into the page. This is how [Tito](https://ti.to/docs/widget) does it. Their docs contain beautiful examples of it.

I think it is clear that the javascript approach looks *way* better than the iframe approach and allows the website owner to apply custom CSS to style the product list. However, there is a strong reason against copying Tito's behaviour: We'd need to maintain two complete sets of UI for all of the ordering process. We can't re-use the existing UI and we can't transform the existing UI to a JavaScript one because we're proud of the fact that pretix is completely usable even without JavaScript.

This leads to the following "middle-ground" suggestion:

1. Build a JavaScript widget that inserts a list of products into an arbitrary webpage that can be styled via custom CSS
2. Once a user clicks the "Add to cart" button, an overlay will be open (like a lightbox that covers e.g. 80-90% of the screen) that includes an ``<iframe>`` with the steps needed to complete the order.

This requires us only to maintain the list of products twice, not the entire process. Open questions:

* How does the order process end? Do we show the order confirmation inside the iframe? The problem with this is that this way, the user will not be seeing the URL in the address bar that they need later to return to the confirmation page (e.g. in case they don't get the email) and reloading the page is not really possible. I think the cleanest solution would be to solve this via the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and a custom thing like ``#pretix-order-ABCDE-secret`` appended to the address bar.
* How do we deal with mobile devices? Tito just opens the normal shop in a new tab for them which is a good behaviour I guess.

Current state: There is initial work in the ``embeddable`` branch that contains a dependency-free JavaScript snippet that shows part of the product list. It does not yet support variations, vouchers or free-price items; it doesn't have a default CSS style yet and it does not open the iframe popup yet. And it's probably not that well-written JS code yet ;)

**Comment by felixrindt** [comment]
Isn't this already implemented as seen on https://pretix.eu/about/en/features/shop ?

**Comment by raphaelm** [comment]
Yep, this is implemented by now :)

**Comment by felixrindt** [comment]
I think many feature idea issues (mostly really early ones like #48) have already been fixed. Maybe you should look through them and close them.
