### ISSUE TITLE
Widget: Option to Show all dates

### ISSUE THREAD

**Issue by hno2** [pretix/pretix#1005]
I'm not sure, wether this was addressed in another issue or not. 
As I understand you need to select on specific date when using the embedded widget.
What's the reason behind this? Or have I overlooked some hidden option?

**Comment by raphaelm** [comment]
> I'm not sure, wether this was addressed in another issue or not.

Yes, this is already open as issue #878  :)

> As I understand you need to select on specific date when using the embedded widget.
> What's the reason behind this? Or have I overlooked some hidden option?

The reason is, that we just haven't implemented the event selection yet (which is not that easy if we want to show a nice calendar as well).
