### ISSUE TITLE
New feature: order questions

### ISSUE THREAD

**Issue by MathyV** [pretix/pretix#1007]
Currently the questions are linked to a product, we would like the possibility to link it to an order, so that it is only asked once if someone buys multiple products at once.

Alternatively, a possibility to add a default, non-deletable product to a shopping cart would result in the same feature as you could link the question to that product.

**Comment by raphaelm** [comment]
I'm not convinced of this, since it adds a *lot* of complexity and I don't feel there is too much to gain. Can you comment a bit on the specific use case you are wanting this for?

**Comment by MathyV** [comment]
The use-case I'm looking at is a sponsor-event where people come over and have a meal. As such one person orders beforehand for all his/hers companions the meals that they want, so multiple products in one order. We would like to ask them however for example at what time they will arrive. 

When the question is linked to the products this means:
* if we link them to all products some people would get them multiple times, which is not desired
* if we don't link them to all products some people would not get them at all since not all the products are ordered

**Comment by chrisdeely** [comment]
Sorry to resurrect a years' old thread, but I have the same feature request. In my use case I'm looking to host an event  comprised of many medium-sized groups. Each group will have 20-100 tickets purchased for the event. We need to collect the name of the group, but we shouldn't need to force the user to repeatedly select the same answer dozens of times to do so.

Is it possible to configure the "Customer data" section to add more fields, or perhaps make the "Invoice Information" required?

**Comment by pc-coholic** [comment]
> Is it possible to configure the "Customer data" section to add more fields, or perhaps make the "Invoice Information" required?

You can write a custom plugin to add more fields to the customer data section; but those won't show up as proper questions in the order or exports; it's up the plugin to wire them in somehow (mostly through meta-data and merge-fields).

But yes - you can make the invoice information obligatory: Settings -> Invoicing -> Tab "Address form" -> "Ask for invoice address" + "Require invoice address". But this will only require the address - not the "custom recipient field".
