### ISSUE TITLE
Template file for manual payment missing from packaged pip file

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#1009]
(disclaimer: I'm not familiar with python and its packaging vernacular, please excuse any misnomers)

It seems the 1.17.1 wheel package (to be found under https://pypi.org/project/pretix/#files for example) is missing the `plugins/manualpayment/templates/pretixplugins/manualpayment/control.html` file.

We noticed this when our installation stumbled over this missing template. I have also confirmed the wheel package does not contain the file.

**Comment by raphaelm** [comment]
Hi Felix, thanks for reporting! This way, we can fix it just in time for 2.0 :)

**Comment by thegcat** [comment]
Thank you for the quick fix. Would it maybe also be worth it to cut a 1.17.2 release for people that can't/won't update to 2.0 right away?
