### ISSUE TITLE
Error while Upgrading to 2.0

### ISSUE THREAD

**Issue by hno2** [pretix/pretix#1018]
Running `python -m pretix migrate` gives the following error: 
```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7efcf68747b8>
Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.5/weakref.py", line 117, in remove TypeError: 'NoneType' object is not callable
```
Ignoring this and while running  `python -m pretix updatestyles` yields the same error.

Using Python 3.5.3 and mysql 15.1 Distrib 10.1.26-MariaDB.

**Comment by raphaelm** [comment]
It looks like a bug in Python rather than in pretix: https://bugs.python.org/issue29519

Is there more stacktrace information so we can see where it is triggered? It also looks like a warning ("Exception ignored"), is there any other output?

Interestingly, it worked for me yesterday on a Debian stretch system, which should also be Python 3.5.3, but maybe a patched version.

**Comment by hno2** [comment]
Ok, the good news is that I fixed this problem by upgrading Python to 3.6 and completely uninstalling and reinstalling pretix
Some (non breaking) errors occured during the install/migration of pretix:

1. `Invalid template /var/pretix/venv/lib/python3.6/site-packages/django_otp/templates/otp/admin19/login.html: 'admin_static' is not a registered tag library.`
2. `Error parsing template /var/pretix/venv/lib/python3.6/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.6/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/job_detail.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.`
3. After Upgrading to Python 3.6 you need to change your nginx-Configuration. Using the Config in your [Documentation](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html#ssl) you need to change the line `alias /var/pretix/venv/lib/python3.5/site-packages/pretix/static.dist/;` to `alias /var/pretix/venv/lib/python3.6/site-packages/pretix/static.dist/;` You might want to make a note in the docs.

**Comment by raphaelm** [comment]
Great!

> Invalid template /var/pretix/venv/lib/python3.6/site-packages/django_otp/templates/otp/admin19/login.html: 'admin_static' is not a registered tag library.

Yeah, there's not a lot we can do about these.

> After Upgrading to Python 3.6 you need to change your nginx-Configuration. Using the Config in your Documentation you need to change the line alias /var/pretix/venv/lib/python3.5/site-packages/pretix/static.dist/; to alias /var/pretix/venv/lib/python3.6/site-packages/pretix/static.dist/; You might want to make a note in the docs.

There is a note, right below the snippet ;)

**Comment by hop** [comment]
I ran into this on an up-to-date Debian stretch system with Python 3.5.3.

`migrate` works until:

```
  Applying ticketoutputpdf.0007_auto_20181123_1059... OK
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb6f87cb510>
Traceback (most recent call last):
  File "/srv/hosting/fubar/venvs/tickets/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb6f87cb510>
Traceback (most recent call last):
  File "/srv/hosting/fubar/venvs/tickets/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

I can provide any information you require.
