### ISSUE TITLE
Ticket selection checkbox nigh invisible on Android/Firefox

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#1019]
The checkbox to select a ticket is nigh invisible on Android with Firefox 62, see:

![img_20180912_171553](https://user-images.githubusercontent.com/22835/45567080-0af18280-b859-11e8-878d-e1f8792c437b.png)

(keep in mind that this is a HiDPI screenshot, so you should imagine this at half the size, and the stroke surrounding the checkbox is accordingly thin)

I'm not quite sure wether this is an issue with Android, Firefox mobile or with the Pretix styling, but as we had 2 users complaining about it out of less than 50 people that subscribed, I thought it was a strong enough signal to make you aware of it.

For reference, this is what it looks like on iOS:

![ima_26eeaa6](https://user-images.githubusercontent.com/22835/45567383-f5308d00-b859-11e8-9806-d9e174b27ed3.jpeg)

Please let me know should you need more information.

**Comment by thegcat** [comment]
Follow-up: It seems with Chrome on Android it works well/it is more visible, so this is probably an issue between Pretix and Firefox/Android. Not sure whether this can be mended via some css or not though.

**Comment by thegcat** [comment]
it is indeed, thanks. I had tried searching beforehand, but wasn't able to find it.

**Comment by raphaelm** [comment]
Yep, closing it as duplicate. Happy if someone wants to fix this :)

**Comment by thegcat** [comment]
After talking to a few more people it seems at least with our users the Firefox/Android Combo isn't that uncommon, and that a few more people than had reported to us had the problem but didn't report it.
