### ISSUE TITLE
Add multiple-choice question types

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#102]
pretix currently allows the admin to define questions which can be answered when ordering a ticket. For example, the admin might ask for the attendee's age. Currently, only questions that ask for text, numbers or Yes/No are supported. It would be nice if we would also support asking to choose one of multiple options
- [x] Checkboxes (choose multiple)
- [x] Selects (choose one)
- [ ] "Other"-option

**Update**: We now have multiple-choice questions that allow the user to select one of many options. The next step would be to (optionally) provide an "Other" option that allows the user to enter custom input in a text field. This would need a new model field for the question and some javascript for the fillout process. A new field on the answer object should not be necessary.

**Comment by simoneott** [comment]
Hello,  I'm new to the  github and I would like to work on the multiple question types. Is it ok if I start working on that or is there an official process I need to go through before jumping in. Don't want to step on anyone's toes but would love to get working on a project and this sounds particularly interesting to me.

**Comment by raphaelm** [comment]
Hello! You are absolutely welcome to start working on this. As this project is currently very small in terms of contributors, we have no formal or official processes. I'd be glad to help you through the technical process, though.

Sadly, it is currently not as easy to set up a local version of pretix as it should be. We have a guide in [our documentation](http://docs.pretix.eu/en/latest/development/setup.html) but it might be incomplete or out of date. Please *do not hesitate* to ask if you get stuck!

In order to tackle this ticket, a few things need to be done:

* In the admin area, called ``pretix control`` in all technical documentation, there is an area in which it is possible to define the mentioned questions and select which type of answer is expected. We have to add two new types of answers here (choose multiple/choose one) as well as a possibility to add choices to those questions. For this, both the ``QuestionForm`` and the respective templates have to be modified.
* The ``Question`` *data model* (living in ``pretix/base/models.py``) needs to be extended in order to store those options. A very simple way would be to store them in a text field, separated by linebreaks; a more advanced way would be to create a separate model ``QuestionOption`` to store them.
* In the frontwend, called ``pretix presale``, when actually ordering one of the products assigned to the question, the user has to be presented a selection field instead of a free input field. This has to be done in ``pretix/presale/forms/checkout.py``.

I can't repeat it often enough, please ask if you get stuck, might be that I can help you with a very simple pointer in the right direction. Also, it is great feedback for me if I hear what is easy and what is hard to understand about the codebase.

Have you used Python and Django before?

**Comment by simoneott** [comment]
Hello!

That's great news. Thank you for being so welcoming, I am really looking
forward to contributing. So far I haven't used Python or Django before - I
hope that is not a problem. I am teaching myself at the moment so it might
take me a bit longer to complete the tasks but I am very motivated to learn
and contribute. I am just setting up my environment and reading up on the
documentation. So far it is looking good but if I'm having questions I will
be sure to ask you.

**Comment by raphaelm** [comment]
No, it is not a problem to me, if you're a total beginner, I just wanted to check so that I neiter bore you to death nor leave you completely alone with it. ;)

**Comment by jlwt90** [comment]
@raphaelm Hello, I think I can take this issue. Could you elaborate what is this `Other` -option?
> The next step would be to (optionally) provide an "Other" option that allows the user to enter custom input in a text field. 

Is it like a textfield with suggested values? It sounds like normal text field for me at this moment :P

**Comment by raphaelm** [comment]
I didn't have a textfield with autocompletion in mind, rather really an "Other" option. To illustrate, currently, multiple choice fields look like this for the user:

- [ ] Option A
- [ ] Option B
- [ ] Option C

In the future, they should optionally be able to look like this:

- [ ] Option A
- [ ] Option B
- [ ] Option C
- [ ] Other: ____textfield____

In contrast to an "autocomplete" field, this still strongly motivates users to select one of the predefined options (which makes evaluating the results easier) while providing the option to go for an individual answer. Think for example about a question asking for food allergies/dietary requirements with the options "Vegetarian", "Vegan", "Lactose-free", "Gluten-free", "Other". You'd probably want to easily count the number of Lactose-free participants but at the same time know what "Other" is exactly.

**Comment by jlwt90** [comment]
@raphaelm I'm sorry that I have been quite busy recently so I may not be able to work on this issue in the coming weeks. If someone is interested on this matter, feel free to assign to someone else :)
Sorry for that!

**Comment by raphaelm** [comment]
No worries! Let's see if someone comes along to work on this or if it will still be free then :)

**Comment by aph3rson** [comment]
Per https://github.com/pretix/pretix/pull/490#issuecomment-302010187, I'm going to take a shot at this.

@raphaelm, feel free to add the assigned label.

**Comment by aph3rson** [comment]
@raphaelm, I've gotten (I believe) about half-way through this. I've defined some things as mentioned above, but I'm stuck on the actual rendering of the fields. From what I could find, a new field/widget would be needed for both forms, in order to display/account for the "Other" field. However, I'm at a loss as to how to do this.

I've pushed some things to [aph3rson/pretix:issues/102](/aph3rson/pretix/tree/issues/102), if you want to see what I've done.

**Comment by raphaelm** [comment]
Hi @aph3rson sorry for the late reply, I'm quite busy at the moment. I'll hope to be able to get back to you tomorrow!

**Comment by raphaelm** [comment]
Yep, that's tougher than I expected. Sorry for that.

We probably really need to somehow build a custom form field with a custom widget, that in turn has custom form rendering. I found this snippet with a quick google search: https://djangosnippets.org/snippets/863/ It's old, but could be a decend start.

**However**, form renderes changed **completely** with Django 1.11, so it might be better to but this on ice until #464 has landed.

**Comment by aph3rson** [comment]
@raphaelm It looks 1.11 has been merged to master - is this safe to be picked back up?

**Comment by raphaelm** [comment]
Ayup, sorry that I forgot about this, too many things at once :(
If you look at the snippet I linked above, you see that it's a custom form field with a custom widget that has a custom renderer. What changed in Django 1.11 is that those renderers do no longer exist and instead, widgets are rendered using templates (which should rather make it easier).

Let me know if I can help you in any way!

**Comment by raphaelm** [comment]
Since this can now be implemented with question dependencies I'm not sure it's worth implementing natively
