### ISSUE TITLE
How to use the french locale ?

### ISSUE THREAD

**Issue by moutonnoireu** [pretix/pretix#1020]
Hllo, I see there is a "fr" folder in the locale folder and I used in the configuration : 
```
[locale]
default=fr
timezone=Europe/Paris
```
But nothing changed. Any idea ?

**Comment by rixx** [comment]
Locales should be chosen on a per-event basis. The French translation will be available as of the upcoming release, it is not part of the current 0.7.1 release.

**Comment by moutonnoireu** [comment]
I saw this issue being closed and reopened and the comment : 

> Locales should be chosen on a per-event basis. The French translation will be available as of the upcoming release, it is not part of the current 0.7.1 release.


I'm using the v2.0.0 release. If it should be chosen on a per-event basis, where is the switch ? Thanks.

**Comment by rixx** [comment]
That is correct, my comment was in error – I thought this issue was in a different repository. I deleted it not a minute after I made it in the hopes of reducing confusion – sorry for the trouble I caused.

**Comment by raphaelm** [comment]
In production builds, we currently only ship langauges that are near complete. So far, French was far from complete, I only now see that it's at 87% in pretix core and 65% in the overall project, so we might consider including it for 2.1.0 (although a better coverage of plugins would be great first). If you want to help out making this a 100%, feel free: https://translate.pretix.eu/languages/fr/pretix/

**Comment by moutonnoireu** [comment]
Is there a way to just translate the public interface (the ticket shop) for now ?

**Comment by raphaelm** [comment]
Unfortunately, not. That would be very useful indeed, but it's hard to implement.
