### ISSUE TITLE
SMTP test is misleading

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1021]
The output I got in the webinterface was:

```
Ein Fehler trat auf beim Versuch, den SMTP-Server zu erreichen: {}
```

What actually happened was this:

```
Sep 16 13:18:18 mail Qsmtpd[1775]: > 220 mail.sf-mail.de Qsmtpd 0.34dev ESMTP
Sep 16 13:18:18 mail Qsmtpd[1775]: < ehlo xxx
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250-mail.sf-mail.de
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250-ENHANCEDSTATUSCODES
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250-PIPELINING
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250-8BITMIME
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250-STARTTLS
Sep 16 13:18:18 mail Qsmtpd[1775]: > 250 SIZE
Sep 16 13:18:18 mail Qsmtpd[1775]: < STARTTLS
Sep 16 13:18:18 mail Qsmtpd[1775]: > 220 2.0.0 ready for tls
Sep 16 13:18:18 mail Qsmtpd[1775]: <e ehlo xxx
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250-mail.sf-mail.de
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250-ENHANCEDSTATUSCODES
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250-PIPELINING
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250-8BITMIME
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250-AUTH LOGIN PLAIN
Sep 16 13:18:18 mail Qsmtpd[1775]: >e 250 SIZE
Sep 16 13:18:18 mail Qsmtpd[1775]: <e rcpt TO:<test@example.org>
Sep 16 13:18:23 mail Qsmtpd[1775]: >e 503 5.5.1 Bad sequence of commands
```

Bad sequence of commands, the "rcpt to" doesn't make any sense here.

```
Sep 16 13:18:23 mail Qsmtpd[1775]: <e mail FROM:<xxx>
Sep 16 13:18:23 mail Qsmtpd[1775]: >e 250 2.1.5 sender <xxx> is syntactically correct
Sep 16 13:18:23 mail Qsmtpd[1775]: <e rcpt TO:<test@example.com>
Sep 16 13:18:29 mail Qsmtpd[1775]: >e 551 5.7.1 relaying denied
Sep 16 13:18:29 mail Qsmtpd[1775]: <e quit
Sep 16 13:18:29 mail Qsmtpd[1775]: >e 221 2.0.0 mail.sf-mail.de service closing transmission channel
```

So far so good, but why is there no output in the webinterface.

**Comment by raphaelm** [comment]
Thanks for reporting. I also noticed already that SMTP-level error messages sometimes don't show up in the interface.

I'm not quite sure about the rest of your report, though. How do the two log snippets relate? How did you come up with the second one if the first one shows that it's already aborting before at the RCPT TO?

> Bad sequence of commands, the "rcpt to" doesn't make any sense here.

Hmm, there should be a ``MAIL FROM`` before, or am I missing something? Funny that it still works with most SMTP server implementations.

**Comment by DerDakon** [comment]
this is the same report, just split into 2 parts. Looks like the first "rcpt to" is rejected because of the bad sequence, and then it sends the correct sequence so it works.

**Comment by raphaelm** [comment]
> this is the same report, just split into 2 parts. Looks like the first "rcpt to" is rejected because of the bad sequence, and then it sends the correct sequence so it works.

Thanks for clarifying. Funny behavior, indeed. We indeed seem to send a ``rcpt to`` before the ``mail from``, I can't see any reason for that. Will fix!
