### ISSUE TITLE
SMTP-Settings by Organisation

### ISSUE THREAD

**Issue by genofire** [pretix/pretix#1026]
It is really usefull, because copies of Events lost SMTP-Settings

**Comment by genofire** [comment]
@raphaelm any statement?

**Comment by raphaelm** [comment]
*Moving* them to organizer settings would be backwards incompatible, so we'd need to have them on both levels, at least for a (longer) transition period. Our settings data store allows this, but we found that it's incredibly hard to build a user interface that communicates the interdependencies of organization end event settings to users. You can look at the design settings for an example of where we tried.

So yes, we want the option to set SMTP (and most other settings!) on organizer level, but it's a hard task and currently not a priority.

> because copies of Events lost SMTP-Settings

I don't quite get that part.

**Comment by genofire** [comment]
Maybe we do not need more then a year for it ;)
