### ISSUE TITLE
Waiting list voucher sent after event has started

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1031]
One of our users has received a waiting list voucher _after_ the event had started. 

I have checked the event log to confirm that this is actually the case: the event started at 2018-09-08 15:00:00 and at 2018-09-08 15:15 (i.e. 15 minutes after the event started) the voucher was created and sent.

After digging around in the code it seems to me that only presale period and product availability is checked when assigning and sending out waiting list vouchers (cf. https://github.com/pretix/pretix/blob/master/src/pretix/base/services/waitinglist.py#L77).

Am I missing something or is a check for the event start time missing when sending out vouchers?

Best regards,
Mikkel

**Comment by raphaelm** [comment]
Interesting edgecase ;) Apparently there isn't a check. For some (e.g. multi-day) events, this might actually make sense, while for others it doesn't, so checking presale_is_running might actually be the best solution.

(Keep in mind that presale_is_running is False after the *end* of the event, even if no presale timeframe is set.)

**Comment by rimi-itk** [comment]
Thanks for the clarification of how `presale_is_running` actually works (I should have read the code more thoroughly).

The best solution is to explicitly set “End of presale” for short events (a few hours) where it doesn't make sense to buy a ticket after event start.
