### ISSUE TITLE
Use markdown.__version__ instead of markdown.version

### ISSUE THREAD

**Issue by cromefire** [pretix/pretix#1032]
When installing `pretix` it errors with the following error:
```
ImportError: Could not import 'rest_framework.pagination.PageNumberPagination' for API setting 'DEFAULT_PAGINATION_CLASS'. AttributeError: module 'markdown' has no attribute 'version'.
```

This is because markdown does not export `version` (anymore?) but `__version__`

Hacky fix: Add `version = _get_version()` at the end of `markdown`'s `__init__.py`

**Comment by raphaelm** [comment]
As far as I can see, that's an incompatibility between two dependencies that we have, and pretix is not really involved?

**Comment by raphaelm** [comment]
The real error is reported here: https://github.com/encode/django-rest-framework/issues/6203

I pushed a workaround commit. On your installation, you can just do a ``pip install "markdown<=2.2"`` to work around the issue.

**Comment by cromefire** [comment]
You're right did not dig too deep thanks
