### ISSUE TITLE
Allow specific sites for iframes

### ISSUE THREAD

**Issue by cromefire** [pretix/pretix#1033]
Currently I cannot see any option where I can whitelist domains that are allowed to embed `pretix` into an iframe.

To make it that possible that domains have to be inserted into the `Content-Security-Policy` (at `frame-src`) and if there are two or more whitelisted pages, `X-Frame-Options` has to be removed.

Currently you can only alter this by a downstream server.

**Comment by cromefire** [comment]
If you point me to the code that sets the headers and tell me, how to read the options, I can implement that.

**Comment by raphaelm** [comment]
pretix is not supposed to be put into iframes for security reasons. If you want to embed a ticket shop into a website, please use our [widget](https://docs.pretix.eu/en/latest/user/events/widget.html), which goes to great lengths to make sure there's no compromise in security.

**Comment by cromefire** [comment]
But the widget doesn't seem to support organizers or collections and we need to host a number of events that change quite often

**Comment by cromefire** [comment]
> pretix is not supposed to be put into iframes for security reasons.

That's why I speak of a whitelist, the embedding site is secured.

**Comment by raphaelm** [comment]
Yes, unfortunately this is not yet implemented (see also #878 which is similar)

**Comment by raphaelm** [comment]
> That's why I speak of a whitelist, the embedding site is secured.

I understand that, however, it's not that simple.

> To make it that possible that domains have to be inserted into the Content-Security-Policy (at frame-src) and if there are two or more whitelisted pages, X-Frame-Options has to be removed.

``frame-src`` is not involved here, you mean ``frame-ancestors``. ``frame-ancestors`` is not set, so it currently allows everything. The only thing currently constraining embedding is the ``X-Frame-Options`` header.

To allow a whitelist of two or more, we'd need to drop ``X-Frame-Options`` as you said, and could enforce the whitelist only via ``frame-ancestors``, which is supported by fewer browsers, so it is a compromise in security. Even with a whitelist of only one, ``X-Frame-Options: ALLOW-FROM`` doesn't work in Chrome or Safari (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options)), so it's not a really suitable option either.

The other way to implement a whitelist would be to do something hacky with referers and iframes, which only properly works on the first request and probably breaks for people with strong privacy settings.

Beyond that, it'd be something that could not be supported on pretix Hosted, but only for people running their own pretix installation. Therefore, I'd like to see this use case solved differently. The best way would obviously be to extend the widget, and the quickest way is probably for you to modify the headers to your liking in your nginx reverse proxy. A clean solution working right now could be to [pull the list of events](https://docs.pretix.eu/en/latest/api/resources/events.html) from our REST API and just build a link list / embed the widget dynamically.

**Comment by cromefire** [comment]
Okay I'll use hacky apache / python tricks for now and hope that that widget improvement gets implemented. `X-Frame-Options` is kind of deprecated anyway and the ssl support restricts our page to modern browsers. Since this year TLS 1.0 is deprecated.

**Comment by raphaelm** [comment]
Yes, the widget is using iframe for the checkout to prevent having to implement everything twice. We jump through many hoops to make this iframe immune to clickjacking attacks, though.

**Comment by devxpy** [comment]
Ah, yes makes sense!

Is there any way to run custom JS on the page? 

We really want to grab user's emails and redirect to our custom login page.

**Comment by raphaelm** [comment]
No, there is not, it would be horrible to keep developing pretix if we'd have to fear breaking people's custom JS. On pretix Hosted, it would also be a security nightmare.

I'm not 100% sure I understand what your objective is but any kind of JS-level login thing sounds inherently insecure.
Proper support for external login pages comes with #2718
