### ISSUE TITLE
405 when adding to cart on small screen

### ISSUE THREAD

**Issue by cromefire** [pretix/pretix#1040]
Given you have a smaller screen, pretix does not display an iframe on the same page, but does open a new tab. That request results in a `405` ([Firefox request recording, `.txt` due to github constraints](https://github.com/pretix/pretix/files/2451435/pretix.har.txt)).

## How to reproduce?

1. Open Firefox (other browser are possible, but have different tool names and shortcuts)
2. Go to [`https://docs.pretix.eu/en/latest/user/events/widget.html`](https://docs.pretix.eu/en/latest/user/events/widget.html)
3. Delete cookies for the site (`Shift + F9`)
4. Reload
5. Press `F12`
6. Enable `Responsive Design Mode` (`Ctrl + Shift + M`)
7. Click `Buy`
8. Firefox will display a blank page, if you are quick enough to press `F12` you will see the `405` error under `Networking` (`Ctrl + Shift + E`)

**Comment by cromefire** [comment]
In Firefox under `Networking` you can import the `.har` file on the right, under `HAR`.

**Comment by raphaelm** [comment]
Interesting. It works in Chrome, and appears to be a problem with firefox: Somehow, Firefox does not send a POST request when submitting that form.

**Comment by cromefire** [comment]
Chrome Desktop and mobile does that, but the Chrome PWA (Progressive Web App, as WebAPK)also  has that bug.

**Comment by raphaelm** [comment]
Probably https://bugzilla.mozilla.org/show_bug.cgi?id=1629441
