### ISSUE TITLE
Multi-level conditional skip logic/branching questions

### ISSUE THREAD

**Issue by Nostaljaded** [pretix/pretix#1047]
Hi,

Feature request on the following:

**1. Multi-level conditional skip logic/branching questions**
**2. Free-Text when choosing 'others' option**

_Example:_

> Q1: Are you in a programming/coding-related field?
> - Yes
> - No [go to Q5]
> 
> Q2: If 'Yes', What is your profile?
> - Employee
> - Student [go to Q4]
> - Entrepreneur/Business Owner [go to Q5]
> - Investor [go to Q5]
> - Others [free-text for user input, go to Q5]
> 
> Q3: If 'Employee', does your company encourage you to devote a certain amount of time to side projects?
> - Yes [go to Q5]
> - No [go to Q5]
> 
> Q4: If 'Student', will you be available to contribute to open-source projects during your holidays?
> - Yes
> - No
> 
> Q5: ...

Maybe can look at how LimeSurvey does them, PHP-based though
[https://github.com/LimeSurvey/LimeSurvey](https://github.com/LimeSurvey/LimeSurvey)

Cheers

**Comment by raphaelm** [comment]
I think we can now do this for a while, at least too some degree
