### ISSUE TITLE
Wrong CSS when using widget with new event

### ISSUE THREAD

**Issue by v0tti** [pretix/pretix#1054]
I just created a new event an wanted to embed the shop to an external website. It seems that for new events a broken widget CSS file is created.

New Event (wrong) CSS:
https://tickets.fem.tu-ilmenau.de/fem/wf18/widget/v1.css
```
@charset "UTF-8";/*!
 * Bootstrap v3.3.6 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
...
```

Old Event (correct) CSS:
https://tickets.fem.tu-ilmenau.de/fem/fiwak18/widget/v1.css
`.pretix-widget a,.pretix-widget-alert-box a{color:#00377c;text-decoration:none} ...`

As a temporary solution I just use the old events CSS for the new widget.

**Comment by raphaelm** [comment]
Can you check if the events have a custom color/font set (at Settings > Display) and if saving that form (i.e. triggering a rebuild of the parameterized CSS) helps/changes the situation? Please note that the widget CSS is cached for 60 seconds.

Did you create the new events from scratch or by copying from another one?

**Comment by v0tti** [comment]
I do not have any custom color/font settings for the new or the old event. Still, saving the form helped to solve the issue.
The event was created from scratch.

**Comment by v0tti** [comment]
I just ran into the same issue again, running 2.5.0.

**Comment by raphaelm** [comment]
Weird. Are you running ``python -m pretix updatestyles`` after every upgrade?

**Comment by v0tti** [comment]
Yes, I am always running `updatestyles` with every update.

**Comment by raphaelm** [comment]
closing for "never seen again"
