### ISSUE TITLE
Custom PDF-Ticket not working

### ISSUE THREAD

**Issue by hno2** [pretix/pretix#1055]
I have a custom pdf ticket design, after updating to the latest version. This ticket design not shown when downloading tickets (or tickets being sent via E-Mail).

The design is shown in the web editor and in the Preview. 
The Logs do not contain any errors. Any ideas?

**Comment by hno2** [comment]
Ok this is interesting. 
The Design is shown in the Chrome PDF-Viewer & in Acrobat but not in the Mac Preview.
Any ideas how to troubleshoot the pdf viewer ?

**Comment by raphaelm** [comment]
Okay, I'm not sure if I understand the problem correctly already. Can you maybe post a few screenshots that explain it?

**Comment by hno2** [comment]
Im sorry, so basically it's down to that some pdf viewer are not displaying any custom design:
So here the pdf of the ticket (don't worry its not valid)
[TTB-HLTEY-1-pdf.pdf](https://github.com/pretix/pretix/files/2524542/TTB-HLTEY-1-pdf.pdf)
See the different, the first screenshot is how the ticket is displayed in Chrome or Acrobat, the second how it looks in the Mac Preview.
<img width="793" alt="bildschirmfoto 2018-10-29 um 10 02 45" src="https://user-images.githubusercontent.com/436990/47639922-ad906700-db62-11e8-886a-8f667dd0f7b7.png">
<img width="1207" alt="bildschirmfoto 2018-10-29 um 10 03 19" src="https://user-images.githubusercontent.com/436990/47639928-b123ee00-db62-11e8-8917-421f6f628f97.png">

**Comment by raphaelm** [comment]
Uff. I have no idea how to debug this. This is either a bug in the Mac Preview (error in the implementation of the PDF spec), or we unknowingly do something not conformant to the Spec (but not even Acrobat cares, so nobody should care?).

If you want to research this further, we're using [this method](https://pythonhosted.org/PyPDF2/PageObject.html#PyPDF2.pdf.PageObject.mergePage) to merge the page with its background. But I'd consider this issue slightly out of scope of pretix.

**Comment by mdelete** [comment]
Looks fine with latest the Preview on macOS and iOS
