### ISSUE TITLE
Pending order email for banktransfer needs more translatable field

### ISSUE THREAD

**Issue by mdehollander** [pretix/pretix#1058]
Currently, the confirmation email with information on the pending payment when using the bank transfer option contains English sentences. It would be nice to have them as translatable strings.

The template [order_pending.txt](https://github.com/pretix/pretix/blob/master/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/email/order_pending.txt) contains the sentence `Please transfer the full amount to the following bank account.` and the words `Reference` and `Amount`. 
https://github.com/pretix/pretix/blob/df2d8925ed74c7195f48f1d4bca9b0748e041e5c/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/email/order_pending.txt#L2

It would be nice translations can be made for these things using translate.pretix.eu
 

Also the email subject says "Your order" 
https://github.com/pretix/pretix/blob/df2d8925ed74c7195f48f1d4bca9b0748e041e5c/src/pretix/base/services/orders.py#L631

**Comment by rixx** [comment]
All of those strings are translatable – in the order_pending.txt you can see that the "blocktrans" marker marks the whole block as translateable, whereas the subject is enclosed by a `_()`, which also marks translateable strings. I can also see that they are present in the translation files which are generated by translate.pretix.eu, e.g. the first example is translated here: https://github.com/pretix/pretix/blob/master/src/pretix/locale/nl/LC_MESSAGES/django.po#L13068

**Comment by mdehollander** [comment]
English, Dutch and French (that's why i am running my own instance(2.2.0.dev0), with Dutch as default language. I did not try this in the pretix hosted version.

**Comment by raphaelm** [comment]
I assume in that case, that your user's language is English (what language is shown in the order details in the top box?) but you only have a Dutch mail template in Setting>Email

**Comment by mdehollander** [comment]
The order locale is Nederlands and there is text for all templates in all languages. I did change the text of the template, not sure of this caused a problem. Could it be a problem that I am running the 2.2.0.dev0 version and not the last stable release?

**Comment by raphaelm** [comment]
> Could it be a problem that I am running the 2.2.0.dev0 version and not the last stable release?

Might be, if we changed that string in source and did not yet push the current sources to the translate portal, we only do that once in a while.

**Comment by raphaelm** [comment]
Thanks for the heads-up that French support is good enough that people self-host just because of that :P I'm deploying French on the SaaS platform now.
