### ISSUE TITLE
Add a map plugin

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#1062]
* Add an event geo-location field to pretix core
* Add a plugin that displays a Google/OSM map to the front page of an event

**Comment by oocf** [comment]
I think that this plugin will be better to be handle by event, each event could have its map to see where the event is going to be, rather than in the principal page of the ticket shop

**Comment by raphaelm** [comment]
@oocf 	I agree, and I even meant that. You're right, I wrote it in a way that could easily be misunderstood
