### ISSUE TITLE
Allow manually creating partial payments

### ISSUE THREAD

**Issue by agowa338** [pretix/pretix#1067]
As discussed in #1065 partial payments are already supported. But as direct hence there still unhedged cases with it.

If one uses a manual payment method or bank transfer (without HBCI or importing data), Pretix does not automatically know about those partial payments and currently there is no option to manually mark a payment as partially paid. Therefore the "Order details"-page needs a button to mark the order as partially paid, so that Pretix can send payment notifications as with automatic payment methods.

**Comment by raphaelm** [comment]
You're right, in full manual mode this is still missing.
