### ISSUE TITLE
Matching participants/customers to workshops/talks by preferences

### ISSUE THREAD

**Issue by Sohalt** [pretix/pretix#1075]
I'm not entirely sure, if this idea is within the scope of the project, but I thought I'd propose it anyway:
When there are multiple workshops or talks offered, but only limited spots available for each slot, it would be cool if participants could specify a ranking of which workshops they would like to attend. Based on this ranking by preference the workshops would then be assigned using the matching algorithm for the college admission problem by Gale and Shapley (see for example https://blogs.cornell.edu/info4220/2016/03/18/the-college-admission-problem-many-to-one-matching/).
This would allow more people to get a good workshop than simply using a FCFS approach.

**Comment by raphaelm** [comment]
I totally agree that this would be nice, but I currently see it out of scope of pretix, at least out of scope of pretix core. Multiple workshops are currently commonly solved through add-on products. However, all products need to be fixed during registration and it's not built for adding them in later, so this wouldn't work with this approach anyways.

I believe if someone wants to do this, the way to go would be to create a pretix plugin that inserts a new page into the checkout process that allows to specify the ranking and then later handle that data externally in some way.
