### ISSUE TITLE
: Internal Server Error Multiple Objects Returned

### ISSUE THREAD

**Issue by kc9ryt** [pretix/pretix#1093]
Hello,
After trying to review the POS reports I am getting the following error on one of our devices.

Log:
Internal Server Error: /control/organizer/LHSMusicDepartment/pos/5/closings/1/report/

MultipleObjectsReturned at /control/organizer/LHSMusicDepartment/pos/5/closings/1/report/
get() returned more than one POSClosing -- it returned 2!

Request Method: GET
Request URL: https://tickets.lebanonauditorium.com/control/organizer/LHSMusicDepartment/pos/5/closings/1/report/
Django Version: 2.1.2
Python Executable: /var/pretix/venv/bin/python3
Python Version: 3.5.2
Python Path: ['/var/pretix', '/var/pretix/venv/bin', '/var/pretix/venv/lib/python35.zip', '/var/pretix/venv/lib/python3.5', '/var/pretix/venv/lib/python3.5/plat-x86_64-linux-gnu', '/var/pretix/venv/lib/python3.5/lib-dynload', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/var/pretix/venv/lib/python3.5/site-packages', '/var/pretix']
Server time: Fri, 16 Nov 2018 22:47:41 -0500
Installed Applications:
['django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'pretix.base',
'pretix.control',
'pretix.presale',
'pretix.multidomain',
'pretix.api',
'pretix.helpers',
'rest_framework',
'django_filters',
'compressor',
'bootstrap3',
'djangoformsetjs',
'pretix.plugins.banktransfer',
'pretix.plugins.stripe',
'pretix.plugins.paypal',
'pretix.plugins.ticketoutputpdf',
'pretix.plugins.sendmail',
'pretix.plugins.statistics',
'pretix.plugins.reports',
'pretix.plugins.checkinlists',
'pretix.plugins.pretixdroid',
'pretix.plugins.badges',
'pretix.plugins.manualpayment',
'django_markup',
'django_otp',
'django_otp.plugins.otp_totp',
'django_otp.plugins.otp_static',
'statici18n',
'django_countries',
'hijack',
'compat',
'oauth2_provider',
'pretix_posbackend',
'pretix_pages',
'pretix_cartshare',
'pretix_cashpayment',
'pretix_fontpackfree',
'pretix_newsletter_ml',
'pretix_passbook']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
'pretix.multidomain.middlewares.MultiDomainMiddleware',
'pretix.helpers.metrics.middleware.MetricsMiddleware',
'pretix.multidomain.middlewares.SessionMiddleware',
'pretix.multidomain.middlewares.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'pretix.control.middleware.PermissionMiddleware',
'pretix.control.middleware.AuditLogMiddleware',
'pretix.base.middleware.LocaleMiddleware',
'pretix.base.middleware.SecurityMiddleware',
'pretix.presale.middleware.EventMiddleware']

Traceback:

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/pretix/control/permissions.py" in wrapper
  64.                 return function(request, *args, **kw)

File "/var/pretix/venv/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/pretix_posbackend/views/control.py" in get
  118.         closing = self.get_object()

File "/var/pretix/venv/lib/python3.5/site-packages/pretix_posbackend/views/control.py" in get_object
  115.         return get_object_or_404(self.device.closings, closing_id=self.kwargs['closing_id'])

File "/var/pretix/venv/lib/python3.5/site-packages/django/shortcuts.py" in get_object_or_404
  93.         return queryset.get(*args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/django/db/models/query.py" in get
  403.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /control/organizer/LHSMusicDepartment/pos/5/closings/1/report/
Exception Value: get() returned more than one POSClosing -- it returned 2!

**Comment by raphaelm** [comment]
Sorry this never caused activity here. Please reach out to support@pretix.eu if this is still an issue.
