### ISSUE TITLE
order search does not find the order code

### ISSUE THREAD

**Issue by j-herden** [pretix/pretix#1098]
When I am searching after an order code I do not get any result. Like this screenshot:

![grafik](https://user-images.githubusercontent.com/2026587/48757793-33a15880-ec9e-11e8-8519-f8cf420d1ff3.png)
When I hit enter the result list will be empty.

However, searching after '2019-BX9WL' does work.

This is not what I would expect and I'd be happy, if the system would learn to find an order by its order code.

**Comment by raphaelm** [comment]
This apparently only occurs if the event slug contains a ``-``. I'll fix it soon, thanks for reporting!
