### ISSUE TITLE
"See order in backend" link when viewing order as user with permissions

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#1102]
A common workflow for me is to be sent a customer's order URL with the request for modifications on that order. I'll then click the link, copy the order code, open a new tab to go to the backend, click my way through to the event and order page, and then enter the order code. If pretix would show me a backend link on the order, I could stop this workflow (which I'm currently shortening with pinned tabs while an event is active, and it still takes some time).

**Comment by raphaelm** [comment]
I'm reluctant, since this won't work e.g. with custom domains, where the frontend does not know who you are. I'd rather e.g. accept the full URL in the search field in the backend so you can more easily copy and paste. What do you think?

**Comment by rixx** [comment]
Anything is better than nothing, and I'll take what I can get. ;) The search field isn't the issue though, unless you mean the new context switcher in the side bar.
