### ISSUE TITLE
Do not send "order will expire" reminders out if the order was just created

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#1106]
Hi,
today I've placed a free order (Total of 0 EUR) within an event, that has its "latest payment date" set to 2 days from today. Pretix successfully send an order confirmation, following a "your order is about to expire"-mail (which was configured to be send three days before "latest payment" date). In the database and on the order page the status states "payed" and I am able to download the tickets normally.
It is kinda counter-intuitive to recieve such an e-mail if you have placed a free order.

Best regards
Jan Felix

**Comment by jfwiebe** [comment]
ah, sorry. I have not found #751.

**Comment by raphaelm** [comment]
I'm not sure this is related to #751 that much. It's more related to the fact that your payment reminder was sent out in the second-long timeframe before the free order was marked paid, which happens a lot if the reminder is scheduled a larger number of days before the expiry than the expiry is actually in the future. Thisis a situation that quite some customers of ours ran into in the past weeks and that caused some trouble, so we should do something about this.

**Comment by jfwiebe** [comment]
Lovely! Thank you!
