### ISSUE TITLE
log level

### ISSUE THREAD

**Issue by hop** [pretix/pretix#1127]
I'm probably missing something, so please bear with me.

I followed the "small-scale manual" deployment guide.

`python -m pretix runperiodic` logs celery success messages at the info level:

`INFO 2019-01-03 20:49:47,479 celery.app.trace trace Task pretix.base.services.quotas.refresh_quota_caches[817c903c-ea12-491f-aa65-23b89e59075a] succeeded in 0.006468222010880709s: None
INFO 2019-01-03 20:49:47,606 celery.app.trace trace Task pretix.base.services.waitinglist.assign_automatically[db93ed55-5e42-4278-8647-3deefa0ea8dc] succeeded in 0.08206735923886299s: 0
`

This means I get a useless email from the cron job twice an hour, unless I set `loglevel` in `pretix/settings.py` to `WARNING`.

Is there a way to override the log level in pretix.cfg that I'm overlooking?

**Comment by raphaelm** [comment]
No, currently the log level is not configurable.

**Comment by hop** [comment]
OK, thanks! I'm maintaining my local patch for now.

If you are interested in a PR, I would need to know in which direction logging configurability should go.
