### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by DevMostafa** [pretix/pretix#1150]
I have completed all steps here on my Linux Ubuntu Machine https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html
till the line starting with **"The following snippet is an example on how to configure a nginx proxy for pretix:"**
I've paste the config script there into "sites-available/pretix.localhost.com" file and it didn't work till now and don't know the reason

**Comment by raphaelm** [comment]
Yeah, you'll need to give a *little* more information, such as the full config file, what error messages you are getting, etc.

**Comment by DevMostafa** [comment]
Sorry for that. I have made this file "/etc/nginx/sites-available/pretix.localhost.com" with the following code 

`server {
    listen 80 default_server;
    listen [::]:80 ipv6only=on default_server;
    server_name pretix.localhost.com;
}
server {
    listen 443 default_server;
    listen [::]:443 ipv6only=on default_server;
    server_name pretix.localhost.com;

    #ssl on;
    #ssl_certificate /etc/nginx/cert.crt;
    #ssl_certificate_key /etc/nginx/cert.key;

    add_header Referrer-Policy same-origin;
    add_header X-Content-Type-Options nosniff;

    location / {
        try_files $uri $uri/ = 404;
        proxy_pass http://localhost/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;

    }

    location /media/ {
        alias /var/pretix/data/media/;
        expires 7d;
        access_log off;
    }

    location ^~ /media/cachedfiles {
        deny all;
        return 404;
    }
    location ^~ /media/invoices {
        deny all;
        return 404;
    }

    location /static/ {
        alias /var/pretix/venv/lib/python3.6/site-packages/pretix/static.dist/;
        access_log off;
        expires 365d;
        add_header Cache-Control "public";
    }

    location ^~ /control/ {
        alias /var/pretix/venv/lib/python3.6/site-packages/pretix/control/;
        access_log off;
        expires 365d;
        add_header Cache-Control "public";
    }
}

`

There are no errors faced me except that I cannot open the url https://pretix.yourdomain.com/control/" on the browser to run the **"Pretix"** solution

**Comment by raphaelm** [comment]
You're at least missing a port in the ``proxy_pass`` directive.

**Comment by DevMostafa** [comment]
I have made it `proxy_pass http://localhost/;` and still no updates

**Comment by raphaelm** [comment]
That's still wrong, you're missing the port, like ``proxy_pass http://localhost:8345/;``. Please have another look at the tutorial. Also, what does your browser say when you're open the URL? Connection error? Error 500? 502? 503?

Please note that hosting pretix yourself in a safe and secure way *does* require some experience with running complex web applications on Linux. If you want to go for a simpler solution, please check out our Hosted service at https://pretix.eu/

**Comment by DevMostafa** [comment]
I have modified it now for the specified port which is the same on pretix-worker.service tutorial 
I had uploaded the file configuration & error faced me.
![config_file](https://user-images.githubusercontent.com/1819136/51826856-bd9a1d00-22f0-11e9-95a3-5a96d794aa2c.png)
![error](https://user-images.githubusercontent.com/1819136/51826857-be32b380-22f0-11e9-8fa0-b5f377356747.png)

**Comment by raphaelm** [comment]
1.) pretix-worker doesn't have a port, pretix-web does
2.) You are opening :8345 in your browser, when you should be opening :80 or :443, where nginx is running
3.) You commented out :80, and only configured :443, which is the HTTPs port, but you commented the SSL directives out.

Sorry, this really isn't an issue with pretix, and I lack the time to support you here. Maybe someone else wants to jump in.

**Comment by DevMostafa** [comment]
(2) the port 80 gave me the same index.html file of nginx and I have enabled the ssl commented and still there's no opening for pretix with that error attached
![error2](https://user-images.githubusercontent.com/1819136/51828630-a9f0b580-22f4-11e9-9af2-7354a6945587.png)
I'm now following the same pretix installation tutorial and still cannot see or deploy the server.

**Comment by DevMostafa** [comment]
Now I've skipped the nginx deployment and I've run "/var/pretix/venv/bin/gunicorn pretix.wsgi" from terminal but have the attached error with 127.0.0.1:8080
![error505](https://user-images.githubusercontent.com/1819136/51843919-b1c45000-231c-11e9-99a9-7cf04fda0384.png)
