### ISSUE TITLE
attendee name issue

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1165]
In order details + order view as customer:
the attendee first name and last name are concatenated

![screen shot 2019-02-11 at 21 54 06](https://user-images.githubusercontent.com/485492/52592851-bc680480-2e47-11e9-95c0-b29718520e9b.png)

**Comment by pc-coholic** [comment]
May I ask, which setting selected for collecting and displaying names? (Settings > General > Name format)

I would assume, that you selected `Ask for Given name + Family name, display like 毛泽东`...

**Comment by Zambiorix** [comment]
That was indeed the case, but then I changed it to "Ask for Given name + Family name, display like John Doe" 

.. but the output remains the same.  I have not tested with a new order.
Cache problem?

**Comment by pc-coholic** [comment]
Yes, that would be a cache issue... But your initial selection worked as intended: https://github.com/pretix/pretix/blob/97f3fbdb80f468d7b349e9d40c479a469811b194/src/pretix/base/settings.py#L693

You can always edit the order and just save it again, that should probably get rid of the wrong display after you changed the setting.

**Comment by Zambiorix** [comment]
yup .. editing the order changes the output immediately
