### ISSUE TITLE
Order payment received email sent twice

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1166]
When in general settings:
selecting -> Ask for the order email address twice

The Payment Received e-mail is sent twice.

When unselecting that option, the payment received e-mail is sent once

The Order Received e-mail is sent once in both cases, so that one is correct.

**Comment by raphaelm** [comment]
This is really confusing. If you search the code base for ``order_email_asked_twice``, you will see that this setting is used for absolutely nothing other than displaying the form field twice and validating its input. The information if the address was entered twice is not even present in the system any more at the time at which we send out the payment received email, so I'm pretty sure that it has nothing to do with the setting.

What version of pretix and what payment provider are you using? My guess is rather that the payment is confirmed twice at the same time, both by the user returning from the payment provider and the payment provider sending a webhook.

**Comment by Zambiorix** [comment]
I have installed the community edition of Pretix only last week, if I'm not mistaken it is version 2.4.

Payment provider is Stripe plugin

Furthermore, I have tested this by enabling/disabling in sequence "order_email_asked_twice" and then immediately tested by ordering. And indeed, the Payment received is sent 2 when enabled and sent 1 time when disabled. It is also visible in the e-mail history of the order.

**Comment by Zambiorix** [comment]
![screen shot 2019-02-12 at 15 00 20](https://user-images.githubusercontent.com/485492/52640704-604cc100-2ed7-11e9-80ef-f217b0e74bc3.png)

**Comment by Zambiorix** [comment]
When "order_email_asked_twice" is enabled:

![screen shot 2019-02-12 at 15 05 09](https://user-images.githubusercontent.com/485492/52640847-c0436780-2ed7-11e9-9109-db0609624458.png)

**Comment by Zambiorix** [comment]
When "order_email_asked_twice" is disabled

![screen shot 2019-02-12 at 15 05 41](https://user-images.githubusercontent.com/485492/52640871-d3eece00-2ed7-11e9-97dc-ff7b41ec4577.png)

**Comment by raphaelm** [comment]
Very weird indeed. However, correlation is not causation and I still believe that the correlation with this setting is a coincidence. Can you post a screenshot of the "order history" column of the order with the duplicate email?

**Comment by Zambiorix** [comment]
![screen shot 2019-02-12 at 15 36 59](https://user-images.githubusercontent.com/485492/52642839-10242d80-2edc-11e9-969e-7758b80bdcd2.png)

**Comment by Zambiorix** [comment]
Event if Stripe reports the order as being paid twice, Pretix should handle it correctly. Doesn't Stripe's API assign unique ID's with every API callback to avoid double processing?

**Comment by Zambiorix** [comment]
Or maybe it is a queue issue? (event not deleted from queue the first time)

**Comment by Zambiorix** [comment]
I have performed 3 test after one another, enabling/disabling "order_email_asked_twice" and the results are consistent on my side. That is very weird indeed!

**Comment by raphaelm** [comment]
> Even if Stripe reports the order as being paid twice, Pretix should handle it correctly. Doesn't Stripe's API assign unique ID's with every API callback to avoid double processing?

It's not that simple if the two notifications arrive concurrently ;) This is likely either a race condition when recieving two webhooks at the same time or a race condition between us polling the payment state in ReturnView and Stripe sending the webhook. 

That's why I asked for your pretix version – we fixed such a race condition in 654be0db recently. As it looks, we didn't fix it but just made it more unlikely. I'll have a look at a deeper fix.

**Comment by Zambiorix** [comment]
I make it look simple, but I do understand your problem. Last year I implemented another payment provider and I had similar problems. I had to pump data from the payment provider in a database, serialise, filter and process it by a single assigned worker (for that order).

**Comment by raphaelm** [comment]
Can you check if 78544cdb helps and if not, reopen this issue?

**Comment by Zambiorix** [comment]
I have installed pretix via pip. I currently have no access to my development install from git, so I cannot give feedback until tomorrow

**Comment by Zambiorix** [comment]
Ok, this is solved for me
