### ISSUE TITLE
Question validation

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1168]
I would love to see a Question validation system, via client side scripting maybe?

Or at least some simple validations with configurable error texts when validation fails

Dates -> min date / max date
(we sell tickets for an event where participants have to be at least 16 years of age)

Numbers -> min / max / default

Lists 
-> use and internal code per answer 
-> be able to upload answers in json format at once

example : countries / languages
de / Germany / Deutschland
be / Belgium / Belgien
etc...

**Comment by Zambiorix** [comment]
We want to sell tickets for a large walking event.
User have to select from a list if they are member of a certain club (many clubs in many countries)
So I'm looking for an easy way to implement that... 
uploading answers with an internal code would solve that without resorting to plugin development

**Comment by raphaelm** [comment]
Nice idea! It would make the configuration interface for questions way more complicated, but it would still be nice and less of a special case than #1154.

**Comment by felixrindt** [comment]
Something like this already came up in #847. Also #794 would be related.

**Comment by Zambiorix** [comment]
The tickets sale (15000 tickets) for our event goes live march 23, but I only have next 2 weeks to implement a plugin that does user input validation (and we have some 20 questions). I know almost nothing about python and django, so i'm in for a steep learning curve. Wish me luck! :-) 

(I managed to setup a working development environment yesterday, got a deployment system to production environment working and have a minimal plugin working) ... Your developer doc's are of great help!

**Comment by raphaelm** [comment]
Good luck! :)

15.000 tickets is an impressivly large event ;) If you need help setting up pretix for that scale quickly, feel free to also have a look at our [pretix Enterprise support contracts](https://pretix.eu/about/en/pricing).

**Comment by Zambiorix** [comment]
Our event is not-for-profit (it is actually the largest walking event of its kind in Europe, if not the world). We rely very much on sponsors and do a lot (until now most) of our development in-house. We are all volunteers, nobody is on the payroll. So, although your offer is tempting, I'm on my own for this one. 

But I do have a lot of experience with high load systems and scaling. During the day of our event, the real-time tracking system I have developed gets about 5 million hits. 

So, all tips are welcome for Pretix ... :-)

This is our 50th anniversary, we expect the 15.000 tickets fly out of the door in a few days, if not hours
(and a lot of our participants are from Germany :-)

**Comment by raphaelm** [comment]
Min/Max for number/date/time is now implemented; country fields are also implemented, therefore closing this for now
