### ISSUE TITLE
Account system

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1169]
It would be a great feature if only registered users could buy tickets.
A user would need to register, confirm e-mail adres and create a real account (with questions etc).

**Comment by raphaelm** [comment]
We had this in a very early version of pretix, and we threw it out. There were two main reasons:

1. We implemented it in a very complex way, differentiating between "global" accounts which are valid for every event on a certain pretix server and "local" accounts which only were valid for a specific event. Global accounts were identified by email address, local accounts were identified by user names. This made it hard to understand for users and hard to code around it. Today, we'd probably settle on organizer-level accounts, but we'd still need a lot of effort to do all the authentication stuff in a way that neither clashes with the backend accounts nor does all the work again from scratch.

2. The first actual usages of pretix showed, that even at an IT event, users are *really* incapable of remembering passwords, usernames and even account email addresses. This caused a lot of support effort, and hat very little upsides.

Today, our recommended option is to have an account system in an external system (e.g. if you have a membership system anyways) and use a plugin to embed a Single-Sign-On Step into the checkout. Or, maybe it would even be possible to implement the whole account system as a plugin.

I'm gonna close this for now, as we do not plan to add such a system back in the near future. This might change at some point, but I don't see it happening right now, sorry.

**Comment by Zambiorix** [comment]
No worries, it was just an idea.

I actually working on a plugin for our event. It might eventually evolve into a real account system. But not this year. Let's see if I can get us going with the question validation first..

Thanks!

Great work BTW, Pretix sure looks like the perfect fit for our event! (I was in the midst of developing a ticketing system myself, but ran into time contraints)

**Comment by Zambiorix** [comment]
.. and thank you for your elaborate feedback!

**Comment by orlando** [comment]
Hello @raphaelm,

We have this need for an upcoming event where we are trying to use Pretix, we need users to create accounts and ask them to complete their profile. With https://github.com/pretix/pretix/pull/1447 now merged is it possible to do this? Or is it only for organizer accounts? 

What we want is an extra step during checkout where users are asked to create an account and complete their profile, then when they are logged in, the would be able to see the tickets.

Thanks

**Comment by raphaelm** [comment]
#1447 only affects organizer accounts. Customer-level accounts are out of scope for pretix core, but can be added through a plugin (which so far nobody did).

**Comment by orlando** [comment]
Hey @raphaelm,

Thanks for the quick reply. Do you know what I can look to get an idea of how to develop this? We need a basic account system using email and password. We would make the plugin available if it provides the functionality we need.

Cheers

**Comment by raphaelm** [comment]
Sorry, no, I don't have really good pointers here. Things to read for a start:

https://docs.pretix.eu/en/latest/development/api/plugins.html
https://docs.pretix.eu/en/latest/development/api/customview.html

Your main entry point will be:

https://docs.pretix.eu/en/latest/development/api/general.html#pretix.presale.signals.checkout_flow_steps

However, this one is currently not really well documented, so you'll need to read some source code there (see how the other checkout steps are implemented).

**Comment by orlando** [comment]
@raphaelm Thanks for the information, this is really helpful.
