### ISSUE TITLE
check-in list displays wrong email address

### ISSUE THREAD

**Issue by j-herden** [pretix/pretix#1170]
When I display a check-in list in the browser, I will not see email address of the participant, but the one from the user who will get the invoice.
However, when I export the same check-in list, I will get the correct email addresses in the exportet data.

I would think that this is a bug and the online visible check-in lists should show the email addresses of the participants too.

**Comment by abramzog** [comment]
Hi I'm new to open source contribution -  would like to get started on this.  Is it OK?

**Comment by raphaelm** [comment]
Sure, go ahead!
