### ISSUE TITLE
Add a signal to add custom question validation

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1171]
I am trying to do answer validations in a plugin.
The only way I can do that, afaik, is via signal `pretix.base.signals.validate_cart`
Unless there is a better way?

The docs say that a `CartError` has to be raised if something is wrong.

So, consider this example:
I raise a CartError when the date of birth is set too young 

```
@receiver(validate_cart, dispatch_uid='pretix_dodentocht_validate_cart')
def dt_validate_cart(sender, **kwargs):
    for index, position in enumerate(kwargs['positions']):
        for answer in position.answers.all():
            if answer.question.identifier == 'dt_dateofbirth':
                maxDateOfBirth = date(date.today().year - 15, 1, 1)
                dateOfBirth = datetime.strptime(str(answer), '%Y-%m-%d').date()
                if dateOfBirth >= maxDateOfBirth:
                    raise CartError(_('You are too young, you must turn 16 in {0}').format(date.today().year))
```

This works, I get the error message on top of the screen, but the cart is showing the wrong tab.
Instead of staying on the "Your Information" tab, where the date of birth field is filled in, it jumps back to the "Add-on products" tab.

If I remove product add-ons in settings (so there is no "Add-on products" tab), it jumps back to the cart overview.

How can I solve this? How can I make sure the "Your Information" tab remains visible?

<img width="1208" alt="screen shot 2019-02-14 at 23 04 17" src="https://user-images.githubusercontent.com/485492/52820911-95127100-30ad-11e9-85d4-85502e594e8b.png">

**Comment by raphaelm** [comment]
That kinda makes sense, because the intent of validate_cart was to check if the *composition* of the cart was valid, i.e. if the combination of products is allowed. Therefore, the user is thrown back to 

I believe we need to introduce a new signal that is called either in ``pretix.base.forms.questions.BaseQuestionsForm.clean`` or in ``pretix.presale.checkoutflow.QuestionsStep.is_completed``.

A very dirty hack that *might* work would be to use the ``question_form_fields`` signal to pass form fields with custom validators attached that *override* the auto-generated form fields by using the same field name.

**Comment by Zambiorix** [comment]
You could also solve this by remembering the current tab and staying there?
`pretix.base.signals.validate_cart` is sent on every step in the checkout process (I have noticed).
If there is an issue with the composition of the cart, this would have been detected and handled before the "Your Information" step. After the "Add-on products" step, it makes no sense to validate the cart, because the cart can't change anymore?

But it also makes sense to separate the signals, just for sake of clarity.

**Comment by raphaelm** [comment]
> `pretix.base.signals.validate_cart` is sent on every step in the checkout process (I have noticed).
> If there is an issue with the composition of the cart, this would have been detected and handled before the "Your Information" step. After the "Add-on products" step, it makes no sense to validate the cart, because the cart can't change anymore?

You are right, it wouldn't strictly be necessary to call this in every step. However, it's not that simple: There is no persistent notion of someone currently "being" in a step other than what's in the URL and we need to prevent that someone e.g. just skips the add-on step by entering the URL of the questions step to avoid this validation. But yes, we could change where the error message takes you. Currently, it always points to the previous step, we could change this to the current step but we'd need to double-check if that makes sense in all cases.

**Comment by Zambiorix** [comment]
> A very dirty hack that _might_ work would be to use the `question_form_fields` signal to pass form fields with custom validators attached that _override_ the auto-generated form fields by using the same field name.

I can confirm that this is not working,  I just get double fields

**Comment by raphaelm** [comment]
Hmm, meh. Are you sure you're guessing the field names correctly? Since Django stores fields in an OrderedDict, it's hard to imagine to get double fields, since dictionaries do not allow to set keys twice.

**Comment by Zambiorix** [comment]
Well that puzzled me too ..

But this is what I have and with that double fields are shown..

```
    fields = {}

... I add other fields here on various conditions ..

            fields['dt_dateofbirth'] = forms.DateField(
                label=_('Date of birth'),
                required=True,
                help_text="",
                validators=[validate_date_of_birth],
                widget=forms.SelectDateWidget(years=dateOfBirthYears),
            )
    return fields
```

<img width="613" alt="screen shot 2019-02-19 at 12 57 14" src="https://user-images.githubusercontent.com/485492/53013392-f89df500-3445-11e9-88e2-9055c694625b.png">

**Comment by Zambiorix** [comment]
I'm not sure what you mean by "guessing the field names" .. is the name different from the internal identifier of the question?

Note that before a few days I only knew Python & Django by name (steep learning curve)

**Comment by raphaelm** [comment]
No, the name (i.e. the key in the fields dictionary) is probably something like question_1234, you can see it as the last part of the name="" attribute of the HTML element.

**Comment by Zambiorix** [comment]
I will look at it when I have more time. I have currently solved it by removing all my questions and adding them via the plugin. I have control over the order and the validation of all fields (15 in our case).

Well all validations work like a charm, I even used disabled fields to display other data (we assign a startnumber for our participants and I assign one when the order is placed) 

But I have exception that pops up (see below the image)

![screen shot 2019-02-19 at 20 24 21](https://user-images.githubusercontent.com/485492/53041547-931d2900-3484-11e9-8a70-75dd03fb13c1.png)


When a correct date of birth is given and I press continue, I get:

```
Object of type date is not JSON serializable
```

It looks like the forms.DateField is not serialised? If I remove only that field, everything works.
That field was the whole reason to put everything in a plugin :-(

**Comment by Zambiorix** [comment]
I guess the solution would be to create a complete custom widget?

**Comment by raphaelm** [comment]
Serializing/deserializing dates and times is always hard. For example, you'll want to *show* and *edit* dates in a locale-dependent date format but *store* them in a locale-independent format. A major part of our questions logic deals just with this issue. We could solve the serialization exception by passing ``cls=CustomJSONEncoder`` (with CustomJSONEncoder from pretix.helpers.json) to the ``json.dumps`` call that causes the exception (feel free to create a PR for this), which would auto-serialize the date in ISO8601 format to the database. However, you'll still see problems during deserialization, I assume.

You can probably solve this with a custom ``Field`` class that subclasses ``CharField`` but uses ``DateWidget`` for the display layer and translates back and forth between the data types.

**Comment by Zambiorix** [comment]
Thanks for the feedback!

> You can probably solve this with a custom `Field` class that subclasses `CharField` but uses `DateWidget` for the display layer and translates back and forth between the data types.

I'm actually trying that right now :-) It's fun learning a new language and environment, albeit time consuming :-(
I tried to do the opposite first; subclassing DateField, but that was a dead end...

**Comment by Zambiorix** [comment]
I fixed it by combining `forms.CharField` with a subclassed `forms.SelectDateWidget` and doing the appropriate changes there. Now it works in all locales.

Thanks!
