### ISSUE TITLE
pretix.event.order.placed.required_approval not called

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1172]
In webhooks, when is this action called?

`pretix.event.order.placed.required_approval`

I have enabled order approval. When ordering, I get `pretix.event.order.placed` and when approving I get `pretix.event.order.approved`, but I never get the above webhook.

**Comment by raphaelm** [comment]
It's called here:

https://github.com/pretix/pretix/blob/70fcba96a54d890500dc113b1d62455dbd50a54a/src/pretix/base/services/orders.py#L569

Seems like we got a typo there, though. Fixed in 166f8b8a, but you might need to configure your webhook again.
