### ISSUE TITLE
Making Nicknames more prominent

### ISSUE THREAD

**Issue by r-dannhauer** [pretix/pretix#1175]
We are using Nicknames for our events, but the problem is that they don't show up on order details or the checkin list. This is frustrating if you need to verify that a certain nickname is member of an organisation. During Check in I can't search for the nicknames, and printing badges won't allow me to use nicknames. I can select them, but it's the "normal name" that is being printed.
Is there a workaround?

**Comment by raphaelm** [comment]
pretix has no concept of "nicknames", so please clarify whether you use the attendee name field or a custom question. In both cases, you should totally be able to use it on badges.

**Comment by r-dannhauer** [comment]
I'm using the field "Rufname".

**Comment by raphaelm** [comment]
> printing badges won't allow me to use nicknames. I can select them, but it's the "normal name" that is being printed.

Which version of pretix are you using? This has been fixed in 2.4.0 (commit 71de71e), as far as I can see.

> During Check in I can't search for the nicknames

Hmm, right, we currently only search the string serialization of the name, which in this naming scheme is the full name. I'm not sure we can do something about that easily.

**Comment by r-dannhauer** [comment]
That got fixed in 2.4? Then it's high time for me to update. I postponed the update due to the start of ticket sales. Thanks!

If it can't be easily fixed then there's no issue. If people don't have their tickets ready, it's their problem.
All right, thanks for the quick info! Have a great day.

**Comment by r-dannhauer** [comment]
As stated, it works in current version. Thanks :)
