### ISSUE TITLE
Consistent handling of linefeeds in PDF preview and renderer

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1177]
I create a custom PDF layout field with following code:

```
@receiver(layout_text_variables, dispatch_uid="pretix_dodentocht_layout_text_variables")
def dt_layout_text_variable(sender, **kwargs):
    return {
        "dt_startnumber": {
            "label": _("Startnumber"),
            "editor_sample": _('Startnumber\n{0}').format(1234),
            "evaluate": lambda orderposition, order, event : dt_fetch_startnumber(sender, orderposition, order, event)
        }
    }
```

Notice the "\n" in the sample format. The evaluate function gets also a string that contains a linefeed.

It works in the editor:

<img width="699" alt="screen shot 2019-02-18 at 15 02 53" src="https://user-images.githubusercontent.com/485492/52957835-fc247400-3392-11e9-8958-12ec94569bd3.png">

But is does not, in the final PDF ticket generation:

<img width="702" alt="screen shot 2019-02-18 at 15 05 55" src="https://user-images.githubusercontent.com/485492/52957877-12323480-3393-11e9-8661-bbb366e299f2.png">

I can confirm that the final data for the ticket contains a linefeed

```
DEBUG 2019-02-18 14:40:49,439 urllib3.connectionpool connectionpool http://127.0.0.1:2345 "POST /startnumber HTTP/1.1" 200 17
INFO 2019-02-18 14:40:49,440 Dodentocht-Plugin signals -----> Startnummer
9
INFO 2019-02-18 14:40:49,595 celery.app.trace trace Task pretix.base.services.tickets.generate[b2fc700b-960d-4b73-805b-ddee56d48396] succeeded in 0.6571914740000011s: 44
```

**Comment by raphaelm** [comment]
Can you try a ``<br />\n`` instead of the ``\n``? That should work. We probably can't do much about the inconsistency between the two renderers.

**Comment by Zambiorix** [comment]
Solved! Thanks!
