### ISSUE TITLE
installation in path containing sub-dir

### ISSUE THREAD

**Issue by knarrff** [pretix/pretix#1180]
I am trying to install pretix in an environment where the same machine also hosts other stuff, so I have it configured like this (pretix.cfg):

[pretix]
url=https://derse19.uni-jena.de/pretix/

Note the sub-directory after the hostname. Everything pretix-related should be within that namespace of the web server. Correspondingly, I've setup the proxy:

location /pretix/ 
...
location /pretix/media/
...
location /pretix/static/
...

Now I can reach pretix through the proxy under "https://derse19.uni-jena.de/pretix/", but the html I get back does not take the sub-path into account when it comes to links (css/href/...).

What I did first is following the installation tutorial (using postgres), but when I realized that I needed the /pretix/ subdir I adapted the pretix and proxy config files. Should this have been sufficient? It didn't change the result for pretix; the proxy seems to work fine.

I did restart pretix-web and pretix-worker.

**Comment by pc-coholic** [comment]
Sorry to say, but running pretix in a subdirectory is not supported. You'll have to use (sub-)domain.

**Comment by raphaelm** [comment]
Correct, we stopped supporting this years ago. In principle, Django has support for the ``SCRIPT_NAME`` variable which allows things like this and we did some effort to comply with it. However, it was *lots* of work and the rest of the Django world doesn't care at all, so we needed to [fix dependencies](https://github.com/heroku-python/dj-static/pull/43) which didn't even care about our fixes :(

**Comment by knarrff** [comment]
Oh, well. That was the answer I feared. One would think this would be a no-brainer, just me missing a configuration option. But I appreciate your fast answer and understand your reasons, so: thanks! There is not much you can do when important dependencies aren't supporting this.
