### ISSUE TITLE
django messages not translated

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1182]
I have noticed that some messages are not translated. I assume they are not Pretix messages but originate from Django?

<img width="678" alt="screen shot 2019-02-19 at 18 36 39" src="https://user-images.githubusercontent.com/485492/53035336-7c230a80-3475-11e9-9cdf-6aa0b36ac226.png">

**Comment by raphaelm** [comment]
Neither, those are messages directly from your browser (caused by HTML-level form validation) :)

**Comment by Zambiorix** [comment]
Ok, now I feel stupid 8-)
In my defence, I always use Firefox and for this project switched to Chrome, so I was a little confused :-)
