### ISSUE TITLE
Display order of questions via plugin

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1185]
In the local development environment of pretix where I test the development of my plugins:
- I see the questions from `question_form_fields` show up exactly in the order I have implemented them in code

As soon as I deploy my plugin to my staging/production environment (installed via pip on a remote server) I notice that questions are scrambled.

My staging/production environment is 2.4. And my local development environment is from 2 or 3 days ago. I have checked the commits but can't see anything related to this.

Has this been addressed recently or is there something else playing?

**Comment by raphaelm** [comment]
Can you test if you run an older python version on your sever? The ``dict`` gained consistent ordering only in 3.6(?). You can use ``collections.OrderedDict`` to force ordering

**Comment by Zambiorix** [comment]
Yup, that's it `Python 3.5.2` on my server

Thanks!

**Comment by Zambiorix** [comment]
Since I don't know much about python, does it matter much for Pretix?
Would you suggest updating python on my server for particular reasons?
(3.5.2 on my sever, 3.7.2 local)

**Comment by raphaelm** [comment]
No, just use OrderedDict in your plugin (if that helps). pretix runs fine with 3.5 for now, we'll likely drop support for 3.5 when we upgrade to Django 3.0 – probably no earlier than early 2020 (Django 3.0 is scheduled to be released this December).

**Comment by Zambiorix** [comment]
The update to `OrderedDict` works, thanks!
In that case I'll postpone an update to 3.7 until after our event in August.

**Comment by rixx** [comment]
Just a short note: Curently, at least one of pretix's dependencies do not work with Python 3.7, so any update should only be up to Python 3.6. There is hope that this issue will be resolved by summer though.

**Comment by Zambiorix** [comment]
Thanks!
Our event is mid August, until then, not setup changes on the ticket-server. After the event we have (I need!) a cool down period. So no updates until late fall...
