### ISSUE TITLE
enhancement : allow unix socket uri for webhooks

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1188]
We have a single server setup and our own backend daemon installed that handles all webhook calls from pretix. We also have installed a newly developed pretix plugin that communicates with our backend daemon via unix sockets (performance / resources).

It would be great if pretix would also accept unix socket uri's for webhooks.
In my plugin module, I only had to import `requests-unixsocket`, and monkeypatch the `requests` module. The rest of my code works out of the box.

The field in pretix where you have to enter the webhook uri has to be more liberal on what it accepts, though.

https://pypi.org/project/requests-unixsocket/

**Comment by raphaelm** [comment]
I've never thought of doing local HTTP via unix sockets, fun idea! :)

Hmm, do you think this might have security impact? Even though there is not much control over the contents of a web socket request, it doesn't feel good to let a web interface user open up connections to arbitrary unix sockets – think e.g. of the usually unauthenticated unix socket of redis, that is readable to the web server process in most pretix setups.

I agree that this isn't a problem on self-hosted servers where you trust all your users with sufficient permissions to set up web hooks, but in any shared system this is likely a concern. If we add this, we'd probably need to hide it behind a configuration flag in pretix.cfg and couldn't turn on on pretix.eu. At that point, it might as well be a plugin that does the monkeypatching? Unsure here.

**Comment by Zambiorix** [comment]
I agree that security could be an issue, but for self-hosting (in our case 3 people in our team have access to those settings) I don't see too many issues. Hiding it behind a config flag would be perfect.

I am unsure how monkeypatching works in python. Is it application global? or only in the plugin? Not sure. I wanted to test that, but I can't change to url due to constraints in the the field.
I'll try later changing the url in the database directly and see if it works

On a side node:
We use the same server during the our event to handle participant geo tracking. 6 million hits in a few hours. Our tracking daemon originally listened on 127.0.0.1 with an nginx reverse-proxy in front for ssl termination. Later, I started listening on unix sockets and nginx forwards to that socket. We saw immediate improvements in performance. Unix sockets use much less resources and have higher performance that web sockets.

Pretix also uses nginx, so maybe it could benefit from the same strategy?

**Comment by raphaelm** [comment]
> I am unsure how monkeypatching works in python. Is it application global? or only in the plugin? Not sure. I wanted to test that, but I can't change to url due to constraints in the the field.

Monkeypatching, when done right, should be thread-global, so as long as the monkeypatching code is imported before the code that uses the monkeypatched function, it should be fine, and in some other cases as well. But yeah, using a config flag is probably cleaner.

>  We use the same server during the our event to handle participant geo tracking. 6 million hits in a few hours. Our tracking daemon originally listened on 127.0.0.1 with an nginx reverse-proxy in front for ssl termination. Later, I started listening on unix sockets and nginx forwards to that socket. We saw immediate improvements in performance. Unix sockets use much less resources and have higher performance than web sockets. nginx uses a websocket+port for each incoming request and one for forwarding. So forwarding to unix sockets frees up websockets+ports for incoming requests.

You can easily use pretix with websockets, just replace the ``--bind`` argument in [your gunicorn command like](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html#start-pretix-as-a-service) with the path to an unix socket, done! I'm leaning a bit against changing it in the (beginner-oriented) tutorial, since unix sockets are a bit harder to work with (file permissions, etc.), especially when it comes to setups involving docker or similar things.

**Comment by Zambiorix** [comment]
Ok, I've run some tests.. 

I have done the monkeypatch in my plugin and then changed the uri for the webhook in the sqlite database. It works just fine, no issues there

When I deploy my plugin to my production environment (pip installed 2.4) and change the uri in the database, it doesn't work ... not sure why (I have to test some more to see it there is something else wrong (with my socket for example))

**Comment by raphaelm** [comment]
Hmm weird, probably something related to how threads are handled differently… Where do you perform the monkeypatching in your plugin?

**Comment by Zambiorix** [comment]
in the signals.py file right after the imports ...

**Comment by raphaelm** [comment]
Meh :\ I hoped that would work. Sorry, not a really good idea here right now (instead of a PR to pretix to add in that option).

**Comment by Zambiorix** [comment]
no worries .. it's not that important
When the sales of our event are started I maybe have some more time to do coding. I'll try to see if I can patch pretix following your guidelines...
