### ISSUE TITLE
Request: change default number of tickets from 0 to 1

### ISSUE THREAD

**Issue by mdehollander** [pretix/pretix#1190]
Currently, the default number of tickets is 0. When redeeming a voucher by using the voucher code in the url, sometimes people just click on 'add to cart' without changing the number of tickets. That is a bit confusing. It would be nice to have a default ticket number, or be able to set it. Maybe even via the redeem link: `redeem?voucher=<code>&number=1`

**Comment by raphaelm** [comment]
Ah, we apparently only fixed this for single-use vouchers. Thanks :)

**Comment by mdehollander** [comment]
:+1:
