### ISSUE TITLE
Different payment methods for different products

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1191]
Is there a way to select different payment methods for different products?

We want to accomplish the following:
We have individuals buying a ticket and a group responsible buying tickets (in several steps) for several people in his/her group.

Individuals can _not pay_ manual and group responsibles _must pay_ manual.

Group responsibles receive an invoice when they have completed buying for all members.

Currently I have solved this by creating a normal ticket and a group ticket. The group ticket can only be bought by a group voucher with a specific quotum. 

The problem now is, I have to set the payment method to Stripe for the individuals, but I must not enable manual payment for them. And I need manual payment for the group ticket.

Currently I set the price for the group ticket to 0, and that works, no payment step during checkout.
But then in the pretix backend we have to calculate manually what invoice we have to send (a ticket can have several merchandise items), I would love to see the numbers there too

Any idea how I can solve this?
A solution would be to split into two events, but then I have trouble with my quota

**Comment by pc-coholic** [comment]
This is more of a hack than a proper solution... But here we go...

Assuming a group ticket costs more than a single ticket and you can limit that individuals' carts dont go over the price of a group ticket (for example by limiting the amount of single tickets per transaction to 1), you could use the "Minimum order total" and "Maximum order total" of the Stripe and Manual Payment method to create a makeshift filter of which payment methods are available.

**Comment by Zambiorix** [comment]
unfortunately the prices are the same :-( that route is no option ..

**Comment by raphaelm** [comment]
> Is there a way to select different payment methods for different products?

Unfortunately, no. We kinda dismissed that in #815 since it gets too complicated and there are rare real use cases.

Since you're rolling your own plugins already, the way to hack it would be:

* Create subclasses of e.g. ``StripeCC`` and ``ManualPayment`` in your plugin and register them as a custom payment provider.

* Override ``is_allowed(self, request: HttpRequest, total: Decimal=None)`` on those subclasses to add a check for the cart contents. You

**Comment by Zambiorix** [comment]
I am working on this, but have difficulties getting the cart contents from the is_allowed method ...
The only object I have is the request info, but I can only see a session id and csrf token in there. I guess I must get the cart from the session, but I'm unsure how. Can you point me the right direction?
Thanks!

**Comment by raphaelm** [comment]
there's a ``get_cart`` method in ``src/pretix/presale/views/__init__.py``, that gets the cart from the session. it even uses a per-request cache to avoid multiple lookups during one request cycle

**Comment by Zambiorix** [comment]
Ok, it works, Thanks! :-)

I had to do some more overriding in the `ManualPayment` subclass, but nothing serious.

For those interested, this is how I did it:

I divided tickets and merchandise in different categories: `ticket-individual` & `ticket-group`
Based on @raphaelm approach, I subclassed `ManualPayment`, `StripeCC`, `StripeGiropay`,`StripeIdeal` ...
... and registered them as a new payment provider.

For group-tickets, only manual payment is allowed, for individual tickets only Stripe methods are allowed. Both Stripe & Manual Payment plugins can now be enabled or disabled, it all still works.

```
# dt_register_payment_providers
#
@receiver(register_payment_providers, dispatch_uid="payment_dodentocht")
def dt_register_payment_providers(sender, **kwargs):
    return [
        DodentochtManualPayment,
        DodentochtStripeCC,
        DodentochtStripeGiropay,
        DodentochtStripeIdeal,
        DodentochtStripeAlipay,
        DodentochtStripeBancontact,
        DodentochtStripeSofort,
        StripeSettingsHolder,
    ]


# DodentochtManualPayment
#
class DodentochtManualPayment(ManualPayment):

    @property
    def is_implicit(self):
        return False

    def is_allowed(self, request: HttpRequest, total: Decimal=None):
        for position in get_cart(request):
            if not position.item.category.internal_name.endswith('-group'):
                return False
        return BasePaymentProvider.is_allowed(self, request, total)

    def order_change_allowed(self, order: Order):
        return BasePaymentProvider.order_change_allowed(self, order)


# DodentochtStripeCC
#
class DodentochtStripeCC(StripeCC):
    def is_allowed(self, request: HttpRequest, total: Decimal=None):
        for position in get_cart(request):
            if not position.item.category.internal_name.endswith('-individual'):
                return False
        return super().is_allowed(request, total)
```

**Comment by Zambiorix** [comment]
I found an issue that I'm unsure how to solve.
using above implementation, I have 2 categories, one for individual- and one for group tickets. Individual tickets are sold via Stripe payments. Group tickets are sold only with a voucher via invoice (we use our own invoicing system) and uses Manual Payment.

Above implementation works fine when the initial order is made.
But when a group ticket is sold (and only manual payment is visible = ok), and the link is sent to the customer. The customer sees the order at its unpaid status and can change the payment method. But the `is_allowed` is not called anymore. All enabled payment providers are visible ... 

Shouldn't `is_allowed` be called at that stage too?

**Comment by raphaelm** [comment]
We can't use ``is_allowed`` here, since it works on the cart data structures but we only have orders at this point. Can you try ``order_change_allowed`` instead?

**Comment by Zambiorix** [comment]
Yup, that fixed it
Thanks!
