### ISSUE TITLE
Sched integration

### ISSUE THREAD

**Issue by bumbleblue** [pretix/pretix#1193]
A feature request for integration with [Sched](https://sched.com/), specifically replacing [Eventbrite integration](https://sched.com/eventbrite-sync) 😜

**Comment by raphaelm** [comment]
What are the most important features for you in such an integration?

**Comment by bumbleblue** [comment]
Sched is becoming increasing popular as an event management tool - it allows people to pick an individual program, which is extremely helpful when there’s a large program offering. I have heard organisations choose services like Eventbrite for their integration with Sched (i.e. you automatically create Sched accounts for registered participants).


(Sched itself is far from perfect of course, so if Pretix could build an alternative tool that’s also very welcome ^^’)

**Comment by raphaelm** [comment]
> Sched is becoming increasingly popular as an event management tool - it allows people to pick an individual program, which is extremely helpful when there’s a large program offering. I have heard organisations choose services like Eventbrite for their integration with Sched (i.e. you automatically create Sched accounts for registered participants).

Sure, but the thing is: Even after reading their marketing material, it is … rather unclear to me what that integration actually can do and which of the features are actually useful and important. So before we do anything here, we should absolutely talk to someone who uses it.

> (Sched itself is far from perfect of course, so if Pretix could build an alternative tool that’s also very welcome ^^’)

That's not something we plan, but @rixx solved many of the same problems with [pretalx](https://pretalx.com).
