### ISSUE TITLE
Rest API remarks

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1195]
I found some inconsistencies the the rest-api documentation:

**Items --> Resource description**

picture --> string --> does not mention it can be null

original_price --> string --> does not mention it can be null

**Item variations --> Resource description**

price --> string --> the returned value is not a string but a number

I mention this because my backend marshals api data into typed data and knowing if certain types can be null is critical.

I have not tested all feedback in all conditions, so there might still be other issues.

**Comment by raphaelm** [comment]
The items documentation has been fixed, for the variations we'll change the datatype since that was a bug, we don't ever supply money as a float on purpose.
