### ISSUE TITLE
Pay what you want Ticket: default value

### ISSUE THREAD

**Issue by navlisilvan-old** [pretix/pretix#1196]
I hope there will be no similar issue, i didn´t find one but i am not very familiar with github.

I would be really happy to have a default value for the "pay what you want"-Ticket. At the moment the lower threshold is the default and the customer has to click +++ or enter a number. 
I Would like do have the default value to be configured in the control panel, so that the customer has to click --- to select a lower price (or +++ for a higher price or enter a number).

e.g.:
Tickets will be sold from 10€. At The moment when you enter the ticket-shop there will be shown 10€ and the customers can enter more.
We would like to have it this way:
Tickets will be sold from 10€. Default Value is 20€. When you enter the Ticket-shop there will be written 20€ and you can click more or less until 10€.

**Comment by navlisilvan** [comment]
We did a hack for this problem, we added  `add:'10'|` to to line 387 of src/pretix/presale/template/event/index.html

`value="{% if event.settings.display_net_prices %}{{item.display_price.net|add:'10'|money_numberfield:event.currency }}{% else %}{{ item.display_price.gross|add:'10'|money_numberfield:event.currency }}{% endif %}"`


:)

**Comment by raphaelm** [comment]
We could re-use the `original_price` field for this, although it is a little  unclean to use it for two purposes. Anyone has thoughts on this?

**Comment by raphaelm** [comment]
Fixed in #3666
