### ISSUE TITLE
Question: Multi-use tickets

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1197]
We're looking for a way to sell a single ticket that can be used a specific number of times for admission to an event. In this context we use “event” in a very broad sense, e.g. “admission to a public swimming pool”, where it makes sense to gain entrance more than once.

We haven't found a way to achieve this with Pretix and it may be completely out of scope. However, given the impressive set of features it may still be possible to sell multi-use tickets with Pretix. 

We've been thinking about using vouchers that can be redeemed multiple times, but these must be generated manually (or using the api) and even with a voucher the customer must buy multiple tickets and keep track of which have been used.

Any suggestions or comments will be appreciated.

Best regards,
Mikkel

**Comment by raphaelm** [comment]
Hmm, yes, I see the problem. I'd consider it slightly out of scope, but not completely impossible. Usually, such things would be solved through check-in lists. For example, you could create a new check-in list every day that includes all of these tickets, thus making every ticket valid once per day. To make it valid $infinity times … well, the easiest would be to just run your own patch of the scanning app and ignore the "ticket already used" message for that product? Would be nice to do this on the server side as well, though, so you can still log entries.

**Comment by rimi-itk** [comment]
Thanks for your comments. We'll look into check-in lists and see if we can come up with a viable solution.
