### ISSUE TITLE
Stripe: Credit Card is not working

### ISSUE THREAD

**Issue by gleichaberanders** [pretix/pretix#1204]
Its not possible to pay with credit card. You just see a "loading" icon in the field. If you Switch to the Stripe Checkout. I just got a red warning box "Please enable javascript to proceed with stripe checkout". 
<img width="1201" alt="Bildschirmfoto 2019-03-12 um 17 47 34" src="https://user-images.githubusercontent.com/48489114/54219290-88880980-44ef-11e9-881c-7fd7a375345d.png">
Info: It seems like something with the js, if you proceed to the payment page. All Payment Option "Boxes" are open. I think they should be folded if you visit this page for the first time.

**Comment by gleichaberanders** [comment]
<img width="1185" alt="Bildschirmfoto 2019-03-12 um 17 58 08" src="https://user-images.githubusercontent.com/48489114/54219798-72c71400-44f0-11e9-878a-737cfef0f14a.png">

**Comment by raphaelm** [comment]
Can you take a look at the error console of your browser (usually F12) and maybe post a screenshot of that? Any issues with loading the JS should be noted there.

**Comment by gleichaberanders** [comment]
It was just a cloud flare problem. A js file could not be loaded because of security reasons. I just had to exlude it. Thanks for the fast reply!
