### ISSUE TITLE
Layout incorrect in Paid status (Pending status is ok)

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1205]
I have used manual payment and noticed a inconsistency in rendering in different status:
(when order is shown as user or using the link)

Pending status (looks correct)

![Screen Shot 2019-03-12 at 21 43 12](https://user-images.githubusercontent.com/485492/54235053-b467b700-4510-11e9-9b79-a8ab0039b5c6.png)

Paid status

![Screen Shot 2019-03-12 at 21 45 05](https://user-images.githubusercontent.com/485492/54235066-ba5d9800-4510-11e9-97c5-4eab7819d9ef.png)

**Comment by raphaelm** [comment]
Interesting. Can you post your screen resolution as well? THis is probably size-dependent.

**Comment by Zambiorix** [comment]
This is what I see in Chrome at >= 992px width:

![Screen Shot 2019-03-13 at 12 02 48](https://user-images.githubusercontent.com/485492/54274316-144d7480-4588-11e9-8c0a-2dea110a0c7b.png)

And this at < 992px

![Screen Shot 2019-03-13 at 12 03 08](https://user-images.githubusercontent.com/485492/54274343-25968100-4588-11e9-8d45-809a25e8436e.png)
