### ISSUE TITLE
Enhancement : Ticket generator exceptions -> better output

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1207]
I have developed a Ticket generator in my plugin. But the ticket itself is not generated in the plugin, it is created & fetched via a rest call from another backend when `generate` is called.

That works as intended. Except, when something is wrong with the backend (absent, timeout, etc). In that case I raise an exception in the `generate` method with a user friendly text : `Ticket currently not available, please try again later.`

Pretix unfortunately shows a message `An unexpected error has occurred`
It would be great if Pretix catches exceptions from `generate` and shows the message from those exceptions.

**Comment by raphaelm** [comment]
Sorry to disagree here: In 99% of cases, exceptions during ticket creation are very technical and unresolvable for the user. I agree that in your case a custom message is wanted, but most exceptions wouldn't be useful to the user, so we'd need to create a custom exception class for this, which I don't see warranted for the narrow use case.

However, we might just rephrase the default error message in a more actionable way and add a "…, please try again later."
