### ISSUE TITLE
Configure workers count in a better way / crash in small machines

### ISSUE THREAD

**Issue by vitorreis** [pretix/pretix#1208]
Relates to #899 

I am trying to run the project in a small machine.
The current setup for how many worker to run is getting wrong info about my machine and spawning too many workers, they compete for cpu and all timeout making the impossible to get the process up and running.
https://github.com/pretix/pretix/blob/master/deployment/docker/pretix.bash#L6

My machine has 2 cpus for example
```
root@ns3035370:~/pretix# cat /proc/cpuinfo | grep "cpu core"
cpu cores	: 2
```
However the command that is currently used identifies 4 and try to spawm up to 8 workers....
```
root@ns3035370:~/pretix-tome-forro# nproc
4
```

In addition to that, I could use the gunicorn timeout configuration to be more forgiven there and allow it to run, [gunicorn](http://docs.gunicorn.org/en/latest/settings.html) can set configuration through environment variable, so what do you think about using it to allow configuration of the image?

My end goal is to be able to run the image with fewer workers, and perhaps also specify a more forgiving timeout for the workers.

**Comment by raphaelm** [comment]
Feel free to create a PR that introduces an environment variable to control this, as long as it stays backwards-compatible :)

**Comment by raphaelm** [comment]
This is now configurable
