### ISSUE TITLE
OfflineGenerationError in image: "pretix/standalone:stable"

### ISSUE THREAD

**Issue by vitorreis** [pretix/pretix#1213]
relates to https://github.com/pretix/pretix/issues/244

the compress it was supposed to be done in the build of the docker image, however I get the error in production build using `image: "pretix/standalone:stable"`

![image](https://user-images.githubusercontent.com/674229/54368886-425cb280-4675-11e9-90ea-a4df6659b94b.png)

**Comment by vitorreis** [comment]
Update... 
Seems that if I run with django debug mode off the problem doesn't happen.

**Comment by raphaelm** [comment]
Great
