### ISSUE TITLE
Image Preview failed / Disable Image Loader

### ISSUE THREAD

**Issue by gleichaberanders** [pretix/pretix#1219]
In comparsion to the hosted version, the cgn is not available. Does anyone other have this bug?

Refused to load the image 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==' because it violates the following Content Security Policy directive: "img-src *".

It would be great to just disable the image loader:

<img width="1226" alt="Bildschirmfoto 2019-03-18 um 21 54 57" src="https://user-images.githubusercontent.com/48489114/54563093-a3afb900-49c8-11e9-8535-fbe4dbf0fce4.png">

**Comment by raphaelm** [comment]
The self-hosted version should not depend on the CDN in any way. I haven'T ever see the data URL, can you find out where it is coming from? The weird pictures at the bottom look like they are from the lightbox library, however they ended up there.

**Comment by gleichaberanders** [comment]
<img width="1319" alt="Bildschirmfoto 2019-03-21 um 03 43 40" src="https://user-images.githubusercontent.com/48489114/54778249-78b9a500-4c14-11e9-92a5-74e272d81d3d.png">
<img width="1641" alt="Bildschirmfoto 2019-03-21 um 03 43 16" src="https://user-images.githubusercontent.com/48489114/54778271-840cd080-4c14-11e9-81a5-e93e6165ee32.png">

**Comment by raphaelm** [comment]
Sorry, unable to reproduce this :(
