### ISSUE TITLE
Configurable frontend texts

### ISSUE THREAD

**Issue by jasle** [pretix/pretix#1221]
There seems not to be an easy way to configure all texts in the presale-frontend.
Would it be possible to make all texts in the presale configurable?

We are using pretix for the registration for events of a non-profit organization and have some doubt, that therms used by pretix by default sounds a little bit too commercial for us and this could be surprising for some people registration for events. So we would be happy to have an easy way to e.g. replace "order" with "register".

**Comment by pc-coholic** [comment]
I don't see an easy way to change this in the core in the near future.

Assuming you are using pretix in English, you could however create a new language translation file just for you, and only include the strings that refer to "order", "ordering", etc. in there.

If you then set that language as your events language, it should use your "translations" and fallback onto the regular English ones for all strings you haven't translated.

Just be aware, that this also means, that you'll have to update your "translation" every now and then.

When it comes to the emails that are being sent out to your participants, things are a lot easier: you can just edit the email-templates to be used for every event directly from the pretix backend and remove any occurrence of the word "order".
