### ISSUE TITLE
Tax exemption

### ISSUE THREAD

**Issue by jasle** [pretix/pretix#1222]
We are using pretix for registration for events of a non-profit organization. The participation fee for this events is tax exempt, so we have to display something like "VAT exempt according to ...".

Is there currently a (good) way to do this?
If not, would it be possible to implement a way to display something like that instead of the actual tax rates?

If you could hint me to the right point to start, would try to implement this.

**Comment by pc-coholic** [comment]
I'm assuming that you are running your own, self-hosted instance of pretix, right?

In that case, you could (with Admin mode enabled) edit the Global Settings and add this text as "Additonal Footer-Text". Then it will be display on all pages across all of your organizers and events.

If you are however sharing your pretix-instance with other organizers/events, that do not want that line, things are more complicated... In that case I would recommend to add the text to the event description text.

In any case, you might want to also add a corresponding line to your invoice- and ticket-template.

**Comment by katrinleinweber** [comment]
Would it make sense to implement a seperate (or even required) field for events in Germany, due to [UStG
§ 14 (4) 8. "[...] im Fall einer Steuerbefreiung einen Hinweis darauf, dass für die Lieferung oder sonstige Leistung eine Steuerbefreiung gilt"](https://www.gesetze-im-internet.de/ustg_1980/__14.html)?

**Comment by raphaelm** [comment]
I don't think we should clutter the invoice settings with fields for each and every piece of legislation in the many countries pretix is used in – we've got enough free-text fields on the invocies, I guess.
