### ISSUE TITLE
BUG: Payment cancelled by Stripe but still pending in Pretix

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1230]
About 5% of our payments are cancelled by Stripe (Payment authorization cancelled), but the event does not cause the payment in Pretix to be cancelled. The customer cannot try again ...

<img width="252" alt="Screen Shot 2019-03-25 at 11 35 27" src="https://user-images.githubusercontent.com/485492/54913319-c07d4c80-4ef2-11e9-8561-c8556488d256.png">

<img width="1233" alt="Screen Shot 2019-03-25 at 11 35 54" src="https://user-images.githubusercontent.com/485492/54913331-c8d58780-4ef2-11e9-9bca-dcfb14301d07.png">

<img width="1182" alt="Screen Shot 2019-03-25 at 11 35 40" src="https://user-images.githubusercontent.com/485492/54913339-cd9a3b80-4ef2-11e9-8fea-56573382a891.png">

**Comment by Zambiorix** [comment]
We sold 13,000 tickets on Saturday in 2 hours time. 95% went well, and 5% have this issue

**Comment by Zambiorix** [comment]
What we do know is to check if indeed the payment has been cancelled in Stripe, then manually cancel the payment in Pretix and send the link again to the user.

But I think this is a bug in Pretix?

**Comment by raphaelm** [comment]
This does look like a bug in pretix, yes. I'm unsure what's happening here, though. Can you reproduce it using Stripe's test API?

**Comment by Zambiorix** [comment]
I have never seen it in the test-environment (and we have tested it many many times)...
But with 13,000 tickets sold, we now have 500 orders with this condition

**Comment by raphaelm** [comment]
I get it, but that makes it hard to reproduce and find it ;)

**Comment by Zambiorix** [comment]
I understand. Can you confirm that I just have to cancel the payment in Pretix to open de link again for new payment attempts? We (I and a few volunteers) are working through the orders to rectify the situation. That will take some time. Later this week I'm able to investigate this further and get more data from the system if needed
