### ISSUE TITLE
Loading dashboard of event is very slow

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1235]
Loading dashboard of event with 13,000 orders takes about 15 seconds to load
On a 16 CPU server with 64GB ram
Database MariaDB 10.3.13 on SSD

**Comment by raphaelm** [comment]
How many quotas do you have? Is it still as slow after repeat loading (there should be some caching)?

**Comment by raphaelm** [comment]
(FWIW, I've got 30,000 orders in a test event with one quota on a 4GB-machine with 2 vCPUs and it loads in well under a second. However, quota calculations are usually the most expensive thing.)

**Comment by Zambiorix** [comment]
we have only 1 quota ..

**Comment by Zambiorix** [comment]
Ok, I think I know what's going on

**Comment by Zambiorix** [comment]
is `question_form_fields` called extensively during dashboard loafing?

**Comment by raphaelm** [comment]
I wouldn't know why, but I haven't checked

**Comment by Zambiorix** [comment]
I make a call to a rest api via uniz sockets on the same server to fetch a startnumber.
Startnumbers on that end are cached in ram, so blazing fast

15 sec would surprise me to fetch 13,000 startnumbers that way, but I'll check

**Comment by Zambiorix** [comment]
and to answer your question, loading the dashboard always takes 15 sec 
Maybe initial loading takes even longer, but due to high activity on our systems I'll have to postpone service reload

**Comment by Zambiorix** [comment]
All other activity is fast, no issues there. Also customer/user interaction was and is always fast

**Comment by raphaelm** [comment]
Workaround in https://github.com/pretix/pretix/commit/5363f4206e2f357dc02252e9aca59f87eca0e65d
