### ISSUE TITLE
Provide Apache ProxyPass example in docs

### ISSUE THREAD

**Issue by muzzol** [pretix/pretix#1237]
I'm configuring pretix with apache and I see there's an example in Docs with nginx.

I would like to find a similar example with apache and ProxyPass.

I'll try to post it here myself if I manage to configure it.

**Comment by rasos** [comment]
This is for Port 80 only (we do SSL at an Edge Proxy).

```
<VirtualHost *:80>

        ServerName pretix.domain.net
        ServerAlias *.pretix.domain.net
        DocumentRoot /var/www/html

        # ProxyVia On
        ProxyRequests Off
        ProxyPreserveHost On
        RemoteIPHeader X-Forwarded-For

        ErrorLog ${APACHE_LOG_DIR}/pretix_error.log
        CustomLog ${APACHE_LOG_DIR}/pretix_access.log combined

        <Location />
                Order allow,deny
                Allow from all
                ProxyPass http://localhost:8345/ retry=0 timeout=30
                ProxyPassReverse http://localhost:8345/
# Restrict access for testing
#        Require ip 123.123.123.00
        </Location>

</VirtualHost>
```
Works here, except that shopping cart confirmation is looping.

**Comment by if0xx** [comment]
It's implicit in the example above, but it seems critical that the Apache module proxy_html is NOT activated for Apache reverse proxying to work properly. To assure this include 

        ProxyHTMLEnable Off

into the config for your pretix site.

Example config:


<VirtualHost *:443>
        ServerAdmin webmaster@example.org
        ServerName tickets.example.org
        DocumentRoot /var/www/tickets-ssl/data

        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>

        <Directory /var/www/tickets-ssl/data/>
                Options FollowSymLinks MultiViews Indexes
                AllowOverride All
                Require all granted
        </Directory>

        SSLProxyEngine on
        ProxyHTMLEnable Off

        ProxyPass "/"  "http://localhost:8345/"
        ProxyPassReverse "/"  "http://localhost:8345/"

...

(further config truncated)

**Comment by sysadminpower2019** [comment]
@if0xx Hello,

do you have any idea how you would add CSRF headers for an apache example site. 
It seems that Pretix has add newer components and the existing docs from before no longer reflect the needs of the designers
