### ISSUE TITLE
Quota issue 

### ISSUE THREAD

**Issue by Zambiorix** [pretix/pretix#1238]
We have one quota of 13000.
All tickets are sold and we have a waiting list.

I have created a voucher for a specific group with a max usage set to 60
with:
reserve from quota: checked
allowto bypass quota: checked

We were able to create the voucher. With "allow to bypass quota" unchecked it was not possible to create (expected behaviour, our quota is used up)

We never used this voucher and later decided to delete it.

Now suddenly 60 vouchers are created for the waitinglist...

This is not expected behaviour. I would assume that if the "allow to bypass quota" is checked and the quota is used and the voucher is not used, then those 60 tickets are void.

Now we have a used up quota of 13000
and 60 extra tickets assigned to people in the waiting list...

How can we correct this problem?

A side note: we have a "special cases" voucher of 250
non of them touched
reserve from quota: checked
allowto bypass quota: unchecked

But if I lower that to 190, I'm afraid that another 60 get assigned to the waiting list ...

I hope I explained the situation clearly

**Comment by raphaelm** [comment]
Hmm, to be absolutely sure what happened I think the exact timing is relevant of when the vouchers were created in relation to the quota being sold out.

**In any case:** If the quota is 13000, the waiting list should never try to give out more tickets than to fill up that. Are you absolutely positive your quota was sold out *without counting those vouchers*? If they are "reserved", they will be counted as "sold" as long as they exist. Can you post a screenshot of the quota detail page (with the calculation table)?

**Comment by Zambiorix** [comment]
Yes, our quota was sold out.

We have special vouchers (on that quota) that are not all used. 
You can see pending orders to -54 .. that is  from the 60 released (6 have already bought a ticket)

![Screen Shot 2019-03-28 at 18 38 24](https://user-images.githubusercontent.com/485492/55179861-b2485e00-5188-11e9-9826-95865bf712d6.png)

![Screen Shot 2019-03-28 at 18 38 11](https://user-images.githubusercontent.com/485492/55179880-b70d1200-5188-11e9-95ab-d5aede281998.png)

**Comment by Zambiorix** [comment]
These are our vouchers:

We have 1079 reserved from quota and 465 already used.
= 614 remaining

But waiting list reservations is 789, that is confusing...

![Screen Shot 2019-03-28 at 18 45 23](https://user-images.githubusercontent.com/485492/55181053-1f5cf300-518b-11e9-8022-993616bf2835.png)

**Comment by raphaelm** [comment]
Hi,

as far as I see it, your quota adds up exactly.

You've got 12157+54=12157 in orders + 789 reservations which adds up to exactly 13000, so pretix didn't sell even one ticket too much. Those 789 are probably your 614 currently available vouchers¹ and 175 people on the waiting list who *currently* have the option to buy (and therefore also have a valid blocking voucher, that isn't shown in the voucher list).

If you delete some of these vouchers, this number 614 will go down. Accordingly, pretix will be able to send out more waiting list notifications to fill up the 13000 again. Frankly, I don't see the problem, this is working as intended.


¹ given that that number is correct, I didn't count it and your screenshot doesn't show which of the vouchers are blocking

**Comment by Zambiorix** [comment]
Yes, that seems logic. But I was surprised as soon as I deleted a voucher, 60 places in the waiting list received one ...
I'll recap how everything was initialised:

1. created 1 quota of 13000
2. made a few test orders and cancelled them afterwards
3. all quota available
4. created 17 vouchers as mentioned above (reserve from quota: **checked**, allow to bypass quota: **unchecked**) (product selected that is connected to quota)(1080 total)
5. dashboard shows quota (13000) and available tickets (11920), correct because 1080 are blocked in vouchers
6. sale starts
7. every available ticket is sold 2 hours later
8. the waiting list starts to fill up
9. as soon as a ticket is cancelled, immediately it is available for the waiting list (correct behaviour)
10. all the vouchers are unused, I lower the in one from 250 to 249 and immediately it is available for the waiting list (correct behaviour)
11. tried to create new voucher (60), but obviously failed because no quota is left (reserve from quota: **checked**, allow to bypass quota: **unchecked**)
12. create new voucher (60) successfully (reserve from quota: **checked**, allow to bypass quota: **checked**)
13. decided after a few hours that I didn't need that voucher after all and deleted it
14. immediately 60 places are available for the waiting list and get a voucher (after the regular interval of 15 or 30 min)

But if every available ticket is sold and al the remaining tickets are blocked in vouchers, where are those 60 seats coming from? Not from quota, that is sure.

I created that last voucher with reserve from quota: **checked**, allow to bypass quota: **checked**
But nothing was used. And when deleting that voucher I assumed that those 60 seats would just be rendered void and disappear. But because 60 seats were assigned to the waiting list when I deleted it, I wonder if there is a bug in Pretix, or my assumption of how the system works is wrong.

I have blocked automatic waiting list assignments, so nobody will get a new voucher. And I am waiting until the remaining waiting list vouchers expire or are used. Then I'll do the math again to see if everything adds up.

**Comment by raphaelm** [comment]
Weird. I get that the combination of "reserve" and "allow bypass" has confusing semantics, but from your explanation, the end result only makes sense if at least 60 tickets have been canceled between step 12 and 13.

**Comment by Zambiorix** [comment]
Yes, but that can be easily checked when the mails go out.
I have check Postmark, our transactional e-mail system and I can see at that exact moment 60 mails going out...

I also saw those "Waiting, product 60x available" labels in the waiting list. Seconds before this was just 0 ...

**Comment by Zambiorix** [comment]
I'll export the complete waiting list and take a snapshot of the quota overview and check If I can find more info

**Comment by Zambiorix** [comment]
Ok, everything adds up. there is no issues! 👍 

But I'm still flabbergasted about what I saw: before deletion 0 available, seconds after deletion 60 available in waitinglist

![Screen Shot 2019-03-29 at 13 06 50](https://user-images.githubusercontent.com/485492/55231680-acec2180-5223-11e9-88b4-41bba16e639e.png)
