### ISSUE TITLE
Test should be Text

### ISSUE THREAD

**Issue by HDValentin** [pretix/pretix#1248]
Typo in configuration at
https://pretix.eu/control/event/.../.../settings/display

![Pretix-Rechtschreibfehler](https://user-images.githubusercontent.com/1276955/55833217-837ea000-5b17-11e9-912d-860f9fff1bb5.jpg)

**Comment by pc-coholic** [comment]
Thank you for your report - I fixed the translation and with the next build of the language packs, this issue should be corrected.

If you find any other wrong translations, feel free to edit them directly at https://translate.pretix.eu/ - or post them here - whatever you prefer :)
