### ISSUE TITLE
Cannot approve order

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1255]
I sent a voucher for a free ticket to someone, who tried to place an order. This was on the day before the event, after the last possible payment date. Now it shows up that this order needs approval, but I can't approve it ("Einige der ausgewählten Produkte sind zwischenzeitlich nicht mehr verfügbar, bitte überprüfen Sie Ihren Warenkorb."). I still gave him the ticket, but this was not acceptable because the order is still pending.

**Comment by raphaelm** [comment]
To clarify, is your product set up to require approvals?

**Comment by DerDakon** [comment]
Yes, free tickets need approvals in this setup.
