### ISSUE TITLE
Plugin idea: raffle tickets 

### ISSUE THREAD

**Issue by David100mark** [pretix/pretix#1264]
Hey,

For our purposes it would be very helpful to raffle tickets among applicants. For example the drawing of tickets for workshops. 
The applicant should be able to apply for one or more courses and then be assigned to one (or no) course.

I suppose other shop owners can also use the feature, because one doesn't always want to sell after the first-come-first-serve.

**Comment by raphaelm** [comment]
Implemented e.g. in https://github.com/pretix/pretix-cliques
