### ISSUE TITLE
urllib3 version support >=1.25 for request 2.21.0

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#1272]
Trying to install pretix with python 3.7 on manjaro (arch) throws an error:

`ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
`

What are the changes made since 1.24.2 that make it incompatible? Or is it possible to simply change the requirements of requests to support the current version?

Changelog: https://pypi.org/project/urllib3/

**Comment by rixx** [comment]
To change the requirements of requests, you'd have to talk to the [requests](https://github.com/requests/requests) project. They are in the process of providing compatibility with urllib 1.25.

Are you installing pretix in your global system environment? Using any kind of virtual environment should take care of conflicts like that.

**Comment by bpcurse** [comment]
@rixx Thank you for the fast response!
A virtual environment is used as shown in "small-scale manual deployment" on pretix.eu

I could solve the problem by uninstalling urllib3 (in venv):
`pip uninstall urllib3`
and installing the last supported version:
`pip install -Iv urllib3==1.24.2`
