### ISSUE TITLE
status is "paid" and not changeable after refund

### ISSUE THREAD

**Issue by naturalgeek** [pretix/pretix#1273]
I'am using pretix 2.3.0, i know its not recent but i'am unable to do a upgrade in the current ticket phase.

After creating i refund, the payment status is still at "paid" and there is no button to change it.

Detailed Process was:

Payment Confirmed
{
  "local_id": 1,
  "provider": "banktransfer"
}

Order marked as paid:
{
  "force": false,
  "date": "2019-02-27T12:20:04.095Z",
  "provider": "banktransfer",
  "info": "{\"reference\": \"\\u00dcberweisungs-Gutschrift 2019-XXXXX NONREF\\XXXX-XXXX-02-27-XXXXXX\", \"trans_id\": 961, \"date\": \"2019-02-27\", \"payer\": \"XXX XXX XXX - DEXXXXXXXXXXXXXXXXXXXX\"}"
}

Manual refund created
{
  "local_id": 1,
  "provider": "manual"
}

Refund completed
{
  "local_id": 1,
  "provider": "manual"
}

Now the order page shows:

![broken_order](https://user-images.githubusercontent.com/3707331/57368281-0fbdca80-718b-11e9-9eaf-64afed405f3e.png)

**Comment by raphaelm** [comment]
Sorry, this appears to be a bug in 2.3. Upgrading to a recent version is the only fix I can think of right now :(

As a workaround, you can try to check if cancelling through the API works?
