### ISSUE TITLE
APIs for Checkin and POS not working

### ISSUE THREAD

**Issue by r-dannhauer** [pretix/pretix#1283]
I updated to the newest version today and wanted to try the Checkin App on Windows (and Android, as it turns out) and it returns an error when I try to search for a person.
I know it worked before, I don't know which version though, sadly. The error I get on the windows app is:
Error in eu.pretix.libpretixsync.check.OnlineCheckProvider.search(OnlineCheckProvider.java:149)
Invalid configuration, please reset and reconfigure.

The last part is also shown as error on Android.

Then, when I try to sync the POS Android app it doesn't even sync, I get the response that the server sent an invalid response.

//EDIT: For windows I tried the normal installable App, and the Java application.

**Comment by raphaelm** [comment]
> I updated to the newest version today and wanted to try the Checkin App on Windows (and Android, as it turns out) and it returns an error when I try to search for a person.
> I know it worked before, I don't know which version though, sadly. The error I get on the windows app is:
> Error in eu.pretix.libpretixsync.check.OnlineCheckProvider.search(OnlineCheckProvider.java:149)
> Invalid configuration, please reset and reconfigure.

This is weird, as we didn't touch that API in a long time. Can you look in your the web server logs what URL was requested and what the response code was?

We're in progress of replacing pretixdroid/pretixdesk with pretixSCAN on both platforms. We already uploaded a beta of pretixSCAN to the Google Play Store. Can you try if it shows the same problem?

> Then, when I try to sync the POS Android app it doesn't even sync, I get the response that the server sent an invalid response.

The POS API is not part of open source pretix.

**Comment by r-dannhauer** [comment]
I'll check the logs later. I tried the beta of PretixScan, but I can't generate a code for it. It tells me, that the configuration code is for the predecessor, yet my installation is up to date.

Regarding the pos, I was once able to connect it. So I assumed the sale of tickets at the event itself was in the open source packet. But now I know.

**Comment by raphaelm** [comment]
> I'll check the logs later. I tried the beta of PretixScan, but I can't generate a code for it. It tells me, that the configuration code is for the predecessor, yet my installation is up to date.

You'll need a code from the "Devices" section of your organizer account, not from the "Check-in" section of the event. Sorry for the confusion – we'll clear this up in the UI once pretixSCAN is fully released.

**Comment by r-dannhauer** [comment]
Okay, definetly my mistake. I missed the /api config in my nginx configuration. Sorry to bother, and thanks for the quick assistance :)
