### ISSUE TITLE
Activate quotas

### ISSUE THREAD

**Issue by loelkes** [pretix/pretix#1285]
Feature request to be able to set a quota without enabling it. I think this means to possibility of having back-orders instead of a waiting list.

Scenario: I order T-Shirts for a large event in two batches. The first large batch is set as quota but not activated. As I order the second batch shortly before the event I can just read the quotas / back-orders on the order overview page (see my comment in #302), correct the quotas and activate them (or disable back-orders depending on how it's implemented).

**Comment by raphaelm** [comment]
Sorry, I still don't really get what you're trying to achive. What do you mean by "enabling"/"activating"? What should that change? What do you mean by back-orders?

**Comment by loelkes** [comment]
Some way that a product can be fully configured without having it appear in the store. Quotas are set the moment they are linked to a product, no way of setting them and enabling them afterwards. I miss this feature (like configuring a product without having it on display at the store).

Backorders I mean that the quota can be overstepped without displaying it to the customer (e.g. not enabled quotas). In our case we don't need a waiting list as we just need to call our supplier to send more stuff as their stock is order of magnitudes larger than any amount of products ordered at our event. Example: Quota of 5, but 10 products ordered. The overview display -5 available so I know that I need to order 5 from the warehouse. The costumer sees none of this.

**Comment by raphaelm** [comment]
wontfix, no more use cases of this came up in over a year
