### ISSUE TITLE
Bugfix releases won't get the "stable" tag on DockerHub

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#1287]
Hi,

recently, there was release 2.7.1 of pretix. The release has not been tagged with the "stable" tag on DockerHub, which is the recommended tag to use when setting up da dockerized version of pretix. Due to the fact, that this is not a "beta" (non-stable) release, I would add the "stable" tag also to bugfix(/minor)-releases, so that users will get the bugfixed version when installing the software.

With best regards,
Jan Felix

**Comment by raphaelm** [comment]
Our docker configuration seems alright, however I apparently forgot the last ``git push`` to the correct branch. Sorry, should be building now!
