### ISSUE TITLE
Filter payment providers in orders view

### ISSUE THREAD

**Issue by joto** [pretix/pretix#1288]
When looking at  the orders, there are several drop down boxes for filtering. The drop down box for payment providers shows all payment providers which is a long list. Would be nice to only see the ones actually enabled or used. Maybe all enabled ones but if they are unused they show up slightly grayed out or so.

**Comment by raphaelm** [comment]
Hi, thanks for the idea! Unfortuantely, that's not gonna be feasible:

* We already only show payment methods from plugins that are enabled. If you disable a plugin at Settings > Plugins, those payment methods vanish.

* It's important to keep disabled provides around: If you disable a provider after a while, you might still have orders with that provider in your event!

* HTML ``<select>`` boxes don't have an easy way to make something "slightly grayed out" that preserves accessibility and still allows to select them.
