### ISSUE TITLE
documentation: Edit on github 404s

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1292]
for https://docs.pretix.eu/en/latest/index.html

**Comment by rixx** [comment]
Sphinx comes with its own linkchecker (`make linkcheck`). It might be worth to just include it in a CI run.

**Comment by raphaelm** [comment]
No, I think @ligi means the "Edit this page on GitHub" URL provided by ReadTheDocs, that points to the wrong location for the main index page (since we use a non-standard filename there apparently). All other pages seems to work?
