### ISSUE TITLE
Show last login timestamp of users

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#1296]
As an administrator, I may want to find out if a user account is still active (or how inactive a user is). I'd like to see the last login date in the administrative user view at /control/users/{id}/.

**Comment by kopite1986** [comment]
Hi. Is there is .py file for this please? Sorry for the basic question but I am new to github and keen to get started in helping. Thanks

**Comment by raphaelm** [comment]
Hmm, it looks like we currently do not even store ``last_login``, so it's gonna be a little more involved, sorry. Also, I'm not even sure if it's a good metric since an active login session can basically stay open forever and the last login might be long ago even though the user is active.

**Comment by rixx** [comment]
> Hmm, it looks like we currently do not even store `last_login`, so it's gonna be a little more involved, sorry.

Huh, I definitely see this filled with valid values on my end.

> Also, I'm not even sure if it's a good metric since an active login session can basically stay open forever and the last login might be long ago even though the user is active.

That's fair, but at least it's an indicator – if the last login was 2017, it is likely that the account is unused.

I mean, we could also try to get a `last_active` timestamp, but that's way more involved.
