### ISSUE TITLE
Mark required question fields at checkout

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#130]
e.g. with a `*`

**Comment by mjbeaton** [comment]
Hi I'm new to this and am looking to make my first contributions.

Do you have any specific advice or objections to me giving this ticket a shot?

Thanks!

**Comment by raphaelm** [comment]
Hi! Did you alread work with Python or Django or is it your first time in this whole field? I'd be glad to give you some pointers here and there if you help me estimate your prior experience :)

**Comment by raphaelm** [comment]
I thought about it and now I'm unsure whether this is a good start because while the task sounds really simple (just put a * next to the description every field that is required) it could require you to dive into https://github.com/dyve/django-bootstrap3 to make this work.

**Comment by mjbeaton** [comment]
I've worked with Python before but not with Django so this probably isn't the most suitable task as you said.

I have 18 months computing experience with Python and I actually teach at GCSE and A level... So a tremendous understanding of all the basics i'm just looking to push myself further, and I'd currently rate myself at CS degree graduate level, maybe a little beyond.

**Comment by raphaelm** [comment]
I suggest you look for a Django project that is smaller in terms of codebase because it will be easier to get an overview of everything. If you'd like to contribute to pretix, I suggest giving #104 a try, it will take you to various parts of the project with only small changes in every part necessary.

**Comment by raphaelm** [comment]
With a bit of luck, Django 2.0 will finally have template-based form rendering which will make this a lot easier.
