### ISSUE TITLE
corrupt invoices zip

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1301]
Just tried to make an export of "All invoices" and got a corrupted zip:

[t1_invoices.zip](https://github.com/pretix/pretix/files/3223942/t1_invoices.zip)

**Comment by raphaelm** [comment]
My system recognizes it as a very valid empty zip. Do you have any invoices in your event?

**Comment by ligi** [comment]
on mac-os you seem to get "operation not permitted" for this zip. And I got this:

![Selection_093](https://user-images.githubusercontent.com/111600/58423721-12c71f00-8096-11e9-8af6-56ab20644068.png)

so I would not count the linux thing as problematic - but the mc-os thing is. Perhaos just place a file "empty.txt" into the Zip?

we made one test-order - not yet sure if this was leading to an invoice. It was manually marked as paid.
