### ISSUE TITLE
voucher required but no input visible

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1302]
![image](https://user-images.githubusercontent.com/111600/58424423-a0efd500-8097-11e9-8544-2496a63c2074.png)

**Comment by pc-coholic** [comment]
Is there a chance, that you defined the product as requiring a voucher to be purchased but did not create any vouchers yet?

**Comment by ligi** [comment]
sorry - yes this is the issue. But perhaps this should be a condition to start the shop then?

**Comment by raphaelm** [comment]
I don't think so, I think more conditions to start the shop rather make it more complicated for users than easier, especially since you can just as easily screw this up after you published the shop already. If anything, we could put a warning with the product in the backend.
