### ISSUE TITLE
how to get google verified by html file validation?

### ISSUE THREAD

**Issue by rkhyd** [pretix/pretix#1304]
I tried adding this to nginx .conf, but doesn't seem to work as its showing 404 error.

location = /googled1085b59adc211cb.html {
            rewrite ^/(.*)  $1;
            return 200 "google-site-verification: $uri";
    }

and pretix log shows
WARNING 2019-05-28 06:43:47,967 django.request log Not Found: /googled1085b59adc211cb.html/

I have uploaded the file to the /var/pretix/venv directory which i the root of pretix installation.
Thanks in advance for the help.

**Comment by raphaelm** [comment]
Can you try to remove the rewrite call from the nginx config?

**Comment by rkhyd** [comment]
Hi @raphaelm,
Thank you for replying. i have removed the rewrite call from nginx config and the result is still 404.

**Comment by raphaelm** [comment]
Just tested 
```
location = /googled1085b59adc211cb.html {
    return 200 "google-site-verification: $uri";
}
```
in my nginx configuration, works wonderfully. Please make sure you have it in the correct server block, put it above the proxy setting and reload nginx properly.
