### ISSUE TITLE
Set Shop to TLD

### ISSUE THREAD

**Issue by flemssound** [pretix/pretix#1306]
Is it possible via the control panel or config file to set a shop directly to the TDL.

From "example.com/operator/event" to "example.com/"

**Comment by pc-coholic** [comment]
Having the shop directly at the TLD-level is not possible at this point, sorry.

You can however eliminate the organizer part, to have your shop at (for example) https://tickets.example.com/event

Depending on your webserver configuration, you can even set up an automatic redirect to /event.

You'll need to configure your webserver to process your (sub-)domain accordingly and then set up the domain in the organizer settings as seen in the "With a custom pretix installation"-section: https://docs.pretix.eu/en/latest/user/organizers/domain.html
