### ISSUE TITLE
Document nav_event capabilities

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#1307]
The `nav_event` documentation doesn't mention that you can pass a `"parent"` attribute, which will be used to (hierarchically) put entries under existing entries. This is a highly useful feature and documenting it would be very appreciated.

---

Please also mention that any entry capable of containing child entries must have an empty `"children": []` list, because without it, pretix will crash.

---

Oh, and while I'm here, I'm sure you'll want to hear about this very interesting bug! If you actually use this feature, as @raphaelm did in the plugin prtx-faq, pretix might make your life very hard indeed if a child link has the same url as the parent link and is *first, alphabetically*. This is because pretix sorts all additional link alphabeticlly by label before merging them.

**Comment by raphaelm** [comment]
:see_no_evil: Thanks
