### ISSUE TITLE
Add email option for specific answers to questions

### ISSUE THREAD

**Issue by katrinleinweber** [pretix/pretix#1313]
At [deRSE19](https://www.de-rse.org/de/conf2019/index.html), the organisers used a bunch of questions during the sign-up (e.g. "Are you a de-RSE e.V. member?"). In pretix' admin interface, it is already easy to filter registrations down to the answers to such sign-up questions.

It would additionally be nice to have a "E-mail these participants" button in that view, _or_ provide question & answer filters in the E-mail section. cc @caha42

**Comment by raphaelm** [comment]
https://github.com/rixx/pretix-question-placeholders might solve this
