### ISSUE TITLE
Girocode must not contain Umlauts

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#1314]
Where as the Bezahlcode allows for DTAUS-compatible charset (incl. German Umlaute), the Girocode does not. Girocodes containing such characters (like in "Stadtsparkasse München") get rejected by most banking apps.

We should either rewrite everything to plain text or at at least show a warning.

**Comment by raphaelm** [comment]
We could try using https://pypi.org/project/text-unidecode/ here
