### ISSUE TITLE
Feature request: Pre-set filename for downloaded tickets

### ISSUE THREAD

**Issue by orithena** [pretix/pretix#1315]
Rationale: I notice that my download folder is getting full of files just named "pdf" -- all tickets downloaded from some pretix installation. As browsers more and more tend to "just download it without asking the user for a filename", this is getting out of hand (especially on Android, where it is a lot of taps to change the filename after downloading it).

Proposed solution: Send a filename along with the pdf containing the title of the event that the ticket is for, possibly also including the ticket number (i.e. that five-character combination).
The Content-Disposition header seems to be the right place for it. As I suspect that Django already sets it to "pdf" as sensible(?) default, I assume that it's just a matter of calling the right method to set the filename... okay, I just tried to verify that and Django seems to support such a method for 15 months now: https://code.djangoproject.com/ticket/16470 

(Really? Only for 15 months?? I'd have assumed that it would have been baked into Django right from the start...)

**Comment by raphaelm** [comment]
We already send a file name with every download:
https://github.com/pretix/pretix/blob/master/src/pretix/presale/views/order.py#L806

I also can't reproduce it. Can you show me the actual headers of a download you have seen?
