### ISSUE TITLE
Check-In Questions for Add-On Products not working

### ISSUE THREAD

**Issue by niklasberlin** [pretix/pretix#1331]
We have an 4 day event where we sell Tickets, on saturday we have an show. Tickets for the Show are sold as an add-on to the regular ticket (we only want to sell the show tickets to people who attend our event). 

We have added a Question which is asked during the Check-In process for the regular Ticket, this works great. But we have another Question for the Add-On (Show Ticket) which is not shown in the Check-In process, probably because the QR-Code on the Ticket points to the admission Ticket and not to the Add-On. We dont create seperat Tickets for Add-Ons (easier handling at the Check-In (only one Scan per person) and less used Paper for printing.

What is the best Method to Check-In the Show-Ticket? Is it possible to Add a second QR Code to the Ticket for the Add-Ons? 

_Originally posted by @niklasberlin in https://github.com/pretix/pretix/issues/1322#issuecomment-507798952_

**Comment by raphaelm** [comment]
Unfortunately this is only possible by issuing separate tickets for the add-ons. We are thinking about better solutions for this, but we haven't found a design that does not cause any major issues.
