### ISSUE TITLE
CRAM-MD5 for STMP ?

### ISSUE THREAD

**Issue by dsko1234** [pretix/pretix#1347]
Hi,
I am trying to set up pretix for a upcoming event I am co-organising.

i have come around to setting up email sending last week.
i have now realized my email provider needs CRAM-MD5 for password verification.

i have attached my email config and some relevant log-lines from my email server.

Did i miss some config option or is CRAM-MD5 not implemented?

Any help would be greatly appreciated.

Thanks

PS: I have replaced IPs, domains and passwords 

from pretix.cfg:
```
[mail]
from=email@domain.com
host=mail-server
user=email@domain.com
password=
port=587
tls=on
ssl=off
 ```
Maillog:
```
Jul 17 23:59:07 user postfix/smtpd[14001]: Anonymous TLS connection established from unknown[ip-address]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Jul 17 23:59:07 user dovecot: auth-worker(13999): Error: sql(email@domain.com,ip-address): Password data is not valid for scheme CRAM-MD5: Input isn't valid base64 encoded data
Jul 17 23:59:09 user postfix/smtpd[14001]: warning: unknown[ip-address]: SASL CRAM-MD5 authentication failed: password
Jul 17 23:59:13 user dovecot: auth-worker(13999): Error: sql(email@domain.com,ip-address): Password data is not valid for scheme CRAM-MD5: Input isn't valid base64 encoded data
Jul 17 23:59:15 user postfix/smtpd[14001]: warning: unknown[ip-address]: SASL PLAIN authentication failed: password
```

**Comment by raphaelm** [comment]
I'm not sure that this is actually the error, from googling around CRAM-MD5 seems to be supported by Python's smtplib implementation. In any case, this would be a problem on either Python or Django level, so there's nothing we can do about it in pretix, sorry.

**Comment by dsko1234** [comment]
So there is nothing to be configured for pretix to use CRAM-MD5?
then i will continue to hunt for the problem
any recommendations for where to look first?
