### ISSUE TITLE
How to install the plugin "Certificates of attendance"

### ISSUE THREAD

**Issue by rkhyd** [pretix/pretix#1348]
Hello
When i try to install the above plugin using the command 
`pip3 install pretix-certificatesofattendance`
i get the error 
`ERROR: Could not find a version that satisfies the requirement pretix-certificatesofattendance (from versions: none)
ERROR: No matching distribution found for pretix-certificatesofattendance`
Please let me know how to resolve the issue.
Thanks in advance.
RK

**Comment by raphaelm** [comment]
Hi,

this plugin is not released as free software. You can find pricing here: https://pretix.eu/about/en/pricing If you're interested, please reach out at sales@pretix.eu

Best
Raphael
