### ISSUE TITLE
Allow a more elegant way to override config file settings with env vars

### ISSUE THREAD

**Issue by davesque** [pretix/pretix#1356]
I've recently been trying to get pretix to run in a docker container and have a nice dev work flow with `docker-compose` and tools like that.  My plan is to eventually be able to deploy a containerized pretix site running behind gunicorn to Heroku or possibly some other hosting setup maybe driven by Docker Swarm or Kubernetes.

I'm aware that there are setup instructions in the documentation for using docker.  However, I don't think those will work for my use case.  Having nginx running in the container seems overkill and I'd also rather have task workers running in other containers.

So far, I've got a custom `Dockerfile` [here](https://github.com/davesque/pretix-eth-payment-plugin/blob/docker/Dockerfile) that's building an image that mostly works for my purposes.  However, I usually like to override django settings via environment variables in docker environments.  The way that pretix does its configuration makes this very difficult.  The default `pretix.settings` module assumes most config settings will come from the `pretix.cfg` file and it does quite a bit of computation with those settings in the `pretix.settings` module.  If I want to override settings via env vars in my `production_settings.py` file, I have to copy and paste a lot of the setup code from the default `pretix.settings` module.

For example, to override the `DEBUG` django settings via env vars in `production_settings.py`, I have to do things like this:
```python
from pretix.settings import *

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

try:
    import debug_toolbar  # noqa
    if DEBUG:
        INSTALLED_APPS.append('debug_toolbar.apps.DebugToolbarConfig')  # noqa: F405
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')  # noqa: F405
except ImportError:
    pass

if DEBUG:
    LANGUAGES = ALL_LANGUAGES
else:
    LANGUAGES = [(k, v) for k, v in ALL_LANGUAGES if k not in LANGUAGES_INCUBATING]

if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = (
        ('django.template.loaders.cached.Loader', template_loaders),
    )

...
```
...and that's not even sufficient because there's a `loglevel` value in `pretix.settings` that's calculated from the `DEBUG` settings in that file and that gets used in several places.

Anyway, I think you get the idea.  It's really unwieldy to follow the [12-factor app config pattern](https://12factor.net/config) when things work this way.

Any thoughts on how to remedy this?  Perhaps we could modify the config loader to look for env vars with a certain format such as `PRETIX_DJANGO_DEBUG` and `PRETIX_PRETIX_URL`?  The format there would be `PRETIX_<CONFIG HEADER>_<CONFIG VALUE>`.  Anyway, that's just an idea.

**Comment by davesque** [comment]
In case anyone's interested, here's the wacky solution I came up with:
* https://github.com/davesque/pretix-eth-payment-plugin/blob/11205b990018d448438d4bfbe5ddde7bec0fbab7/docker_files/pretix.bash#L22-L27
* https://github.com/davesque/pretix-eth-payment-plugin/blob/11205b990018d448438d4bfbe5ddde7bec0fbab7/docker_files/update_cfg_from_env.py
* https://github.com/davesque/pretix-eth-payment-plugin/blob/11205b990018d448438d4bfbe5ddde7bec0fbab7/docker_files/pretix_cfg_env_whitelist.txt

**Comment by raphaelm** [comment]
This is probably kind-of a religious question. I do like environment variables, but they get messy very quickly since they don't have sections etc. Also, there's some code in pretix that relies on having that config file present by directly accessing ``settings.CONFIG_FILE``. For example, plugins like [pretix-bounces](https://github.com/pretix/pretix-bounces#configuration) do this to support additional options in the file.

So yeah, I'm open to have a better story here, but it's not gonna be trivial :)

**Comment by davesque** [comment]
> This is probably kind-of a religious question. I do like environment variables, but they get messy very quickly since they don't have sections etc.

I don't have an emotional (or religious) attachment to env vars.  It's just that a lot of dockerized and serverless hosting environments tend to assume you'll provide settings via env vars.  So I'm just looking for a way to make that work.

> Also, there's some code in pretix that relies on having that config file present by directly accessing `settings.CONFIG_FILE`.

Yeah, I assumed that might be the case.  The hacky solution I came up with is that I wrote a little script (linked above) that generates a local `pretix.cfg` file from env vars in the working directory of the pretix wsgi process.  It does this every time gunicorn starts up.  So it gets me what I want but it feels really weird and not ideal.  Ah well, it'll work for now I guess!

**Comment by raphaelm** [comment]
Yeah, let's leave this around as an area of future improvement without urgent need. I certainly agree that it would be nice. At the same time, I'm a bit annoyed by other tools I'm deploying myself through docker (I think both Weblate and Sentry share this problem) where I can configure *most* things via env variables but not all. In these cases, I think I'd prefer to be forced to deal with the configuration file right away ;)

**Comment by IrmantasM** [comment]
Would really like to have an ability to configure pretix via env variables, especially when deploying dockerised pretix, I am now forced to build hardcoded values into docker image, not only that it is arguably not secure it also means that I have to rebuild docker image every single time any of the parameters change.

**Comment by raphaelm** [comment]
I agree that env variables would be great, but what prevents you from mounting the file into the docker container?

**Comment by raphaelm** [comment]
\o/ I found an elegant way to do this in the next release
