### ISSUE TITLE
Easy overview about the answered Questions

### ISSUE THREAD

**Issue by HDValentin** [pretix/pretix#1357]
It is a feature request:
In the Backend > Products it is possible to ask several Questions:
https://pretix.eu/control/event/eventname/2019/questions/

When I want to have an overview about the given answeres I have to export all  Orders
https://pretix.eu/control/event/eventname/2019/orders/export/ 

I would like to have an easy overview about the answers to each Question in the backend of Pretix.
For example: We asked the people if they want to help at the event. An Overview about this question would give us "30 yes" and "15 no".

**Comment by pc-coholic** [comment]
If you click on the name of the question in the question overview, you get a list of all the given answers to the question as well as a nice chart.

![Screenshot from 2019-08-03 11-48-43](https://user-images.githubusercontent.com/654548/62410342-afe98b00-b5e4-11e9-8aa6-4cf42e3cc71b.png)

**Comment by HDValentin** [comment]
Thank you fpr the hint.
That is what I was searching for.
