### ISSUE TITLE
Option if someone payed too much

### ISSUE THREAD

**Issue by HDValentin** [pretix/pretix#1365]
It is a featurerequest:
- someone has bought two seperate tickets
- he pays both tickets with one wire transfer
- now the first Ticket is unpayed
- and the second ticket is not payed

I have only the option to pay back
Then the customer has the hassle to transfer the money again.

I would love to have the option to transfer the money from one ticket to another:
- Take the overpaid amound from ticket A
- Put the amount taken to the ticket B and mark it paid.

**Comment by pc-coholic** [comment]
You can actually already do this!

If an order is overpaid and you initiate a refund, you are given the option to apply the refunded money towards another order (see screenshot, second line).

![Screenshot from 2019-08-12 17-36-54](https://user-images.githubusercontent.com/654548/62877670-d9628f00-bd27-11e9-864a-d11574458da2.png)

**Comment by HDValentin** [comment]
Thank you. This is clearly solving the problem.
But as usability aspect: I would never search there for this option.
