### ISSUE TITLE
Mass emails to people according to their check-in status 

### ISSUE THREAD

**Issue by cbrocas** [pretix/pretix#1369]
Hello,

Pretix gives organizers the capability to send mass emails to attendees according to their tickets types and to their payment status.

But to be able to deal with after event communication, it would be very nice to be able to send emails to people that have done their check-in and those who have not.

It may be especially **useful for organizers of free access conferences** who usually have to deal with some high level of attendees that finally do not attend the event (20-25% style).

**Use case:** sending a post event survey *only* to people who finally came to the event.

This issue can be complementary to #1192 :)

Thanks!

**Comment by raphaelm** [comment]
This sounds useful :)

**Comment by cbrocas** [comment]
Thank Raphaël! Do you think you would integrate it to your roadmap?

**Comment by raphaelm** [comment]
I don't think we'll prioritize it very high, but it's possible :) It also should be pretty straightforward to add in, in case someone wants to make a contribution.

**Comment by cbrocas** [comment]
"pretty straight forward to add in" : not so sure from my point of view ;-) Thanks for everything you do on Pretix.
