### ISSUE TITLE
Show full shop header and footer in widget

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretix#1373]
On the shop page, there is a full header (with header picture, language-selector and time and date of the event) as well as a full footer (with links to contact organizer and imprint). 

In previous versions, this was also displayed when embedding the shop using the widget. Since 3.0, this seems to be missing. Is there a new setting I couldn't find to control this?

**Comment by raphaelm** [comment]
No, this was not present in previous versions, if it was, that was a bug. The widget itself does contain neither header nor footer. The overlay opened by the widget does still contain the full footer, but not the header. Can you post me an URL or screenshots if you still run into this problem?

**Comment by b-schweiger** [comment]
The page with the widget is here:
https://avantgardista.net/tickets/

The ticket shop is here:
https://partyticket.de/AV/AV2019/

In the widget page, there is an empty box that looks like it should contain something and the footer only shows "event ticketing powered by pretix" not "Veranstalter kontaktieren · Impressum · Prometheus Produktionen UG · Event-Ticketing-Software von pretix" like the shop

**Comment by raphaelm** [comment]
The empty box is a CSS bug that I don't quite understand right now, it should be invisible but I can't see why the CSS rule is missing on your site right now. There shouldn't be a header and there never was.

The footer of the widget only shows "event ticketing powered by pretix" and this never was different either.

We expect that your page usually has a ink to an imprint or contact page on it's own. Once you start to buy something, the embedded page will have the full pretix footer
