### ISSUE TITLE
Last inlined images in Outlook mail broken

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#1374]
We are using MacOS with AppleMail and Microsoft Outlook (Version 16.27). In the Outlook only the last image is broken. 

Outlook: 
<img width="701" alt="Bildschirmfoto 2019-08-25 um 22 03 30" src="https://user-images.githubusercontent.com/1153741/63655150-d2566a80-c784-11e9-9b75-0bce2137bf24.png">
Apple Mail: 
<img width="810" alt="Bildschirmfoto 2019-08-25 um 22 06 00" src="https://user-images.githubusercontent.com/1153741/63655152-da160f00-c784-11e9-9ce7-82cf9a693f20.png">
Maybe this is linked to this pull request: 
https://github.com/pretix/pretix/pull/1358
Pretix is the last version 3.0.1

**Comment by saschafoerster** [comment]
![PNG-Bild](https://user-images.githubusercontent.com/1153741/63655189-77714300-c785-11e9-901b-df4fa41a5554.png)

**Comment by raphaelm** [comment]
Huh, this is weird. @pc-coholic any ideas? I don't think anyone of us has Outlook on Mac to reproduce, though.

**Comment by pc-coholic** [comment]
@saschafoerster That is indeed strange...

Could you provide me with an eml or any other raw dump of the email, that includes the base64-encoded attachments?

**Comment by saschafoerster** [comment]
@pc-coholic Can I send it to you via e-mail?

**Comment by saschafoerster** [comment]
I sent it to the general rami.io-mail. Here are some more screenshots from the fresh emails in black and white. 
<img width="697" alt="Bildschirmfoto 2019-09-08 um 21 10 14" src="https://user-images.githubusercontent.com/1153741/64493283-832d3100-d27e-11e9-89a5-33a360b4dcce.png">
<img width="677" alt="Bildschirmfoto 2019-09-08 um 21 10 33" src="https://user-images.githubusercontent.com/1153741/64493284-832d3100-d27e-11e9-9dd2-8fb46b27823c.png">
<img width="640" alt="Bildschirmfoto 2019-09-08 um 21 10 41" src="https://user-images.githubusercontent.com/1153741/64493285-832d3100-d27e-11e9-8721-956162653f5f.png">
<img width="641" alt="Bildschirmfoto 2019-09-08 um 21 10 48" src="https://user-images.githubusercontent.com/1153741/64493286-83c5c780-d27e-11e9-9d3e-94b07b9067ba.png">

**Comment by Sohalt** [comment]
I might have an idea what caused this.

The last image is large enough that the base64 encoded version exceeds 1000 characters, which is the line length limit for SMTP. 

I stumbled on this when checking why my DKIM suddenly fails for pretix (it used to work with the inlined images prior to 18c8933c649753e6f8589f6eb41328eb6eb5350b). In the body which is signed by my opendkim the line with the last image is 1510 long, whereas in the delivered e-mail it is broken after 1000 characters and a erroneous space gets introduced, which breaks the DKIM signature.

Can you try formatting your outgoing email to have at most 998 characters per line to see if that fixes the issue?

**Comment by raphaelm** [comment]
Thank you, this is a very helpful theory. We'll try that out.

**Comment by Sohalt** [comment]
It fixed my dkim issue. Thanks!

**Comment by saschafoerster** [comment]
<img width="731" alt="Bildschirmfoto 2019-09-13 um 22 53 08" src="https://user-images.githubusercontent.com/1153741/64894218-6e371000-d679-11e9-8f0f-0685ee3de38c.png">
 it just works...
