### ISSUE TITLE
Option for users to decide on per-attendee email

### ISSUE THREAD

**Issue by meatballs** [pretix/pretix#1375]
When using the "Ask for email addresses per ticket" option, order confirmation emails are still only sent to the primary email address rather than the individual attendees.

It's understandable why that should be the default - in order to avoid unecessary spammy emails - but it would be useful to allow the user placing the order to have the option that they would like attendees to receive individual emails.

Our use case is where we have corporate purchasing departments placing orders for several employees who then fail to send ticket information on to the attendees.

**Comment by raphaelm** [comment]
This can not be activated by the customer, but you can set it at Settings > E-mail as an event organizer.
