### ISSUE TITLE
Make pretixSCAN connect token visible in "devices" list

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretix#1376]
I just disconnected my pretixSCAN by accident (by clicking on "Diconnect from current Event" (on a side note: This text is misleading: It disconnects from current organizer not from current event)). I couldn't find a way to reconnect my device (It is entirely possible I was just to stupid to find the way. If that's the case, I'd appreciate a pointer in the right direction). 
It would be great to have the possibility to show the connect information (QR-Code, Token) again from the device view. This would come in especially handy, if the same devices are used for multiple organizers switching back and forth. This would result in an endless list of deleted and recreated devices.

**Comment by raphaelm** [comment]
> I just disconnected my pretixSCAN by accident (by clicking on "Diconnect from current Event" (on a side note: This text is misleading: It disconnects from current organizer not from current event)).

Which platform was this text on?

> I couldn't find a way to reconnect my device (It is entirely possible I was just to stupid to find the way. If that's the case, I'd appreciate a pointer in the right direction).

No, this is on purpose for security and auditability reasons, connecting a device is a one-way street, you need to set up a new device.

**Comment by b-schweiger** [comment]
> Which platform was this text on?

Windows. I created a new issue in the pretixSCAN section with a screenshot.
