### ISSUE TITLE
Question: Cloning “event series” via api

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1377]
I've just noticed that [POST /api/v1/organizers/(organizer)/events/(event)/clone ](https://docs.pretix.eu/en/latest/api/resources/events.html#post--api-v1-organizers-(organizer)-events-(event)-clone-) does not clone the `has_subevents`property.

Are there technical reasons for this (e.g. “what to do with subevents?”) or is it an oversight in the api?

Best regards,
Mikkel

**Comment by raphaelm** [comment]
I believe this is a bug/oversight :)

**Comment by rimi-itk** [comment]
Thanks. We'll create a pull request for this (unless you beat us to it). Apparently, we can work around this issue by setting `has_subevents` in the request body.

**Comment by rimi-itk** [comment]
@raphaelm, thanks for this fix. And sorry for not getting around to fixing it ourselves.
