### ISSUE TITLE
Add count of tickets left to quota API endpoint

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1386]
With the API you already can get the quota "size".
Would it be possible to add an "tickets_left" (or similar) field to get the count of tickets left in one quota?

By now I go this way:
* get quota size
* get item id's per quota
* sum up sold items per quota
* output sum of sold items and quota size to sth. like: `Great Event (adults): 70/100 tickets sold`.

**Comment by raphaelm** [comment]
It's right there: https://docs.pretix.eu/en/latest/api/resources/quotas.html#get--api-v1-organizers-(organizer)-events-(event)-quotas-(id)-availability-

It has its own endpoint since it's performance-intensive to calculate and we don't want to do it on every API pull of quota objects.

**Comment by TimmThaler** [comment]
Hups, sorry 🙈
