### ISSUE TITLE
Stripe PaymentIntent.state: "pending" should be "processing" ?

### ISSUE THREAD

**Issue by sylvinus** [pretix/pretix#1389]
Hello!

Not sure it's a real issue, but I stumbled on this while reading the new Stripe plugin PaymentIntent code:

https://github.com/pretix/pretix/blob/262fb822376bfb555ac7b5fc82463e166daad218/src/pretix/plugins/stripe/payment.py#L726

There is no state `pending` in the stripe docs for PaymentIntent, only `processing` (contrary to Charge.state which can be `pending`):
https://stripe.com/docs/payments/intents

Feel free to close if I missed something and the code is valid!

**Comment by pc-coholic** [comment]
I think the point you're raising is valid - thank you for pointing this out!

I guess this happened when migrating/copying most of the code handling `charge`-objects which do have a `pending`-status.
