### ISSUE TITLE
You have offline compression enabled but key is missing from offline manifest

### ISSUE THREAD

**Issue by dschulte** [pretix/pretix#1398]
Hi!
I'm trying to run pretix as a docker container. My docker-compose file worked a year ago and since then afaik nothing changed on my side.

This is a completely fresh installation with a clean database and no other files except the configured pretix.cfg.

Some searches on the internet showed me that this problem seems to be an "internal" problem which couldn't be fixed from the outside of the docker container. But maybe I'm just doing something wrong.

I'm totally unsure in which information might be interesting. Feel free to ask for any further debug information.

With django debug on this is the first part of the page:
```
Request Method: | GET
-- | --
https://tickets.mydomain.de/
2.2.5
OfflineGenerationError
You have offline compression enabled but key "4051f28e50d46882c462f578bf687cc96f7bc75bd6aa17f84f8f945c00a29060" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:           <link rel="stylesheet" type="text/x-scss" href="/static/pretixcontrol/scss/auth.scss"/>
/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py in render_offline, line 75
/usr/local/bin/python
3.6.9
['/pretix/src',  '/pretix/src',  '/usr/local/bin',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
Mi, 11 Sep 2019 11:32:25 +0200
```

**Comment by raphaelm** [comment]
Can you post your pretix.cfg file?

**Comment by raphaelm** [comment]
Hmm. Do you have custom static URLs configured in your pretix.cfg, e.g. something like

```
[urls]
static=https://…
```

**Comment by dschulte** [comment]
No.

This is my current pretix.cfg:
```
[pretix]
instance_name=Pretix Shop
url=https://pretix.mydomain.de
currency=EUR
; DO NOT change the following value, it has to be set to the location of the
; directory *inside* the docker container
datadir=/data

[locale]
default=de
timezone=Europe/Berlin

[database]
backend=mysql
name=db
user=db
password=db
host=db
port=3306

[mail]
from=mailer@mydomain.de
host=mail.mydomain.de
user=mailer@mydomain.de
password=xxx
port=587
tls=on
ssl=off

[redis]
location=redis://redis/0
; Remove the following line if you are unsure about your redis' security
; to reduce impact if redis gets compromised.
sessions=true

[celery]
backend=redis://redis/1
broker=redis://redis/2

[django]
debug=on
```

**Comment by dschulte** [comment]
Any thoughts for what I have to look for? Checking out the master and building a fresh docker image results in the same error.

I also tried another docker system. Same error.

There is a small mistake in my pretix.cfg above. url should match the traefik domain in the docker-compose. Unfortunately that didn't fix the problem.

**Comment by raphaelm** [comment]
Sorry, no ideas. It usually happens because the static URL is changed and a re-build of the static files is thereby required.
I just verified that the current stable docker container is built correctly in itself. You can see the exact script that I used to verify here: https://github.com/pretix/pretix-test-tutorials/blob/master/docker_smallscale/install.sh

**Comment by dschulte** [comment]
Ok, I get the same error with that test script. Or better to say after installing sudo, gnupg2 and with the previous version because the last changes some hours ago breaks the installation process on the current debian buster due to failing signature checks.

The problem seems to be the "new" debian buster as the vagrant script still uses the old debian jessie. But due to docker this shouldn't actually affect pretix as it is running inside docker.

After installing debian buster (10.1.0) with no special settings I did:
```
apt update && apt dist-upgrade
apt install tmux vim rsync
tmux a || tmux
apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common sudo
wget https://raw.githubusercontent.com/pretix/pretix-test-tutorials/69e642fc81f846c38ca973b28c1362d1537b532e/docker_smallscale/install.sh
bash install.sh 
```

**Comment by rimi-itk** [comment]
I'm having the exact same issue. I don't know why (and haven't yet investigated), but setting `debug=off` in the `django` config section works wonders.

**Comment by raphaelm** [comment]
Oh yeah, that makes a lot of sense! I completely overlooked the debug parameter in @dschulte's config file above. Debug=on + docker/gunicorn is not a combination we really ever test, it should work, but I'm not really surprised if it doesn't

**Comment by shocker0815** [comment]
I added the ```debug=on``` just for debugging. It didn't work even without the django section. It isn't (directly) related to docker. It doesn't even work on a current version of debian. But maybe there were some changes in the last months. I haven't tried again since then.

**Comment by dschulte** [comment]
I added the debug=on just for debugging. It didn't work even without the django section. It isn't (directly) related to docker. It doesn't even work on a current version of debian. But maybe there were some changes in the last months. I haven't tried again since then.

**Comment by patrick91** [comment]
We had a similar issue and we made a custom Dockerfile, I'm going to be honest, we didn't have much time to investigate (and to fix it properly), but here it is:

https://github.com/pythonitalia/pycon/blob/master/pretix/Dockerfile

as you can see we run staticfiles and compress :)

Hope it helps :)

**Comment by gvarela1981** [comment]
setting in pretix.cfg works fine

[django]
debug=false
