### ISSUE TITLE
Privacy page: Empty row with icon when no payment provider chosen

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1400]
When you only offer free tickets, you don't need methods to receive money from your customers. So you don't need any payment providers and no entry on the privacy page for it.
At the moment, when you don't choose a payment provider, on the privacy page there is no text (that's correct), but the credit card icon is still shown.

I think, the icon should / could be hidden in such a case.

![thing](https://user-images.githubusercontent.com/22148307/64712623-d3dd9d80-d4bb-11e9-8f75-1449c7ef1e3b.jpg)

🙂

**Comment by raphaelm** [comment]
Hi! Thanks a lot, we'll deploy a fix in the next days. As this is not part of this repository, no changes will be visible here.
