### ISSUE TITLE
Allow Date Format Change

### ISSUE THREAD

**Issue by skillsgarage** [pretix/pretix#1406]
Allow the format of the date used in the system, tickets and events to be changed.

Currently uses m.d.Y

Other options such as d.m.Y, d/m/y etc would be a good idea (unless this can already be done and I've missed it)

**Comment by felixrindt** [comment]
This depends on the locale used to view a page, but it's probably fixed for a given locale.

**Comment by raphaelm** [comment]
Yes, and I don't think it's feasible to make it configurable, sorry :(
