### ISSUE TITLE
Use proper MIME structure

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#1415]
Since #1358, we've been sending emails with a MIME structure like this:

```
multipart/related
   multipart/alternative
      text/plain
      text/html
   image/png (images for HTML content)
   application/pdf (tickets)
   …
```

Unfortunately, this broke attachments on Apple devices entirely: iOS Mail no longer showed any attachments. As a quick fix, in ca0c0f4ae, I changed ``multipart/related`` to ``multipart/mixed``. This has the upside of showing all attachments again, but the downside of showing the PNG images as attachments as well.

The correct structure would look like this:

```
multipart/mixed
   multipart/alternative
      text/plain
      multipart/related
         text/html
         image/png (images for HTML content)
   application/pdf (tickets)
   …
```

I verified that this yields the correct results on iOS. What's left to do is changing our code to generate this structure and verify that it works as intended in at least GMail and Outlook.

**Comment by Abhi-khandelwal** [comment]
@raphaelm , Can I take this issue ?

**Comment by raphaelm** [comment]
@Abhi-khandelwal Feel free! It will require some deep-diving into Django's email code, though, I'm afraid.
