### ISSUE TITLE
Question: Disable User Creation

### ISSUE THREAD

**Issue by exp625** [pretix/pretix#1418]
Hi,
is there a posibillity to completly disable the user registration on the /control/register page so that only the logged in admin can create new users?

**Comment by exp625** [comment]
Adding

`# Block access to the registration site
    location ^~ /control/register {
        deny all;
    }`

does the trick but is rather ugly. An option in the global settings to disable user registration would be a lot nicer.

Anyway thanks for the awesome project!

**Comment by raphaelm** [comment]
Pssst, it's right there and documented: https://docs.pretix.eu/en/latest/admin/config.html#pretix-settings
