### ISSUE TITLE
[German] Gendered language

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#1421]
One of our customers, who has to take care a lot of gendered language, asks us, if we can change "Firmenkunde" to "Firmenkund*in" or other variants of different forms of gendering. 
I thought about creating a new language file "Deutsch (gendered)", but I am not sure if I can change the language file by importing this file and some config-files, especially not trough docker? 
Or is there any other more or less "easy" way, to do this? If support can be bought for this issue, I would be happy to get an offer. ;)

**Comment by raphaelm** [comment]
We absolutely do not want to end up with more than two versions of German, it's already a pain to maintain these.

In general, we currently try to lean towards non-gendered, "traditional" terms in the ``de`` language package (e.g. "Attendee name" translates to "Teilnehmername") and more progressive, "gendered" terms in the ``de_Informal`` language package (e.g. "Name des/der Teilnehmer*in"). This is already in place and so far there have been zero complaints.

**Comment by raphaelm** [comment]
I think this is fixed by now :)
