### ISSUE TITLE
Plugins for Custom Question Types 

### ISSUE THREAD

**Issue by Sohalt** [pretix/pretix#1426]
It would be cool to have the possibility for plugins to register custom question types which then would show up in the normal drop down in the question editor with other question types and with the other questions in the checkout process.

**Comment by raphaelm** [comment]
Yes, that would be cool, but I have some hesitation:

* Just adding more options to the dropdown is probably not enough, many questions (such as the choice-types) require additional options or semantics
* Questions are also supported in pretixSCAN across three platforms, those question types would not work there.

Can you tell me examples of question types that you have in mind?

**Comment by Sohalt** [comment]
I didn't think about pretixSCAN - that's indeed an issue.

One of the simplest cases for custom question types would for example be regular text inputs, just with some additional validation (e.g. for club membership numbers). Another case would be drop downs with a predetermined selection (e.g. if you have a club with different levels of membership it would be nice to have a question type for the membership level instead of having to always recreate the same options (although copying events/questions can somewhat help with this).
A more complicated use case would be a question type to select points or regions on a map.

**Comment by raphaelm** [comment]
I don't think we'll invest this level of complexity here, plugins should rather add their own native mechanisms. The forms involved can already be extended, even if you don't get all features of the question system "for free".
