### ISSUE TITLE
Allow to configure an end date for the waiting list

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#1427]
Allow to configure a datetime (relative to the event date) that will be the latest time anyone on the waiting list will be notified.

Internal ticket: Z#2343450

**Comment by abhishekmodak** [comment]
Hi @raphaelm can I pick it up ??

**Comment by raphaelm** [comment]
HI @abhishekmodak, yes, feel free!

**Comment by Mezgrman** [comment]
This seems to have been implemented in 2024.3.0 if I'm not mistaken. Could the configured end date also be shown in the "overview" tab, where things like start/end of presale and event dates are shown?

**Comment by raphaelm** [comment]
You are right, this has been fixed in #4004 – did not even notice this old issue here :) I've created a PR for your request in #4036
