### ISSUE TITLE
Undismissable Alert

### ISSUE THREAD

**Issue by MrGirlyMan** [pretix/pretix#143]
When registering for pretix, enter a password that is too common. When the page refreshes, the alert that is given should be dismissable, but isn't (Chrome 47.0.2526.73, Mac 10.11.4).

**Comment by raphaelm** [comment]
Thank you for your feedback! All other error messages in pretix are non-dismissable as well, so I'll change this to be coherent (e.g. remove the icon).
Also, the error should be right next to the password field, not above, I'll look into this.
