### ISSUE TITLE
Question: Is it possible to change the customer's name? (typo etc.)

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1430]
Hey there, me again...

I was wondering, if there is a possibility to change the name of a customer.
Although we do not ask for the customer's address or create an invoice, in the ordering process you have to type in your first and last name. Now, some people enter their full name in both fields, which results in something like "John Doe John Doe" or have a typo in the spelling.

Trying to correct these "mistakes" I wanted to use the "change" link at the invoice information of the affected order (in the back-end), because the customer's name is displayed there.
![01](https://user-images.githubusercontent.com/22148307/66296286-7fc4ae00-e8ed-11e9-81e7-efbf4a247102.jpg)

But then there is no possibility to change the name. It is not even displayed.
![02](https://user-images.githubusercontent.com/22148307/66296371-b26ea680-e8ed-11e9-9ad2-bb19d23d1471.jpg)

I guess, it is not intended to correct / change the name of a customer, because of reasons with the invoice etc.. And probably because we don't ask for an address, there is nothing displayed to change anyway.

Thank you in advance!

**Comment by raphaelm** [comment]
Hmm, looks like a bug if the form field is missing in the combination of "don't ask for invoice address" but "require name"

**Comment by felixrindt** [comment]
I've seen the "John Doe John Doe" thing with our customers as well. I'm not sure wether that's because all those users made a mistake or the form is strange in some environments...

**Comment by TimmThaler** [comment]
I assume, a lot of those customers used their cell phone to order.
Often you just have to tap onto the suggested string ("first name last name") to fill the required field. And this suggested string is the same in both input fields (at least on iOS).

**Comment by raphaelm** [comment]
Yes, I also believe that the "John doe john doe" thing is an autofill problem. If someone know how to convince browsers of doing this better, feel free! (But in a separate issue, please)

**Comment by TimmThaler** [comment]
I just had a look at the w3schools website (https://www.w3schools.com/html/html_form_input_types.asp), where they have an example for first name and last name input fields.
They use `name="firstname"` and `name="lastname"` to specify the fields additionally and on my iPhone that does the job. The suggested string is either my first name or my last name.
At the moment in pretix the field names are `name="name_parts_0"` for the first name and
`name="name_parts_1"` for the last name (whole html line below), so I think, that at least iOS doesn't know what to suggest exactly and offers the full name (first name + last name) for both fields.

---
I took this from `https://pretix.eu/[organizer]/[event]/checkout/questions/`, line 224:

`<div class="form-group required"><label class="col-md-3 control-label" for="id_name_parts_0">Name</label><div class="col-md-9"><div class="nameparts-form-group"><input type="text" name="name_parts_0" data-fname="given_name" class="form-control" placeholder="Vorname" title="Vorname" id="id_name_parts_0" data-size="1"><input type="text" name="name_parts_1" data-fname="family_name" class="form-control" placeholder="Nachname" title="Nachname" id="id_name_parts_1" data-size="1"></div></div></div>`

**Comment by pc-coholic** [comment]
When we changed the name-handling in pretix, the invoice-field for the name also got reworked to use the new `name_parts` instead of a plain `name`-field. Seems like we overlooked one occurrence...

Thanks for the find, @TimmThaler!

**Comment by TimmThaler** [comment]
You're welcome!
Wow, that was fixed faster than I imagined.
Awesome! :+1:

**Comment by TimmThaler** [comment]
Hey, I've got just one more thing ...
After changing / editing the customer's name, the **"successful" notification** is (in my case) in english and **not translated** into german.

> The invoice address has been updated. If you want to generate a new invoice, you need to do this manually.

A german version could be
> Die Rechnungsadresse wurde aktualisiert. Wenn Sie / Du eine neue Rechnung erstellen möchten / möchtest, müssen / musst Sie / Du das manuell machen.

**Comment by raphaelm** [comment]
Indeed, there seems to be a bug. We'll fix it with the next translation cycle.
