### ISSUE TITLE
Auto-filling first name and last name fields results in "John Doe John Doe".

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1432]
As mentioned in #1430, there sometimes are customers typing the same things into the fields for first name and last name. We already assumed, that this might be a thing on mobile devices and mobile browsers, that are always suggesting the full name.

**Comment by TimmThaler** [comment]
I just had a look at the w3schools website (https://www.w3schools.com/html/html_form_input_types.asp), where they have an example for first name and last name input fields.
They use `name="firstname"` and `name="lastname"` to specify the fields additionally and on my iPhone that does the job. The suggested string is either my first name or my last name.
At the moment in pretix the field names are `name="name_parts_0"` for the first name and
`name="name_parts_1"` for the last name (whole html line below), so I think, that at least iOS doesn't know what to suggest exactly and offers the full name (first name + last name) for both fields.

---
I took this from `https://pretix.eu/[organizer]/[event]/checkout/questions/`, line 224:

`<div class="form-group required"><label class="col-md-3 control-label" for="id_name_parts_0">Name</label><div class="col-md-9"><div class="nameparts-form-group"><input type="text" name="name_parts_0" data-fname="given_name" class="form-control" placeholder="Vorname" title="Vorname" id="id_name_parts_0" data-size="1"><input type="text" name="name_parts_1" data-fname="family_name" class="form-control" placeholder="Nachname" title="Nachname" id="id_name_parts_1" data-size="1"></div></div></div>`

**Comment by raphaelm** [comment]
> At the moment in pretix the field names are name="name_parts_0" for the first name and
name="name_parts_1" for the last name (whole html line below), so I think, that at least iOS doesn't know what to suggest exactly and offers the full name (first name + last name) for both fields.

Yeah, but we can't easily make the names much simpler, as they are pretty autogenerated and we might have multiple name forms on a page. Chrome appears to support attributes like ``autocomplete="fname"`` ([docs](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill#name)) but support in other browsers is at least unclear.

**Comment by rixx** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)/[WHATWG](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) says `"given-name"` and `"family-name"`.

**Comment by TimmThaler** [comment]
> Yeah, but we can't easily make the names much simpler, as they are pretty autogenerated and we might have multiple name forms on a page.

Yup, I already thought, that Django names the fields itself.

> Chrome appears to support attributes like `autocomplete="fname"` ([docs](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill#name)) but support in other browsers is at least unclear.

No, the `fname` is for the `name attribute`, for the `autocomplete` there are other values, which are the same rixx just reported:

> [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)/[WHATWG](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) says `"given-name"` and `"family-name"`.

Following the [W3](https://www.w3.org/TR/html52/sec-forms.html#autofill-field), you can use `autocomplete="given-name"` and `autocomplete="family-name"` for (almost) all browsers supporting the `autocomplete` attribute.
The [W3 also gives an example](https://www.w3.org/TR/html52/sec-forms.html#sec-autofill) for multiple address forms on one page by adding a *section-...* string in the `autocomplete` value.

**Comment by TimmThaler** [comment]
Consulting [caniuse.com](https://caniuse.com/#search=autocomplete) about 98% of the current browsers should support this `autocomplete` feature.
