### ISSUE TITLE
no {invoice_name} placeholder for free tickets

### ISSUE THREAD

**Issue by gruenzeug** [pretix/pretix#1439]
Dear pretix community,
for free tickets, there is no {invoice_name}. As a result, there's no working name placeholder for e-mails. It would be great to have {name}, {given_name} etc placeholders available for the free ticket use case.
This also applies to the orders overview, where only user e-mails are listed, even if a name is required for ordering a ticket. Especially for ticket confirmations, showing the name would come handy :)

**Comment by raphaelm** [comment]
> for free tickets, there is no {invoice_name}.

This is not necessarily the case, you can also configure invoice addresses to be asked for free orders (Settings → Invoicing → Address Form)

> It would be great to have {name}, {given_name} etc placeholders available for the free ticket use case.

I'm assuming you are referring to attendee names. That's not really possible, since a person could be buying 5 tickets under 5 names. Which name should we use? The person placing the order is not even necessarily part of the attendees.

**Comment by gruenzeug** [comment]
>> for free tickets, there is no {invoice_name}.

> This is not necessarily the case, you can also configure invoice addresses to be asked for free orders (Settings → Invoicing → Address Form)

Uh, I tried this before, it had no effect on free orders (at least in my case). But I didn't know it was supposed to work :D That would indeed resolve the placeholder issue.
 Quick test: checking "ask for invoice address" has no effect, checking one of the "require" options, (and of course "Do not ask for invoice address if an order is free" unchecked) results in an error when I'm test-ordering. But nevermind, I have to properly test and think it through!

>>It would be great to have {name}, {given_name} etc placeholders available for the free ticket use case.

> I'm assuming you are referring to attendee names. That's not really possible, since a person could be buying 5 tickets under 5 names. Which name should we use? The person placing the order is not even necessarily part of the attendees.

You're right, I looked into my order json, and the name is in the attendee_name only, my bad!
