### ISSUE TITLE
API Doc: payment_provider field listed as optional, but it's not

### ISSUE THREAD

**Issue by gruenzeug** [pretix/pretix#1440]
> `payment_provider` (optional) – The identifier of the payment provider set for this order. This needs to be an existing payment provider. You should use `"free"` for free orders, and we strongly advise to use `"manual"` for all orders you create as paid.
https://docs.pretix.eu/en/latest/api/resources/orders.html#creating-orders

Got a 400 telling me, that a payment_provider is needed. Added `"payment_provider": "free"` to my order, and it worked fine.
So I guess "optional" is just a mistake in the docs?

**Comment by raphaelm** [comment]
It is indeed optional since c2eba2135, but only for non-paid orders. I agree that this doesn't make much sense for free orders which are instantly paid and where we have a reasonable default. I will push both a clarification to the docs as well as a fix.
