### ISSUE TITLE
create new organizer

### ISSUE THREAD

**Issue by van15h** [pretix/pretix#1444]
hi
first of all thanks for your amazing work!

I have a question regarding creation of a new organizer. 
Pretix is installed as docker container (pretix/standalone:stable, postgres 11.5). New user is created after installation through web interface. As I understood from the documentation this user is an Admin.

Now when i'm trying to add an event i get always the error:
"Every event needs to be created as part of an organizer account. Currently, you do not have access to any organizer accounts." 
pretix.log is empty
The only option that is available for my admin user is to "Filter" organizers.

From the user documentation:
"If you want to use the hosted pretix service, you can create an organizer account on our Get started page. Otherwise, ask your pretix administrator for access to an organizer account."

How can Admin create this organizer account?

thank you

**Comment by pc-coholic** [comment]
First, you have to login and activate Admin-Mode (top right corner) of your screen.

Then, you can select the Organizers overview from the navigation bar (/control/organizers) and click the "Add new Organizer"-button.

Once the organizer has been created, you can also create events for said organizer.

**Comment by van15h** [comment]
This is my user account settings. Top right corner has only two options: Account Settings or Logout.
![image](https://user-images.githubusercontent.com/28344928/66745508-6e484c80-ee7f-11e9-8abd-1da07fd495a8.png)
Sorry but i still can not find any option to activate Admin-Mode here :-(

Do I have to activate my account also per Email? After registration I did not get any mails. 

thanks

**Comment by raphaelm** [comment]
Then you are not an admin user ;) The default admin user is admin@localhost with passwort admin.

**Comment by van15h** [comment]
That's it! 
Thank you!
