### ISSUE TITLE
Reordering Question throws verification error

### ISSUE THREAD

**Issue by Maradonna90** [pretix/pretix#1445]
If I am trying to reorder question per drag and drop I get a "Verification failed" message.
![Screenshot_2019-10-14 Questions pretix eu](https://user-images.githubusercontent.com/4048848/66771503-b042b400-eeba-11e9-8932-0fdfaaf50f84.png)
I saw in #1433 that there will be changes to the functionality, so this might be fixed in the next release?

/edit: Firefox 69.0.1 (64-bit), Arch Linux. I turned off ublock origin and allowed cookies. It also happened on a mobile device from a mate (dont have more details right now)

**Comment by raphaelm** [comment]
No, #1433 is already live on hosted, #1433 introduced drag+drop in the first place. For me it works with Firefox on Arch Linux. Can you try to reload without cache?

**Comment by Maradonna90** [comment]
No it doesn't work. Maybe some specific browser settings?

**Comment by raphaelm** [comment]
Fixed in https://github.com/pretix/pretix/commit/fa3b40f53c21e5bb0741c16af2c1e0a2e182e2c4
