### ISSUE TITLE
forms.NullBooleanSelect not rendering current selection

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#1446]
The `ShowQuotaNullBooleanSelect`-widget, used in the items settings ("Show number of tickets left") is not appending the `selected` property to any choice.

This leads to a user being able to select any of the choices, saving the form and then having the quota displayed accordingly in the presale. However, in the backend the display defaults back and with the next save the setting is overriden to the default again.

Edit: Also applies to `TicketNullBooleanSelect` - so at this point probably all `forms.NullBooleanSelect`-fields.

Z#2351209

**Comment by pc-coholic** [comment]
Changing

https://github.com/pretix/pretix/blob/fa3b40f53c21e5bb0741c16af2c1e0a2e182e2c4/src/pretix/control/forms/item.py#L369-L376

to 
````python
class ShowQuotaNullBooleanSelect(forms.NullBooleanSelect):
    def __init__(self, attrs=None):
        choices = (
            ('unknown', _('(Event default)')),
            ('true', _('Yes')),
            ('false', _('No')),
        )
        super(forms.NullBooleanSelect, self).__init__(attrs, choices)
````

will display the selections in the backend correct again - but will need some additional rework on the displaying end of things... (Note that `None`, `True` and `False` will not work)

**Comment by raphaelm** [comment]
Apparently, this was caused by the upgrade to Django 2.2: https://github.com/django/django/commit/35a08b8541c856a51b2ab718e0a2fe060debfa2a

Why does it need further work on the displaying end? Just replacing the three strings should work.

**Comment by pc-coholic** [comment]
> Why does it need further work on the displaying end? Just replacing the three strings should work.

My mistake... Didn't remember that the quota is never displayed when it's unlimited :see_no_evil:
