### ISSUE TITLE
Discount vouchers, Voucher wizard

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#145]
- [x] Multi-use vouchers #337 
- [x] Vouchers that give % or € off the original price
- [ ] Voucher creation wizard

See also #311

**Comment by rixx** [comment]
It seems to me that either adding a `multi_use` flag or an `availability` field (naming things, meh. an IntegerField, anyways) to the Voucher model would be the best choice to implement multi-use. I find a BooleanField cleaner, but an IntegerField might capture more accurately what's actually needed in practice.

**Comment by raphaelm** [comment]
Yes, I think it is a possible to reuse the Voucher model. However, adding a count is not sufficient, we also need.to:

* allow a list of applicable products (can be done with pseudo-quotas currently but this is not very nice from an UX view)
* differentiate between absolute (-5€) and relative (-5%) discounts in addition to the "set price to" that we currently have
* let the organizer, decide whether the voucher can be applied to one ticket per order or whether it is a discount on the total sum. In the latter case, taxes can get complicated.

This all makes Voucher feel cluttered und complicated and I don't like this feeling.

**Comment by rixx** [comment]
+1 for avoiding cluttered concepts.

The thing is that you have multiple features here and you need to decide how to divide them up:

 - multi-use vs single-use
 - relative vs absolute discounts
 - discounts per ticket or per order

I agree that this would be a lot of features in addition to the already-existing features of vouchers:

 - blocking vs non-blocking
 - ignoring quota vs not
 - applying to items or quotas or variations

The question is whether it is possible to find two reasonable (overlapping, probably) feature sets that would feel intuitive for users (find names, too). Implementation should probably still use a common interface for less cluttered coding, but that should be an afterthought.

**Comment by raphaelm** [comment]
Yep, you are totally right. See why I postponed this so far? :/

**Comment by raphaelm** [comment]
XING Events does not have all of our features (e.g. like blocking vouchers and applying to quotas, they don't even have quotas as we know it), but they solve the UI problem by having a four-step wizard that lets you make a number of decision first and then sends you into a suitable stripped-down form that only shows you the relevant options. This gives the possibility to better explain the implications of some fields, I believe we should go for a similar approach.
