### ISSUE TITLE
Request: Prefill the maximum redeeming quantity when redeeming voucher

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1465]
Hi there,

when redeeming a voucher you see the field where you can type in your desired quantity of tickets, limited to the maximum value set while creating the voucher before.

After typing in the voucher code, the field always is prefilled with _1_ as starting value and you can't go higher than _n_. Wouldn't it be nicer to have the maximum value of _n_ tickets prefilled and the customer can adjust this? So perhaps the customers are less confused, if they have a voucher for 3 tickets, but only _1_ is prefilled

This request makes only sense, if you send one voucher to one person and don't use it for multiple customers, of course.

Cheers :)

**Comment by raphaelm** [comment]
> This request makes only sense, if you send one voucher to one person and don't use it for multiple customers, of course.

Yes, that's where I see the problem. Unlimited-use vouchers are not supported (for other reasons), and therefore lots of people create vouchers which can be used e.g. 9999 times. This would be a pretty bad default quantity.

Even though we could to a heuristic (e.g. handle vouchers with more than 10 usages differently), I think it will create more confusion than it solves :(
