### ISSUE TITLE
German informal missing translations

### ISSUE THREAD

**Issue by gilbertf** [pretix/pretix#1477]
Hi,
using german (informal) I noticed that some text is not translated e.g. "Your orders for" in emails to the client.

In "locale/de/LC_MESSAGES/django.po" we have:
#: pretix/presale/views/user.py:45
msgid "Your orders for {}"
msgstr "Ihre Bestellungen für {}"

This is missing in locale/de_Informal/LC_MESSAGES/django.po

Next I treid to add the translation here: https://translate.pretix.eu/projects/pretix/pretix-js/de_Informal/, but searching for this string does not give any results.

So what to do?

best regards

**Comment by raphaelm** [comment]
> This is missing in locale/de_Informal/LC_MESSAGES/django.po

This is not true, the string is there in line 18794 at the moment.

The untranslated subject was a software bug that we fixed just last week: https://github.com/pretix/pretix/commit/2e9e5a89945474272a528af401806621db15886b
