### ISSUE TITLE
Add more information to PDF tickets

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#148]
e.g. the order code

**Comment by FlaviaBastos** [comment]
Hi, @raphaelm 
I added the order code to the PDF - please check file attached.
Is this ok? Is there anything else you think should be added also?
[1d73f4f9-8ae4-464d-becd-a0accfed05d0..pdf](https://github.com/pretix/pretix/files/514727/1d73f4f9-8ae4-464d-becd-a0accfed05d0.pdf)

**Comment by raphaelm** [comment]
Yes, this is totally fine as a default :) Just like the other strings in the PDF, there should be settings for their position and size such that one day we can build a fancy drag-and-drop PDF editor :)
From the top of my head, I currently cannot think of other useful information to include there.
