### ISSUE TITLE
Error: API Endpoint for a list of all event items returns a 500 error.

### ISSUE THREAD

**Issue by superscreen** [pretix/pretix#1480]
Hello

the **API Endpoint** for a list of all items (better known as products) returns a **500 Error**.

**GET /api/v1/organizers/(organizer)/events/(event)/items/**
/api/v1/organizers/prr/events/award-2019/items/
Returns a 500 Error

Nov  8 12:24:37 tickets gunicorn[5594]: AttributeError: 'list' object has no attribute 'get'

Also with the next request a error appears
**GET /api/v1/organizers/(organizer)/events/(event)/items/(id)/**
/api/v1/organizers/prr/events/award-2019/items/4/
Returns a 500 Error

AttributeError at /api/v1/organizers/prr/events/award-2019/items/4/
'list' object has no attribute 'get'

**Pretix  Version:  2.9.0 - 3.3.0**
Django Version: 2.2.1
Python Version: 3.5.2

**The following endpoints are ok:**
GET /api/v1/organizers/
GET /api/v1/organizers/(organizer)/
GET /api/v1/organizers/(organizer)/events/
GET /api/v1/organizers/(organizer)/events/(event)/orders/

**Comment by pc-coholic** [comment]
I just checked on our instance and I cannot see the same behaviour here...

> Pretix Version: 2.9.0 - 3.3.0
Is this happening to you on pretix 2.0.0 and 3.3.0? Or did you recently update from 2.9.0 to 3.3.0?

In case you recently updated: Did you make sure to run all the migrations and restart pretix-web as well as the pretix-workers?

**Comment by raphaelm** [comment]
Also, prlease have a look if pretix.log contains a full stacktrace

**Comment by superscreen** [comment]
The same behaviour on 2.9.0, 3.0.0, 3.2.0 and now 3.3.0

Here a output for
**GET /api/v1/organizers/(organizer)/events/(event)/items/(id)/**

HTTP: 500
AttributeError at /api/v1/organizers/prr/events/award-2019/items/4/
'list' object has no attribute 'get'

Request Method: GET
Request URL: http://tickets.local/api/v1/organizers/prr/events/award-2019/items/4/
Django Version: 2.2.1
Python Executable: /var/pretix/venv/bin/python3
Python Version: 3.5.2
Python Path: ['/var/pretix', '/var/pretix', '/var/pretix/venv/bin', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/var/pretix/venv/lib/python3.5/site-packages']
Server time: Fri, 31 May 2019 10:57:05 +0000
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'pretix.base',
 'pretix.control',
 'pretix.presale',
 'pretix.multidomain',
 'pretix.api',
 'pretix.helpers',
 'rest_framework',
 'django_filters',
 'compressor',
 'bootstrap3',
 'djangoformsetjs',
 'pretix.plugins.banktransfer',
 'pretix.plugins.stripe',
 'pretix.plugins.paypal',
 'pretix.plugins.ticketoutputpdf',
 'pretix.plugins.sendmail',
 'pretix.plugins.statistics',
 'pretix.plugins.reports',
 'pretix.plugins.checkinlists',
 'pretix.plugins.pretixdroid',
 'pretix.plugins.badges',
 'pretix.plugins.manualpayment',
 'django_markup',
 'django_otp',
 'django_otp.plugins.otp_totp',
 'django_otp.plugins.otp_static',
 'statici18n',
 'django_countries',
 'hijack',
 'compat',
 'oauth2_provider']
Installed Middleware:
['pretix.api.middleware.IdempotencyMiddleware',
 'django.middleware.common.CommonMiddleware',
 'pretix.multidomain.middlewares.MultiDomainMiddleware',
 'pretix.multidomain.middlewares.SessionMiddleware',
 'pretix.multidomain.middlewares.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'pretix.control.middleware.PermissionMiddleware',
 'pretix.control.middleware.AuditLogMiddleware',
 'pretix.base.middleware.LocaleMiddleware',
 'pretix.base.middleware.SecurityMiddleware',
 'pretix.presale.middleware.EventMiddleware']


Traceback:

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/var/pretix/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/viewsets.py" in view
  116.             return self.dispatch(request, *args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  495.             response = self.handle_exception(exc)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/mixins.py" in retrieve
  57.         serializer = self.get_serializer(instance)

File "/var/pretix/venv/lib/python3.5/site-packages/rest_framework/generics.py" in get_serializer
  111.         kwargs['context'] = self.get_serializer_context()

File "/var/pretix/venv/lib/python3.5/site-packages/pretix/api/views/item.py" in get_serializer_context
  64.         ctx['has_variations'] = self.request.data.get('has_variations')

Exception Type: AttributeError at /api/v1/organizers/prr/events/award-2019/items/4/
Exception Value: 'list' object has no attribute 'get'
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:

**Comment by raphaelm** [comment]
Huh, that's weird indeed. The offending code line also does not seem to do anything, removing it doesn't break any tests and even reading the old #676 diff that introduced it I'm not quite sure why it's there, so I removed it. I'm still not sure why it is only triggering for you, request.data shouldn't normally be a list.

**Comment by superscreen** [comment]
Thank you

I get a result now with 3.4.0-dev
