### ISSUE TITLE
Automatic email link detection in emails doesn't recognise top-level-domain .digital

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#1488]
When we create a signature or an e-mail, that should be sent to participants, we have to add our e-mail address xyz@bonn.digital with html. If we don't add them with HTML, the created link will miss one letter and a click on the link will lead to xyz@bonn.digita (without l). 

**Signature in backend**
![Unknown-1](https://user-images.githubusercontent.com/1153741/68895892-8fc08080-072a-11ea-9aa2-d95ac6c6af3e.png)

**Result**
<img width="587" alt="Bildschirmfoto 2019-11-14 um 22 03 03" src="https://user-images.githubusercontent.com/1153741/68895880-8afbcc80-072a-11ea-9aeb-84f7c7f97c5a.png">

**Workaround**
![Unknown](https://user-images.githubusercontent.com/1153741/68895884-8d5e2680-072a-11ea-938b-e2ce0cb075b6.png)

**Comment by raphaelm** [comment]
This is not a bug in pretix, but in [bleach](https://github.com/mozilla/bleach)'s linkify function. It would be interesting if it's an active bug in bleach or if we just need to upgrade our bleach version.

**Comment by pc-coholic** [comment]
It seems like bleach is not planning on including more TLDs themselves and isn't open to pulling in the latest list of TLDs dynamically from IANA...

One possible way forwards would be to use https://pypi.org/project/tlds/ and just feed bleach with that list.

However, we should consider the following: Installing the `tlds`-package will download the current list of TLDs from IANA and keep them local.

Advantage: Every time pretix is installed/updated (and by extension also the `tlds`-package), a current list of TLDs is provided.

Disadvantage: Yet another call to an external webservice which might get stuck in some firewall.

Alternative: Download the list and ship it with pretix, taking care to update it every now and then. Or just vendor the whole `tlds`-package...

**Comment by raphaelm** [comment]
Hmm, yeah, I don't really like the approach of ``tlds`` updating it silently every day. I think we should just ship a list and include updating it to our release checklist. Alternatively, we could include an update mechanism ourselves like the currency rates, but I think that's a lot of work for little gain.

**Comment by pc-coholic** [comment]
Depends on https://github.com/mozilla/bleach/pull/486 (unless we just roll our own email-regex in the future).
