### ISSUE TITLE
Copy answers into multiple tickets

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#149]
If a user buys more than one ticket, in many cases he has to enter multiple names and answer multiple questions defined by the admin. In some cases, it would be useful to have a butten that copies the answers from the first ticket into the other tickets.

**Comment by andmckvr13** [comment]
Hello raphaelm, sorry if this is a stupid question, but are you using JavaScript for this or a different language? I'm a new developer (JS only for now)  and looking to gain more contributions.

**Comment by raphaelm** [comment]
Hi @andmckvr13, yes, I would do this in JavaScript. We do not have a lot of JS in pretix right now, but this is one of the points where it makes sense.

If you want to to contribute to this, the best way to start is to [get pretix running on your machine](https://docs.pretix.eu/en/latest/development/setup.html) and play with it for a few minutes to get a feeling of how pretix works and where this is going. If you have any questions on the way, no matter how stupid they seem, please do not hestitate and ask, I'll be happy to guide you through the process!

**Comment by andmckvr13** [comment]
Danke Schön

**Comment by chrisdamba** [comment]
Hi @raphaelm Is this feature still needed? This would be my first pull request but I would like to give it a go?

**Comment by raphaelm** [comment]
Hi @chrisdamba! I believe this would still be useful, so feel free to try yourself! If you get stuck in the process, please ask, I'll be happy to help :)

**Comment by chrisdamba** [comment]
Thanks @raphaelm for the opportunity, let me set up pretix and will definitely give you a nudge should I bump into any problem :)

**Comment by chrisdamba** [comment]
@raphaelm I've attached a screenshot of what I think may be the correct page to implement the enhancement, is that right? Am I looking into the right place, i.e. `pretix/control/templates/pretixcontrol/order/index.html`?
![pretix_1](https://cloud.githubusercontent.com/assets/2035056/19658130/b6e7e2d8-9a1e-11e6-8a16-3948c2ddb909.png)

**Comment by raphaelm** [comment]
Yes, that is the correct file!
