### ISSUE TITLE
Adding U2F device complains about missing https

### ISSUE THREAD

**Issue by DerDakon** [pretix/pretix#1501]
```
WebAuthn-Unterstützung ist nur verfügbar, wenn pretix über HTTPS ausgeliefert wird.
```

Guess what, this actually _is_ a https connection, so what am I doing wrong? How does pretix detect if this is https or not?

**Comment by raphaelm** [comment]
There's either something wrong with the headers your reverse proxy (e.g. nginx) is setting, or there's something wrong with the URL in your pretix.cfg file.

**Comment by DerDakon** [comment]
In the pretix.cfg I have ```url=https://…```, so it's probably not that. I use apache as proxy, so a missing header is probably the right thing. Sadly all examples were using nginx, so I probably missed something when I built that together. Which header is pretix looking at?

**Comment by raphaelm** [comment]
Hmm, this is coming from djnago, can you try "X-Forwarded-Proto: https"? I'm not exactly sure either.

**Comment by DerDakon** [comment]
Awesome, that did the trick:

```apache
RequestHeader set X-Forwarded-Proto "https"
```
