### ISSUE TITLE
"Internal Server Error" when using emojis

### ISSUE THREAD

**Issue by malfynnction** [pretix/pretix#1503]
Hey there, 
I was trying to change the invoice information for my ticket and put "🤷‍♂️" as the "internal reference" - this was the result: 
![Screenshot 2019-11-26 at 15 59 38](https://user-images.githubusercontent.com/24372341/69645163-041dec80-1066-11ea-9742-86d1efc586f2.png)

**Comment by raphaelm** [comment]
This is not a bug in pretix, pretix supports full UTF-8. Probably this is an instance running with a MySQL server where the database uses a limited charset.

(That said, the Emoji would not be rendered on the invoice anyways, since the font does not support it.)

**Comment by malfynnction** [comment]
Okay, thanks for the quick reply!
