### ISSUE TITLE
Extending Content-Security-Policy settings.

### ISSUE THREAD

**Issue by enyachoke** [pretix/pretix#1519]
Am developing a payment plugin for a provider that only allows me to insert an iframe. Hence am forced to add an exemption  to https://github.com/pretix/pretix/blob/master/src/pretix/base/middleware.py alongside stripe. My question is is there a way of extending the exemptions  without modifying  the core? I really  want to keep the core unmodified.

**Comment by raphaelm** [comment]
Yes, it's possible! You can use a ``process_response`` signal to merge the core CSP header with your own. You can see an example here:
https://github.com/pretix/pretix-wirecard/blob/master/pretix_wirecard/signals.py#L24
