### ISSUE TITLE
External authenticated users cannot delete events.

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#1521]
With the release of #775 users are able to authenticate using external password validation. Deleting events currently requires the password of the user. Is there any way we can update this, such that external authenticated users can also delete events? I'd be open to implementing a solution, however would like your opinion on how such feature should work.

**Comment by raphaelm** [comment]
Good one! This is something we did not think about. Same for the "shredding" feature probably.

I'm not sure how such a solution could look except for … not asking for the password?

We can force a full re-authentication if the user is an external user and wasn't recently logged in, e.g. like this:

```
        tdelta = time.time() - request.session.get('pretix_auth_login_time', 0)
        if tdelta > self.max_time:
            return redirect(reverse('control:user.reauth') + '?next=' + quote(request.get_full_path()))
```

(That's from ``RecentAuthenticationRequiredMixin``, which we could use, but then it would also be effective for pretix-native users which might be a bit annoying)

**Comment by MaicoTimmerman** [comment]
Currently, the `RecentAuthenticationRequiredMixin` and specifically the `ReauthForm` does not really take into account external authentication. It only allows validating form fields using `pretix.base.auth.BaseAuthBackend.form_authenticate`, resulting in the following screen:

![image](https://user-images.githubusercontent.com/904824/70806157-f765fc00-1dba-11ea-9aad-bc03ae5d360a.png)

My suggestion would be to:
1. Add the `RecentAuthenticationRequiredMixin` to event deletion and remove the seperate password fields from the event deletion and data shredder.
2. Add logic to the reauth to check whether the users authentication backend supports form fields. If it does not, do a fresh login using the `BaseAuthBackend.authentication_url`.

**Comment by raphaelm** [comment]
> Add the RecentAuthenticationRequiredMixin to event deletion and remove the seperate password fields from the event deletion and data shredder.

Hmmm, yeah, I guess that's sensible.

> Add logic to the reauth to check whether the users authentication backend supports form fields. If it does not, do a fresh login using the BaseAuthBackend.authentication_url.

Agreed.
