### ISSUE TITLE
External authentication without second login backend enabled not possible

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#1522]
When using multiple authentication backends, `nav-pills` are shown shown to select the authentication method. These buttons will replace the `backend` parameter for form based authentication methods. For `authentication_url`-based backends clicking the button will redirect to an external webpage.

We exclusively use an `authentication_url`-based backend, which results in the following login screen:

![image](https://user-images.githubusercontent.com/904824/70807661-495c5100-1dbe-11ea-87b8-609770c85497.png)

Since the `nav-pills` are not rendered, we are unable to redirect to the login page.

My suggestion would be to:
1. Hide the `Log In` button when no backends are used which are submitted using form fields.
2. Always show the `nav-pills` when the only available backend uses `authentication_url` based authentication.

**Comment by raphaelm** [comment]
> Hide the Log In button when no backends are used which are submitted using form fields.
> Always show the nav-pills when the only available backend uses authentication_url based authentication.

Agreed! Happy for a PR! ;)
