### ISSUE TITLE
Allow to only purchase one product that grants access

### ISSUE THREAD

**Issue by r-dannhauer** [pretix/pretix#1524]
In regards to the GSDPR a person can't give the consent for someone else when it comes to transmit their personal data. When you only ask for a name, then there's no problem, in my understanding. But I have following scenario:
I have 1 Tickets that has 3 variations. A day pass, a place on the camping ground, and a bed in the house. I set the product up so that only one is allowed to be ordered per order.
All products have questions and asks for adresses for every ticket.

So far so good.

Even though I only allow one ticket per order it is possible to tick the boxes of two variations. There's no error message and the system thinks all is in order.
Then at a certain point in the system only shows a "500 internal server error", with no explanation.

Is it possible to implement a setting in which it is only allowed to buy one product that allows access, or to not let the customer put both in the cart?

**Comment by raphaelm** [comment]
This doesn't sound right. Can you share screenshots of the settings you mentioned, the shop page with the two checkboxes, as well ass the ``pretix.log`` lines of the error 500?

**Comment by r-dannhauer** [comment]
Okay, I don't know what happened, but after updating the system, plugins and pip I can get to the button "Zahlungspflichtig bestellen", and clicking on that shows the error that I can only put one in my cart.
Can that message pop up earlier, when I actually put them in the cart?
(We did the test some time back and they mentioned the error a few days back, so that bug seems to have been fixed)

**Comment by r-dannhauer** [comment]
Here the screenshots:
![grafik](https://user-images.githubusercontent.com/7952758/70868447-43fb3400-1f81-11ea-8abd-002379044f06.png)
The settings

![grafik](https://user-images.githubusercontent.com/7952758/70868460-55dcd700-1f81-11ea-9f80-0c63db70de51.png)
The shop

![grafik](https://user-images.githubusercontent.com/7952758/70868465-6bea9780-1f81-11ea-9a0d-c09c80b2b643.png)
Both products in the shopping cart.

After entering information for both products I get the overview with both tickets still in the cart. After hitting "Zahlungspflichtig bestellen" I get this:
![grafik](https://user-images.githubusercontent.com/7952758/70868477-9177a100-1f81-11ea-9e44-67e6d28420a7.png)

**Comment by raphaelm** [comment]
Thanks a lot, we identified the bug and fixed it for the next release!
