### ISSUE TITLE
Stripe failes with: The statement descriptor cannot include "

### ISSUE THREAD

**Issue by buttle** [pretix/pretix#1535]
Hi,

We are having trouble with an event's tickets purchasing via Stripe.

https://***.com/control/event/word/event_name/orders/PPYXE/
2019-12-21 18:08 | Credit card via Stripe | failed | €8.00 | Error message The statement descriptor cannot include "

We've tried with a couple of credit cards and get the same result.

Other events work fine so, might this be a field we've filled out incorrectly?

Thanks.

**Comment by pc-coholic** [comment]
This is probably get related to the short form of your event name... Did you use any special characters in there?

**Comment by raphaelm** [comment]
This is fixed in 3.4.0, you are probably running 3.3.0
56cfdfc5b

If you are indeed running 3.4.0, please reopen (and tell us the name of your event). Otherwise, please update :)

**Comment by buttle** [comment]
> This is probably get related to the short form of your event name... Did you use any special characters in there?

hmmm. I don't know. Maybe. I didn't create the event. Looking at it now, the short form seems ok.

And yes. I was on 3.3.0. Upgraded now :)
Thank you all.
