### ISSUE TITLE
I just want to thank you all!

### ISSUE THREAD

**Issue by ajpierson** [pretix/pretix#1537]
I am using Pretix for selling fundraiser tickets for my daughter's jump rope team and I just want to thank you all for such a fantastic product.  I evaluated pretix last year for the same event but removed it from consideration because it didn't support check-in on iOS.  Since you added that feature, I tried it out again, and I am just so impressed at the power of this application.  It has met nearly every need I've had.  I hope to be able to contribute some additional features to the product in the future to show my gratitude.  Again, thank you for providing this application to the community!

**Comment by raphaelm** [comment]
Thank you for the feedback! <3
