### ISSUE TITLE
API-only endpoint

### ISSUE THREAD

**Issue by sylvinus** [pretix/pretix#1547]
Hello,

To optimize memory usage and have a tighter security boundary, it would be great to be able to start pretix in "API-only" mode, where presale, control and many other apps are disabled and pretix is only serving its API.

This would also contribute to the already very modular design of pretix.

I have made a quick & dirty prototype of this and was able to remove these from INSTALLED_APPS:

```
            'django.contrib.staticfiles',
            'pretix.control',
            'storages',
            'compressor',
            'bootstrap3',
            'djangoformsetjs',
            'pretix.presale',
            'django_otp',
            'django_otp.plugins.otp_totp',
            'django_otp.plugins.otp_static',
```

This seems to have removed around 80mb from the memory footprint at startup.

What do you think?

(If we push this further, maybe `presale` could be a plugin?)

Thanks!

**Comment by raphaelm** [comment]
I don't think this is relevant for 99% of our userbase, so I wouldn't want to change pretix for this. Especially, it's not a use case we can continously test changes for. Out of curiosity: What did you need to change apart from the settings.py, though?

You are free to pass your own settings module as DJANGO_SETTINGS_MODULE in the environment where you change the installed_apps value.

**Comment by sylvinus** [comment]
Makes sense, no worries.

We maintain quite an extensive fork of pretix now so it's a bit too late for just changing DJANGO_SETTINGS_MODULE ;-)

For this to work, apart from the settings.py it was relatively straightforward, mostly about imports here and there to refactor or make conditional.

thanks!
