### ISSUE TITLE
Feature Request (widget): Publish button open function

### ISSUE THREAD

**Issue by fmalcher** [pretix/pretix#1549]
The `<pretix-button>` component from the widget is a great tool to integrate the presale workflow in our own web page.
However, this is bound to a button that
- is harder to style than a native button
- flickers when the widget.js loading is delayed
- can only be triggered by a real button, but not programmatically

### Proposal

Publish the `buy()` method (or a suitable wrapper) under `window.PretixWidget` so we can open the presale modal programmatically.

**Comment by fmalcher** [comment]
Tried to identify the relevant parts but didn't feel ready to prepare a PR:

https://github.com/pretix/pretix/blob/master/src/pretix/static/pretixpresale/js/widget/widget.js#L1044

https://github.com/pretix/pretix/blob/master/src/pretix/static/pretixpresale/js/widget/widget.js#L454-L479

I suppose it's not a good idea to publish `buy()` directly since it's connected with the form from the button. Thus, we should probably rather publish a wrapper around `buy` that abstracts the call:

`openDialog(event, items, voucher, skip-ssl-check)`

**Comment by raphaelm** [comment]
This should be a separate function, yes, that behaves exactly like a button click. I'm putting this on our roadmap!

**Comment by raphaelm** [comment]
Turns out we actually need to render the button somewhere (but we can completely hide it), since we require a ``<form>`` for the fallback behaviour (opening in a new tab instead of an overlay) with pre-selected items. I've implemented that now and hope it works for your use case!
