### ISSUE TITLE
Feature Request: Different page layouts

### ISSUE THREAD

**Issue by fmalcher** [pretix/pretix#1550]
With pretix, you can serve a variety of event types. From what I imagine, among them are
- cultural events (theatre, concerts)
- dedicated education events (workshop, training)
- conferences
- meetups
- …

If I should build dedicated sales pages for different kinds of events, I'd build them differently since the audience and their expectations are different.
For a concert it's already clear that I want to see the artist, they just need tickets now. For a workshop event where there are similar competing offers, it's all about simplicity and persuading the user to buy tickets in MY shop.

Thus, the shop layouts should be different. For a concert I'd present information first, then tickets. For a workshop, the user probably came from an info page and they just want to buy a ticket now. (...or whatever reasons might apply from a UX perspective.)

## Proposal

**Provide different shop layouts.** This doesn't have to be customizable, but 3 different layouts to choose from would be enough. I imagine something like

- Info first, then tickets (current layout)
- tickets first, then info (like the cart that is always fixed at the top)
- column layout: metadata at the side, info in the main area, ticket area collapsable (like Eventbrite)
- …

**Comment by JohannesHoppe** [comment]
We definitely also need the possibility to upload some pictures!

**Comment by raphaelm** [comment]
I'm not convinced that multiple layouts are the way to go. We're trying to make pretix simpler to set up, not more complicated, and I think the widget provides enough flexibility to design a good onboarding experience. I'd rather add another text box so you can enter text both above and below the list of products. (And pictures need to be solved in some way, of course.)
