### ISSUE TITLE
Feature Request: Header image should be higher

### ISSUE THREAD

**Issue by fmalcher** [pretix/pretix#1551]
The header image ("logo") height is limited to 120px at the moment.
While this is great for a logo, this does not work well with header images in the "big picture" concept.

## Proposal

- Allow header images to be higher, e.g. 400px
- If uploades image is higher than 120px, show a warning that it might not be suitable for mobile users and that it should be tested thoroughly

Could be solved with different layouts and therefore possibly related to https://github.com/pretix/pretix/issues/1550

**Comment by raphaelm** [comment]
I'm a bit skeptical here but we should make this somehow more flexible. I'm mostly concerned that people will start putting content into these pictures which will be horrible on mobile where the image gets resized to a very small size.

I think we should introduce a boolean switch that defaults to the current behaviour (resize to 120px height) but allows to instead keep the original size of the picture if desired (capped at the max page width)

**Comment by raphaelm** [comment]
Fixed in the meantime
