### ISSUE TITLE
Individual payment term per payment provider

### ISSUE THREAD

**Issue by n0emis** [pretix/pretix#1554]
It would be nice to set a individual payment-term per method. When providing the option to pay the admission-fee onsite, but also having to option to pay via bank transfer, this could give the organizer the option, to have the money on-hand.

**Comment by raphaelm** [comment]
Pretty sure we had this ticket before but can't find it right now, #1333 is only similar.

I understand the line of thought, but I would say that this is wrong. The payment term is not a property of the payment, but of the order. The acceptance of an order forms a (social, if not legal) contract that says "You'll get this ticket if you pay by X". A person who initially selected bank transfer can switch their payment method at any time before their payment succeeded. It does not make sense that this would change their payment term, does it? I think the date that an order actually expires shouldn't depend on the selected payment method. If you offer participants to pay cash on site, why shouldn't the person who selected bank transfer but forgot to make the transfer not be able to pay cash on site?

I know that this regularly causes problems in combinination with cash sales, but I think the solution needs to look different. Maybe we need to differentiate between displayed payment term and actual payment term? :D
