### ISSUE TITLE
Extend core views from plugins

### ISSUE THREAD

**Issue by orlando** [pretix/pretix#1555]
Hello!

We are doing customizations to our Pretix instance via plugins and has been working great. We added some extra steps to our checkout process to ask our users to create a profile

![image](https://user-images.githubusercontent.com/849872/72824159-7233f980-3c3a-11ea-90ef-2c4d57bca77c.png)

We want to link to this user profile from core views in the backend. For example, adding a button to the Order details toolbar.

![image](https://user-images.githubusercontent.com/849872/72824075-49abff80-3c3a-11ea-96fb-5ece62c67005.png)

Is this possible via plugins?

Thanks!

**Comment by raphaelm** [comment]
You can add sections to the backend page, but no additional buttons:
https://docs.pretix.eu/en/latest/development/api/general.html#pretix.control.signals.order_info

**Comment by orlando** [comment]
Cool, I'll check that and see how it works. In case we need the button, are you open for PRs that add this functionality? Just for orders atm

**Comment by raphaelm** [comment]
I'm honestly not sure if I think it warrants the added complexity. I also don't see how "just a button" is useful here, wouldn't you want to show some details from the profile directly on the order page?

**Comment by orlando** [comment]
Yeah, probably that will solve the need we have, will try it and see.

Thanks @raphaelm!
