### ISSUE TITLE
Override the Term "order" in pretix

### ISSUE THREAD

**Issue by mistressofjellyfish** [pretix/pretix#1557]
So, this one's kind of fun.

We use pretix to manage attendence to our Freizeitfahrten (if any native speaker has a nice translation for that uber-german term, please let me know). However, some folks in our youth centre have raised concerns that the term "order" ("Bestellung") sounds too commercial for our volunteer run programs.

At the Moment, I get by by simply making another version of the de_informal language; but obviously that breaks on updates. It would be nice if we could override the term "Order" at least in the front end with a custom term on a per-organizer-per-language basis.

Now; I know next to nothing about how the translating features of pretix work, however I'm willing to spend time to learn and make a suitable pull request with that functionality as I don't believe this can be reasonably implemented with a plugin. Would that be a feature that could be merged or is my time better spent automating the editing of the language file?

**Comment by mistressofjellyfish** [comment]
Another suitable way to address this would be Languages-as-plugins. That would keep the diff on updates small and would solve my issue too.

**Comment by raphaelm** [comment]
To be honest: Nope, this would not be merged. You can run your own translation file, it's standard .po files like in use in most Linux software and there are tools to edit them.

**Comment by mistressofjellyfish** [comment]
Thank you for the quick reply! I'll go automate that then.
