### ISSUE TITLE
Provide a unified approach to plugin settings

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#156]
At the moment (https://github.com/pretix/pretix/commit/8dcb8193fa185b894b3024e53299e07017c6704e), the [docs](https://docs.pretix.eu/en/latest/development/implementation/settings.html) reference both `SettingsSandbox` and `SettingsForm` as a way of interacting with settings storage. But at this point, the plugin is still responsible for providing a view and a template for the `SettingsForm`, and there is no way to add a page/tab to the normal/core settings page.

I'd propose a signal similar to `pretix.control.signals.nav_event`, probably just receiving a `SettingsForm`.
We might also want to consider a `PluginSettingsForm` that handles prefixing/sandboxing, to prevent plugins from overriding settings other than their own. Maybe introduce a unified plugin prefix that will be used both for settings and views prefixes.

I'd look into this one in a few weeks, but until then, it's up for grabs :)

**Comment by raphaelm** [comment]
As the plugin list grows, the sidebar navigation becomes very long, so I'd really like to see this, in case somebody wants to work on this :)
