### ISSUE TITLE
Giftcard Filters

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#1565]
It would be great, if the giftcard-overview on the Organizer-level could get some filtering capabilities - right now, we can only search by name.

Ideas:
- Filter by value
- Hide empty giftcards
- Filter by Test/Prod

Z#2355601

**Comment by Arnovsky** [comment]
Hi, can I take this issue? @pc-coholic

**Comment by pc-coholic** [comment]
Sure! Go ahead! :-)

**Comment by Arnovsky** [comment]
Is there a complete list of features? or should I start with implementing the ideas first?

Also from a looking at the code, a regular table is used to display the information, how about using [datatables](https://datatables.net) for this issue?
