### ISSUE TITLE
Grants from cybercoin foundations

### ISSUE THREAD

**Issue by burdges** [pretix/pretix#1566]
Almost anyone buying anything in cybercoins does so in BTC or ETH, but those projects have many problems that other cybercoins projects exist to fix.  These newer projects like zcash, polkadot, cosmos, etc. often have foundations that give grants for ecosystem work, possibly including payment method plugins.  These foundation run yearly developer conferences that sell tickets, but also you can ask them for small development grants under open source licenses: 
 - ZCash foundation: https://www.zfnd.org/grants/
 - Web3 foundation (Polkadot): https://github.com/w3f/Web3-collaboration/

**Comment by raphaelm** [comment]
Not sure what the issue in pretix is here.

**Comment by burdges** [comment]
It's merely a small dev funding source people here might look into, no reason to keep this issue open after you guys have seen it.  :)
