### ISSUE TITLE
Discussion on database design decisions 

### ISSUE THREAD

**Issue by saiprashanth173** [pretix/pretix#1579]
Hello,

Thanks for developing Pretix.

We are part of the database group at Georgia Institute of Technology. We are developing a tool, called sqlcheck, for assisting database application developers in designing performant and maintainable applications. sqlcheck automatically detects sub-optimal database design choices and suggests better alternatives. For instance, storing comma-separated values in a column violates the first normal form, which impacts the performance, maintainability, and extensibility of the application.

We extracted SQL queries from Pretix and analyzed them with sqlcheck. Here are the results:

- **Too many indexes/Indexes not being used [Postgres]:** In certain columns (e.g., pretixbase_giftcard - (secret), pretixapi_oauthgrant - (code), pretixbase_invoice -(full_invoice_no) etc.), we observed that the application constructs multiple indexes on the same column, i.e. btree index and a btree index with ‘varchar_pattern_ops’.  From the queries obtained by running your integration tests, we feel that the index with ‘varchar_pattern_ops’ is never used by your application. We believe that these indexes are created by Django as a default behavior (refer: https://code.djangoproject.com/ticket/12234, and https://code.djangoproject.com/ticket/24507 ).  In your application, we observed 36 ‘varchar_pattern_ops’ indexes and we wanted to validate if it’s just not because of the default behavior. Our experiments with sqlcheck showed that constructing too many indexes slows down data ingestion and also increases the disk usage.

- **Usage of pattern matching:** For pages that have auto-suggest feature, such as Products page Category field,  we observed queries with predicates that have a leading and trailing wild card on most of the fields in the filters (eg. UPPER("pretixbase_itemcategory"."name"::text) LIKE UPPER('%na%'). As you might be aware, for such queries a sequential scan is performed and the indexes on these columns will not be utilized. We wanted to know if the team has considered the possibility of using trailing wildcards for some of the cases so that the index on these fields can be utilized. We feel in most cases, it’s sufficient to perform queries with trailing wild card i.e. (UPPER("pretixbase_itemcategory"."name"::text) LIKE UPPER(‘na%')) for auto-suggestion, however, we were not sure about the requirements of your application. 

- **Missing database level constraint checks:** For certain columns, (eg. “pretixbase_order”.”status”), we observe that there is validation at the application level to restrict the values which can be stored in these fields. We believe it’s best practice to have database level checks to make sure data integrity is always maintained. This can be achieved in two ways, (i) through the ‘CHECK’ constraint feature provided by the DBMS or, (ii) [preferred/better] have a new table which stores a list of possible statuses and have a foreign key relationship in the “pretixbase_order” table. 

- **Multi-valued attributes:** Storing delimiter separated values in a single column. In Pretix, the tool identified delimiter separated values in “pretixbase_checkinlist”.auto_checkin_sales_channels, "pretixbase_item".sales_channels. Our experiments with sqlcheck showed that there is a significant performance impact in querying or updating such columns and could also lead to returning of inaccurate records. The alternate better approach, i.e., having an intermediate table to represent this Many to Many relationship, could result in an approximately 10x performance gain and also makes sure that the application is maintainable, accurate and extensible. We understand that this design decision could stem from application requirements. Could you please share the rationale behind this design decision?

Please note that we are researchers (Masters/PhD students) and we don't intend to advertise any product. Our team aims to understand the best practices in using Databases by analyzing some big open-source repositories, such as yours, and make them available to a broader community of developers.

We hope that sqlcheck will assist the broader community of database application developers with designing applications. Your feedback will be greatly appreciated.

Thanks for your time.

**Comment by raphaelm** [comment]
This looks like spam, not like a serious discussion.

**Comment by raphaelm** [comment]
On second thought, looks like you seriously had a look at the project. Thanks. However, I'm afraid I do not have the time to discuss all of these in detail, especially since there is no current need to do so.

> Too many indexes/Indexes not being used [Postgres]

Yes, this is because of Django'S default behaviour.

> Usage of pattern matching

Good point, although I think in many places it would confuse users if they could only search at the beginning of a string. For example, if users have the events "Conference 2019" and "Conference 2020", they expect to be able to search for "2020".

> Missing database level constraint checks

CHECKs is missing due to Django (at least in the past) not being able to do this in a cross-database way. In the years of operation, this has never shown to be a problem.

> Multi-valued attributes

Yeah, we know. This is a trade-off with simplicity and happens in a few places. It works good for us right now, in the future we'd want to upgrade this to something to JSONField, which Django will only be able to do cross-database in a couple of versions.

**Comment by saiprashanth173** [comment]
@raphaelm, thanks for making time and replying.
