### ISSUE TITLE
AWS EC2 install

### ISSUE THREAD

**Issue by Pilly170** [pretix/pretix#1580]
Hi,
I wanted to test this out, so created an aws ec2 instance  (ubuntu18.04)

Most of it had to be run as root, otherwise it wouldnt install

Are there any instructions I should use for ec2 instances? As there were permissions issues all through the manual install guide especially when you start to get to the virtual env.

I had issues such as no pretix module, no permissions, I had to also do pip3 install cryptography==2.3.1

Any ideas on how to proceed?

**Comment by raphaelm** [comment]
You should be able to use our usual install guide for EC2.

**Comment by Pilly170** [comment]
Thanks. 
I did try the guide, hence the post. Heres a summary of the issues
"Most of it had to be run as root, otherwise it wouldnt install"
"As there were permissions issues all through the manual install guide especially when you start to get to the virtual env."
"I had issues such as no pretix module, no permissions, I had to also do pip3 install cryptography==2.3.1"
