### ISSUE TITLE
403 Forbidden error for presale-CSS file in docker installation

### ISSUE THREAD

**Issue by Chessmasterrr** [pretix/pretix#1587]
Thanks for your awesome work!

I'm trying to get pretix running in docker, following the setup instructions at https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html. I use a freshly set up, empty mysql container as database. Afterwards I can call the pretix admin interface and create a sample shop. But as soon as I open the shop page, I only see the HTML code, because the request of the CSS file `presale.a37ec5cea5997d87.css` is answered by the server with an 403 (Forbidden) error code.

I have tried everything I could think of in terms of debugging possibilities and have rebuilt the whole setup in several versions on different environments over and over again without success. Since I have the same problem on my local machine there is no proxy which can block something. I also tried to customize the color of the shop to generate custom CSS files without success.

Steps to reproduce:
* Create folders for /data and config-file with appropriate permissions
* Create docker network: `sudo docker network create pretix_network`
* Start database: `sudo docker run --name pretix_mysql --network pretix_network -v /docker/pretix/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=<PASSWORD> -e MYSQL_DATABASE=pretix -d mysql:latest`
* If necessary, adjust database authentication by executing `alter user 'root'@'%' identified with mysql_native_password by '<PASSWORD>';` in the container in mysql.
* Start pretix: `sudo docker run --name pretix_main --network pretix_network -p 127.0.0.1:5505:80 -v /docker/pretix/main/data:/data -v /docker/pretix/main/etc:/etc/pretix --sysctl net.core.somaxconn=4096 -d pretix/standalone:3.6`
* Set up a shop with sample data.
* Open the shop and get page without CSS.

Used pretix.cfg file:
```
[pretix]
instance_name=Testinstanz
url=http://localhost:5505
currency=EUR
datadir=/data

[database]
backend=mysql
name=pretix
user=root
password=<PASSWORD>
host=pretix_mysql

[mail]
from=<MAIL>
host=<HOST>
user=<USER>
password=<PASSWD>
port=25
tls=on
```

Output from `sudo docker logs pretix_main`
```
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  [...]
  Applying ticketoutputpdf.0006_auto_20181017_0024... OK
  Applying ticketoutputpdf.0007_auto_20181123_1059... OK
2020-02-19 20:29:32,868 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-02-19 20:29:32,869 WARN No file matches via include "/etc/supervisord-*.conf"
2020-02-19 20:29:32,875 INFO RPC interface 'supervisor' initialized
2020-02-19 20:29:32,875 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-02-19 20:29:32,875 INFO supervisord started with pid 13
2020-02-19 20:29:33,878 INFO spawned: 'pretixweb' with pid 16
2020-02-19 20:29:33,882 INFO spawned: 'pretixtask' with pid 17
2020-02-19 20:29:33,883 INFO spawned: 'nginx' with pid 18
2020-02-19 20:29:34,889 INFO success: pretixweb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-19 20:29:34,889 INFO success: pretixtask entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-19 20:29:34,890 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

Output from `sudo docker exec -it pretix_main pretix upgrade`:
```
Operations to perform:
  Apply all migrations: auth, badges, banktransfer, contenttypes, oauth2_provider, otp_static, otp_totp, paypal, pretixapi, pretixbase, pretixdroid, pretixhelpers, pretixmultidomain, sessions, stripe, ticketoutputpdf
Running migrations:
  No migrations to apply.
INFO 2020-02-19 21:58:10,815 celery.app.trace trace Task pretix.presale.style.regenerate_css[a194dfd8-b424-4093-aa92-06beaa7f08b0] succeeded in 1.1878380769994692s: None
```

What am I doing wrong or how can I debug the problem further? If further information is needed, I will be happy to provide it!

**Comment by Chessmasterrr** [comment]
That was a tricky one, but after hours of debugging and a hint from a friend I located my mistake:

In the container runs nginx, which needs read-access to the presale-CSS file to serve it AND additionally needs to have execute permission in EACH of the parent directories along the path from 
the root to the generated presale-CSS file! So I set the execute permission on the `/data` directory and everything is working.

Maybe you want to add this detail in your documentation (https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#data-files) as precondition? If not, feel free to close this issue.

**Comment by raphaelm** [comment]
I'm not sure this is worth mentioning in the docs because afaik on most linux system +x is set by default for directories, you actively have to remove that. If more people stumble into this issue we sure can mention it.

**Comment by dadada** [comment]
I stumbled into this. I created the directory through systemd-tmpfiles. There is no execute bit unless you tell it to set it. Example that shows what I had:

```
d /var/pretix-data 0750 pretixuser pretixuser - -"

```

and what I needed

```
d /var/pretix-data 0751 pretixuser pretixuser - -"
```

**Comment by raphaelm** [comment]
I'm not familiar with systemd-tmpfiles, but please make sure it's not accidentally cleaned up, that directory is important ;)
