### ISSUE TITLE
Widget: missing SameSite=None cookie

### ISSUE THREAD

**Issue by Patta** [pretix/pretix#1588]
Chrome console warning on a website with embed pretix widget.

`A cookie associated with a cross-site resource at http://pretix.eu/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by raphaelm** [comment]
Hmm, can you send the full Set-Cookie header? This should either already be fixed or intentional.

**Comment by Patta** [comment]
@raphaelm i don't know how to get the set-cookie header in chrome. But we have a cookie named `__stripe_mid` from pretix.eu which has no values for secure or samesite.

**Comment by raphaelm** [comment]
Okay, that's from the Stripe API then and probably not a problem. At least we can't do anything about it!
