### ISSUE TITLE
Best way to add custom translation

### ISSUE THREAD

**Issue by hastern** [pretix/pretix#1589]
What would be the best way to add a custom translation to pretix? 

We're using pretix as a registration system, but don't use the payment part. To better approach our target audience we adjusted some of the phrasing/wording by employing a custom translation, that we patched into the settings.py file. 

Moving forward I'd rather not have to manually apply the patches to the settings.py file after each pretix release. 

As far as I understand the system, only the languages defined by `ALL_LANGUAGES - LANGUAGES_INCUBATING` are available. Since there already is a `"[languages]"` section in the configuration that allows for a custom path, my instinct is to add another option `"custom_language"` and than add this to the `ALL_LANGUAGES` list.

Is this the right approach or am I missing something? I would write the required changes (and pull-request) myself, but I'm not sure if my idea is sound.

**Comment by raphaelm** [comment]
This is not something we officially support or encourage, so we I think we won't merge any PRs adding complexity for this use case. However, you will likely want to modify an already supported langauge such as English or German. In this case the ``path`` option in the config file should be enough, they will have higher precedence than the translations that ship with pretix, so you can use it to override strings.

**Comment by trysten** [comment]
I successfully applied this method thanks to the above guidance from raphaelm. I agree with the official stance on the issue as well. Translation files indicated by the `path` option suffice to modify English text in pretix.
1. Edit the `django.pot` file to your requirements
1. Rename to `django.po` and put in the appropriate location in production environment `/<somewhere>/en/LC_MESSAGES/django.po`
1. Add the <somewhere> directory to your pretix.cfg (a relative path worked for me)
My understanding is that it must be in `en` directory if that is your selected language.
