### ISSUE TITLE
Granting tickets?

### ISSUE THREAD

**Issue by julien51** [pretix/pretix#1595]
I looked at the API documentation but could not find a way to do this. I am myself not a user of Pretix and I do not have access to a "backend" so I am not sure this is already possible, but is there a mechanism to "grant" tickets to users who have used a 3rd party system to acquite their tickets?

We are working with a conference who is considering using both Pretix and a tool that we're building and they (rightfully!) want to limit the check-in complexity by making sure they have a single system that can act as the "source" of truth. On our side, we obviously let them export the full list of ticket purchasers, and we are considering the addition of a webhook system which would let us "ping" your API to grant a new ticket for a user (as long as we provide all required fields + authentication).

**Comment by raphaelm** [comment]
Yes, this is possible: https://docs.pretix.eu/en/latest/api/resources/orders.html#creating-orders

**Comment by julien51** [comment]
Thanks a lot!
