### ISSUE TITLE
Document that 'collectstatic' is required in development for some features to work

### ISSUE THREAD

**Issue by FlaviaBastos** [pretix/pretix#160]
When trying to edit the display event settings, after hit 'save' you get:
```
sass.CompileError: Error: File to import not found or unreadable: main.scss
       Parent style sheet: stdin
        on line 2 of stdin
>> @import "main.scss";
   ^
```
STEPS TO DUPLICATE:

1. Access http://localhost:8000/control/event/mrmcd/2015/settings/display
2. Add text to 'Frontpage text' field
3. Click on 'save'
Error will be displayed

**Comment by raphaelm** [comment]
Uhm, that should not happen. I can only imagine it is a problem of the ``DEBUG`` mode. Can you try running ``python manage.py collectstatic`` to copy the SCSS files from the source folder to the ``STATIC_ROOT`` directory?

**Comment by FlaviaBastos** [comment]
Yes.
Running `python manage.py collectstatic` fixed this issue.
This can be closed now.

**Comment by raphaelm** [comment]
I'm afraid it can't ;) We need to fix developer documentation here

**Comment by raphaelm** [comment]
Alternatively we could make it such that this is *not* necessary in development :)

**Comment by FlaviaBastos** [comment]
Ops, sorry for closing the issue. You are right! :)
I will research how to make it not necessary in development and see what I come up with.

I am also planning to make one or two documentation suggestions because I finally sorted out what was wrong with my setup and failing tests. The doc had no reference to some requirements I didn't know I hadn't met (I will elaborate later).

**Comment by FlaviaBastos** [comment]
I made a couple additions to dev doc but I noticed that `_build/` is listed in `.gitignore`. 
Should I force to add and commit my changes or is it better to edit the page through GitHub directly? I'm fine with either - I just want to make sure someone has the chance to review the changes before they go live :)

**Comment by rixx** [comment]
Ah, no, `_build/` has just the compiled output, you'd add the changes you want to make to the `rst` files in the `doc/` directory. Then, to see the changes applied, you'd run `make html` in the `doc/` directory again, which would rebuild the contents of `_build/`.
