### ISSUE TITLE
Add recommended redis version to documentation

### ISSUE THREAD

**Issue by jkbschk** [pretix/pretix#1608]
Do you recommend a specific redis version when installing pretix? Currently the documentation does not give any information regarding the best version to use.
https://pretix.readthedocs.io/en/latest/admin/installation/docker_smallscale.html#redis

**Comment by raphaelm** [comment]
We have no documented knowledge of any redis version differences that caused problem with pretix. pretix.eu runs with whathever ships with Debian stable.
