### ISSUE TITLE
Add "Empty Cart" button

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#161]
Just a feature proposal, feel free to disregard:

Maybe that's only relevant for testing, and not for actual users, but an "Empty Cart" button would have made my life a bit simpler today. Maybe just a small 'X' in a corner somewhere?

**Comment by raphaelm** [comment]
Good idea! :) Should be easy to implement.

If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!

**Comment by sathe-aditya** [comment]
Hello, I'm a beginner to open-source, and would like to address this issue! Could anyone please guide me?

**Comment by rixx** [comment]
Hi! There are several starting points you could choose. If you are not familiar with Django (the Python web framework used in pretix), you could follow the [official Django tutorial](https://docs.djangoproject.com/en/1.9/intro/tutorial01/) or the [Django Girls tutorial](http://tutorial.djangogirls.org/) to familiarize yourself with Django's overall structure.

If (or: once) you are familiar with Django, you might want to follow the [development setup guide](https://docs.pretix.eu/en/latest/development/setup.html), and play around a bit.

The template `src/pretix/presale/templates/pretixpresale/event/index.html` and the view `src/pretix/presale/views/cart.py` are probably the most relevant to this ticket. You could look at the existing `CartRemove` view, and maybe add a similar view named `CartRemoveAll` ...

Feel free to ask questions if you run into any problems, or if something is unclear to you.

**Comment by sathe-aditya** [comment]
Sure! I am not familiar with Django; I'll start getting familiarized with it right away!
Thanks a lot for your help, I'll definitely ask you if I run into some problem!

**Comment by FlaviaBastos** [comment]
@sathe-aditya hey! Are you planning to work on this or could I take a look?

**Comment by sathe-aditya** [comment]
Hey there! Could you please take a look? Thanks.



On Fri, Oct 28, 2016 at 4:24 AM +0530, "Flavia Bastos" <notifications@github.com<mailto:notifications@github.com>> wrote:


@sathe-aditya<https://github.com/sathe-aditya> hey! Are you planning to work on this or could I take a look?

-

**Comment by raphaelm** [comment]
THis has been fixed in the meantime :)
