### ISSUE TITLE
show products which are not available (yet)

### ISSUE THREAD

**Issue by flootr** [pretix/pretix#1614]
Hey there! I couldn't find anything in the documentation as well as in :octocat: issues so I thought it may be worth to ask: Is there a way to show products which are not available yet?

Right now if we set availability of a product to a certain date it doesn't show up in the list anymore (which makes sense). However, we want our customers to see "hey, there's more – you just have to wait another two weeks for this product to become available".

**Comment by raphaelm** [comment]
No, there currently isn't, and when we last discussed this internally we leaned towards not wanting to implement this either, since it's *even more options* in the product settings for pretty little gain and we have so many options already :(
