### ISSUE TITLE
Automatically ask for bank in case of Canceling event

### ISSUE THREAD

**Issue by chaot2** [pretix/pretix#1616]
Hello,
Thanks for your work and the "corona-Patch"! :)
On our Pretix the customers are paying with classical bank transfer. When we cancel the event, how is it possible to automatically ask fot the bank data to transfer the money back?

Thanks.

**Comment by raphaelm** [comment]
Unfortunately, there are currently no plans to ask users for banking information for refunds. We plan on storing imported payment data in a more structured form so that the system can provide better exports with the IBANs used to pay the tickets, but that will only be good for future events.
