### ISSUE TITLE
Question: show link to webpage after completed purchase?

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1618]
We're building a website where users can order tickets using pretix (hosted on pretix.eu) and we would like to help our customers get back to where they came from after ordering a ticket.

Is this currently possible to add a “Thanks for your purchase. Go back to «some url»” message somewhere in pretix and show this message when a purchase is completed?

Item metadata might be a way to store the text and url (and this makes it updateable using the REST API), but then we need a way to show the values on the order confirmation page.

Any thoughts and suggestions on this?

Best regards,
Mikkel

**Comment by raphaelm** [comment]
Is that URL individual or fixed for all users?

**Comment by rimi-itk** [comment]
The URL is fixed for all users.

**Comment by raphaelm** [comment]
There's currently not a good way but there might be one later today or tomorrow, stay tuned :)

**Comment by rimi-itk** [comment]
Wow, looking forward to that!

We're using the REST API to create/edit pretix events so we hope that the new functionality can be managed through the API. Let me know if I can do anything to help.

**Comment by raphaelm** [comment]
On pretix.eu, you can now enable the new plugin "digital content" in your events. This will allow you to add links/videos/downloads to the order confirmation page of paid tickets :)

REST API: https://docs.pretix.eu/en/latest/plugins/digital.html
