### ISSUE TITLE
Allow admin to change order to different products/variations

### ISSUE THREAD

**Issue by abrock** [pretix/pretix#163]
Imagine someone would organize a IT-security conference where the visitors can order T-Shirts.
Suddenly a wild visitor writes an hypothetical e-mail, asking the organizers to change the (already paid) T-shirt size from "XXL" to "XL".
That should be possible as an admin.

**Comment by rixx** [comment]
Agreed, that would be cool.

This is a bit more tricky than it seems because variations (such as XXL and XL) are allowed to have different prices. Changing a variation to a variation of a different price would introduce a new payment cycle. So we either handle that complexity, or we make sure that only variations of the same price are allowed.

**Comment by abrock** [comment]
The restriction could be reduced to allowing only changes where the total price doesn't increase :-)

Or there could be a warning like "The price is going to change from X to Y, are you sure?"

**Comment by raphaelm** [comment]
They can not only be different in price, one size could already be sold out, or only be available in a given timeframe. Also, if the total changes, invoices need to change and if the payment is already paid via PayPal or Stripe, there needs to be user interaction for a partial re-payment. Then, payment fees might need to be calculated differently, ... The list goes on, this is the classic "ticket upgrade" problem :)

**Comment by abrock** [comment]
> [... Lots of problems...]

That's all true but these are reasons why users shouldn't be able to change these things.
There are also a lot of cases where it would be convenient if the admin could just change something small like the size of the t-shirt.

**Comment by raphaelm** [comment]
> There are also a lot of cases where it would be convenient if the admin could just change something small like the size of the t-shirt.

I totally see your point. This *needs* to be possible, absolutely. But I'm trying to figure out a way to enable admins to do this, while still preventing admins to shoot themselves into their own foot.
