### ISSUE TITLE
Vouchers missing after last update

### ISSUE THREAD

**Issue by r-dannhauer** [pretix/pretix#1636]
We noticed that the vouchers are not being displayed. They are still noted when they have been used in orders, they are still counted in the voucher tags, and are still usable for new orders.
![grafik](https://user-images.githubusercontent.com/7952758/78254635-82980880-74f6-11ea-93d5-19d498495672.png)

![grafik](https://user-images.githubusercontent.com/7952758/78254710-96dc0580-74f6-11ea-819e-74a6f289ed0c.png)

This behaviour is being shown throughout all events of different organisations. Is there something I missed during the update process?

**Comment by raphaelm** [comment]
If I remember correctly, we've seen this with a customer and it wasn't a bug in pretix but in the Python MySQL driver, can you try a ``pip3 install -U mysqlclient``?

**Comment by r-dannhauer** [comment]
Yes, thank you, that fixed the problem. Is there a way to update all pip packets that are required by Pretix?

**Comment by felixrindt** [comment]
You can tell pip to read required packages from a requirements file:

```
(venv) $ pip install --upgrade --requirement src/requirements.txt
```

Check `man pip-install` for documentation of these options and [the installation guide](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html) for more info on how to install pretix.
