### ISSUE TITLE
Mail sending issue

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#164]
When sending mails in a production environment, the pretix `mail()` method returned non-success values while the mail server actually succeeded in sending the mail.

While I understand that a positive return value does not guarantee that a mail has actually been sent (let alone delivered), a negative (well, zero) value should definitely indicate an issue with the mail delivery, imo.

**Comment by raphaelm** [comment]
I came to the conclusion that ``mail()`` shouldn't return anything at all and should raise an exception whenever it is clear that it errored. Returning a boolean to indicate success is neither pythonic nor good style.

**Comment by rixx** [comment]
Would you want to include error handling on all pretix-core calls of `mail()`? There are only about five of them, but we''d need to decide on what to do with them. None of these checked the return value of `mail()` up until now.

**Comment by raphaelm** [comment]
Fixed in #169
