### ISSUE TITLE
Slug of an Event cannot be only single character

### ISSUE THREAD

**Issue by kvbik** [pretix/pretix#1645]
There was a change introduced in deff282a63baef6fa1f770ef0f12bd5ba5c4359a that forces a `slug` of an `Event` to be at least two characters. I'd vote to change `+` to `*` in the regular expression, so the slug can be single letter again. Eg: in our case, we name an Organiser as the event series and slug of the Event is just an incremented number every edition => http://ourawesomeconf.com/awesomeconf/2/

**Comment by raphaelm** [comment]
Fixed it for event slugs (but not organizer slugs, which is on purpose)

**Comment by kvbik** [comment]
Wohoo, very cool! Thank you! What is the release cycle of Pretix? Any chance this will get to PyPI soon?

**Comment by raphaelm** [comment]
In fact, I just rushed this because there will be a release in the next days. ;)

**Comment by kvbik** [comment]
Amazing! Looking forward!
