### ISSUE TITLE
There is no order button at event page

### ISSUE THREAD

**Issue by justinushermawan** [pretix/pretix#1651]
Hi, I've created a test event, but there is no order button showing for user to let them make an order or purchase.

<img width="1245" alt="Screen Shot 2020-04-20 at 19 17 31" src="https://user-images.githubusercontent.com/13159271/79750751-a7d0a780-833b-11ea-9b6a-7c5f6331076b.png">

**Comment by pc-coholic** [comment]
Seems like there is nothing for sale at that particular event date.

Please make sure you also added items and that there is a quota with the items for that event date.

**Comment by justinushermawan** [comment]
@pc-coholic I've added one product and it is in active, but still there is no purchase button.

<img width="1246" alt="Screen Shot 2020-04-20 at 19 37 29" src="https://user-images.githubusercontent.com/13159271/79752469-8cb36700-833e-11ea-822c-e799d6aa5dbc.png">
