### ISSUE TITLE
Gender-"stars" in mails interpreted as italic.

### ISSUE THREAD

**Issue by chaot2** [pretix/pretix#1652]
Hello,
we have people in our Team who wants to use the *-gender-crap in german mails (e.g. "Künstler*innen).
When you write two of such words in one line, everything between the stars is interpreted as italic, like markdown does it.

And is there a Option to create a own E-Mail-theme or e.g. add images to an email?

Thank you very much!

**Comment by raphaelm** [comment]
> gender-crap

Sorry, that's not the tone we like to communicate in.
