### ISSUE TITLE
Gender-"stars" in mails interpreted as italic.

### ISSUE THREAD

**Issue by navlisilvan** [pretix/pretix#1653]
Hello,
we have people in our Team who wants to use the star-gender in german mails (e.g. "Künstler*innen").
When you write two of such words in one line, everything between the stars is interpreted as italic, like markdown does it.

And is there a Option to create a own E-Mail-theme or e.g. add images to an email?

Thank you very much!

**Comment by Corinari** [comment]
Hi navlisilvan, 

i have no idea regarding the gender stars, sorry.

can you specify your option with the own E-Mail theme? Create your own Mail Template? Yes, that is possible

**Comment by wiffbi** [comment]
Regarding the gender stars: you spotted the problem around markdown right. You need to escape the * so markdown (even in emails) does not interpret it. So you need to write „Künstler\*innen“
