### ISSUE TITLE
"Add to calendar" feature

### ISSUE THREAD

**Issue by maartenba** [pretix/pretix#1664]
After ordering a ticket, it would be nice to have an "add to calendar" option which could generate an ICS file that can easily be added into a calendar.

**Comment by raphaelm** [comment]
We already have that on the event front page, and – if enabled – we already send you an ICS in your email. Not sure if we need it on the order page as well. Might be useful, but also the page shouldn't get to crowded.

**Comment by maartenba** [comment]
Could maybe be useful as part of the confirmation e-mail? Was looking for it and it was not super obvious to add a reminder.

**Comment by raphaelm** [comment]
Already there: Settings > E-mail > Attach calendar files

Might become a default in the future :)

**Comment by maartenba** [comment]
Why do I even open issues with Pretix, everything is always there already 💌 
You folks are awesome!
