### ISSUE TITLE
Extend list of sans-serif fonts in CSS

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#167]
Below, you see Chromium on the left, Firefox on the right. Since status indicators are very prominent in pretix, having them look good in both major browsers would be cool.

![2016-08-07-231700_1666x94_scrot](https://cloud.githubusercontent.com/assets/2657547/17465349/2cf5ec02-5cf5-11e6-83e8-724e3dd75800.png)

**Comment by rixx** [comment]
So apparently this happens because I have neither of `"Helvetica Neue", Helvetica, Arial, sans-serif` installed on my system, and Firefox falls back on Nimbus (which looks awful) while Chrome falls back on Liberation.

I'd suggest extending the fonts list provided by another one or two fallback fonts such as Liberation. We could either hardcode this, or offer the font as another variable as `$brand-color`.

**Comment by raphaelm** [comment]
Wow, neither Helvetica nor Arial is surprising ;) Is Nimbus your system font? Could you check how DejaVu Sans looks?

This should be an easy change, there is a LESS variable from bootstrap that we can just override.
If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!

**Comment by raphaelm** [comment]
I created #182 that probably solves this.
