### ISSUE TITLE
Feature Request: Refund vouchers

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretix#1673]
It would be great to have the possibility to refund gift-vouchers. In the current situation with many events cancelled, there are a lot of gift-vouchers created. In some special cases, an organizer might want to have the possibility to refund them (e.g. special circumstances on the customer side) and in German law, after a certain date, customers have to possibility to get a refund for unused gift vouchers that were given for cancelled events.

**Comment by raphaelm** [comment]
We've recently added the option "reverse" a gift-card-based refund. You open up the gift card details, hit "reverse" on the transaction and we'll book the money back to the order. Then, you can do a regular order refund with another method.

Alternatively, you can do a manual deduction of the gift card.

> in German law, after a certain date, customers have to possibility to get a refund for unused gift vouchers that were given for cancelled events.

So far, this is a law proposal. We'll deal with it once it's a law.
