### ISSUE TITLE
Clarify E-mail vs Email spelling

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#1674]
Forwarding a suggestion I got in QA for an event. I think this makes sense - especially the consistency of E-Mail vs E-Mail address.

![Selection_498](https://user-images.githubusercontent.com/111600/81523965-dd235080-934f-11ea-9a91-b3f91605ae10.png)

**Comment by raphaelm** [comment]
Yes, but we should research and fix this on a system-wide basis, if we go for it

**Comment by morrme** [comment]
Has there been a consensus on the accepted style of the term? I am happy to help with the edits.

**Comment by trysten** [comment]
I found [this post](https://grammarist.com/style/e-mail-email/) rather convincing: it doesn't matter. Either is fine, we just need to make sure we are consistent. I would say e-mail is more formal than email, so I guess we could go with the former.
