### ISSUE TITLE
Only working in debug mode, "Bad Request" in production mode

### ISSUE THREAD

**Issue by florko** [pretix/pretix#1676]
I followed the Small-scale manual deployment installation guide on a fresh Debian Buster server.

After switching off compression (see below), everything seems fine as long as I stay in debug mode. I can create organizers, events and everything.

But as soon as I switch debug mode off, I get 

"Bad Request
We were unable to parse your request."

There is no entry in pretix.log

All I get from journalctl is

```
DEBUG 2020-05-13 13:17:09,399 asyncio selector_events Using selector: EpollSelector
[2020-05-13 13:17:11,065: INFO/MainProcess] Connected to redis://127.0.0.1:6379/2
[2020-05-13 13:17:11,079: INFO/MainProcess] mingle: searching for neighbors
[2020-05-13 13:17:12,110: INFO/MainProcess] mingle: all alone
[2020-05-13 13:17:12,139: WARNING/MainProcess] /var/pretix/venv/lib/python3.7/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  leak, never use this setting in production environments!''')
[2020-05-13 13:17:12,139: INFO/MainProcess] celery@<myserver> ready.

```

Could there be a connection to my initial settings change?

When I navigated to the site for the first time after installation, the browser got a Bad Request error caused by a compression key missing from offline manifest.

I found no way to solve that, so I changed the setting

```
COMPRESS_ENABLED = COMPRESS_OFFLINE = not debug_fallback
```
to

```
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = False

```
in settings.py.

**Comment by raphaelm** [comment]
Most likely pretix does not know how to handle requests for the domain you are using. Either your ``url`` setting in ``pretix.cfg`` is wrong or your reverse proxy does not pass the ``Host`` header.

**Comment by florko** [comment]
There was actually a typo in pretix.cfg
Solved
Thank you so much! Stupid me
