### ISSUE TITLE
Update to Ubuntu 20.04, now web interface is displayed with pure HTML (php missing?)

### ISSUE THREAD

**Issue by gldhnchn** [pretix/pretix#1679]
Hi,
I updated my server to Ubuntu 20.04, so the php version updated to 7.4. Now the web interface is displayed with just pure HTML. After the upgrade pretix wasn't working at all, so I did again:
```
pip3 install "pretix[mysql]" gunicorn
python -m pretix migrate
python -m pretix rebuild
```
It is working now again, but only with an ugly interface. While installing I followed the instructions for manual small deployment: https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html

I don't know were to start. Does somebody have an idea what could be the problem here?

Here is a picture, how the interface looks like:
![pretix](https://user-images.githubusercontent.com/24368572/82472350-53e6e900-9ac8-11ea-89cf-d4d550443901.png)

**Comment by raphaelm** [comment]
PHP is unrelated, Django does not use PHP. Probably your Python version updated as well, though, so have a look at your nginx config (see https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html#ssl ) and adjust the python version in there.

**Comment by gldhnchn** [comment]
Yes that was the problem. Stupid from me. Thanks for pointing me into the right direction!
