### ISSUE TITLE
Performance Issue related to event page and payment

### ISSUE THREAD

**Issue by hh-project-config** [pretix/pretix#1680]
## Issue summary
- The time to load the event page to buy tickets  can take as long as 1.5-2 seconds.
-  I use a profiling tool PyLive, and find 40% time on render  and 20% time on the cart. 
-  I wonder if there is space to optimize this two part of time? 
- 
- The time to checkout and finish payment also takes a long time.
-  In the profiling results, I notice that 12% time spent on order._send_paid_mail, is it possible to async this step and show the payment success info first?  What about the step to generating the ticket PDF file?

## Steps to Reproduce
- I follow the developer documentation to set up my pretix sever. 
- I use postgre as database and Gunicorn as web server.

## Technical details
- Python: 3.7.6
- Pretix: latest
- profiling tool: [Pylive](https://github.com/devopspp/pyliveupdate)

**Comment by raphaelm** [comment]
Our recommended production installation does async these steps. Please do not run the developer setup in production.
