### ISSUE TITLE
Free of charge events

### ISSUE THREAD

**Issue by buttle** [pretix/pretix#1682]
Hi,

We use Pretix at a citizens' (grass roots) run Civic Center. We have a small theater/stage. Some events are free, and others have an entrance fee, and that's where Pretix works very well. :)

Since the Covid-19 lockdown, all activity has stopped, but now we are beginning to open up again, slowly, under strict supervision of the City Council.

One of their requirements is that the theater only fills to a third of full capacity, and that seating reservations ensure that no two people are sitting beside each other.

We would like to use Pretix for both paid and free events, but it seems that it is not possible to create "free events", is that so?

Thanks!

**Comment by pc-coholic** [comment]
> We would like to use Pretix for both paid and free events, but it seems that it is not possible to create "free events", is that so?

No, you totally can! When creating a product/item for sale, you can just set the price of the item to 0. It will then even be display as "free" in the shop.

> One of their requirements is that the theater only fills to a third of full capacity, and that seating reservations ensure that no two people are sitting beside each other.

If by "seating reservation" you mean that people only need to reserve a ticket in advance: You are good to go with pretix as is.

If however you want a proper seating plan reservation, where people click on a seating plan where they want to sit, you'll need a seating plan plugin for pretix. On our hosted service on pretix.eu, we do offer such a plugin included - if you want to self-host, you'd need to sign a licensing agreement. If that is ever something you'd want to do, feel free to reach out at support@pretix.eu
