### ISSUE TITLE
Security error while trying to reach the server

### ISSUE THREAD

**Issue by sborja** [pretix/pretix#1683]
I have al self hosted installation of pretix, but i have a problem trying to connect any andorid device throguht PretixSCAN.

When I read QR code with PretixSCAN in Android, my mobile phone says "Security error while trying to reach the server".

In have this issue with Windows App too, with same error... only I can register devices with iOS but it have an error when trying to list attendants inside event: “the data couldn’t be read because is missing”.

Can anyone help me please?

**Comment by raphaelm** [comment]
Duplicate of https://github.com/pretix/pretixscan-android/issues/15
