### ISSUE TITLE
Can't create Check-In Lists

### ISSUE THREAD

**Issue by rp3r** [pretix/pretix#1687]
Hi,

we try the self-hosted edition and it works pretty good.
I'm trying to test the scanning feature but I can't create a Check-In list. The error page is shown when I save the new date.
No quota is set for this date and if there's an error log I can post it, but couldn't find one.

**Comment by raphaelm** [comment]
What exactly is the error message shown?

An error log is probably at ``$DATA_DIR/logs/pretix.log`` in your installation, depending on where you set your pretix data directory.

**Comment by rp3r** [comment]
The error message is "Internal Server Error" responed with code 500.

This is what I've found at the error log:
```
ERROR 2020-05-29 10:04:33,141 django.request log Internal Server Error: /control/event/ORGANIZER/EVENT/checkinlists/add
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1364, "Field 'allow_entry_after_exit' doesn't have a default value")
```

I couldn't find an option to set `allow_entry_after_exit`.

**Comment by raphaelm** [comment]
Did you recently upgrade your installation or is it a new one?

**Comment by rp3r** [comment]
It's a new one, we've installed it yesterday.

**Comment by raphaelm** [comment]
Can you post the output of ``pretix -m showmigrations``?

**Comment by seybsen** [comment]
This was caused by first using the docker image `pretix/standalone:latest` (which ran database migrations) and then switching to `pretix/standalone:stable`.
I don't know the exact versions that those cotainers have had at this time.
Sorry for any inconvenience 🙂
