### ISSUE TITLE
`pip3 install -r requirements/production.txt` failed

### ISSUE THREAD

**Issue by colourful-land** [pretix/pretix#1691]
Reproduce:
````
$ sudo pip3 install -r ../src/requirements/production.txt
…
Successfully built paypalrestsdk pycparser mt-940 vobject cbor2
ERROR: celery 4.4.2 has requirement kombu<4.7,>=4.6.8, but you'll have kombu 4.6.7 which is incompatible.
````
On this particular system, I already have kombu 4.6.7 installed, which matches the requirement 

    kombu==4.6.*

But in fact that requirement is not good enough. Maybe update `../src/requirements/production.txt`?

Thanks.

**Comment by raphaelm** [comment]
We do not support installing pretix with ``sudo``, please us an isolated python environment, as both our dev and production tutorials tell you to.
