### ISSUE TITLE
Feature Request: Customizable personal reference code

### ISSUE THREAD

**Issue by Flauschbaellchen** [pretix/pretix#1705]
I'm searching for a possibility to adjust the reference code which is automatically generated for bank transfers.
Is there a way to customize the way it is generated?

Currently it seems it is in the form of "{event}-{code}".
I'd like to change it to something like "{event}-presale-{code}".

We have a huge number of bank transfers regarding different "subsections" of the event, not only the (pre)sales done by pretix but also insurance, artists, exhibitors etc.
This would allow us to easier split the transfers into these subsections and to submit them e.g. to the collection office.

Is there currently a possibility to adapt this differently?

**Comment by raphaelm** [comment]
This is basically the (unfinished) https://github.com/pretix/pretix/pull/1252 (except maybe a little more complicated)

**Comment by Flauschbaellchen** [comment]
Hi @raphaelm 
Thanks for the super-fast response!

I'm sorry I wasn't able to find the PR.
I'll close this issue in favour of #1252.

Unfortunately, the author seems to be inactive and did not continue working on it.

When looking at the PR, all outstanding items would only be minor changes.
Would this be still correct if used with the current version?

I have little experience with Django myself. Therefore I could try to finish the MR, if it is not possible from your side. - Just need some time to get the development environment up and running..

**Comment by raphaelm** [comment]
No, the PR needs to be updated for the current version. Shouldn't be too bad, though, feel free to continue the work.
