### ISSUE TITLE
403 error when buying ticket - CSRF cookie error

### ISSUE THREAD

**Issue by gvarela1981** [pretix/pretix#1711]
Hi, I'm testing pretix standalone:stable on a docker instance. Everything works fine except for one thing:
When I'm trying to purchase a ticket with an anonymous session I get a 403 error, pretix cant't validate CSRF cookie

I've try this on mi PC and on 2 different laptops adn enable cookies for both Firefox and Chrome.
I was able to complete the purchase after loggin into the system.

Maybe there's something misconfigured ?
Thanks in advance

Some strange thing I was able to find is that pretix_csrftoken cookie seems to be different across request. 
event page
first request -- 
request url: localhost/org1/foss4g2021/

pretix_csrftoken |  
expires | "2021-07-03T23:03:36.000Z"
path | "/"
samesite | "None"
secure | true
value | "TpKryh7zzZocUCaJjjaTSREuLUr17Etl6CWz4Y06Ga96nNoqNnjgePxEk4iReHzk"

second request -- 
request url: localhost/media/pub/org1/foss4g2021/presale.0334ccfc0665d0b0_OhSBMRc.css
csrftoken=ERD2rUAEdjYPSSXj30FkodX8LhHahbFjBtvw2Yq2Bpyh9NHVjZ7UVl8JaLfrsxr7; sessionid=tfgpzxmk2zr7yv8rzxmh5luihc0yi15v

Cart page
After clicking "add to cart" button
request url = localhost/org1/foss4g2021/cart/add?next=/org1/foss4g2021/
csrftoken=ERD2rUAEdjYPSSXj30FkodX8LhHahbFjBtvw2Yq2Bpyh9NHVjZ7UVl8JaLfrsxr7; sessionid=tfgpzxmk2zr7yv8rzxmh5luihc0yi15v

**Comment by raphaelm** [comment]
Can you check whether Referrer headers are send correctly?

**Comment by gvarela1981** [comment]
Hi, sorry for the delay.  I've been messing around with the container, it turns out the errors starts after executing ```make staticfiles```  and ```make compress```

On a fresh install with docker works fine.

Regards !
