### ISSUE TITLE
Create anonymous tickets for COVID-19 tracking

### ISSUE THREAD

**Issue by loelkes** [pretix/pretix#1712]
I'm in a situation where I would need to quickly generate tickets for people who forgot to register one at home and do not own a smartphone or do not feel confident using one (e.g. senior citizens). All other visitors, who did register at home or at the location with their mobile device are not concerned. 

Visitors need a ticket so they can be tracked (using Check-In lists) under the current COVID-19 regulations. The idea is to write a small Python script that places an anonymous order and prints the QRCode on a label printer. Labels are printed twice, one is given to the visitor and one is attached to the paper form they filled out in order to link it to the anonymous visitor.

1. Create an order over the API
2. Retrieve the code and print it

Before I start hacking this I wanted to know if someone sees a better solution (as in: some feature I am unaware of) to this problem. From our perspective this is the easiest solution considering the staff resources (no time budget available to register visitors, must be a one-click solution), the hygiene regulations (setting up self registration terminals creates more problems) and other requirements.

**Comment by raphaelm** [comment]
I think the way you're planning to do it is a good way to go. (The other one would be pretixPOS which contains the featureset you're looking for, but isn't available openly and is probably overkill if no money is involved.)

Keep in mind that *if* money is involved, you might run into legal trouble with KassenSichV.

Closing this ticket as it's not something to be changed in pretix, but feel free to use it for further discussion.
