### ISSUE TITLE
Latest version 3.9.0 > check for version update is still on 3.8.0

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#1716]
An image says more than thousand words
<img width="935" alt="Bildschirmfoto 2020-07-10 um 14 13 31" src="https://user-images.githubusercontent.com/1153741/87153298-8be3fe80-c2b7-11ea-9492-d539f294f2ac.png">

**Comment by raphaelm** [comment]
Thanks will be fixed with the new update today
