### ISSUE TITLE
Stornierungsgebühr bei unbezahlten Bestellungen

### ISSUE THREAD

**Issue by navlisilvan** [pretix/pretix#1723]
Hallo,
sorry für die Nicht-Englische Beschreibung, ich habe leider gerade nicht viel Zeit.

Mir ist gerade ein Problem aufgefallen (3.10.0):

Wenn man in den Optionen der Stornierung von Bezahlten Bestellungen eine "Prozentuale Stornogebühr einbehalten" eingestellt hat, wird diese auch bei der Stornierung von unbezahlten Bestellungen berechnet. (Habe das stornieren bezahlter Bestellungen deaktiviert).
Ich weiß nicht, ob es am Ende auch irgendwie im System ist, aber wenn man eine unbezahlte Bestellung als Kunde stornieren möchte, wird ein negativer Erstattungsbetrag angezeigt und gefragt ob es als Gutschein oder auf die ursprüngliche Zahlungsmethode ausgezahlt werden soll.

Liebe Grüße!

**Comment by raphaelm** [comment]
Das sollte inzwischen sinnvoller sein
