### ISSUE TITLE
Translation problem zh_Hans

### ISSUE THREAD

**Issue by ateuber** [pretix/pretix#1724]
Somehow this text in `src/pretix/presale/templates/pretixpresale/event/order.html` is not translated, when selecting `zh_Hans`. It appears to be translated in `src/pretix/locale/zh_Hans/LC_MESSAGES/django.po`, though?!

![grafik](https://user-images.githubusercontent.com/44349054/88148148-7bf4e480-cbfe-11ea-8012-aba75915442a.png)

**Comment by raphaelm** [comment]
What version of pretix are you using? Did you follow all upgrade steps after the last upgrade?

**Comment by ateuber** [comment]
I'm using version `3.10.x`, but have the same problem when using different versions in my development setup. It seems to be a problem with the `#, fuzzy` line in the po-file - when I remove it and run `make localecompile` again, the translations shows up properly.

**Comment by ateuber** [comment]
I see, it is marked as `Needs editing` [here](https://translate.pretix.eu/translate/pretix/pretix/zh_Hans/?q=This+will+invalidate&checksum=&offset=). TIL that not all translations in po-files are compiled. ;-)
