### ISSUE TITLE
Data protection law consent

### ISSUE THREAD

**Issue by buttle** [pretix/pretix#1728]
Hi,

Is it possible to include a checkbox "I agree" to our data protection text? I haven't seen an option.

It has been brought to our attention that it is a legal requirement.

Thanks in advance.

**Comment by pc-coholic** [comment]
In your general event-settings, Tab "Texts" you can add a "Confirmation text" that will do exactly what you're looking for.

Alternatively you also install/enable pretix-pages, which gives you not only the option to have custom text-pages in your ticketshop, but to also have a requirement for your customers to acknowledge then before being able to order.

**Comment by buttle** [comment]
Thank you very much!
