### ISSUE TITLE
Add context variables to emails (sendmail plugin)

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#173]
When sending emails, you might want to reference some user-dependant data, that could be provided and then used as `{{ variables }}`.
- link to the user's order(s)
- username?
- order date
- due date

For the best UX, one would probably provide an exemplary rendered email for confirmation before actually sending the whole batch.

**Comment by raphaelm** [comment]
Sounds reasonable. :)

If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!

**Comment by FlaviaBastos** [comment]
Hi, @raphaelm 
I would like to work on this but I need a few pointers, please, if you don't mind. 

From the issue's description I understand that @rixx is suggesting that the sendmail plugin has similar capabilities that the Email settings in control, where one can edit the email content by using {event}, {total}, etc (the available placeholders).
If so, I am looking into modifying `pretix/src/pretix/plugins/sendmail/forms.py` to start using a `I18nModelForm,` correct? 

I tried a couple things that didn't get me anywhere so I thought I'd better check first.

**Comment by raphaelm** [comment]
Hi Flavia!

An ``I18nModelForm`` won't get you very far as we aren't dealing with models here. I'll try to describe more precisely what this is about.

If you activate the sendmail plugin (in settings → plugins), you see that it adds a new menu entry in the main menu that allows you to do a very simple thing: Send an email to all or some of the conference attendees. The interface is also rather simple: You select the desired recipients, enter the mail text (possibly in multiple languages) and click "send".

What this ticket is about is the possibility to include placeholders in the text, e.g. the link to the user's order. This is, as you said, very similar to the email settings and I'd prefer to use the same syntax there, e.g. ``{order_url}``. The "parsing" (e.g. replacing of the placeholders with the actual content) is currently done by using Python's [str.format()](https://docs.python.org/3/library/stdtypes.html?highlight=str.format#str.format) API. 

You do not need to change the form code at all and you do not even have to call ``str.format`` yourself, [pretix' ``mail()`` method](https://docs.pretix.eu/en/latest/development/implementation/email.html#pretix.base.services.mail.mail) does this for you.

The absolute minimum to go forward with this ticket would be:

* Think of a set of useful placeholders that could be included there
* Extend the form template to explain and list the possible placeholders to the user
* Replace the context parameter of value ``None`` in the ``mail()`` call in the ``pretix.plugins.sendmail.views`` module with a dictionary that contains the replacements for the placeholders. An example can be seen e.g. in ``pretix.base.services.orders.mark_order_paid``.

The nice-to-have would be to extend the form with a ``Preview`` button that shows an example of how the mail could be rendered with the placeholders replaced. This is slightly harder as you need to:

* Extend the form with a different action and handle the form differently depending on the button pressed (without clearing the form accidentally)
* Call ``str.format()`` yourself (not that hard :wink:)
* Come up with suitable "demo content" to replace the placeholders with

Does that make it more clear? If not, please ask :)

Best
Raphael

**Comment by FlaviaBastos** [comment]
Wow, thank you very much for the detailed explanation! It sounds much less complicated now :grin:
I will chew this info and submit something for feedback. 
I will try to add the preview also - sounds like an interesting part to work on. I will reach out if I get stuck.
Thanks again!
