### ISSUE TITLE
Exclude external payment provider fees from sales value

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#174]
Currently payment fees are added to the sales value. This only makes sense for internal payment fees. If the fees are charged by an external payment provider (eg. Stripe for credit cards) those fees should not be included in sales values, as they never reach the events account.

**Comment by rixx** [comment]
Both in the orders overview (when choosing to see revenue) and the standard dashboard widget.

**Comment by Unicorn-rzl** [comment]
Nevermind. Regarding taxation the behavior is correct as it is.

**Comment by raphaelm** [comment]
Yep, the order overview is correct this way. One *could* argue to subtract them in the dashboard, but I'm nor in favour of differentiating between internal and external fees.
