### ISSUE TITLE
Order page shows only one gift card code

### ISSUE THREAD

**Issue by destruktomatik** [pretix/pretix#1740]
When ordering multiple gift cards in a single order, only a single gift card code is shown on the order page after payment , see images attached. Is this intended?
Frontend:
![image](https://user-images.githubusercontent.com/12897721/89043958-98ed8e00-d349-11ea-89f3-7b75806a2316.png)
Backend:
![image](https://user-images.githubusercontent.com/12897721/89044377-2a5d0000-d34a-11ea-83cb-a5254eb72f2c.png)

**Comment by raphaelm** [comment]
It is not. We need to exclude gift cards from the grouping of positions apparently.
