### ISSUE TITLE
HTML Emails completely empty and PlainText not shown in mail client

### ISSUE THREAD

**Issue by uplexPaul** [pretix/pretix#1742]
I do have a severe problem with email generation. The HTML-Part of Email generation is completely empty and the Plaintext is not shown because the html part seems to be preferred by the mail-clients.

Just looks like this in the plain mail:

--===============5270515281003567649==
Content-Type: multipart/related;
 boundary="===============0604934123943063068=="
MIME-Version: 1.0

--===============0604934123943063068==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

--===============0604934123943063068==--

--===============5270515281003567649==--

I already tried running the app in debug mode and much other stuff.
Could somebody point me to what the problem could be and where i can start digging into?

**Comment by raphaelm** [comment]
I have not seen this before.

Can you show us the full email incl (maybe redacted) headers?

**Comment by uplexPaul** [comment]
Sure, here is the complete email:

Return-Path: <tickets@soko-kickloch.de>
Received: from mail.int.uplex.de
	by mail.int.uplex.de with LMTP
	id oPJxFCH5J1+y1gAA0J78UA
	(envelope-from <tickets@soko-kickloch.de>); Mon, 03 Aug 2020 11:46:41 +0000
Received: from mail.thebrake.org (techno-tischtennis.de [212.12.63.121])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(Client did not present a certificate)
	by mail.int.uplex.de (Postfix) with ESMTPS id 5174F1E43B
	for <paul@uplex.de>; Mon,  3 Aug 2020 11:46:41 +0000 (UTC)
	(envelope-from tickets@soko-kickloch.de)
Received: from localhost (localhost [127.0.0.1])
	by mail.thebrake.org (Postfix) with ESMTPSA id CBE58479D5
	for <paul@uplex.de>; Mon,  3 Aug 2020 11:46:10 +0000 (UTC)
	(envelope-from tickets@soko-kickloch.de)
Content-Type: multipart/alternative;
 boundary="===============3301320907522424840=="
MIME-Version: 1.0
Subject: [TESTMODE] Ihre Bestellung: K0GRF
From: SOKO Kickloch - Hula Whoop <tickets@soko-kickloch.de>
To: paul@uplex.de
Date: Mon, 03 Aug 2020 11:46:10 -0000
Message-ID: <159645517079.48587.9834107669139195401@localhost>
X-Auto-Response-Suppress: OOF, NRN, AutoReply, RN
Auto-Submitted: auto-generated
Reply-To: kontakt@soko-kickloch.de

--===============3301320907522424840==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit

Hallo,

wir haben deine Bestellung fÃ¼r HULA-WHOOP mit einem Gesamtbetrag von
30,00Â â¬ erhalten. Bitte schlieÃe die Bezahlung bis 17.08.2020 ab.
Sende das Geld an: paypal@soko-kickloch.de

Du kannst die Bestellung unter folgender Adresse einsehen und Ã¤ndern:
https://tickets.soko-kickloch.de/openair/hula-whoop/order/K0GRF/tbiwao9pw4fhosle/open/61242b9ea/

Viele GrÃ¼Ãe,
SOKO-Kickloch Musik und Kulturverein e.V.

-- 
Sie erhalten diese E-Mail, weil Sie eine Bestellung fÃ¼r die Veranstaltung HULA-WHOOP getÃ¤tigt haben.
Sie kÃ¶nnen Ihre Bestellung unter folgender Adresse einsehen:
https://tickets.soko-kickloch.de/openair/hula-whoop/order/K0GRF/tbiwao9pw4fhosle/open/61242b9ea/.

--===============3301320907522424840==
Content-Type: multipart/related;
 boundary="===============3820096621310712315=="
MIME-Version: 1.0

--===============3820096621310712315==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit


--===============3820096621310712315==--

--===============3301320907522424840==--

**Comment by uplexPaul** [comment]
I checked the code in site-packages/pretix/base/services/mail.py.
If i manually set body_html to a test html snippet before the call to mail_send_task.si(, i can see that html in the mail.
So it somehow seems that renderer.render( is returning an empty html...

Already tried to strace the process to see if it maybe doesn't find a template or something else but it doesn't look like...

**Comment by uplexPaul** [comment]
If i just set the body_html = None the resulting email does look fine and only contains plain text.
So that call is definitely returning an empty string:
body_html = renderer.render(content_plain, signature, raw_subject, order, position)

**Comment by raphaelm** [comment]
And I assume you use one of our standard renderers?

**Comment by uplexPaul** [comment]
Yes exactly i tried both of the standard renders and none of them works

**Comment by uplexPaul** [comment]
Okay i start to get digging into this a bit deeper.
Debugging in pretix/base/email.py showed that markdown_compile_email returns correct html (printing this out with a logger). But after the call to inline_css(tpl.render(htmlctx)) the body_html is empty.

**Comment by raphaelm** [comment]
Which version of pretix are you running exactly? What operating system do you run on? How did you install pretix?

I assume this is related some of the conversion steps in our HTML email pipeline which uses things like ``inlinestyler`` to convert CSS to inline statements, and ``BeautifulSoup`` to convert images.

**Comment by raphaelm** [comment]
> Debugging in pretix/base/email.py showed that markdown_compile_email returns correct html (printing this out with a logger). But after the call to inline_css(tpl.render(htmlctx)) the body_html is empty.

Can you check if it is ``tpl.render`` or ``inline_css``? For both of them I don't really see how they would fail silently, though.

**Comment by uplexPaul** [comment]
It is definitely inline_css - i tried tpl.render and that does give correct output.
I am running the latest version (installed yesterday via pip3 install "pretix[mysql]"".

Ah and i just see that i get some csp errors every time, that inline_css gets called.
I think there is the error. But i don't know how to solve it. Do i need to disable csp? How can i achieve this?

From my csp log:

Blocked: inline
Violated: script-src
Original polity: default-src 'self' https://tickets.soko-kickloch.de; script-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; object-src 'none'; frame-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; child-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; style-src 'self' https://tickets.soko-kickloch.de 'self'; connect-src 'self' https://tickets.soko-kickloch.de 'self' https://checkout.stripe.com; img-src 'self' https://tickets.soko-kickloch.de 'self' data: https://*.stripe.com; font-src 'self' https://tickets.soko-kickloch.de; media-src 'self' https://tickets.soko-kickloch.de data:; form-action 'self' https://tickets.soko-kickloch.de https:; report-uri https://tickets.soko-kickloch.de/csp_report/
WARNING 2020-08-03 13:21:32,100 pretix.security.csp csp CSP violation at https://tickets.soko-kickloch.de/
Referer:
Blocked: inline
Violated: script-src
Original polity: default-src 'self' https://tickets.soko-kickloch.de; script-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; object-src 'none'; frame-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; child-src 'self' https://tickets.soko-kickloch.de https://checkout.stripe.com https://js.stripe.com; style-src 'self' https://tickets.soko-kickloch.de 'self'; connect-src 'self' https://tickets.soko-kickloch.de 'self' https://checkout.stripe.com; img-src 'self' https://tickets.soko-kickloch.de 'self' data: https://*.stripe.com; font-src 'self' https://tickets.soko-kickloch.de; media-src 'self' https://tickets.soko-kickloch.de data:; form-action 'self' https://tickets.soko-kickloch.de https:; report-uri https://tickets.soko-kickloch.de/csp_report/

**Comment by raphaelm** [comment]
CSP does not run in the email stack, only in the browser, this is not the error.

Can you show the output of ``pip freeze``? Again, which OS are you on exactly?

**Comment by uplexPaul** [comment]
pip freeze:
`amqp==2.6.0
arabic-reshaper==2.0.15
asgiref==3.2.10
attrs==19.3.0
Babel==2.8.0
beautifulsoup4==4.8.2
billiard==3.6.3.0
bleach==3.1.5
cbor2==5.1.2
celery==4.4.6
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cryptography==3.0
csscompressor==0.9.5
cssutils==1.0.2
defusedcsv==1.1.0
dj-static==0.0.6
Django==3.0.8
django-appconf==1.0.4
django-bootstrap3==12.0.3
django-compat==1.0.15
django-compressor==2.4
django-countries==6.1.2
django-filter==2.2.0
django-formset-js-improved==0.5.0.2
django-formtools==2.2
django-hierarkey==1.0.4
django-hijack==2.1.10
django-i18nfield==1.8.0
django-jquery-js==3.1.1
django-jsonfallback==2.1.2
django-libsass==0.8
django-localflavor==3.0.1
django-markup==1.5
django-mysql==3.8.1
django-oauth-toolkit==1.2.0
django-otp==0.7.5
django-phonenumber-field==4.0.0
django-redis==4.11.0
django-scopes==1.2.0
django-statici18n==1.9.0
djangorestframework==3.11.0
et-xmlfile==1.0.1
future==0.18.2
gunicorn==20.0.4
idna==2.8
importlib-metadata==1.7.0
inlinestyler==0.2.5
isoweek==1.3.3
jdcal==1.4.1
jsonschema==3.2.0
kombu==4.6.11
libsass==0.19.2
lxml==4.5.2
Markdown==2.2.0
mt-940==3.2
mysqlclient==2.0.1
oauthlib==3.1.0
openpyxl==3.0.4
packaging==20.4
paypalrestsdk==1.13.1
phonenumberslite==8.11.5
Pillow==7.2.0
ply==3.11
pretix==3.10.0
psycopg2-binary==2.8.5
pycountry==20.7.3
pycparser==2.13
pyOpenSSL==19.1.0
pyparsing==2.4.7
PyPDF2==1.26.0
pyrsistent==0.16.0
python-bidi==0.4.2
python-dateutil==2.8.1
python-stdnum==1.13
python-u2flib-server==4.0.1
pytz==2020.1
pyuca==1.2
PyYAML==5.3.1
rcssmin==1.0.6
redis==3.4.1
reportlab==3.5.46
requests==2.22.0
rjsmin==1.1.0
sentry-sdk==0.14.4
six==1.15.0
slimit==0.8.1
soupsieve==2.0.1
sqlparse==0.3.1
static3==0.7.0
stripe==2.42.0
text-unidecode==1.3
tlds==2020073000
urllib3==1.25.10
vat-moss-forked==2020.3.20.0.11.0
vine==1.3.0
vobject==0.9.6.1
webauthn==0.4.7
webencodings==0.5.1
zipp==3.1.0`

**Comment by uplexPaul** [comment]
I'm on solaris (SmartOS):
SunOS www 5.11 joyent_20180412T025853Z i86pc i386 i86pc Solaris

**Comment by raphaelm** [comment]
inlinestyler, lxml and cssutils are the very same versions as in our production setup, so this isn't it.

I strongly assume it's an issue with lxml on Solaris. We only officially support pretix on Linux, so sorry, you're on your own here. If you have a solution, feel free to post it though for future Solaris users :)
