### ISSUE TITLE
Support for stripe SEPA 

### ISSUE THREAD

**Issue by ghoeffner** [pretix/pretix#1749]
Hi team,

first of all, thanks for the great product and continous development! We have recently started using stripe SEPA on another system and think it is a great way to automate SEPA payments. The burden to get activated is quiet low as well, so I was wondering if it would be possible to add it to pretix (as Germans still prefer the SEPA-way over credit card?). I have found issue #407 which is marked as closed, but it seems like SEPA was never actually added. 

Thanks for your consideration!

**Comment by pc-coholic** [comment]
Good catch!

We wanted to add Stripe SEPA for some time - but until recently it would have required us to go back to using sources for charging. But from what I can see, we can now use the new Payment Intents - so integrating this should be quite straight forward... :)

**Comment by ghoeffner** [comment]
That's great news @pc-coholic, I will be around to try it out ;)

**Comment by raphaelm** [comment]
Just to be clear here, do we talk about SEPA debits (which Stripe supported for a while) or SEPA transfers (which is in private beta at stripe)?

I'm really excited about SEPA transfers, but so far they aren't really available.

For SEPA debits, I think the reason we never implemented them, is that Stripe considers it to be a "delayed notification" payment method which is highly unexpected to both event organizers and ticket buyers. As I understand [the docs](https://stripe.com/docs/payments/sepa-debit), Stripe will only mark the payment as complete once the money actually has been moved. So if I buy a ticket for an event today and choose to pay by SEPA debit, I'd usually expect to get my ticket immediately, but in reality Stripe might take 1-2 business days or more to confirm the payment. This may lead to extremely high frustration. (Note that Stripe has a similar problem with the SOFORT method which caused us a lot of trouble in the past.)

Also, the dispute process of SEPA debits is quite bad for the organizer, but that's a risk many would take, probably.

**Comment by ghoeffner** [comment]
Hi Raphael,

my request is about SEPA debits (which is "invite only", but every account I manage got it enabled by now...). I agree that it might not be suitable for every type of event, however, in our case it would be highly desireable to be able to offer SEPA payments until 5 days before the event starts. Usually the SEPA payments do indeed take a couple of days to confirm. I hope that it can still be implemented as there are still many people which prefer SEPA over other payment methods and the fees are quiet low as well.

Let me know what you think.

**Comment by teawithfruit** [comment]
For us SEPA direct debit would be very helpfull, too. Our clients hosts events for a special group of clients who are used to pay allmost by SEPA direct debit. Support for that payment method would be very very great.
