### ISSUE TITLE
Question: Do we need to inform users about cookies?

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1752]
I'm not trying to open old wounds, but we're currently discussing whether or not we need some sort of cookie banner in our pretix solutions (both self-hosted and cloud-based).

https://github.com/pretix/pretix/issues/95 states that we don't need to inform users about cookies in pretix. If we still use only the cookies mentioned in that issue we're home safe according to https://www.iubenda.com/en/help/5525-cookies-gdpr-requirements#exemptions (we have a “[Privacy](https://pretix.eu/about/en/privacy)” link on all shop pages; cf. https://pretix.eu/ulf-test/8/privacy/, say).

Can anybody (more versed in both pretix and the cookie law than me) confirm that we still use only the cookies mentioned in https://github.com/pretix/pretix/issues/95 and that having the Privacy link on all shop pages makes pretix comply with the current EU cookie law?

Best regards,
Mikkel

**Comment by raphaelm** [comment]
We're no lawyers and EU cookie law is confusing and contradictory.

We believe that the cookies set by pretix (as long as you do not use something like the pretix-tracking or pretix-campaigns plugin) are only used for purposes that can be considered essential for technical purposes (carts, logins, security, language). pretix (by default) does not use cookies for any kind of tracking or profiling purposes, so you should be fine.

That said, we *do* plan to add more advanced cookie consent management to pretix at some point, we just haven't got around to it yet and we don't think it's really necessary.

**Comment by rimi-itk** [comment]
Thanks for your reply. I agree with your points.
