### ISSUE TITLE
Bug on SMTP configuration interface if no changes on the form

### ISSUE THREAD

**Issue by Delawen** [pretix/pretix#1768]
As discovered below on https://github.com/pretix/pretix/issues/1768#issuecomment-692000022

**There is a bug when trying the SMTP configuration if the form is not changed.**

### Previous message 

**No longer relevant but keeping for history purposes (in case someone else has the same problem):**

I'm using a dockerized Pretix (as in https://github.com/gvarela1981/pretix-docker-compose) that just takes a generic stable Pretix docker image and adds a couple of extra plugins and a custom payment plugin (soon to be ready for a public release). 

Whenever I try to send an email with a custom SMTP, that has been tested with Pretalx and works, it just silently fails (the save and test smtp page returns a 502 bad gateway on nginx). I don't even get if this is a timeout, a login problem or what.

Email configuration on `pretix.cfg` is as shown:
```
[mail]
from=CorrectEmail
host=CorrectHost
user=CorrectUser
password=CorrectPassword
port=465
tls=off
ssl=on
```

I also tried to override the configuration on the user interface with the same data, but with no luck. And data should be right, Pretalx has no problem sending emails with the same parameters.

Is there  any way to debug this properly to check why it is failing? 
Setting the pretix.cfg debug variable to True doesn't seem to change anything on the logs side.

**Comment by raphaelm** [comment]
502 is weird, if it's a pretix error it should be 502 and a timeout should be 504. can you check what the ``DATA_DIR/logs/pretix.log`` says? Also, can you check your nginx error logs?

**Comment by Delawen** [comment]
That's the thing, both nginx log and `data/logs/pretix.log` don't show anything. I would gladly debug further but I don't know how.

**Comment by Delawen** [comment]
So I get there is some error, but I don't see on which point does the connection to SMTP fails.

**Comment by Delawen** [comment]
Could it be an uncaught exception on Pretix side that makes the thread die? Can you point me where this code is so I can add a wide catch of exceptions to see if I can catch something interesting?

Weird stuff I'm thinking: the username has an "@" and two dots on the domain side (someusername@geolibres.org.ar). Could that be it?

I can give you access to the server (privately) so you can live test if you want. It is still a small server for testing, so no problem if you break it completely.

**Comment by raphaelm** [comment]
Any uncought exception should be in the log.

The code for the "test" option of the formis here:
https://github.com/pretix/pretix/blob/master/src/pretix/control/views/event.py#L600

I think doing research of your server goes beyond the level of support we can offer for free ;)

**Comment by Delawen** [comment]
> I think doing research of your server goes beyond the level of support we can offer for free ;)

I had to ask :) Thank you.

**Comment by Delawen** [comment]
I changed the code a bit to add the backend initialization inside the try and commented the second part of the test:

```            if request.POST.get('test', '0').strip() == '1':
                try:
                    backend = self.request.event.get_mail_backend(force_custom=True)
#                    backend.test(self.request.event.settings.mail_from)
                except Exception as e:
                    messages.warning(self.request, _('An error occurred while contacting the SMTP server: %s') % str(e))
                else:
```

Now I get an error:

![imagen](https://user-images.githubusercontent.com/726590/93081900-43b6d300-f690-11ea-9540-b8af9f0f94db.png)

What's k? I see a loop inside the previous event.log.action that uses it, but no initialization:

```        if form.is_valid():
            form.save()
            if form.has_changed():
                self.request.event.log_action(
                    'pretix.event.settings', user=self.request.user, data={
                        k: form.cleaned_data.get(k) for k in form.changed_data
                    }
                )

            if request.POST.get('test', '0').strip() == '1':
                try:
```

**Comment by Delawen** [comment]
Forget about that, it fails if there's no change on the form (bug?)

**Comment by raphaelm** [comment]
Closing since we've rewritten the entire form since this issue
