### ISSUE TITLE
Question: Will it be feasible to trigger order exports via the api?

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#1780]
We're using the pretix api extensively to manage events, and we're currently exposing order lists to user without access to pretix using data from the api. This works great and now we're looking into also exposing answers to order questions for these users.

We can get all the data, i.e. questions and answers, from the api, but we then have to render the data in a way that makes it usable for the users. This gives rise to the following question:

Will it be feasible to make it possible to trigger (and download the result of) an order export, e.g. “Check-in list (PDF)”, through the pretix api?

We appreciate that the exports have a lot of individual options and that we have to pass all these options along when triggering an export, but before getting into the details on this, we'd like to know if it is at all feasible to extend the api to be able to do something like this.

Best regards,
Mikkel

**Comment by raphaelm** [comment]
I think it would be feasible!

May main concern would indeed be the individual options of the exporters and the fact that there's no stability guarantee for that. But other than that, I don't see a big blocker here.

**Comment by rimi-itk** [comment]
Great news!

I share your concern, but having to maintain api calls with the correct options for each exporter will still be easier – and much better – than having to duplicate generation of the actual export results (pdf, csv, …) and adapting to new exporters will be quite manageable as well.
