### ISSUE TITLE
Can't connect to paypal to ticket shop

### ISSUE THREAD

**Issue by KBUnulleins** [pretix/pretix#1782]
I am useing the self hosted version and tryed to connect PayPal to the pretix system. I used this Button to activate PayPal:
"Pretix Backend -> Event -> Settings -> Payments -> PayPal"

![firefox_em7vWSVfVA](https://user-images.githubusercontent.com/71531559/94018952-7d36bf00-fdb1-11ea-957a-f3a829c582ed.jpg)

After the clicked the button, i get redirected to the paypal connect page (`https://www.paypal.com/connect/?response_type=code&scope=openid%20profile%20email&client_id=[censored]&redirect_uri=[censored]`) and get this error message:
(invalid scope)
![firefox_88XG8fg3B5](https://user-images.githubusercontent.com/71531559/94019139-b4a56b80-fdb1-11ea-8b23-1d0fc4c1d572.jpg)

## Issue:
The problem seems to be the the "profile" parameter in the scope. If i remove the "profile" tag from the scope, i can authenticate the app on PayPal page. 
**But** if i then get redirected back to the ticket-shop i get the error message from Pretix that the authentification failed.

Is there maybe a manual way to connect paypal to pretix?

**Debug information:**
The stored PayPal connect information under "Pertix Backend -> Admin mode -> Global settings -> PayPal" are correct, as I have previously received another error message from the PayPal page. Also i contacted PayPal-Support-team and they meant that this is a issue from the CMS and not from PayPal.

**Comment by raphaelm** [comment]
If you use the self-hosted version, there's usually no reason to use the OAuth connection, which (iirc) requires special approval from PayPal.

You can just keep the global settings empty and set your keys on a per-event basis

https://docs.pretix.eu/en/latest/user/payments/paypal.html

**Comment by KBUnulleins** [comment]
Thanks for your quick reply - saved my day!
