### ISSUE TITLE
Dashboard shows tile off-by one in Firefox

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#179]
See attached images, issue does not occur with Chrome. FF version is 48.0, haven't verified it on a different PC.

In attributes inherited from body, the inspector shows this:

```
{
    font-family: "Helvetica Neue", Helvetica, "Liberation", Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857;
    color: #333333;
}
```

Note the `line-height`. Setting it to `1.4` fixes the issue. 

`1.417` seems to be the largest working value, as an aside, which is incidentally the exact value set in `pretix/src/static/bootstrap/scss/bootstrap/_scaffolding.scss`. It _looks_ like a floating-point error, but nothing is ever simple:

Up until then, a quick fix would involve overriding either line-height or font-size in the `dashboard` class.

[This](http://stackoverflow.com/questions/25344493/discrepancy-in-line-height-computation-how-does-bootstrap-do-it) SO question indicates it's a font rendering issue - seeing as this is the second font issue (#167), maybe pretix should choose a font for recognition similar to its charming color. (A font that is rendered about the same in every browser.)

<img src="https://cloud.githubusercontent.com/assets/2657547/17642028/7b4cc326-6137-11e6-9c29-bc8021894843.png">
<img src="https://cloud.githubusercontent.com/assets/2657547/17642029/7b714e26-6137-11e6-808b-def2ec912405.png" height=300px>

**Comment by raphaelm** [comment]
If we go for a custom font, I'll vote for Open Sans that the pretix.eu landing page already uses.

**Comment by raphaelm** [comment]
It's not font-related and it also happens in Chrome :/

**Comment by raphaelm** [comment]
It happens whenever the boxes are of different height. In your example, it is this fragile and line-height dependent because the "your shop is live" box is just *slightly* higher than the other ones. If the differences get larger, the problem gets worse.

Without giving them a fixed height (hard to determine as they come from plugins) this is not really fixable without losing some responsiveness in pure CSS and would probably require a JS solution like https://dfcreative.github.io/projects/waterfall/

**Comment by rixx** [comment]
Soo, would an easy fix include setting a sensible minimum height for tiles, so that offsets aren't as easy to reach, as long as plugins add reasonable tiles?

**Comment by raphaelm** [comment]
Yes. We already have a min-height of 160px, increasing that by a few pixels should help in *this* case. However it will still break even without plugins in many cases, e.g. the same view is used on /control/ showing all events you have access to. As soon as an event name takes more than one line, your heights begin to vary a lot. If the height is to big, we have huge white gaps which doesn't look nice as well.

To illustrate that, here's a screenshot of the pretix.eu interface from my account that has access to all events:

![download](https://cloud.githubusercontent.com/assets/64280/20731716/c746f892-b68b-11e6-991b-56ab74baf1a0.png)

This would look better only at min-height: 250px which would waste a lot of space in the general cas.e

**Comment by rixx** [comment]
Okay, I'm just going to ask a silly question and then slink away and leave this alone, but: Wouldn't flexbox kinda sorta solve this?

Try [this](http://codepen.io/anon/pen/ENbWeL) for size (and see the comments and try it with stretch in the child divs, too).

**Comment by raphaelm** [comment]
Not silly, great thought!

**Comment by raphaelm** [comment]
> "then slink away and leave this alone"

> " rixx self-assigned this 2 hours ago"

:heart:

**Comment by rixx** [comment]
Well that was thinking my idea would be silly and already proven not to work :stuck_out_tongue:
