### ISSUE TITLE
Allow to change the date format

### ISSUE THREAD

**Issue by Frammo** [pretix/pretix#1792]
Currently dates are shown as YEAR-MONTH-DAY is there a way an option to event setting could be added to allow other variations. Such as standard UK format DAY-MONTH-YEAR?

**Comment by raphaelm** [comment]
This would require to decouple the concepts of "language" and "locale/region" in the system, which is a large undertaking, but also something that we wished to have for a long time :)

**Comment by raphaelm** [comment]
We now have a "region" setting
