### ISSUE TITLE
Hidden payment Links not working after event slug change

### ISSUE THREAD

**Issue by Frammo** [pretix/pretix#1793]
Just trying to allow Manual Payments and use the Hidden Link but get the below error in the browser Pretix installed on Debian 10 running as a container on Proxmox:

I'm afraid we could not find the the resource you requested.

The selected event was not found.

Take a step back

And lots of entries in syslog

gunicorn[93]: WARNING 2020-09-28 18:23:24,626 django.request log Not Found:

**Comment by raphaelm** [comment]
Can you post the full link (without domain and secret)?

> The selected event was not found.

looks like a non-existing event slug in the URL

**Comment by Frammo** [comment]
Yes it has an old event slug in the URL is there a way to correct as it would appear to have not updated when I changed the slug. 

I recreated a new event and it had the correct slug and worked.

**Comment by Frammo** [comment]
On further testing when cloning an event or copying into a new event the slug does not update the hidden link.
