### ISSUE TITLE
Is SV correct translation folder for Sweden?

### ISSUE THREAD

**Issue by tobiassundgren-collector** [pretix/pretix#1795]
Hi,
I see that the translations for Swedish is stored in the "locale/sv/LC_MESSAGES"-folder.
According to http://www.i18nguy.com/unicode/language-identifiers.html it should be "SE", or am I wrong?
When enabling SV in my dev environment, I get the sv.png flag (which is El Salvador)

**Comment by pc-coholic** [comment]
ISO 639-1 defines `sv` as the language Code for Swedish and `se` as `Northern Sami` - even according to the link you provided. The `SE` on your list designates the country/region code.

Our issue here is, that we equivalate the language and the country/region code, which works fine for most tuples - just not here...

I'll manually switch the flag for sweden to 'se' - but I think we'll keep the language-code of 'sv'
