### ISSUE TITLE
Plugins (Manual Payment) expandable for instances running on hosted environment 

### ISSUE THREAD

**Issue by BeQui57** [pretix/pretix#1797]
I am pretty new to pretix community and started to evaluate the current Pretix version based on company requirements. We are planing the transition of an existing self-written booking system towards Pretix. The main challenge is to handle vouchers created and managed in an online shop system. We would like to keep the well accepted voucher function in the shop system and looking for a way to give customers the option to choose a pretix payment where voucher code can be entered as required data.
The payment plugin "Manual payment" might be a suitable module but it needs to be extended in order to include a "must fill"  field for voucher code during order processing. We know that Pretix do have extensive voucher functions but we need to keep the shop system as the reference for vouchers because of intergration with ERP. 
> Are there any other Pretix functions which would/could fullfill the requirement?
> Would it be possible to run a modified plugin (i.e. Manual Payment + Extension) within the hosted environment?

I am not quite sure whether such kind of questions are acceptable for this community. Please let me know.

**Comment by raphaelm** [comment]
I don't think there's currently a plugin that can do exactly what you need.

If you're looking to use pretix Hosted, feel free to reach out to our team at support@pretix.eu and talk this through in detail. Running modified plugins on Hosted is generally not possible, but there are exceptions toe very rule :)
