### ISSUE TITLE
Creation of new giftcards via REST API not possible

### ISSUE THREAD

**Issue by BeQui57** [pretix/pretix#1798]
Trying to create giftcards using REST API with no success. GET method worked fine hence the credentials (Token based) are correct. GET and POST requests have been executed by Postman and a small Python script. Here the code snippet from Postman:
**POST /api/v1/organizers/ruf/giftcards HTTP/1.1
Host: pretix
Authorization: Token 1ofmnayp501wgyokqr2opbggeuozidrhtlv3lfrizrrgw89oexgcyvcruxei6mhp
Accept: application/json
Content-Type: application/json
{
    "secret": "HUGO12345678",
    "value": "8.15",
    "currency": "EUR"
}**
Regarding pretix documentation, POST method should be supported for giftcards and the above request is similar to the example. No error messages in pretix- and apache log. Secret of giftcard has been configured with 12 char.
http response is ok (Return code 200) but response data is the query result of stored giftcard entities in the DB rather successful creation message.
> Are there any specific configurations or credentials needed in order to execute POST requests?
> Any hints what went wrong?

**Comment by raphaelm** [comment]
You're missing a / at the end of the URL, and are therefore being redirected to the correct URL, after which your http client likely sends a GET request instead of a second POST
