### ISSUE TITLE
"Add to cart" is shown when there are no products listed

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#180]
![2016-08-13-121250_1289x371_scrot](https://cloud.githubusercontent.com/assets/2657547/17642681/4655263c-614f-11e6-8584-c7277a52ac11.png)

**Comment by raphaelm** [comment]
If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!

**Comment by vishalsodani** [comment]
I would like to have a go at this. I have figured out that we have to check - 

1. if there are no items active or 
2. if no vouchers exist for any of the items 

then the 'Add to cart' button can be hidden.  Am I correct?

**Comment by rixx** [comment]
Hi! :)

I think your first point is sufficient - voucher redemption works separately from the normal way items are added to a cart.

**Comment by vishalsodani** [comment]
Hi,

I actually meant to say "if no available quantity in quotas exist for any of the items" for second point.

I  ran the unit tests but some of them are failing. Are they supposed to? I am using sqllite3 for tests.

**Comment by rixx** [comment]
That sounds basically correct, but it might be a bit more simple: Pretix is already doing all of these checks in the view (if an item is active, if the item or its variations are still available according to their quotas). It then supplies the template with a variable containing all items that are active and available, `items_by_category`, which is then rendered by the template.

As long as this variable is filled, we need the "Add to cart" button, but if it is empty, the button is not necessary. Does that sound about right to you?

**Comment by vishalsodani** [comment]
Yes. I will push my change.

**Comment by vishalsodani** [comment]
Hi,

I have pushed my change. I see 2 tests are failing as they expect 'Add to cart' row.

**Comment by rixx** [comment]
I think @raphaelm is away atm, so it could take until next week until he has a look at your pull request.

As for the tests, I think the best thing would be for you to adjust the tests so that they don't expect the 'Add to cart' button on empty item lists - instead they could assert that the button is **not** there :)
