### ISSUE TITLE
Move Payment to global Settings

### ISSUE THREAD

**Issue by Erlix322** [pretix/pretix#1803]
Behavior right now:
Payment has to be configured in the individual Event Settings which comes with several problems.

1. it's not possible to clone events for users who do not have the permission to change event settings with payment configured.

2. Granularity of event settings permission ist not good. You can either change everything or nothing.

Example use case:
Admin A wants user B to be able to create events with paypal settings activated. user B needs full permission and can see the paypal api secret.

Expected behavior:
Admin A sets up paypal once on organisations level and user B can activate paypal in the settings without seeing critical information.

I'd like to establish pretix as our main event system but as of today. Fine granular user management and central payment administration is a blocker.

**Comment by raphaelm** [comment]
While your concerns are valid, moving the settings. will not happen, as it would be a very very breaking change. We have lots of users actually requiring different paypal settings.

Having the settings on both levels would technically work, but is an incredibly hard cahllenge to do in a way that does not complicate the user interface. (see also eg #1026)

Also, it would involve a complete redesign of pretix' plugin system which currently works a lot on the event level.

Sorry to be so harsh but: Not gonna happen in the next year probably, if ever.

**Comment by Erlix322** [comment]
Thanks for the clarification!
Maybe the workflow is not clear to me right now!

Our organization has only one paypal account as well as on central bank account.

We have one person who is responsible for creating events who should not be able to see the paypal credentials. How could this be achieved? 

Because as of now our admin can create a template with paypal settings. But user with lower access rights (event settings) cannot clone the event.

**Comment by raphaelm** [comment]
The fix for this btw is that we stop echoing back credentials to users which I think we did for most payment methods by now

**Comment by nexus671** [comment]
This would be a great feature as i prevents other from changing it. 

But also as of right now Paypal still shows the secret key after saving it while stripe does not.
