### ISSUE TITLE
Voucher list shows only Product

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#181]
In the voucher list, only the chosen product is shown even if a variation is specified. This is kind of misleading.

**Comment by raphaelm** [comment]
Yes, that should be fixed. This will require a small template change in the voucher list as well as an extended ``select_related`` in the voucher list view to save database calls.

If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!

**Comment by koebi** [comment]
This seems like it got fixed in #213, this issue can be closed
