### ISSUE TITLE
Multiple pdf tickets on one page

### ISSUE THREAD

**Issue by mohe2015** [pretix/pretix#1811]
For environmental reasons I think it would be great to have an option to print multiple tickets onto one page.
The most basic implementation would be to add a pageHeight to allow multiple tickets on one page if the pageHeight is a multiple of the templateHeight. This would mean that only vertical stacking is possible which I think would be fine.

**Comment by raphaelm** [comment]
Hmm, just adding a page height might be the least complex solution that has been proposed for this so far, I like it :)

It would be nice to be able to do something stylish with the "empty space" when only one ticket is bought, but this adds so much complexity that we discarded the idea so far.
