### ISSUE TITLE
Reserve dialogue hanging. Big isssue for multiple customers

### ISSUE THREAD

**Issue by ben-hearn-sb** [pretix/pretix#1815]
Hello,

We have a big issue after updating to 3.11.0 and then subsequently 3.12.0.dev0.

We updated from 3.8.0 in which we had no issues whatsoever, we needed to update so we could use pretixScan. After this update we have multiple events in which the reserve tickets dialogue hangs indefinately.

Is this a known issue / are other versions more stable?

![image](https://user-images.githubusercontent.com/13691166/96508226-8d2faa80-125a-11eb-92a9-eecdbfb346a7.png)

**Comment by raphaelm** [comment]
This is not a known issue, we process thousands of tickets each day and haven't seen this once.

Please do not open up duplicate issues (see #1802).
