### ISSUE TITLE
Using Pretix as Product-Shop, NOT as a Ticket-Shop

### ISSUE THREAD

**Issue by bastieb** [pretix/pretix#1822]
Hello, I want to use Pretix as a  Shop to sell a Product. Is there an way to remove the word "Ticket"? 
i.e. on a shops startpage in the lower section "If you already ordered a ticket" 
more better: just to remove for one "Organizer"

I am just asking, because it is written, when I am creating an event to make a shop for an "event or an shop, which is not an event", but I am also thankful for an advice to change it not just in the GUI. Because I am hosting it by my own and have access to the Server.

**Comment by raphaelm** [comment]
Sorry, no, pretix is a ticket shop, we consider this out of scope.

Yes, we do to some extend support shops that are no ticket shops, for example, shops for gift cards for tickets ;) Some people use it even for shipping goods, but we will not make the software more complicated for that.

**Comment by bastieb** [comment]
Thanks for your answer, so fast!
But there is just one word what is bothering me, everything else is perfect.
It's "Ticket" in some default sentence. If I could edit these sentences? You could use these option for other cases as well. 
And I want not to forget to say thank you for these amazing software ❤️

**Comment by raphaelm** [comment]
You can, of course: https://github.com/pretix/pretix/search?l=HTML&q=If+you+already+ordered+a+ticket

**Comment by bastieb** [comment]
Thanks for your answer,
I tried to change not the index.html, I changed the german translation under /var/pretix/venv/lib/python3.8/site-packages/pretix/locale/de/LC_MESSAGES/django.po but it didnt show the change. I tried already to migrate, rebuild, and restart the pretix service like you would do for an update or plugin installation. But it didnt worked out. I just get a random Error for another Language File: 
> The po files under /var/pretix/venv/lib/python3.8/site-packages/pretix/locale/pt_BR/LC_MESSAGES are in a seemingly not writable location. mo files will not be updated/created.
CommandError: compilemessages generated one or more errors.

Do you have any hint for me?
