### ISSUE TITLE
permission denied error for installing plugins 

### ISSUE THREAD

**Issue by bastieb** [pretix/pretix#1842]
Hello,
when I want to install  any plugin, i got the permission denied Error: 

> ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/var/pretix/venv/lib/python3.8/site-packages/pretix_fontpackfree'
Consider using the `--user` option or check the permissions.
 
What can I check to find the reason?

**Comment by raphaelm** [comment]
Apparently, the linux user you are logged in as has no permission to write to ``/var/pretix/venv/lib/python3.8/site-packages/pretix_fontpackfree``. I assume you installed pretix as root and are now installing the plugin as non-root
