### ISSUE TITLE
Migrate Pretix to new server

### ISSUE THREAD

**Issue by kc9ryt** [pretix/pretix#1847]
Hello Everyone,

I was wondering if someone could tell me what I need to move to migrate pretix from one host to a new one...i try dumping the MySQL database and importing it on the new server but it is still missing many organizers and events.... is there somewhere else that this data is store now?

Thanks!

**Comment by raphaelm** [comment]
Nope, migrating the database and the /data directory is all you need.

Is it missing MANY organizers… or ALL? Maybe you dumped the wrong database?
