### ISSUE TITLE
Unify usages of canceLed vs canceLLed

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#187]
currently is mixed througout the sourcecode and texts... LL leads in usage, L is probalby what we want.

**Comment by FlaviaBastos** [comment]
Hi, @raphaelm 
Both 'cancelled' and 'canceled' [are correct](http://www.dictionary.com/browse/cancelled). It's a matter of preference (American x British), I think. 
I can work on this, if that's ok.
I'm assuming you will want all to be 'canceLed', correct?

**Comment by raphaelm** [comment]
Hi @FlaviaBastos!

I prefer the L version, because American English is more common in the project and in programming in general, however, LL is already more widespread in the project. (153x LL and 26x L). But I guess, we should still go for L, as consistency wins.

Replacing the strings is straightforward, replacing variable names requires some caution. Especially renaming things like ``Order.STATUS_CANCELLED`` is changing a public API that plugins could depend on. However, there are not yet any relevant plugins out there so if there is a time to change this, it is now.

So, yeah, if you want to, go ahead :)

**Comment by FlaviaBastos** [comment]
Got it! Thanks!
I will start working on this and reach out if needed.
