### ISSUE TITLE
Save a Template with selected fields to Export a Check-In list

### ISSUE THREAD

**Issue by vflg** [pretix/pretix#1882]
I have a use case where I would need to export data from the orders to share them with others / or e.g. perform actions and calculations in an excel sheet.
Is there any way to save a "template" with selected fields for the export?
So if I need to have the same exported list again I simply choose this Export Template and I always receive the same columns in the exported file?

**Comment by raphaelm** [comment]
Unfortunately not :( We might add a custom "export builder" at some point, but that's going to be a big project for the not-so-close future.
