### ISSUE TITLE
Reauthentication session timing not updated

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#1884]
Our setup is based on the pretix/standalone Docker image with redis. We're using an external login plugin for authentication with OAuth 2.0.

When a view uses`RecentAuthenticationRequiredMixin`, the authentication process works correctly, however I end up back at the /control/reauth/ page. I've been able to track this issue down to the `pretix_auth_login_time` in the session not being updated. I've run and inspected the [code](https://github.com/pretix/pretix/blob/master/src/pretix/control/views/user.py#L119) responsible for the reauthentication and that seems to set the variables correctly.

Now usually I'd be able to debug this in a local environment, however frustratingly when running django locally the issue doesn't seem to persist. I'm unsure whether this bug is caused by our environment or due to some django session/cache settings as I'm not familiar with the inner workings of django sessions/caching.

Is there anything that might help me locate this issue? I'd be happy to create a test-case and PR if I'm able to locate it, however currently I'm quitte stuck.

**Comment by raphaelm** [comment]
Are you running the latest version? This sounds *a lot* like a bug I fixed in 836da09cd33a767ead8ed4c57b4a285018333b2 in september.

**Comment by MaicoTimmerman** [comment]
Nice catch, locally I was running master... Thanks a lot!
