### ISSUE TITLE
Default configuration of pretix & celery generates emails to local user using sendmail

### ISSUE THREAD

**Issue by noc0lour** [pretix/pretix#1886]
I've recently installed pretix release 3.13 on a Debian 10 host. 

I've noticed that celery generates log emails to the localuser@host e.g. pretix@myhost and queues them to the local MTA. 
pretix.cfg is default with nothing special in celery or mail settings, in fact pretix is configured to send emails through a different MTA. 

Celery is executed like this `/var/pretix/venv/bin/python  /var/pretix/venv/bin/celery -A pretix.celery_app worker -l info`

Mail body:
```
 INFO 2020-12-19 20:15:04,780 celery.app.trace trace Task pretix.base.services.quotas.refresh_quota_caches[2abbb6d1-362e-41ab-a668-430d10cf6eb4] succeeded in 0.0029638800006068777s: None
```

I couldn't find a hint of default logging via email for celery, but I might have missed that. Would be great to have it go into the regular system logging, either in the code ore by defining something in the configuration file.

**Comment by raphaelm** [comment]
Never seen this before. Can you post as much of pretix.cfg as you're willing to share and the subject/body of one of those emails, so I have some idea where to look for it?

**Comment by raphaelm** [comment]
ah sorry, you've posted a body. that's the full body?

how do you start celery, through systemd?

**Comment by noc0lour** [comment]
Yes, the email body is what I pulled from the local exim, since it gets stuck there. But funny enough it shouldn't go there in the first place. 
I'm a bit baffled, I haven't seen a lot of code logging to mail by default. As far as I can tell this has not been an issue on a older version of pretix, but with a different setup. 

This is my pretix.cfg 
```
# Ansible managed
[pretix]
instance_name=My instance
url=https://pretix.$domain
currency=EUR
datadir=/var/pretix/data

[database]
backend=postgresql
name=pretix
user=pretix
password=
host=

[mail]
from=pretix@$domain
host=mail-01.$domain
port=25
tls=On

[redis]
location=redis://127.0.0.1/0
session=true

[celery]
backend=redis://127.0.0.1/1
broker=redis://127.0.0.1/2
```
And this is the systemd unit startnig the celery worker
```
[Unit]
Description=Pretix background worker
After=network.target

[Service]
User=pretix
Group=pretix
Environment="VIRTUAL_ENV=/var/pretix/venv"
Environment="PATH=/var/pretix/venv/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=/var/pretix/venv/bin/celery -A pretix.celery_app worker -l info
WorkingDirectory=/var/pretix
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

And this is the django app systemd unit
```
[Unit]
Description=Pretix web service
After=network.target

[Service]
User=pretix
Group=pretix
Environment="VIRTUAL_ENV=/var/pretix/venv"
Environment="PATH=/venv/bin:/usr/local/bin:/usr/bin:/bin"
ExecStartPre=/var/pretix/venv/bin/python -m pretix compilemessages
ExecStartPre=/var/pretix/venv/bin/python -m pretix compilejsi18n
ExecStartPre=/var/pretix/venv/bin/python -m pretix collectstatic --noinput
ExecStartPre=/var/pretix/venv/bin/python -m pretix compress
ExecStartPre=/var/pretix/venv/bin/python -m pretix migrate --noinput

ExecStart=/var/pretix/venv/bin/gunicorn pretix.wsgi \
                      --name pretix --workers 5 \
                      --max-requests 1200  --max-requests-jitter 50 \
                      --log-level=info --bind=127.0.0.1:8345
WorkingDirectory=/var/pretix
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by noc0lour** [comment]
Ah, ok. Now I checked the headers and saw it was actually a cronjob. Sorry for the noise.
