### ISSUE TITLE
MT940 import not always detecting IBAN/BIC/Payer

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#1897]
When using .swi-Files from Dutch Rabobank, the IBAN, BIC and Payer is not detected by the importer, thus rendering automated refunds impossible.

My understanding of MT940 is limited, but I would assume that the problem is that RABO-Bank puts the IBAN into the second account-statement line of tag 61 (`Supplementary Details`). Not sure, if that is where it's supposed to be or just Rabobank doing things...

```
:61:200824C000000000150,00N541NONREF//26643593505
DE12345678901234567890
:86:/TRCD/541/ORDP//NAME/Franz Nord/REMI/2020-F0OBAR/ISDT/202
0-08-24
:61:200824C000000000050,00N541NONREF//26643593504
DE12345678901234567890
:86:/TRCD/541/ORDP//NAME/Eris Discordia/REMI/2020-T0ASTER/ISDT/2020-
08-24
```

**Comment by raphaelm** [comment]
MT940 predates SEPA by a lot, so there's lots of different ways banks embed IBAN information into those files. I've seen at least two this week. The other banks at least have the courtesy of putting ``IBAN`` in front or using non-standardized sub-fields IDs, which is at least pareseable. This one isn't, really. I don't think we should start "searching" for IBANs in unstructured fields. Does Rabo Bank implement a CSV export with better quality? In that case, I'd immediately consider this a wontfix.

**Comment by pc-coholic** [comment]
The csv does indeed have the required information, so we can close this as wontfix.
