### ISSUE TITLE
E-mail is not send to waiting list automatically

### ISSUE THREAD

**Issue by vflg** [pretix/pretix#1899]
I tested the waiting list functionality today. I noticed that (even after a few hours I didn‘t receive a voucher on my test mail address. I enabled the setting, that the voucher should be send automatically.
It only sends the mail when I manually force the system to send either as much as possible, or just a single one.

**Comment by raphaelm** [comment]
Is the cronjob on your installation running correctly?
Is the event shop live? Is the event date in the future?

**Comment by vflg** [comment]
> Is the event shop live? Is the event date in the future?

The event shop isn't live - wasn't aware that this prevents sending the e-Mails.
Since we're new to Pretix we wanted to test everything first :)

**Comment by raphaelm** [comment]
Yeah, there were too many cases of "oops, my waiting list triggered even though I disabled the shop!", so we stopped the waiting list from processing disabled shops.
