### ISSUE TITLE
Support redis sentinel

### ISSUE THREAD

**Issue by neumantm** [pretix/pretix#1905]
Redis Sentinel provides high availability for Redis \[[redis docs](https://redis.io/topics/sentinel)\].
django-sentinel does not yet support redis sentinel \[[open issue](https://github.com/jazzband/django-redis/issues/426)\]
Therefore, afaik pretix does not support redis sentinel.

It would be great if this support could be added.
Maybe https://pypi.org/project/django-sentinel/ helps with that.

**Comment by neumantm** [comment]
Sadly https://pypi.org/project/django-sentinel/ requires an old version of django-redis.
As far as i can tell https://pypi.org/project/django-sentinel-sifter/ fixes this.

**Comment by neumantm** [comment]
Working on a PR. Will submit once ready.

**Comment by raphaelm** [comment]
Hmm.

On one hand, I'm personally not really keen on introducing another small, unclear-whether-maintained dependency to support a setup that very few pretix users use and is therefore likely to break :\ In principle, I'd rather wait on django-redis to support this, although it's not clear to me whether that will happen. 

On the other hand, the implementation of django-sentinel-sifter is a mere 125-line wrapper around redis-py, so it's hopefully unlikely to break often.

At pretix.eu, we do use redis sentinel for our production setup, but we use a haproxy installation in front of it that just redirects the TCP connections to the current master, which adds complexity in the server administration but keeps the complexity out of pretix/django. It's unclear to me whether doing this in python instead would have a significant upside or downside.

**Comment by neumantm** [comment]
Yes, I understand that. I would prefer a solution directly in django-sentinel as well.
Thanks for pointing out the solution with haproxy, I didn't think of doing something like that.
But I think the benefit of doing it in python is reducing the complexity of deploying pretix in self hosted scenarios,
especially in cloud infrastructure, where Redis Sentinel is a common thing.
