### ISSUE TITLE
ReplyTo in mail setup

### ISSUE THREAD

**Issue by pat95st** [pretix/pretix#1916]
I think it would be useful to have the possibility to set a Reply-to mail address for outgoing mails from Pretix. This would be beneficial e. g. if you send the mails from another mail address then the mail address of the person/team who is responsible for the event.

There are some workarounds for that, e. g. forwarding the mails sent to the Pretix mail address, but this may cause some issues if the mail server which Pretix uses is another than the mail server for the main addresses and this server does not support SRS properly.

**Comment by raphaelm** [comment]
pretix does set a ``Reply-To`` header to the value of the "contact email address" from the event settings if that is different than the ``From`` address from the email settings.

**Comment by pat95st** [comment]
Ok, I have tested this again and it did not work with my Pretix instance. I have Pretix running on a subdomain (it also uses a subdomain mail account for sending mails out) - the mail server of the main domain is a shared server, so it is not allowed to send mass mailing from there. Is it a problem if the domain of the mail address used for authentication does not fit the event mail address?

**Comment by raphaelm** [comment]
That shouldn't be a problem
