### ISSUE TITLE
Importing bank transfers after last payment date (global setting) should show better visible error

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#192]
Currently it is not possible to change the payment state of an order after the global set "last payment date" is over. If you try to change an order manually, it will show a correct error (like "too late to accept payment").
How ever: When importing bank transfers, there is only a small yellowish notice on the top instead of a error. Furthermore the message is not really helpful (in comparison to the error shown while manually changing payment status of an order).

Idea: Make a visible warning "Payments are no longer possible, as last payment date (change _here_) has passed" on every page of the import bank data plugin and every unpaid order detail page.

**Comment by yash2696** [comment]
hey I want to work on it.

**Comment by raphaelm** [comment]
Hi @yash2696, very sorry, I somehow did not see this! Are you still looking into it? Just say if you need any help!
