### ISSUE TITLE
502 Error Always all services running 

### ISSUE THREAD

**Issue by nexgenbh** [pretix/pretix#1920]
I'm getting 502 error. All services are running. Postgresql also 11
But always getting error

server {
	listen 443 ssl; 
	# root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name domain.com www.domain.com pretix.domain.com;
	ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
        add_header Referrer-Policy same-origin;
        add_header X-Content-Type-Options nosniff;

    location / {
        proxy_pass https://pretix.domain.com:8345/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
    }

    location /media/ {
        alias /var/pretix/data/media/;
        expires 7d;
        access_log off;
    }

    location ^~ /media/cachedfiles {
        deny all;
        return 404;
    }
    location ^~ /media/invoices {
        deny all;
        return 404;
    }

    location /static/ {
        alias /var/pretix/venv/lib/python3.6/site-packages/pretix/static.dist/;
        access_log off;
        expires 365d;
        add_header Cache-Control "public";
    }
    
    
}

server {
    if ($host = pretix.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

	listen 80 default_server;
	server_name domain.com www.domain.com pretix.domain.com;
    return 404; # managed by Certbot
}

**Comment by raphaelm** [comment]
Please have a look in the ``error.log`` file of nginx for info on why it's a 502.

**Comment by nexgenbh** [comment]
314 connect() failed (111: Connection refused) while connecting to upstream, client: *.*.*.*, server: pretix.domain.com, request: "GET /control/ HTTP/1.1", upstream: "http://127.0.0.1:8345/

**Comment by nexgenbh** [comment]
always there are these errors. 

2021/02/06 05:23:13 [error] 2700#2700: *493 connect() failed (111: Connection refused) while connecting to upstream, request: "GET /robots.txt HTTP/1.1", upstream: "http://127.0.0.1:8345/robots.txt", 
2021/02/06 05:23:15 [error] 2700#2700: *495 recv() failed (104: Connection reset by peer) while reading response header from upstream, request: "GET /robots.txt HTTP/1.1", upstream: "http://127.0.0.1:8345/robots.txt",

2021/02/06 05:23:16 [error] 2700#2700: *497 connect() failed (111: Connection refused) while connecting to upstream, request: "GET /app-ads.txt HTTP/1.1", upstream: "http://127.0.0.1:8345/app-ads.txt",

2021/02/06 05:23:52 [error] 3092#3092: *512 connect() failed (111: Connection refused) while connecting to upstream, request: "GET /control/ HTTP/1.1", upstream: "http://127.0.0.1:8345/control/",

2021/02/06 05:23:53 [error] 3092#3092: *512 connect() failed (111: Connection refused) while connecting to upstream, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8345/favicon.ico", 

I don't know whats wrong with this. All services are running fine. Can you please help me for this.

Thanks

**Comment by raphaelm** [comment]
i think you proxy_pass line is wrong. shouldn't that go to localhost and http not https?

**Comment by nexgenbh** [comment]
I tried everything

proxy_pass http://localhost:8345/;
Also this
proxy_pass http://127.0.0.1:8345/;

Also i put server IP. But nothing working

**Comment by nexgenbh** [comment]
2021/02/06 05:23:53 [error] 3092#3092: *512 connect() failed (111: Connection refused) while connecting to upstream, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8345/favicon.ico",

This result is changing that to 
proxy_pass http://127.0.0.1:8345/;

**Comment by raphaelm** [comment]
Can you show the output of ``netstat -nplt`` on the server where the nginx is running?

**Comment by nexgenbh** [comment]
server:~# netstat -nplt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2261/redis-server 1
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      8750/nginx: worker
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      817/sshd
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      20641/postgres
tcp        0      0 127.0.0.1:8345          0.0.0.0:*               LISTEN      29520/python3
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      25883/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      8750/nginx: worker
tcp6       0      0 :::22                   :::*                    LISTEN      817/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      25883/master

I see sometime ( pretix-worker ) showing me active and sometime activating

**Comment by raphaelm** [comment]
Looks good. What does ``http://localhost:8345`` output?

**Comment by nexgenbh** [comment]
When i run this command

service pretix-web status

I gets below result
---------------------
gunicorn[32460]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
gunicorn[32460]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
gunicorn[32460]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
gunicorn[32460]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
gunicorn[32460]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
gunicorn[32460]:   File "<frozen importlib._bootstrap>", line 228,  in _call_with_frames_removed
gunicorn[32460]:   File "/var/pretix/venv/lib/python3.9/site-packages/pretix/settings.py", line 47, in <module>
gunicorn[32460]:     with open(SECRET_FILE, 'r') as f:
gunicorn[32460]: PermissionError: [Errno 13] Permission denied:  '/var/pretix/data/.secret'
gunicorn[32460]: [2021-02-06 10:36:36 +0000] [32461] [INFO] Worker exiting (pid: 32461)

**Comment by nexgenbh** [comment]
curl -v http://localhost:8345
* Expire in 0 ms for 6 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 0 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 2 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
* Expire in 1 ms for 1 (transfer 0x55baed61df90)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55baed61df90)
* connect to 127.0.0.1 port 8345 failed: Connection refused
* Failed to connect to localhost port 8345: Connection refused
* Closing connection 0
**curl: (7) Failed to connect to localhost port 8345: Connection refused**

**Comment by nexgenbh** [comment]
**sudo lsof -i -n -P | grep LISTEN**
sshd        817     root    3u  IPv4   13976      0t0  TCP *:22 (LISTEN)
sshd        817     root    4u  IPv6   13985      0t0  TCP *:22 (LISTEN)
gunicorn   1578   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
gunicorn   1579   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
gunicorn   1580   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
gunicorn   1581   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
gunicorn   1582   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
gunicorn   1583   pretix    5u  IPv4 6230867      0t0  TCP 127.0.0.1:8345 (LISTEN)
postgres  20641 postgres    3u  IPv4 2334451      0t0  TCP 127.0.0.1:5432 (LISTEN)
nginx     22169     root    6u  IPv4 2361293      0t0  TCP *:443 (LISTEN)
nginx     22169     root    7u  IPv4 2361294      0t0  TCP *:80 (LISTEN)
master    25883     root   13u  IPv4 2113969      0t0  TCP 127.0.0.1:25 (LISTEN)
master    25883     root   14u  IPv6 2113970      0t0  TCP [::1]:25 (LISTEN)
nginx     32047 www-data    6u  IPv4 2361293      0t0  TCP *:443 (LISTEN)
nginx     32047 www-data    7u  IPv4 2361294      0t0  TCP *:80 (LISTEN)
redis-ser 32303    redis    4u  IPv4 6189025      0t0  TCP 127.0.0.1:6379 (LISTEN)

**Comment by nexgenbh** [comment]
when i tried this command **curl -v http://127.0.0.1:8345/** below is output
* Expire in 0 ms for 6 (transfer 0x560e0b885f90)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x560e0b885f90)
* Connected to 127.0.0.1 (127.0.0.1) port 8345 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8345
> User-Agent: curl/7.64.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by raphaelm** [comment]
>  gunicorn[32460]: PermissionError: [Errno 13] Permission denied: '/var/pretix/data/.secret'

That's it. The user you are running pretix pretix with apparently has no permission to write into the data folder ``/var/pretix/data``.

**Comment by nexgenbh** [comment]
I changed permission of user but now I'm getting time out error.

504 Gateway Time-out

------
I'm really thankful to you for your help
