### ISSUE TITLE
Couldn't load serialization.

### ISSUE THREAD

**Issue by HansF** [pretix/pretix#1930]
Migrate didn't work on latest version 
in /pretix/base/secrets.py
cannot import name 'Encoding' from 'cryptography.hazmat.primitives.serialization.base'

needed to change 
`from cryptography.hazmat.primitives.serialization.base import (
`
to
`from cryptography.hazmat.primitives.serialization import (
`
And now it builds without issues.

This is fixed on master branch, but not on release 3.15

**Comment by raphaelm** [comment]
For the time being, a ``pip install "cryptography==3.3.*"`` should fix it. We'll release the next stable version soon that also fixes compatibility with 3.4.x
