### ISSUE TITLE
Rebuild: Invalid Template/Error Parsing Template

### ISSUE THREAD

**Issue by misters84** [pretix/pretix#1976]
After fixing of Serialization Error from [https://github.com/pretix/pretix/issues/1930#issuecomment-781242156](url) i got an Template error by using python -m pretix rebuild.

`Invalid template /var/pretix/venv/lib/python3.7/site-packages/django_otp/templates/otp/admin19/login.html: 'admin_static' is not a registered tag library. Must be one of:
bootstrap3
cache
captureas
commadecimal
compat
compress
countries
dotdecimal
escapejson
eventsignal
eventurl
expiresformat
formset_tags
getitem
hierarkey_form
hijack_tags
i18n
ibanformat
l10n
mail_settings_preview
markup_tags
money
order_overview
phone_format
rest_framework
rich_text
safelink
static
statici18n
thumb
tz
unidecode
urlreplace
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/django_otp/templates/otp/admin30/login.html: admin/base_site.html
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/refund_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/django_otp/plugins/otp_totp/templates/otp_totp/admin/config.html: admin/base_site.html
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/job_detail.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/sepa_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
Error parsing template /var/pretix/venv/lib/python3.7/site-packages/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_form.html: Invalid template name in 'extends' tag: ''. Got this from the 'basetpl' variable.
WARNING on line 29, column 11 of /var/pretix/venv/lib/python3.7/site-packages/pretix/static.dist/pretixpresale/scss/_forms.scss:
Compound selectors may no longer be extended.
Consider `@extend .form-control, :focus` instead.
See http://bit.ly/ExtendCompound for details.`

**Comment by raphaelm** [comment]
This is safe to ignore
