### ISSUE TITLE
Presale: Empty list if no permissions

### ISSUE THREAD

**Issue by gabriele-h** [pretix/pretix#1977]
I am not entirely sure this is the right place to post this issue, so please correct me if this needs to be filed elsewhere!

As a logged in user with no permissions in any "Vorverkaufsstelle", the page loads with an empty table and above just the string "Oh, du bist ein Profi!" (Just to mention this detail: In German there is a line below containing both "du" and "Sie").

If the user has no permission in any of the "Vorverkaufsstellen", there should be a message instead of the empty table. Just seeing the "Oh, du bist ein Profi!" string is not very informative.

**Comment by raphaelm** [comment]
The reseller plugin is not on github, so feel free to just redirect these issues to support@pretix.eu. We'll take care of this one!
