### ISSUE TITLE
CommandError: An error occurred during rendering /var/pretix/venv/lib/python3.6/site-packages/pretix/plugins/webcheckin/templates/pretixplugins/webcheckin/index.html: /usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by kc9ryt** [pretix/pretix#2017]
**Describe the bug**
CommandError: An error occurred during rendering /var/pretix/venv/lib/python3.6/site-packages/pretix/plugins/webcheckin/templates/pretixplugins/webcheckin/index.html: /usr/bin/env: ‘node’: No such file or directory

**Expected behavior**

**Screenshots**

**Additional context**
Internal Server Error: /control/

OfflineGenerationError at /control/
You have offline compression enabled but key "8db6c6a918bbf763123433597ec01ef1dd55eed8dc91f99c76868ac8f3d1e7bc" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:

           <script type="text/javascript" src="/static/jquery/js/jquery-2.1.1.min.e40ec2161fe7.js"></script>
           <script type="text/javascript" src="/static/js/jquery.formset.5f6b62d88653.js"></script>
           <script type="text/javascript" src="/static/typeahead/typeahead.bundle.28654235b116.js"></script>
           <script type="text/javascript" src="/static/bootstrap/js/bootstrap.894d79839fac.js"></script>
           <script type="text/javascript" src="/static/moment/moment-with-locales.42d5c7ca492b.js"></script>
           <script type="text/javascript" src="/static/datetimepicker/bootstrap-datetimepicker.8d7293336e00.js"></script>
           <script type="text/javascript" src="/static/select2/select2.2f9a54c25009.js"></script>
           <script type="text/javascript" src="/static/select2/i18n/de.887bfc43e9d1.js"></script>
           <script type="text/javascript" src="/static/select2/i18n/en.a283e3dd0ae0.js"></script>
           <script type="text/javascript" src="/static/charts/raphael-min.06557bf5ef58.js"></script>
           <script type="text/javascript" src="/static/charts/morris.d995698f8d57.js"></script>
           <script type="text/javascript" src="/static/clipboard/clipboard.238dfb9a5014.js"></script>
           <script type="text/javascript" src="/static/rrule/rrule.e2d0f3efd7ed.js"></script>
           <script type="text/javascript" src="/static/pretixpresale/js/ui/questions.5cfc73204443.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/jquery.qrcode.min.05f0b1d7d4b9.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/clipboard.b4d8b9a54770.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/menu.3799201d46c7.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/sb-admin-2.18aa75419be1.js"></script>
		    <script type="text/javascript" src="/static/pretixcontrol/js/ui/main.91f464cd87d2.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/quota.4a59c32426a9.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/subevent.0b8675644778.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/question.59fc7a62e356.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/dragndroplist.1acc76c2d58f.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/mail.7f14809f7883.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/orderchange.f0a2bd4619c1.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/typeahead.08b41cc756e4.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/quicksetup.1a45b1ae40dc.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/dashboard.f7b5dc5f61b0.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/tabs.ccc044f45b99.js"></script>
           <script type="text/javascript" src="/static/leaflet/leaflet.386e649222d7.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/geo.420bb02ca48a.js"></script>
           <script type="text/javascript" src="/static/pretixbase/js/details.6e7e42c5b669.js"></script>
           <script type="text/javascript" src="/static/pretixbase/js/asynctask.c8f050de8b75.js"></script>
           <script type="text/javascript" src="/static/sortable/Sortable.a4a0f1e33390.js"></script>
           <script type="text/javascript" src="/static/colorpicker/bootstrap-colorpicker.3b2dc9e3223c.js"></script>
           <script type="text/javascript" src="/static/fileupload/jquery.ui.widget.0b44270691b4.js"></script>
           <script type="text/javascript" src="/static/fileupload/jquery.fileupload.1a6f827f35e3.js"></script>
           <script type="text/javascript" src="/static/lightbox/js/lightbox.min.db3e1524e9f2.js"></script>
           <script type="text/javascript" src="/static/are-you-sure/jquery.are-you-sure.4842acab6887.js"></script>
		

Request Method: GET
Request URL: https://events.indianadistrict5.com/control/
Django Version: 3.0.13
Python Executable: /var/pretix/venv/bin/python3
Python Version: 3.6.9
Python Path: ['/var/pretix', '/var/pretix', '/var/pretix/venv/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/var/pretix/venv/lib/python3.6/site-packages']
Server time: Fri, 2 Apr 2021 18:21:00 -0400
Installed Applications:
['django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'django.contrib.humanize',
'pretix.base',
'pretix.control',
'pretix.presale',
'pretix.multidomain',
'pretix.api',
'pretix.helpers',
'rest_framework',
'django_filters',
'compressor',
'bootstrap3',
'djangoformsetjs',
'pretix.plugins.banktransfer',
'pretix.plugins.stripe',
'pretix.plugins.paypal',
'pretix.plugins.ticketoutputpdf',
'pretix.plugins.sendmail',
'pretix.plugins.statistics',
'pretix.plugins.reports',
'pretix.plugins.checkinlists',
'pretix.plugins.pretixdroid',
'pretix.plugins.badges',
'pretix.plugins.manualpayment',
'pretix.plugins.returnurl',
'pretix.plugins.webcheckin',
'django_markup',
'django_otp',
'django_otp.plugins.otp_totp',
'django_otp.plugins.otp_static',
'statici18n',
'django_countries',
'hijack',
'compat',
'oauth2_provider',
'phonenumber_field',
'prtx_faq',
'pretix_telephone',
'pretix_passbook',
'pretix_pages',
'pretix_fontpackfree',
'pretix_closer2event',
'pretix_cashpayment']
Installed Middleware:
['pretix.api.middleware.IdempotencyMiddleware',
'pretix.multidomain.middlewares.MultiDomainMiddleware',
'pretix.base.middleware.CustomCommonMiddleware',
'pretix.multidomain.middlewares.SessionMiddleware',
'pretix.multidomain.middlewares.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
'pretix.control.middleware.PermissionMiddleware',
'pretix.control.middleware.AuditLogMiddleware',
'pretix.base.middleware.LocaleMiddleware',
'pretix.base.middleware.SecurityMiddleware',
'pretix.presale.middleware.EventMiddleware',
'pretix.api.middleware.ApiScopeMiddleware']

Traceback (most recent call last):
 File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/var/pretix/venv/lib/python3.6/site-packages/pretix/control/views/dashboards.py", line 634, in user_index
   return render(request, 'pretixcontrol/dashboard.html', ctx)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
   content = loader.render_to_string(template_name, context, request, using=using)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
   return template.render(context, request)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
   return self.template.render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 171, in render
   return self._render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
   return self.nodelist.render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 936, in render
   bit = node.render_annotated(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
   return self.render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
   return compiled_parent._render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
   return self.nodelist.render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 936, in render
   bit = node.render_annotated(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
   return self.render(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 143, in render
   return self.render_compressed(context, self.kind, self.mode, forced=forced)
 File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 97, in render_compressed
   return self.render_offline(context)
 File "/var/pretix/venv/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 82, in render_offline
   'is the original content:\n\n%s' % (key, original_content))

Exception Type: OfflineGenerationError at /control/
Exception Value: You have offline compression enabled but key "8db6c6a918bbf763123433597ec01ef1dd55eed8dc91f99c76868ac8f3d1e7bc" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:

           <script type="text/javascript" src="/static/jquery/js/jquery-2.1.1.min.e40ec2161fe7.js"></script>
           <script type="text/javascript" src="/static/js/jquery.formset.5f6b62d88653.js"></script>
           <script type="text/javascript" src="/static/typeahead/typeahead.bundle.28654235b116.js"></script>
           <script type="text/javascript" src="/static/bootstrap/js/bootstrap.894d79839fac.js"></script>
           <script type="text/javascript" src="/static/moment/moment-with-locales.42d5c7ca492b.js"></script>
           <script type="text/javascript" src="/static/datetimepicker/bootstrap-datetimepicker.8d7293336e00.js"></script>
           <script type="text/javascript" src="/static/select2/select2.2f9a54c25009.js"></script>
           <script type="text/javascript" src="/static/select2/i18n/de.887bfc43e9d1.js"></script>
           <script type="text/javascript" src="/static/select2/i18n/en.a283e3dd0ae0.js"></script>
           <script type="text/javascript" src="/static/charts/raphael-min.06557bf5ef58.js"></script>
           <script type="text/javascript" src="/static/charts/morris.d995698f8d57.js"></script>
           <script type="text/javascript" src="/static/clipboard/clipboard.238dfb9a5014.js"></script>
           <script type="text/javascript" src="/static/rrule/rrule.e2d0f3efd7ed.js"></script>
           <script type="text/javascript" src="/static/pretixpresale/js/ui/questions.5cfc73204443.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/jquery.qrcode.min.05f0b1d7d4b9.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/clipboard.b4d8b9a54770.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/menu.3799201d46c7.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/sb-admin-2.18aa75419be1.js"></script>
		    <script type="text/javascript" src="/static/pretixcontrol/js/ui/main.91f464cd87d2.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/quota.4a59c32426a9.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/subevent.0b8675644778.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/question.59fc7a62e356.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/dragndroplist.1acc76c2d58f.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/mail.7f14809f7883.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/orderchange.f0a2bd4619c1.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/typeahead.08b41cc756e4.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/quicksetup.1a45b1ae40dc.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/dashboard.f7b5dc5f61b0.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/tabs.ccc044f45b99.js"></script>
           <script type="text/javascript" src="/static/leaflet/leaflet.386e649222d7.js"></script>
           <script type="text/javascript" src="/static/pretixcontrol/js/ui/geo.420bb02ca48a.js"></script>
           <script type="text/javascript" src="/static/pretixbase/js/details.6e7e42c5b669.js"></script>
           <script type="text/javascript" src="/static/pretixbase/js/asynctask.c8f050de8b75.js"></script>
           <script type="text/javascript" src="/static/sortable/Sortable.a4a0f1e33390.js"></script>
           <script type="text/javascript" src="/static/colorpicker/bootstrap-colorpicker.3b2dc9e3223c.js"></script>
           <script type="text/javascript" src="/static/fileupload/jquery.ui.widget.0b44270691b4.js"></script>
           <script type="text/javascript" src="/static/fileupload/jquery.fileupload.1a6f827f35e3.js"></script>
           <script type="text/javascript" src="/static/lightbox/js/lightbox.min.db3e1524e9f2.js"></script>
           <script type="text/javascript" src="/static/are-you-sure/jquery.are-you-sure.4842acab6887.js"></script>

**Comment by raphaelm** [comment]
Please install nodejs.


We mentioned it in the release notes, it's probably still missing from the install guide.
