### ISSUE TITLE
How to silence WARNING: "MariaDB does not support a database index on longtext columns"

### ISSUE THREAD

**Issue by thisispatman** [pretix/pretix#2035]
Hello there,

when executing the runperiodic cronjob, it generates the following message:

> System check identified some issues:
> WARNINGS:
> pretixbase.RevokedTicketSecret.secret: (fields.W162) MariaDB does not support a database index on longtext columns.
>         HINT: An index won't be created. Silence this warning if you don't care about it.

Since this seems to be a constraint of MariaDB we cannot do anything about (right?), we want to silence this warning. This shouldn't compromise the functionality anyway, does it? 
But how can we silence it? Is there a way to exclude this specific check from the system check?

Thanks in advance,
best regards

**Comment by raphaelm** [comment]
> Since this seems to be a constraint of MariaDB we cannot do anything about (right?), we want to silence this warning. This shouldn't compromise the functionality anyway, does it?

Correct

> But how can we silence it? Is there a way to exclude this specific check from the system check?

I'm not sure. We can turn off ``fields.W162`` completely, but that would also turn off all future similar warning which might cause problems.
