### ISSUE TITLE
Correct error message when adding too many products

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#206]
The error message itself is fine, but when I have 10 products (which is the maximum) in my cart, every remaining product is still available - maybe add text like "Your cart is already full/at maximum capacity" instead.

On that note, maybe adding a "Contact our support at <mail> for larger orders." would be nice, too.

**Comment by raphaelm** [comment]
Can you please specifiy this further? I get a very correct error message of "You cannot select more than %s items per order."

**Comment by rixx** [comment]
Yeah, didn't describe it properly, sorry.

What I meant was: It'd be nice if all products/variations would have a message instead of a textinput field (or a disabled field, maybe) once your cart is full, similar to products/variations that are only available using a voucher etc.

**Comment by raphaelm** [comment]
Ah, I see. I'm not decided on that one. Currently those type of message is used only for issues that are (a) specific to an item and (b) the user cannot do anything about. "Cart is full" is neither of those things, so I'm not quite sure I want to use this UI concept here. It might be a good idea but I'm not yet sure :)

**Comment by rixx** [comment]
I think the most idiomatic thing in terms of web interfaces would be disabling the inputs. Just my two cents, and nothing I feel strongly about - but I dislike GUIs that let me try things that are obviously impossible (like adding items to a full cart).

**Comment by raphaelm** [comment]
Yes, but a disabled field doesn't ever tell you *why* it's disabled. But it might be a start, combined with a message.
