### ISSUE TITLE
Time slots show as available in calendar even when only tickets with special voucher codes can be booked

### ISSUE THREAD

**Issue by floscher** [pretix/pretix#2063]
**Describe the bug**
First off a bit of context on what kind of use case I'm trying to use pretix for:

In my case there are two groups of people who each get a different voucher code to book their tickets.
For the purpose of this issue, I'll call the first group instructors, the second one beginners.
The instructors should always be able to book any timeslot, but beginners can only book when at least one instructor has already booked that slot.

So I set up two products, one for instructors and a general one that anyone can buy. For each date I created a quota of 1 for instructor tickets and in the availability settings for the general ticket I set it so it only shows when the instructor quota is sold out.

In principle this setup works, but there is one big problem: For beginners every timeslot is shown as available, even when there are no tickets available for them, because no instructor has booked that slot.
That makes it very hard for the beginners to find slots that they can book.

**Expected behavior**
I would expect that "Book now" is only shown in the calendar and list views when the user really can book a ticket for that slot.

**Screenshots**
This is what beginners see when so far no instructor has booked the slot:<details>

![grafik](https://user-images.githubusercontent.com/3904348/117270437-7f89ed00-ae59-11eb-9116-48a8a4f81981.png)

</details>

This is what instructors see when entering their voucher code:<details>

![grafik](https://user-images.githubusercontent.com/3904348/117270656-bbbd4d80-ae59-11eb-828d-a35d7ad6abc6.png)

</details>

The relevant availability settings for the "Beginner" product:<details>

![grafik](https://user-images.githubusercontent.com/3904348/117271447-7e0cf480-ae5a-11eb-8cb2-149c7997035e.png)

</details>

The relevant availability settings for the "Instructor" product:<details>

![grafik](https://user-images.githubusercontent.com/3904348/117271854-e52aa900-ae5a-11eb-87ab-62aaa63692e9.png)

</details>

**Comment by raphaelm** [comment]
Unfortunately, we'll probably not fix that bug. It is a bug, agreed, but fixing it would have extreme consequences and the use case you are using this feature for is clever, but not really what the feature was intended for.

Fixing this bug would make the logic of "which calendar slot is available" much more complicated, which would lead to performance problems for all pretix users with lots of slots and lots of traffic.

**Comment by floscher** [comment]
@raphaelm Thanks for the quick response!

Yes, I know, it is kind of a fringe case that normally won't happen under "normal" circumstances for which the software was built. We'll probably only need a reservation system until the pandemic is over anyway, so it wouldn't be a problem for a long time anyway. There might be a few post-pandemic use cases for us when real-life events return, but those would then be more aligned with pretix's more common use cases.

Would an option to display the number of tickets already sold in the calendar more in the realm of possibilities? That would also have only very few use cases, but I guess that this should be easier to calculate than calculating the number of remaining tickets.

**Comment by raphaelm** [comment]
In fact we currently *do* calculate the number of remaining tickets in the background, the thing that's missing is the info that one product is currently hidding.

I don't think we'll start showing numbers in the calendar, though, since (a) they'll be often out of date due to caching and (b) it's pointless 99% of use cases and our software has enough complexity with just looking at the main use cases already, sorry :(

**Comment by floscher** [comment]
@raphaelm Alright, I'll close the issue then. Thanks for the insights.
