### ISSUE TITLE
Separate custom text for cancellation invoice

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#209]
I think for most cases, the custom added text will mostly include thanks for buying a ticket and maybe the reminder to pay within the payment term … which is fairly nonsensical on cancellations. So there should either be a separate cancellation text, or none at all (which I think is reasonable).

**Comment by raphaelm** [comment]
No, it needs to be the same or a separate text. The custom text might include important things like "No taxes applied due to $LAW" that need to be included.

**Comment by rixx** [comment]
I think we can consider this closed: regular configured text will be included in cancellations while payment provider specific text will be omitted.
