### ISSUE TITLE
Flaky AttributeError: 'HttpResponse' object has no attribute 'headers'

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2113]
We host on our instance on https://pretix.domain.org and I'm running into flaky 500 errors when requesting `/site.webmanifest`. When requested directly in the browser, it works fine. However when requested in the background by means of the `<link rel=manifest>` it results in the following stacktrace.

I've tried locally reproducing, however it doesn't seem to fail there. It seems to come from the Pretix middleware. Any tips on locating this issue?

**Describe the bug**
```pytb
AttributeError: 'HttpResponse' object has no attribute 'headers'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "pretix/base/middleware.py", line 235, in process_response
    resp['X-XSS-Protection'] = '1'
  File "django/http/response.py", line 172, in __setitem__
    self.headers[header] = value
```
**Expected behavior**

**Screenshots**

**Additional context**
We run a image build from the docker image `pretix/standalone:4.0.0`, it includes the follow versions.

<details>
<summary>version overview</summary>

lib | version
-- | --
amqp | 2.6.1
arabic-reshaper | 2.0.15
asgiref | 3.3.4
attrs | 21.2.0
babel | 2.9.1
backcall | 0.2.0
beautifulsoup4 | 4.8.2
billiard | 3.6.4.0
bleach | 3.3.0
cbor2 | 5.3.0
celery | 4.4.7
certifi | 2021.5.30
cffi | 1.14.5
chardet | 3.0.4
cryptography | 3.4.7
csscompressor | 0.9.5
cssutils | 2.3.0
decorator | 5.0.9
defusedcsv | 1.1.0
dj-static | 0.0.6
django | 3.2.3
django-appconf | 1.0.4
django-bootstrap3 | 15.0.0
django-compat | 1.0.15
django-compressor | 2.4.1
django-countries | 7.2.1
django-extensions | 3.1.3
django-filter | 2.4.0
django-formset-js-improved | 0.5.0.2
django-formtools | 2.3
django-hierarkey | 1.0.4
django-hijack | 2.1.10
django-i18nfield | 1.9.1
django-jquery-js | 3.1.1
django-libsass | 0.8
django-localflavor | 3.0.1
django-markup | 1.5
django-mysql | 3.11.1
django-oauth-toolkit | 1.2.0
django-otp | 0.7.5
django-phonenumber-field | 4.0.0
django-redis | 4.11.0
django-scopes | 1.2.0
django-statici18n | 1.9.0
djangorestframework | 3.12.4
elementpath | 2.2.2
et-xmlfile | 1.1.0
future | 0.18.2
gunicorn | 20.1.0
idna | 2.10
inlinestyler | 0.2.5
ipython | 7.24.0
ipython-genutils | 0.2.0
isoweek | 1.3.3
jedi | 0.18.0
jsonschema | 3.2.0
kombu | 4.6.11
libsass | 0.20.1
lxml | 4.6.3
markdown | 3.3.4
matplotlib-inline | 0.1.2
mt-940 | 3.2
mysqlclient | 2.0.3
oauthlib | 3.1.0
openpyxl | 3.0.7
packaging | 20.9
parso | 0.8.2
paypalrestsdk | 1.13.1
pexpect | 4.8.0
phonenumberslite | 8.11.5
pickleshare | 0.7.5
pillow | 8.2.0
pip | 21.1.2
ply | 3.11
pretix | 4.0.0
pretix-mollie | 1.3.2
pretix-pages | 1.4.1
pretix-via | 1
prompt-toolkit | 3.0.18
protobuf | 3.15.8
psycopg2-binary | 2.8.6
ptyprocess | 0.7.0
pycountry | 20.7.3
pycparser | 2.13
pygments | 2.9.0
pylibmc | 1.6.1
pyopenssl | 20.0.1
pyparsing | 2.4.7
pypdf2 | 1.26.0
pyrsistent | 0.17.3
python-bidi | 0.4.2
python-dateutil | 2.8.1
python-stdnum | 1.16
python-u2flib-server | 4.0.1
pytz | 2021.1
pyuca | 1.2
pyyaml | 5.4.1
rcssmin | 1.0.6
redis | 3.4.1
reportlab | 3.5.67
requests | 2.25.0
rjsmin | 1.1.0
sentry-sdk | 1.1.0
sepaxml | 2.4.1
setuptools | 57.0.0
six | 1.16.0
slimit | 0.8.1
soupsieve | 2.2.1
sqlparse | 0.4.1
static3 | 0.7.0
stripe | 2.42.0
text-unidecode | 1.3
tlds | 2021053000
tqdm | 4.61.0
traitlets | 5.0.5
urllib3 | 1.26.5
vat-moss-forked | 2020.3.20.0.11.0
vine | 1.3.0
vobject | 0.9.6.1
wcwidth | 0.2.5
webauthn | 0.4.7
webencodings | 0.5.1
wheel | 0.36.2
xmlschema | 1.6.2
</details>

**Comment by raphaelm** [comment]
This will happen for maximum 24 hours after an upgrade from 3.18 to 4.0 for all views where we use ``@cache_page``, because Django 3.0 cache values are incompatible with Django 3.2. Since it doesn't impact any very important views, I don't think it warrants a more involved fix. If you want, you can flush your redis instance, but that will also delete open sessions etc.

**Comment by MaicoTimmerman** [comment]
Thanks for the quick reply!
