### ISSUE TITLE
Decouple language selection in /control

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#212]
The language used in the /control/ backend should be determined **only** by the user's language and any session/cookie choice set by the frontend should be ignored.

- [ ] Decouple language choice from frontend. The backend language should be coming from the user object, not from the session.
- [ ] MAYBE: Introduce a quick way to change the user locale in the backend if ``DEBUG`` is on to ease development

original ticket content
> At the moment, if I want to see the control interface in another language, I open the shop, switch the language there and reload the control interface which is a bit annoying.

**Comment by rixx** [comment]
Hm, by now I discovered that you *can* change your locale in `/control`, but you have to go and edit your user profile to do it. I'm standing by my original suggestion.

**Comment by rixx** [comment]
Should wait for #300.

**Comment by raphaelm** [comment]
Yes. Also, I'm not yet sure that we need this. It should be enough that you can change the backend language in your user settings. However, the language controls in the shop should not influence the backend language.
