### ISSUE TITLE
System very slow after a while - Version 4.1 (same problem with 3.18)

### ISSUE THREAD

**Issue by misters84** [pretix/pretix#2149]
hallo,

i have the problem, that my pretix installation is very slow after a few days of running.
I often get an 502 Bad Gateway response.
When i restart the machine everything is very fast for a few hours/1 day and works very fine.
I had the same problem with version 3.18 and after an update to 4.1 the problem is still there.

top says that the machine has enough ressources in state when it is low:

_top - 20:48:51 up 3 days,  2:57,  1 user,  load average: 0.50, 0.39, 0.20
Tasks:  50 total,   1 running,  49 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.2 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   8192.0 total,   7334.4 free,    705.2 used,    152.4 buff/cache
MiB Swap:   1024.0 total,    637.1 free,    386.9 used.   7452.0 avail Mem_

**No error messages in nginx error log.
No error messages in postgresql log.**

**Pretix log shows many entry like:**
_WARNING 2021-07-06 01:50:15,935 django.request log Bad Request - with different folders
ERROR 2021-07-06 10:41:28,355 django.request log Internal Server Error: /control/login_

**But it seems, that pretix-web service maybe has a problem:**

● pretix-web.service - pretix web service
   Loaded: loaded (/etc/systemd/system/pretix-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-07-08 17:51:50 CEST; 3 days ago
 Main PID: 306 (gunicorn)
    Tasks: 6 (limit: 4915)
   Memory: 666.6M
   CGroup: /system.slice/pretix-web.service
           ├─  306 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
           ├─ 5819 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
           ├─14780 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
           ├─14781 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
           ├─16000 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345
           └─16843 /var/pretix/venv/bin/python3 /var/pretix/venv/bin/gunicorn pretix.wsgi --name pretix --workers 5 --max-requests 1200 --max-requests-jitter 50 --log-level=info --bind=127.0.0.1:8345

Jul 11 20:40:53 gunicorn[306]: WARNING 2021-07-11 18:40:53,213 django.request log Bad Request: /_ignition/execute-solution
Jul 11 20:46:42  gunicorn[306]: [2021-07-11 20:46:42 +0200] [306] [CRITICAL] WORKER TIMEOUT (pid:638)
Jul 11 20:46:43 gunicorn[306]: [2021-07-11 20:46:43 +0200] [306] [WARNING] Worker with pid 638 was terminated due to signal 9
Jul 11 20:46:56 gunicorn[306]: [2021-07-11 20:46:55 +0200] [16823] [INFO] Booting worker with pid: 16823
Jul 11 20:47:13 gunicorn[306]: [2021-07-11 20:47:13 +0200] [306] [CRITICAL] WORKER TIMEOUT (pid:16823)
Jul 11 20:47:14 gunicorn[306]: [2021-07-11 20:47:14 +0200] [306] [WARNING] Worker with pid 16823 was terminated due to signal 9
Jul 11 20:47:14 gunicorn[306]: [2021-07-11 20:47:14 +0200] [16836] [INFO] Booting worker with pid: 16836
Jul 11 20:47:44 gunicorn[306]: [2021-07-11 20:47:44 +0200] [306] [CRITICAL] WORKER TIMEOUT (pid:16836)
Jul 11 20:47:45 gunicorn[306]: [2021-07-11 20:47:45 +0200] [306] [WARNING] Worker with pid 16836 was terminated due to signal 9
Jul 11 20:47:45 gunicorn[306]: [2021-07-11 20:47:45 +0200] [16843] [INFO] Booting worker with pid: 16843

**Any ideas what my problem/s can be?**

**Comment by misters84** [comment]
When i get 502 bad gateway error nginx log shows an error:

2021/07/11 20:55:23 [error] 735#735: *846 upstream prematurely closed connection while reading response header from upstream, client: x.x.x.x, server: subdomain.domain.com, request: "GET /XW/XW21/?require_cookie=true HTTP/1.1", upstream: "http://127.0.0.1:8345/XW/XW21/?require_cookie=true", host: "subdomain.domain.com", referrer: "https://subdomain.domain.com/"

**Comment by raphaelm** [comment]
This all sounds like *something* the Python process does takes very long. After a while, nginx stops waiting (hence the 502) and after another while, gunicorn kills the process (hence the kill signal in the journal). A reason could be a broken or very slow connection between pretix and a database / redis.

> Pretix log shows many entry like:
> ERROR 2021-07-06 10:41:28,355 django.request log Internal Server Error: /control/login

Is this followed by a stack trace you could post here?

**Comment by misters84** [comment]
Hi Raphael,

i have installed redis, but not configured itself and removed from pretix config file (only a small installation).
Postgresql database is running on the same machine, so it shouldnt be a broken or a slow connection.

I have restartet machine yesterday and waiting that it to slow down, so that i can post stack traces here.

Thank you in advance and best regards

**Comment by raphaelm** [comment]
Can you please post the stacktrace from log I asked for?

**Comment by misters84** [comment]
Hi,

here it is (it was before i removed redis from config file and made a rebuild). Today i only have this error in log (without trace):

WARNING 2021-07-13 10:59:21,300 django.request log Bad Request: /
WARNING 2021-07-13 10:59:21,300 django.request log Bad Request: /
WARNING 2021-07-13 13:47:59,867 django.request log Bad Request: /
WARNING 2021-07-13 13:47:59,867 django.request log Bad Request: /
WARNING 2021-07-13 14:32:48,777 django.request log Bad Request: /
WARNING 2021-07-13 14:32:48,777 django.request log Bad Request: /


`Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/var/pretix/venv/lib/python3.7/site-packages/django_redis/cache.py", line 81, in get
    client=client)
  File "/var/pretix/venv/lib/python3.7/site-packages/django_redis/client/default.py", line 201, in get
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/pretix/venv/lib/python3.7/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/var/pretix/venv/lib/python3.7/site-packages/pretix/base/middleware.py", line 229, in process_response
    if gs.settings.leaflet_tiles:
  File "/var/pretix/venv/lib/python3.7/site-packages/hierarkey/proxy.py", line 181, in __getattr__
    return self.get(key)
  File "/var/pretix/venv/lib/python3.7/site-packages/hierarkey/proxy.py", line 162, in get
    if key in self._cache():
  File "/var/pretix/venv/lib/python3.7/site-packages/hierarkey/proxy.py", line 50, in _cache
    timeout=1800
  File "/var/pretix/venv/lib/python3.7/site-packages/django/core/cache/backends/base.py", line 167, in get_or_set
    val = self.get(key, version=version)
  File "/var/pretix/venv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/var/pretix/venv/lib/python3.7/site-packages/django_redis/client/default.py", line 199, in get
    value = client.get(key)
  File "/var/pretix/venv/lib/python3.7/site-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/var/pretix/venv/lib/python3.7/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/pretix/venv/lib/python3.7/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/var/pretix/venv/lib/python3.7/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.`

**Comment by raphaelm** [comment]
Well, it says it can't connect to the configured redis server…

**Comment by misters84** [comment]
But why is this only a problem after 1 or 2 days? After reboot everything works fine for 1-2 days and the system was very fast in our tests.

And where does the warnings with "django.request log Bad Request:" come from?

**Comment by raphaelm** [comment]
> But why is this only a problem after 1 or 2 days? After reboot everything works fine for 1-2 days and the system was very fast in our tests.

No idea, maybe it's unrelated to that message. Haven't heard that before.

> And where does the warnings with "django.request log Bad Request:" come from?



The bad request is because some spammers are trying to access pages that do not exist. You can ignore it.

**Comment by misters84** [comment]
It seems, that the only problem was not totally configured redis. System is stable since 4 days. I will close that ticket and when problem comes back i will reopen it. Thank you for your support.

**Comment by misters84** [comment]
The problem is back. In the meantime i installed and configured redis and it works fine.

**I've checked the following logs:** 
redis - no errors
pretix - no errors
postgresql - no errors
nginx:
```
2021/07/23 19:30:21 [error] 294#294: *381 upstream prematurely closed connection while reading response header from upstream, client: x.x.x.x, server: subdomain.domain.com, request: "GET /XX/XX21/ HTTP/1.1", upstream: "http://127.0.0.1:8345/XX/XX21/", host: "subdomain.domain.com", referrer: "https://subdomain.domain.com/"
```

Output from service pretix-web status:

```
Jul 23 19:30:21 xxx gunicorn[281]: [2021-07-23 19:30:20 +0200] [281] [CRITICAL] WORKER TIMEOUT (pid:315)
Jul 23 19:30:21 xxx gunicorn[281]: [2021-07-23 17:30:21 +0000] [315] [INFO] Worker exiting (pid: 315)
Jul 23 19:30:24 xxx gunicorn[281]: [2021-07-23 19:30:24 +0200] [281] [WARNING] Worker with pid 315 was terminated due to sig
Jul 23 19:30:24 xxx gunicorn[281]: WARNING 2021-07-23 17:30:24,517 django.request log Not Found: /favicon.ico/
Jul 23 19:30:24 xxx gunicorn[281]: WARNING 2021-07-23 17:30:24,517 django.request log Not Found: /favicon.ico/
Jul 23 19:30:26 xxx gunicorn[281]: [2021-07-23 19:30:26 +0200] [14815] [INFO] Booting worker with pid: 14815
Jul 23 19:30:56 xxx gunicorn[281]: [2021-07-23 19:30:56 +0200] [281] [CRITICAL] WORKER TIMEOUT (pid:14815)
Jul 23 19:30:56 xxx gunicorn[281]: [2021-07-23 17:30:56 +0000] [14815] [INFO] Worker exiting (pid: 14815)
Jul 23 19:30:57 xxx gunicorn[281]: [2021-07-23 19:30:57 +0200] [281] [WARNING] Worker with pid 14815 was terminated due to s
Jul 23 19:30:57 xxx gunicorn[281]: [2021-07-23 19:30:57 +0200] [14818] [INFO] Booting worker with pid: 14818
```

There is actually only 1 order in the database, so it should be very fast.

TOP says 99,8% IDLE, 6818/8192MB free Memory.
Database and redis are running on the same machine like pretix. So it could not be a bad connection to the database.

I've reinstalled postgresql completely, but that dont solve the problem.

System is running very fast after a reboot and after a few days pretix is running very slow and the errors like described are happening. 

But today it was a bit different. Now it is running fast after the errors without a restart.

**Comment by raphaelm** [comment]
closing because we're not getting anywhere here and don't have any other reports. sorry :(
