### ISSUE TITLE
Internal Name on "Modify Order"-Page

### ISSUE THREAD

**Issue by Janfred** [pretix/pretix#2150]
When modifying an order, for AddOn products the internal name is shown instead of the localized public name.
This also persists when changing the translation.

I have detected this problem in 4.0.0 and just updated to 4.1.0, the problem exists in both versions.

**Comment by wiffbi** [comment]
According to the comment on the field „Internal name“, this behaviour is intentional:

> If you set this, this will be used instead of the public name in the backend.

**Comment by raphaelm** [comment]
I think @Janfred is refering to the "modify information" page in the frontend

**Comment by Janfred** [comment]
I'm sorry, my description was probably misleading.

The issue is with the modify page for the participants (via https://<domain>/<slug>/order/<order_id>/<secret>/modify ) not in the backend interface.

Probably the Issue is in the file `src/pretix/presale/templates/pretixpresale/event/order_modify.html`
Unfortunately I currently don't have the time to try out a fix.

**Comment by wiffbi** [comment]
Sorry, I misunderstood. I can confirm the bug and will PR a fix soon.
