### ISSUE TITLE
Order with "manual approval" after deleting parts of the order

### ISSUE THREAD

**Issue by navlisilvan** [pretix/pretix#2160]
Hi,
i think i found a  bug:

There was a order with many tickets, also one with "manual approval". So, the order was marked als "needs to be approved".
When i cancel the "manual approval"-tickets in this order, the order is still marked as "needs to be approved". I think i should not be like this, or?

(I hope, that i used the right english words, use pretix in german).

**Comment by raphaelm** [comment]
Uh, hmm. I *think* I'd consider this a wontfix. I understand it is surprising behavior, but I could think of just as many situations where the opposite behavior (auto-approving the order) would be surprising – and much more dangerous.
