### ISSUE TITLE
Slots not marked as booked in the monthly, weekly, list overview after quota is empty

### ISSUE THREAD

**Issue by k3v1n-eu** [pretix/pretix#2168]
**Describe the bug**
After a ticket for a specific time slot is booked it does not get marked as booked in the monthly overview. Just if you click on that time slot you get the information that the slot is fully booked. But if you go back afterwards to the overview, you will see that the slot is fully booked now. Sometimes it seems to be working but not always. I tested the same also on a Pretix.eu test version and experienced the same issue. 

**Expected behavior**
After a quota is fully booked, the slot shot be marked as booked also in the monthly, weekly, list overview and not just if you click on that slot.

**Comment by pc-coholic** [comment]
Sorry to say, but this is more or less "as intended"...

Calculating available quotas is expensive (as in: uses a lot of resources), so for pages with a lot of quota-related views, we cache the displayed status.

When using pretix, the sold-out-message should also appear in the overview within a minute or two - or when the next person hits the actual event-page forcing a recalculation.

Unfortunately we have to go this way, else the system would become unusable for bigger events with multiple dates and multiple quotas within each date.

**Comment by k3v1n-eu** [comment]
Hi @pc-coholic 

thanks for this really fast response. I understand that problem now and don't need to think about that i did something wrong on the configuration. Did not found anything about this in the documentation. Maybe i'll be the only one wondering about that. :-)
So after i run pretix cron it should be marked correct in the overview? Couldn't test it now, will do later.

Thanks again!

**Comment by k3v1n-eu** [comment]
Okay the Cron Job didn't the recalculation of the overview.
But as you said, after 1-2 minutes the page got refreshed. 👍 

THX again!
