### ISSUE TITLE
Dockerhub missing 4.2 release image

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2186]
**Describe the bug**
From the blog I saw the new version has been released, which are normally instantly available on Dockerhub. For the 4.2 release it did not (yet) get published. Is that intentional?

**Expected behavior**
https://hub.docker.com/r/pretix/standalone/tags to have the newest release.

**Screenshots**

**Additional context**

**Comment by raphaelm** [comment]
No, not intentional, will look into it tomorrow

**Comment by raphaelm** [comment]
Okay, so in addition to Docker Hub turning off autobuilds, our Dockerfile did no longer build correctly because the `python:3.8` base image switched from Debian buster to bullseye. I've now adjusted it to `python:3.9-bullseye` and backported that commit to the 4.2 release branch.

→ Fixed now :)
