### ISSUE TITLE
Refactor user input handling/validation in orders and cart views

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#220]
At the moment, cart and presale data are rendered by using hand-made html forms and "manual" validation of POST parameters. Even though Django forms might seem clumsy for relatively dynamic content, being able to just call `form.is_valid()` might provide more security and stability than a custom validation logic of raw POST params.

**Comment by raphaelm** [comment]
This might be a solution, but I believe there are other, maybe easier ways to achive this than to squeeze this into Django forms. Let's discuss this when we refactored the services.orders into a state machine and use that structure to refactor services.cart.

**Comment by rixx** [comment]
In that case, let's keep this issue as a general "unify user input validation/handling in orders and cart" issue.

**Comment by raphaelm** [comment]
I think CartManager does a decent job here
