### ISSUE TITLE
Stripe Credit Card option should allow ZIP with Letters

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#2206]
in UK there are letters in the ZIP/postal code - this blocks these people from using the stripe credit card option.
Entering letters in this state does not work:
![image](https://user-images.githubusercontent.com/111600/133487540-d8f38906-0630-4164-b582-93eb79dfafc8.png)

**Comment by pc-coholic** [comment]
Hi ligi,

the Stripe Elements/Widget is initialized without a country indicator. As such, it relies only on the entered credit card number to determine the card holders country.

If the card is UK-issued, the ZIP-code will also accept letters.

Grab yourself a UK testcard, and this should work as intended: https://stripe.com/docs/testing#international-cards

42x is unfortunately US ;-)

**Comment by ligi** [comment]
Interesting - with the 42er one I just tried to reproduce a error a user reported. I do not own a UK credit card to test this.

**Comment by pc-coholic** [comment]
4000008260000000 should do the trick while in test-mode - when it comes to real credit cards, I unfortunately cannot help with a real UK one either, sorry...

**Comment by ligi** [comment]
thanks - inteesting - can confirm with this one I can enter letters:
