### ISSUE TITLE
[A11y] remove cart-deadline from basket on order confirm page

### ISSUE THREAD

**Issue by wiffbi** [pretix/pretix#2214]
**Describe the bug**
On the order confirmation page there is still the hint regarding the cart-deadline – often being „your cart is no longer reserved for you“.

**Expected behavior**
cart-deadline should be removed completely from order confirmation page

**Comment by raphaelm** [comment]
:o where yxactly? Is this only a a11y bug or a general bug?

**Comment by wiffbi** [comment]
It is a a11y-bug, but JavaScript-related. I added a short description to the basket-„table“ (it has to have one to be compliant) and that is overwritten when JavaScript is trying to determine the deadline even on a confirmation-page. I fixed it by changing the description-ID on the confirmation page.

P.S.: Sorry, I forgot to assign this to me. I just added issues that I needed to address, so I do not forget them.
