### ISSUE TITLE
Open Shop results in broken URL

### ISSUE THREAD

**Issue by jasonjenssen** [pretix/pretix#2223]
Hello,

when I got admin mode enabled and I click on "Open Shop", it redirects me to:

"https/auth"

Is there any configuration I missed out?

Thanks.

**Comment by pc-coholic** [comment]
Could you check your pretix.cfg if you set the `url` in the `[pretix]` section?

**Comment by jasonjenssen** [comment]
Hey, yes, it is set.
Scheme: 
url=https://mydomain.de

**Comment by jasonjenssen** [comment]
We bought enterprise and currently testing it, we ran into this issue.

**Comment by jasonjenssen** [comment]
Also, when it redirects me to https/testevent and I call mydomain.de/testevent manually, it cant find something.

**Comment by jasonjenssen** [comment]
Okay, so what is really weird is that I created a new organizer and there it sets the links correctly.

**Comment by jasonjenssen** [comment]
I already checked it, nothing is set there, also no whitespace. Thats really weird.

**Comment by raphaelm** [comment]
If you bought Enterprise support, also feel free to reach out at support@pretix.eu so we can maybe jump on a quick call with screen sharing to get to the bottom of this.
