### ISSUE TITLE
Batch vouchers with duplicate code is unhandled.

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2246]
**Describe the bug**
When creating batch vouchers and a single code exists twice, this results in a "An unexpected error has occurred, please try again later.". Particularly it results in:

```
IntegrityError
duplicate key value violates unique constraint "pretixbase_voucher_event_id_code_b07c351f_uniq"
DETAIL:  Key (event_id, code)=(1, TESTTEST) already exists.
```

**Expected behavior**
A clear error message in the interface. I think we could check the list of codes, before sending the celery task. Just like we do when creating a single code.

**Comment by raphaelm** [comment]
The code here has been rewritten by now, I think this no longer applies
