### ISSUE TITLE
Fresh install of pretix - reports error 400 Bad request

### ISSUE THREAD

**Issue by smejkalv** [pretix/pretix#2270]
Hi,
I have just finished my first fresh install of pretix exactly step by step using the documentation. And I get django error 400 when I try GET /

The only error in logs I can see is this... and it is not helpful

gunicorn[17326]: WARNING 2021-10-28 16:21:03,125 django.request log Bad Request: /

I don't have a clue what can be wrong...
Thx for help

**Comment by Justessej** [comment]
What do you mean with wrong url settings i have the same issue

**Comment by raphaelm** [comment]
This URL probably: https://docs.pretix.eu/en/latest/admin/config.html#pretix-settings
