### ISSUE TITLE
Substring search when matching voucher tags

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#228]
I might use a tagging structure such as "DE-Berlin", "DE-Stuttgart" for vouchers, and it'd be neat to match all "DE-" tagged vouchers at once.

**Comment by koebi** [comment]
Hey,
I'm willing to contribute to pretix, and @raphaelm pointed me to this. I'm currently kind of getting the hang of pretix and just thought I'd let you know I'm working on this.
