### ISSUE TITLE
customer-bound voucher

### ISSUE THREAD

**Issue by s72785** [pretix/pretix#230]
To prevent people from selling vouchers, they could be bound to either
-  to a member id (e.g. CCC e.V. Mitgliedsnummer)
- email address of the purchaser (issued to email address)
- organisation (to be delegated as one of the versions above, e.g. by erfa/chaostreff)

**Comment by raphaelm** [comment]
Thanks for your suggestion and sorry for me not answering earlier! I'm closing this here now, as it is a *very* c3-specifc feature that would better live in a plugin to pretix.

However, I also don't think it would be used at CCC, beause of first, voucher selling wasn't *that* much of a problem this year (I only know of one *fake* offer) and second, we *really* dislike storing unnecessary data about our participants. Also, the vouchers were *meant* to be spread across organizations.
