### ISSUE TITLE
Support for Stripe's Bitcoin API

### ISSUE THREAD

**Issue by davidak** [pretix/pretix#231]
You already use Stripe for credit card payments, they also support Bitcoin.

It should be very easy to enable: https://stripe.com/bitcoin

Bitcoins have a lot of advantages like fast (unlike wire transfer) and secure payment and you can use them anonymously.

**Comment by raphaelm** [comment]
Yes, that would be a nice addition to the software! However, its not very relevant to the events this is currently used for,  because of this:

> Bitcoin processing is currently limited to users in the United States.

Source: https://stripe.com/docs/bitcoin

**Comment by raphaelm** [comment]
I'm labeling this with "plugin ideas" as I do not see this getting into pretix' core, but I do encourage you to create a payment provider plugin that adds this functionality.

**Comment by cptfoo** [comment]
Why stripe? The whole point of Bitcoin is that it makes it easy to accept payments without a third party. Why give Stripe money instead of just writing the code? And writing the code would make it easy for others to use since its free software.

**Comment by raphaelm** [comment]
Nobody ever said that you cannot implement other plugins that accept bitcoin in a different way. :) Tgat's just not what this "plugin idea" ticket is about :)

The reason some event organizers would want stripe to handle this is not only the technical part, it is also about the organizational part regarding flaky conversion rates, taxes, etc. which are abstracted a layer away if you use Stripe or a similar service.

**Comment by ligi** [comment]
Like this issue! But I would rename it from "Support for Stripe's Bitcoin API" to "Add payment-plugin for crypto-currencies ) as I agree with @cptfoo - no need for stripe here

**Comment by davidak** [comment]
@ligi maybe create a new issue and close this since the discussion yet was about stripe.

**Comment by ligi** [comment]
Not sure about this - @raphaelm - rename or reopen?

**Comment by raphaelm** [comment]
As I stated above, this issue is specifically for Stripe's bitcoin API. There is #411 for Coinify. For the **vast** majority of event organizers a gateway like Stripe or Coinify is required. I don't know of any event organizers who would want to deal with the issues that come with crypto currencies (fluctuating prices, taxes, conversion to a traditional currency) etc. themselves without an abstraction layer like Stripe or Coinify.

You can surely create a different issue for other approaches to deal with crypto currencies, and if someone wants to use and implement that, that is fine with me. Please note however that this is a issue of type "plugin ideas", as I currently do not have plans to add any more payment providers to the core package, the plugin ecosystem is there for a reason :)

**Comment by davidak** [comment]
@raphaelm you are right.

>I currently do not have plans to add any more payment providers to the core package

Stripe is already there.

>only one code change is needed to begin accepting Bitcoin payments—the addition of `data-bitcoin="true"`

https://stripe.com/docs/bitcoin#quickstart-using-checkout

I'm not sure if Stripe supports Bitcoin in Germany now.

Would you accept such small Code change in core? Probably need to be made optional in pretix.

**Comment by raphaelm** [comment]
> Would you accept such small Code change in core? Probably need to be made optional in pretix.

As the Stripe plugin currently lives in core, I probably accept extensions to it if they are properly configurable. This goes also for #407 which I find even more interesting personally.

> only one code change is needed to begin accepting Bitcoin payments—the addition of data-bitcoin="true"

...if you use Stripe Checkout, yes. Unfortunately, we currently support two Stripe interfaces, one based on Stripe Checkout, one based on Stripe.js. I'm totally for dropping one of them in the long run, but while bitcoin is simpler with Checkout, the SEPA/iDEAL stuff (see #407) is only available with Stripe.js currently. So for now, we'd probably need to implement bitcoin for both interfaces to be flexible in the future.

> I'm not sure if Stripe supports Bitcoin in Germany now.

Does not seem so.

**Comment by davidak** [comment]
@raphaelm i agree that we should implement SEPA first since more people are using it (all bank accounts in the EU).

**Comment by davidak** [comment]
>Stripe users in the United States can accept Bitcoin for USD payment

https://stripe.com/docs/bitcoin#bitcoin-requirements

**Comment by raphaelm** [comment]
Bitcoin is no longer supported by Stripe: https://stripe.com/blog/ending-bitcoin-support
