### ISSUE TITLE
Minor: mail layout displays centered on Apple mail

### ISSUE THREAD

**Issue by rradmin** [pretix/pretix#2363]
**Describe the bug**
This is the email display on Apple Mail version 11.5 (3445.9.7):
![image](https://user-images.githubusercontent.com/19307018/144481635-e39a110e-958d-4341-9aff-752c76fcfb41.png)
This is the same email in gmail: 
![image](https://user-images.githubusercontent.com/19307018/144481829-1407a7ef-c553-4e60-be06-8f5c9743fd76.png)

**Expected behavior**
I'd like the mails left alligned, like in Gmail.

**Screenshots**
See above.

**Additional context**
Thanks for your efforts.

**Comment by raphaelm** [comment]
@wiffbi can you reproduce this?

**Comment by wiffbi** [comment]
Yes I can confirm. I remember stumbling upon this when fixing the header-image for Outlook 2010+. I will look into this.
