### ISSUE TITLE
IBAN is not very readable

### ISSUE THREAD

**Issue by majewsky** [pretix/pretix#239]
![screen1](https://cloud.githubusercontent.com/assets/24696/18541796/bacb40a4-7b27-11e6-988b-4bd37e162b3d.png)

This applies to both the web UI and the emails sent: It's customary to group the IBAN into four-digit groups with non-breaking spaces to make them easier to read and memorize, e.g. in this case `DE05 1001 0010 0017 6951 05`.

**Comment by raphaelm** [comment]
This is not a software problem, just a configuration issue. Thanks for the feedback anyway, we'll change that on tickets.events.ccc.de!
