### ISSUE TITLE
Impossible to customize week format in calendar view

### ISSUE THREAD

**Issue by cpoisnel** [pretix/pretix#2390]
**Describe the bug**
Hi,

Formats defined in Pretix (Week format or Day format in formats.py) are not shared with translation files (*.po). We can offer new translations using https://translate.pretix.eu/ but the formats seem to be outside the scope of web translation. 
This bug could be a new feature: include formats in po files to ensure consistency.

**Expected behavior**
Translate W for week in S for "Semaine" in django.po so if you use the calendar view of events of organizer with French translations, W ( Week) / KW (Kalenderwoche) should be replaced by S.

**Screenshots**

![image](https://user-images.githubusercontent.com/1509166/146814315-f2614e93-d542-4ce3-832b-dc95f9e15d47.png)

**Comment by raphaelm** [comment]
We will not handle formats through .po files as we do not want to deviate from how Django handles formats.

We'd of course be happy to adjust the French format :)

**Comment by wiffbi** [comment]
It used to be a translatable string „W“, but in the context of date formatting this was not optimal (it was basically a fixed format string in the template, only the letter was translatable – no way to localize the way a week was displayed other than the translatable letter „W“). We changed it to date-formatting with `WEEK_FORMAT` in #2382

**Comment by cpoisnel** [comment]
Thanks! How fast!
