### ISSUE TITLE
Only can open pretix as localhost:8345 on the host server. Not on my local PC. Fix?

### ISSUE THREAD

**Issue by Justessej** [pretix/pretix#2427]
I installed everything Postgre, Redis, Python, Nginx, Nodjs. Everything is Active but still i cant figure out what is blocking pretix. Can someone please help me :)

**Comment by raphaelm** [comment]
- If you have trouble setting up pretix and no certainty that there's a bug in pretix, please create a "discussion" in the Q&A session, not an issue
- Please always include as many details as possible, including what you mean by "is blocking" i.e. what your exact error message is and what your log says
