### ISSUE TITLE
OfflineGenerationError at /control/login

### ISSUE THREAD

**Issue by FlaviaBastos** [pretix/pretix#244]
I ran into this error when trying to access http://localhost:8000/ and http://localhost:8000/mrmcd/2015
This is after a fresh installation (clone and all). `python manage.py runserver` doesn't generate any error on the terminal but the browser gives this:

`You have offline compression enabled but key "22a806d67d65a69a2a5c00eb139516ce" is missing from offline manifest. You may need to run "python manage.py compress".`

Running `python manage.py compress` as recommended generates a list of files and the following message: 
`Compressing... done
Compressed 16 block(s) from 95 template(s) for 1 context(s).`

Running server after this gives the same results: no error on terminal but no access through the browser. 

Oh, all tests (except for `send_mail_with_user_locale`) are passing.

I wasn't sure if this is just on mine but decided to report anyway. If it's local, maybe I get some help fixing it 😬

**Comment by raphaelm** [comment]
We need to somehow solve this for development. To find the error source, can you try if ``python manage.py collectstatic`` helps?

**Comment by raphaelm** [comment]
Oh, I just found I accidentally commited a settings change. Fixed in 912a81d. Thanks!

**Comment by laf0rge** [comment]
I'm getting the same 
`compressor.exceptions.OfflineGenerationError:` You have offline compression enabled but key "c0a2acda3c76cefe5aa46a520b92f92a" is missing from offline manifest. You may need to run "python manage.py compress".` all the time. Running the "manage.py compress" command as the pretix user doesn't fix the situation.  The only workaround known so far is to disable COMPRESS_OFFLINE in settings.py.

**Comment by raphaelm** [comment]
@laf0rge Well, your situation is different in that Flavia's bug was that we tried to find offline compressed files in dev mode.

In your case, COMPRESS_OFFLINE is rightfully on, the question is why it doesn't find the files. Have you made any other changes to settings.py? Can you paste the output of the compress command? Are you sure you're running the compress command from the right working directory, i.e. with the correct pretix.cfg?

**Comment by laf0rge** [comment]
Thanks for your quick follow-up.

I tried to attach the output of the compress command to this github issue, but it keeps telling me "Something went really wrong, and we can't process that file".  I've made it available at http://people.osmocom.org/laforge/tmp/20170405-pretalx-compress.txt

* there are no other modifications to settings.py
* The command has been run inside the stock "pretix/standalone:stable" docker container in the /pretix/src directory
* The pretix.cfg is in  /etc/pretix/pretix.cfg
* there is a (working) symlink from /etc/pretix/pretix.cfg to /pretix/src/pretix.cfg

**Comment by raphaelm** [comment]
Hmm, to check that we don't have a bug in the docker container, I just made the very simple test of pulling it and running it without any configuration or external services:

```
docker pull pretix/standalone:stable
/usr/bin/docker run --rm -p 8345:80 pretix/standalone:stable all
```

Works totally fine. Also, with Docker, ``compress`` is being run during the image build so there should be no need to run it later at all. Could you, just to be sure, pull the image again? We release 1.14 yesterday and maybe it already (accidentally) fixes the isseu?

**Comment by laf0rge** [comment]
"pretix/standalone:stable" still points to an older release, but i will try "pretix/standalone:latest" now, guess that's what you're asking?

**Comment by laf0rge** [comment]
root@admin2 /etc/compose # docker pull pretix/standalone:stable

stable: Pulling from pretix/standalone
Digest: sha256:9ce2ac9b52e49b2366781b9517c55d44a7018d11f64b169218919b39e0b42437
Status: Image is up to date for pretix/standalone:stable

pretix/standalone    stable              6b6af0667f30        4 weeks ago         1.19GB

**Comment by laf0rge** [comment]
just tried with "pretix/standalone:latest" and the problem persists: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/pretix/src/pretix/base/views/errors.py", line 68, in server_error
    'request': request
  File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 86, in render_compressed
    return self.render_offline(context)
  File "/usr/local/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 71, in render_offline
    'You may need to run "python manage.py compress".' % key)
compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "c0a2acda3c76cefe5aa46a520b92f92a" is missing from offline manifest. You may need to run "python manage.py compress".

**Comment by raphaelm** [comment]
No, I was meaning stable, but apparently that was in fact still pointing to something wrong. I'll rebuild ``stable``  now, in the meantime the tag ``1.14`` is equivalent

**Comment by raphaelm** [comment]
Uh, the traceback has something interesting in it:
```
File "/pretix/src/pretix/base/views/errors.py", line 68, in server_error
'request': request
```

This means that the OfflineGenerationError occurs **while rendering the error 500 page**. This sounds like there might be a different type of stacktrace in your logs that might lead to the problem source.

**Comment by laf0rge** [comment]
just downgraded to "pretalx/standalone:1.14" and still getting the same error. full backtrace of a single access to https://pretix.sysmocom.de/control/ can be found at http://people.osmocom.org/laforge/tmp/20180405-pretix.log

**Comment by laf0rge** [comment]
config file shouldn't contain any surprises either: http://people.osmocom.org/laforge/tmp/20180405-pretix.cfg

**Comment by raphaelm** [comment]
In fact, it probably does. Even though it shouldn't be, this *might* actually be due to the fact that you're using a custom URL for static files (``/pretix/static/`` instead of ``/static/``). Changing this in fact requires re-compression unfortunately. Is there a special reason for you not using the default path here? (I'm aware that it should still work, but for now, this might help.)
