### ISSUE TITLE
Correctly format variation price

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#2449]
Right now, prices in the variation-accordeon in pretixcontrol are only displayed based on the raw value in the input field.

Depending on the amount of effort given by the user when entering those prices, they might have anywhere from zero to n decimals:
![Screenshot from 2022-02-04 16-51-38](https://user-images.githubusercontent.com/654548/152559962-dc557e4e-a116-4231-bd6c-b948bac2c442.png)

I don't see this as a burning issue but rather as a small UI improvement to have a properly formatted decimal value there and perhaps event a currency symbol.

https://github.com/pretix/pretix/blob/c65883b32889a1fa6c022a177a01a79f6bde17da/src/pretix/static/pretixcontrol/js/ui/variations.js#L10-L14

**Comment by raphaelm** [comment]
I don't really want to re-implement all of babel's currency output in javascript… but yes, decimal format would be nice :)

**Comment by wiffbi** [comment]
What about [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)? Of course IE does not have it, but when its available, we could/should use it. `body[data-pretixlocale]` and `<input> + .input-group-addon` for the currency is already available, so I could look into this.
