### ISSUE TITLE
Max Ticket Amount per Order not working

### ISSUE THREAD

**Issue by choseh** [pretix/pretix#2452]
Max amount is set to 0 in my setup, but the shop does not allow more than one. Changing the value to something > 0 works (e.g. 2,3, etc.), but 0 only allows 1 Ticket.

The max amount field also accepts values like -1, which might actually break things in a worse way, just a side note though.

pretix version 4.6.0

![image](https://user-images.githubusercontent.com/5830192/153158048-0a6e9b68-e2d7-4500-8855-0922478cf895.png)
![image](https://user-images.githubusercontent.com/5830192/153158515-39be2126-cffc-484a-944c-b98d4b97ff7d.png)

**Comment by raphaelm** [comment]
Could you maybe just keep the field empty? Not sure what the correct behaviour for 0 should be. We should probably limit the field to values of 1 or higher

**Comment by choseh** [comment]
Hi Raphael,

leaving it empty shows the same behavior (1 ticket max).

Best,
Alex

**Comment by wiffbi** [comment]
Could you check your settings regarding max. number of products in cart (Einstellungen => Allgemein => Tab „Warenkorb“)? I can only get it to work the way you describe it when I set the maximum number of products in the cart to 1. Then leaving max. ticket amount per order on the product empty or 0, it defaults to max number of products in cart.

Two things:

1. obviously this is a config error, but should we check in presale if max. num in cart is smaller than max. num in products?
2. max. as well as min number of products on products settings should be an `<input type="number">` as it is on the cart settings.

I will fix the number input (2). Regarding (1) let me know, what you think, we should do.

**Comment by raphaelm** [comment]
> obviously this is a config error, but should we check in presale if max. num in cart is smaller than max. num in products?

I don't think so. Since these two configs are in different places, it would be annoying if you would need to change them in a specific order to get around the vlaidation.

> max. as well as min number of products on products settings should be an <input type="number"> as it is on the cart settings.

fine with me

**Comment by wiffbi** [comment]
> > obviously this is a config error, but should we check in presale if max. num in cart is smaller than max. num in products?
> 
> I don't think so. Since these two configs are in different places, it would be annoying if you would need to change them in a specific order to get around the vlaidation.

Sorry, I wasn’t clear. I meant, should we check in pretix-presale (not in pretix-control when editing config) to limit number-inputs to `min(ev.max_items_per_order, item.max_per_order)`? This does not prevent a misconfig, but it helps users not entering to add 5 products and then get an error-message that only 3 products total are allowed in basket. It is a tiny edge-case, I know, and probably not worth it as it is already handled server-side.

**Comment by choseh** [comment]
> Could you check your settings regarding max. number of products in cart (Einstellungen => Allgemein => Tab „Warenkorb“)? 
Okay, my bad, I forgot there's a second setting for this. This is indeed set to 1.

**Comment by wiffbi** [comment]
> > Could you check your settings regarding max. number of products in cart (Einstellungen => Allgemein => Tab „Warenkorb“)?
> 
> Okay, my bad, I forgot there's a second setting for this. This is indeed set to 1.

No problem. Thanks for pointing out that negative inputs are possible in those fields, which indeed has the side-effect of the product not being available for purchase. Fix is on the way.
