### ISSUE TITLE
Hard-coded constraint for shredding data

### ISSUE THREAD

**Issue by hansegucker** [pretix/pretix#2456]
**Describe the bug**
The number of days after which admins are allowed to shred personal data of an event is hard-coded to 30 days. But some times there are scenarios like using Pretix just for Covid 19 contact registration in which shredding between 21 and 30 days after the event would be necessary.

**Expected behavior**
There should be a setting or a configuration option to change the number of days.

**Additional context**
Affected lines: https://github.com/pretix/pretix/blob/master/src/pretix/base/shredder.py#L65

**Comment by raphaelm** [comment]
we might just want to soften the limit to "as soon as the event is over", there is no good reason for the 30/60 days. I think the original idea was just too prevent people from accidentally deleting data before they really know if they'll need it again

**Comment by hansegucker** [comment]
If you agree with this solution, I could provide a fix for that.

**Comment by raphaelm** [comment]
Yes, fine with me!
