### ISSUE TITLE
pretix docker setup does not cope with updating/restarting redis

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#2476]
**Describe the bug**

I woke up to cron failure mails stating that connecting to redis failed:
```
File "/usr/local/lib/python3.9/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 2 connecting to unix socket: /var/run/redis/redis.sock. No such file or directory.
```

Looking at redis-server.service, I can see that unattended-upgrades restarted it:

```
● redis-server.service - Advanced key-value store
     Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-02-20 06:45:08 UTC; 2h 50min ago
```

Restarting pretix in docker makes things work again, but ideally pretix should survive a redis restart.

Speculation: perhaps the `-v /var/run/redis:/var/run/redis` docker volume is the problem somehow? Not entirely sure.

**Comment by raphaelm** [comment]
My guess would be that the redis restart causes /var/run/redis to be removed and recreated entirely, which causes the docker volume mount to reference the wrong inode. I'm not sure how we could work around this other than switching to a TCP-based setup which is hard to get right for inexperienced users security-wise?

**Comment by stapelberg** [comment]
I’m not sure why /var/run/redis is re-created, but it would explain the symptom.

I agree that switching to TCP isn’t great. An alternative might be to use a more persistent path for the redis socket file, but I’m not entirely sure how feasible that is. Another alternative might be to change the pretix systemd unit to restart when redis restarts? Not entirely sure how feasible that is either, just spitballing :)

**Comment by raphaelm** [comment]
> I agree that switching to TCP isn’t great. An alternative might be to use a more persistent path for the redis socket file, but I’m not entirely sure how feasible that is.

Yeah, you could e.g. configure redis to put its socket to a `/var/pretix/redis/redis.sock` instead and make sure that directory exists permanently, but that would require (a) changing redis config file (b) changing redis systemd unit to allow it to access the directory (c) changing the docker line. I'm not sure it's over the top for the install guide given (b).

> Another alternative might be to change the pretix systemd unit to restart when redis restarts? Not entirely sure how feasible that is either, just spitballing :)

That should be solvable with a `PartOf=redis.service` in `pretix.service` if pretix is started by systemd, I guess.

**Comment by stapelberg** [comment]
I tried `PartOf=redis-server.service`, which propagates `stop` and `restart`.

Unfortunately, Debian maintainer scripts first `stop` the service, install the new package, then `restart` the service.

With `PartOf=` configured, this means `systemctl stop redis-server.service` will stop pretix as well. But: `systemctl restart redis-server.service` will not bring pretix back up!

---

Instead, I think I found an easier alternative: creating the following snippet using `systemctl edit redis-server`:
```
# /etc/systemd/system/redis-server.service.d/override.conf
[Service]
# Keep the directory around so that pretix.service in docker does not need to be
# restarted when redis is restarted.
RuntimeDirectoryPreserve=yes
```

This way, I can stop and restart redis, and the pretix Docker container can keep running :)

Maybe `RuntimeDirectoryPreserve=yes` should be recommended in the install guide?
