### ISSUE TITLE
Privacy page shows icon from empty content section

### ISSUE THREAD

**Issue by pReya** [pretix/pretix#2521]
**Describe the bug**
When viewing the privacy page of an event, there seems to be an empty content block, where only the credit card icon is shown. I assume there will be content when a certain feature is activated for this event (not sure which feature this is). Anyway, if the text is not shown, the icon should probably be hidden, too.

**Expected behavior**
The icon should not show up. The whole block should not be visible.

**Screenshots**
<img width="1042" alt="Screenshot 2022-03-08 at 17 54 00" src="https://user-images.githubusercontent.com/4677417/157287149-ade72196-8d3b-4c1f-83b4-489c6ed9dcda.png">

**Additional context**
Latest Firefox on latest mac OS.

**Comment by wiffbi** [comment]
This might be due to a payment provider, that is not yet added to the automatic privacy page. Would it be possible for you to disclose, which payment provider plugin you use?

**Comment by pReya** [comment]
No additional providers, just the default settings.
<img width="1180" alt="Screenshot 2022-03-09 at 10 51 13" src="https://user-images.githubusercontent.com/4677417/157416896-5b6379a9-5e25-4b5e-acfd-9f71c6bdae5a.png">

**Comment by wiffbi** [comment]
Thanks for letting me know. I will look into this.

**Comment by wiffbi** [comment]
Is fixed and about to be deployed.
