### ISSUE TITLE
Always allow creating manual refunds when canceling events

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2522]
We have come in the situation that we needed to cancel an event and refund a large number of payments. Using the new method described in https://pretix.eu/about/en/blog/20200309-cancelling/ we wanted to create mass refunds. However, in our case our payment method supports automatic refunds, however in the most cases does not support immediate refund for all users, as it requires funds to be available in the payment provider. 

Instead, I'd like to use the option "Create manual refund if the payment method does not support automatic refunds" in all cases.

I'd be happy to create a pull request :)

**Comment by raphaelm** [comment]
I'm not sure I fully understand the need yet. Creating manual refunds for all orders would mean you are not using the refund capabilities of your payment provider at all?

Wouldn't it be a solution to just not create any refunds at all and work through the list of overpaid orders?

I have a feeling this might be too special-case to introduce additional complexity for, given that the event cancel interface is already hard and scary to understand for new users

**Comment by MaicoTimmerman** [comment]
> I'm not sure I fully understand the need yet. Creating manual refunds for all orders would mean you are not using the refund capabilities of your payment provider at all?

Correct. The total amount of refunds needed is not available, as the payment provider has already paid out to the bank account. Unfortunately, the payment provider does not support depositing funds for refunds into the account.

> Wouldn't it be a solution to just not create any refunds at all and work through the list of overpaid orders?

That is indeed what we have done in this case. However, doing it on a per-order basis is an extremely inefficient process. Per order we need to:
1. Navigate to the order
2. Initiate a refund
3. Copy the payment amount to the "Manual refund"
4. Mark the refund in the refund overview done after the bank transfers have been made.
Given that we are canceling events with dozens of orders, this will take long time and a lot of manual effort.

> I have a feeling this might be too special-case to introduce additional complexity for, given that the event cancel interface is already hard and scary to understand for new users

We already resort to creation of manual payments, when payment providers does not support refunds. I'd like to be able to do that in all cases, unconditionally.

**Comment by raphaelm** [comment]
>  I'd like to be able to do that in all cases, unconditionally.

I understand, but I want to to not introduce more checkboxes that users need to read and understand :wink: I'm not saying I won't move on this, but I want to at least think through all possible alternatives first.

Would "create a manual payment if the automatic payment fails" be an automatism that would work properly in your case?

I'm not sure it would be helpful in all other cases, though, that would require some additional thought.

**Comment by MaicoTimmerman** [comment]
> I understand, but I want to not introduce more checkboxes that users need to read and understand wink I'm not saying I won't move on this, but I want to at least think through all possible alternatives first.

Of course :)

> Would "create a manual payment if the automatic payment fails" be an automatism that would work properly in your case?
> I'm not sure it would be helpful in all other cases, though, that would require some additional thought.

I'd have to do some testing, however on first look it looks like the  `manual_refund` would almost directly function. However, currently it is conditioned on `auto_refund`:

https://github.com/pretix/pretix/blob/86d28b3f21af0052b42c017acabb1af6640df605/src/pretix/base/services/cancelevent.py#L275-L279

Given that's the case, could we do by adjusting the description and removing the dependency and allow the same functionality to skip the automatic creation of refunds:

https://github.com/pretix/pretix/blob/86d28b3f21af0052b42c017acabb1af6640df605/src/pretix/base/services/orders.py#L2440-L2444

Which would not introduce any new checkboxes for the end user.

**Comment by raphaelm** [comment]
That sounds reasonable
