### ISSUE TITLE
Voucher-counting returning True/False

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#253]
The tag-counting of vouchers seems two have two issues at the moment:

- No voucher has been used yet:
`False/<Number of Vouchers>` instead of `0/<Number of Vouchers>`

- Some other bug, if some vouchers have already been redeemed (cannot put my finger on, when this happens/why this happens):
`True/<Number of Vouchers>` instead of `<Number of used Vouchers>/<Number of Vouchers>`

Second item can be observed at the moment for example for budapest.

**Comment by raphaelm** [comment]
``True`` seems to be ``1``. As I can't reproduce this locally, this *might* be MySQL-specific.

**Comment by rixx** [comment]
[It is](https://code.djangoproject.com/ticket/24662)
