### ISSUE TITLE
Widget close icon is not centerd relative to its circular background

### ISSUE THREAD

**Issue by pReya** [pretix/pretix#2531]
**Describe the bug**
The close icon for the Pretix widget is not centered inside its background circle.

**Expected behavior**
The x icon should be centered within its surrounding circle. My suggestion would be to use the following approach:

```css
.pretix-widget-frame-close a {
    height: 100%;
    display: flex;
    justify-content: center;
}
```

P.S.: On a related note, the close icon currently uses a `<a href="#">...</a>`, which semantically is not very nice. Since this is a JS-only link that [does not trigger any navigation](https://weblog.west-wind.com/posts/2019/Jan/21/NonNavigating-Links-for-JavaScript-Handling), it should not use the `<a>` tag, but rather use a `<button>` or just a `<div>` with an `onClick` handler.

**Screenshots**
<img width="544" alt="Screenshot 2022-03-14 at 11 38 39" src="https://user-images.githubusercontent.com/4677417/158156806-c1fd0072-fb38-4765-9621-c46b8240d0f8.png">

**Additional context**
Recreated both in latest Firefox and latest Chrome on latest macOS.

**Comment by wiffbi** [comment]
I have not double checked but it looks like some styling of the embedding website is overwriting that element’s styling partially. On the one hand, this is intended behaviour – being able to style it to your websites looks. On the other hand, it should not break.

You are absolutely right, this element should not be a link, but a `<button>`.

The problem I see when fixing this: for existing installations that use the widget and customized this control, this will be a breaking change. I am not sure, how many users of the widget actually customized this close-control though. @raphaelm  do you have any opinion on this?

**Comment by pReya** [comment]
@wiffbi Thanks for pointing me in that direction. Indeed, the parent page has `font-size` and `line-height` set, which creates this problem. I will work around it. Sorry for blaming this on the widget. Feel free to close this, or a keep it as a reminder/issue for the semantic problem (`a` vs. `button`)

**Comment by vchrisb** [comment]
I have the same issue and the body has configured `line-height`.
IMHO being configured at the body level, it is not overwriting the pretix styling but rather the pretix css isn't setting a value for it?
```
.pretix-widget-frame-holder .pretix-widget-frame-close a {
    color: white;
    font-weight: bold;
    font-family: sans-serif;
    text-decoration: none;
    padding: 4px 0;
    display: block;
}
```

**Comment by wiffbi** [comment]
Thanks for the hint regarding line-height. I used a fixed line-height of 16px instead of 1em as the SVG-icon is fixed in 16px height and changing the font-size would result in a wrong line-height when using 1em.

**Comment by pReya** [comment]
@wiffbi Semantics is still an open issue. It should be a button, not a link.

**Comment by wiffbi** [comment]
Yes, you are right, semantically this should be a button. But as the widget and that close-link/button is embedded inside other webpages I am a bit cautious about changing HTML elements, which could cause custom styles and custom JS to break. I will create an issue for this and will discuss with the team.

**Comment by pReya** [comment]
> Yes, you are right, semantically this should be a button. But as the widget and that close-link/button is embedded inside other webpages I am a bit cautious about changing HTML elements, which could cause custom styles and custom JS to break. I will create an issue for this and will discuss with the team.

It just requires a button-specific reset – just like you did with the line-height. Should only be 4-5 lines of CSS to remove default styles from the button.

Would be nice if this could be implemented – it's an accessibilitiy issue, and typically these never get prioritised :(

**Comment by wiffbi** [comment]
The CSS-reset on the button is not the problem. As mentioned in the comments of #3174 the problem is users of our widget, that style the close button themselves or even listen to a click-event on that `<a>`-element – replacing that with a `<button>` would break their code, so we decided on `role=button`. Not ideal, but hopefully better than nothing.
