### ISSUE TITLE
Tag filtering, again

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#256]
Substring search in tags is great! … Except when it isn't.

If you have a category `free` and a category `freebies`, and you look at them in the tag overview to see their usage, and then click on `free` to see which vouchers are in there … you'll naturally get vouchers of both `free` and `freebies`. For a better user experience pretix should probaby differentiate between _showing_ a tag and _filtering_ by tags.

**Comment by raphaelm** [comment]
This is what I originally intended with the tag filter... I originally deliberately did not do substring matching in the "tag" input field, but also matched for tag substrings in the "search" field. But apparently, that was unclear in the UI and everyone expected the "tag" field to do substrings again. So yeah, we need a different way for this.

**Comment by rixx** [comment]
So if pretix were to differentiate between search and a tag view, there'd be some nice things it could do:

 - when filtering: highlight the matched part of a tag
 - when selecting: show usage stats above matches, and show the tag name more prominently
 - when selecting: maybe pre-fill the voucher creation form with the correponding tag when coming from here

I *think* the most natural thing would be to keep the filtering in the "All vouchers" tab, and move the selection process to the "Tags" tab.

**Comment by raphaelm** [comment]
Agreed.
