### ISSUE TITLE
Text not aligned in definition lists

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#2572]
**Describe the bug**
`dd` and `dt` in a definition list don't have the same baseline for text.

**Expected behavior**
Text on the same line is aligned on the same baseline.

**Screenshots**
<img width="176" alt="Bildschirmfoto 2022-04-04 um 12 36 39" src="https://user-images.githubusercontent.com/22835/161527290-a55e06a2-a270-45af-8929-5fde9eb98e38.png">

**Additional context**
This is on the `checkout/confirm` screen, I'd guess this is the case for all `dl`.

**Comment by TheHotatoPotato** [comment]
hi, has this issue been assigned? if not you may assign it to me.

**Comment by thegcat** [comment]
Can't reproduce currently, I think this can be closed.
