### ISSUE TITLE
Cached widget files should be ignored after version upgrade.

### ISSUE THREAD

**Issue by MaicoTimmerman** [pretix/pretix#2625]
**Describe the bug**
I upgraded from Pretix 4.8 to 4.9, which contained changes to the widget.js. These were not available until I wiped redis keys `widget_js_data_*`, `:1:hierarkey_global__global` and database global settings `widget_file_*`.

**Expected behavior**
Include some kinds of versioning in the caching of widget.js (and probally widget.css as well).

**Screenshots**

**Additional context**

**Comment by raphaelm** [comment]
How certain are you, that you executed the "updatestyles" command successfully after the upgrade?

It contains all required logic to so this
https://github.com/pretix/pretix/blob/master/src/pretix/presale/management/commands/updatestyles.py#L65-L82

So far it has not failed us in production

**Comment by MaicoTimmerman** [comment]
Our installation is based of the docker image `pretix/standalone`, so most likely I've never ran `updatestyles` during upgrades as the schema updates did actually happen automatically.

I missed the https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#updates section here. Thanks!
