### ISSUE TITLE
Stripe + Bancontact : Abandoned payement never expires

### ISSUE THREAD

**Issue by aethernet** [pretix/pretix#2629]
**Describe the bug**
When a user start a Payment using Bancontact (Stripe) but doesn't finish transaction the order stays "pending" and is never cancelled (even after the timeout period specified in the payment panel)

**Expected behavior**
The order should expire after the timeout period.

**Additional context**
Manually mark  the payment as failed is not enough (stays in "Pending" state), only solution is to "cancel" the order (without sending an email because most of the time the user has re-ordered and succeed and if he receive a cancellation order with another order id, he's super confused).

Reasons for not finishing transaction might be he's not redirected to his bank due to popup blocker, or his bank ask for a code from a digipass he doesn't have with him, or ...)

Note that the transaction doesn't appear at all on stripe backend (not even pending).

Capture with credit card, works as intended with the same stripe account.

**Workaround**
Made a script that call the api to get the all the pending orders and cancels the ones that are older than my timeout.

**Comment by aethernet** [comment]
More context : 

I see in Stripe that the webhook has been called with a type `source.failed` message with this payload : 

```
{
  "id": ["evt_***********4"](https://dashboard.stripe.com/events/evt_1K**********4),
  "object": "event",
  "api_version": "2020-08-27",
  "created": *************,
  "data": {
    "object": {
      "id": ["src_1****************A"](https://dashboard.stripe.com/sources/src_1*********A),
      "object": "source",
      "amount": 5110,
      "bancontact": {
        "bank_code": null,
        "bic": null,
        "bank_name": null,
        "iban_last4": null,
        "statement_descriptor": null,
        "preferred_language": null
      },
      "client_secret": "src_client_secret_*********I",
      "created": *********2,
      "currency": "eur",
      "flow": "redirect",
      "livemode": true,
      "metadata": {
        "order": "4***",
        "event": "174",
        "code": "T****"
      },
      "owner": {
        "address": null,
        "email": null,
        "name": "S*************",
        "phone": null,
        "verified_address": null,
        "verified_email": null,
        "verified_name": null,
        "verified_phone": null
      },
      "redirect": {
        "failure_reason": "user_abort",
        "return_url": "https://**********/2022/stripe/return/***/**********************3/5018/",
        "status": "failed",
        "url": "https://hooks.stripe.com/redirect/authenticate/src_1******************?client_secret=src_client_secret_*********************"
      },
      "statement_descriptor": "2022-*****************",
      "status": "failed",
      "type": "bancontact",
      "usage": "single_use"
    }
  },
  "livemode": true,
  "pending_webhooks": 1,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "source.failed"
}
```

And the order stays "pending"

**Comment by raphaelm** [comment]
If pretix does not mark orders as "expired" as the timeout, this is unrelated to whatever payment method might be in use.

Are you sure your pretix cronjob is running correctly?

Can you post a screenshot of the settings at Settings > Payment > Deadlines?

**Comment by aethernet** [comment]
Sure, here it is : 

<img width="1192" alt="Pretix_Settings" src="https://user-images.githubusercontent.com/447631/166522278-7656b26f-0e69-4694-ad10-0e21b7558fea.png">

I'm running Pretix in a docker, I'll look at that cronjob, looks like the right direction.

**Comment by aethernet** [comment]
Ok, just found the docs for it, completely overlooked it while i set the whole thing up.

Thank you so much for pointing me to it :)

**Comment by raphaelm** [comment]
Perfect :)

**Comment by aethernet** [comment]
yes it works 👍 

Thanks again !
