### ISSUE TITLE
Mail sender config is ignored after upgrade to 4.8

### ISSUE THREAD

**Issue by marcoacierno** [pretix/pretix#2634]
**Describe the bug**

The "system" sender specified in the django settings is ignored and not used

We have in our settings (https://github.com/pythonitalia/pycon/blob/main/pretix/settings.py)

```
MAIL_FROM = SERVER_EMAIL = DEFAULT_FROM_EMAIL = "noreply@pycon.it"
```

but in the UI and when sending emails it still uses `pretix@localhost`.

The django settings seem correct (shell on the docker container):

```python
In [1]: settings.SERVER_EMAIL
Out[1]: 'noreply@pycon.it'

In [2]: settings.MAIL_FROM
Out[2]: 'noreply@pycon.it'

In [3]: settings.DEFAULT_FROM_EMAIL
Out[3]: 'noreply@pycon.it'
```

**Expected behavior**

It should use the system setting noreply@pycon.it

**Screenshots**

![image](https://user-images.githubusercontent.com/3382153/167250584-245c210c-97b4-4ed9-8b9d-4fe4ebb9d840.png)

**Additional context**
It started happening after upgrading to 4.8 from 4.4

Our first log showing the error is around 2022-04-25 10:47 
The upgrade happened at April 23rd, 2022 9:48 PM

We didn't receive any order between the 23 Apr and 25 Apr but the first order on 25th triggered the error, so I assume the bug was caused by the upgrade

I tried restarting the docker container in case it was a random issue but still nothing

**Comment by raphaelm** [comment]
Changing settings.py is not officially supported or documented and hence there are no warnings if changes are needed after the update. We introduced new variables, see

https://github.com/pretix/pretix/blob/master/src/pretix/settings.py#L217-L219
