### ISSUE TITLE
Pretix Bug with Embedable Widget - Quantity Selector

### ISSUE THREAD

**Issue by Dragonstyl444** [pretix/pretix#2649]
Hi, i got following bug while using the pretix embeddable widget.

The error is: if i want to sell for example just 2 Tickets for a VIP Area, it will not work because if someone buys 1 Slot the quantity selector disappears and the normal shopping cart is not showing up as it is in the regular Shop.

https://vimeo.com/710103114

**Comment by raphaelm** [comment]
pretix in some cases renders a checkbox (if there can be no more than 1 ticket selected), however your website (I looked at the URL visible in the video) includes CSS to hide all checkboxes:

```
input[type="radio"],
input[type="checkbox"] {
	display:none;
}
```

in https://endorphine.events/wp-content/themes/apollo/style.css

**Comment by Dragonstyl444** [comment]
Thank you for the quick response! :)

Raphael Michel ***@***.***> schrieb am Mo. 16. Mai 2022 um
09:30:
