### ISSUE TITLE
Call celery tasks not before the end of a transaction

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#267]
See: https://blog.hypertrack.io/2016/10/08/dealing-with-database-transactions-in-django-celery/

Currently this is solved in some places by a timeout, e.g. invoices.py in the last line

**Comment by rixx** [comment]
[services/invoices.py](https://github.com/pretix/pretix/blob/master/src/pretix/base/services/invoices.py#L400), that is.

**Comment by raphaelm** [comment]
fixed in #268
