### ISSUE TITLE
If I brute force a voucher or found a hack to let me buy a ticket, will anyone be really mad?

### ISSUE THREAD

**Issue by cptfoo** [pretix/pretix#269]
I have went for the last 3 years, I usually volunteer but do not typically volunteer enough to get shirts and I'm a loner so I'm not part of any hacking oragnziation in Germany. I'm also kinda an outsider since I moved here from California, but not for that startup bullshit, I just work on open source projects I think are fun.

I don't have a voucher and I'm worried I won't get a ticket, if I brute forced a voucher in the DB or found another way to hack a ticket would anyone be truly offended by that?

**Comment by raphaelm** [comment]
Hey @cptfoo,

please note that this is the issue tracker of pretix, a free software that can be used to run conference sales. This is *not* a Q&A forum for the 33rd Communication Congress ticket sale. If you want to contact the 33c3 team, please write to 33c3-tickets@cccv.de.

If you do find a security-relevant issue in pretix, I politely ask you not to disclose it in public but privately to support@pretix.eu or me personally (GPG keys can be found on the usual keyservers) such that we can fix it in an appropriate way.

Cheers
rami

**Comment by cptfoo** [comment]
Ack, sorry for cluttering the issues
