### ISSUE TITLE
Display correct expiry timestamp

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#273]
An order expires after a day is over - the time of the `DateTimeField` is ignored. We could:

 - always show midnight (`23:59`) next to the expiry date
 - show only a date
 - show and save only a date (migrate to DateField)

For a more complete solution, I'm in favor of migrating to a `DateField` and renaming the field to `valid_until` instead of `expires` (which is ambiguous on if the date is included or excluded).

If you don't want that, I'd be all for getting only a date as user input and then displaying the time next to it (to prevent confusion as to the exact time of expiry: "Expires on [date]" sounds, to me, like it might be expired at the beginning of the day).

**Comment by raphaelm** [comment]
I see two valid options:
* Use a ``DateTimeField`` but let the user only edit the date and always *set* the time to 23:59 (in the event's timezone)
* Use a ``DateField`` and make clear that the expiry happens at the end of the day (I'm fine with renaming the field)

I don't want to have a time saved in the database that is then ignored.

**Comment by raphaelm** [comment]
I believe the first approach is easier in terms of timezone handling, so I'd recommend that (although I'd also merge a patch using the other approach).
