### ISSUE TITLE
Disable weekends in datetimepicker for expiry

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#274]
… if `payment_term_weekdays` is set. The datetimepicker accepts a `daysOfWeekDisabled` option for this purpose.

**Comment by chrisdamba** [comment]
Could pick this up if that's ok?

**Comment by raphaelm** [comment]
Sure, go ahead! :)

**Comment by chrisdamba** [comment]
@rixx This may sound silly but how do I pass the `payment_term_weekdays` context variable into the main.js file where the datetimepicker plugin is initialised?

**Comment by raphaelm** [comment]
@chrisdamba it isn't, there is no obvious solution for that. But we had the problem before e.g. with the date formats and we solved it like this:

* in ``pretix/control/context.py`` we pass the variable to the template
* in the ``pretix/control/templates/pretixcontrol/base.html`` we set it as a data attribute to the ``<body>`` tag
* we then read it from there with javascript

**Comment by chrisdamba** [comment]
Thanks @raphaelm for the workaround, that's quite helpful
