### ISSUE TITLE
ALT attributes missing in mails for img

### ISSUE THREAD

**Issue by ligi** [pretix/pretix#2760]
I tested mails send out via pretix with https://www.mail-tester.com and it complains some (3) images do not have alt attributes (and removes -0.5 points) - I think it would be nice to add these attributes

**Comment by wiffbi** [comment]
Thanks for reporting the missing alt-attributes. I can replicate with the default email-template. It is the half-circle images at the top and bottom as well as the line-seperator. I will add `alt=""` as these images are purely decorative.
