### ISSUE TITLE
Confusing template settings for incomplete payment mails

### ISSUE THREAD

**Issue by julianrother** [pretix/pretix#2819]
The built-in banktransfer plugin reuses the `mail_text_order_expire_warning` setting ("Payment reminder" on "E-mail" event settings page) for incomplete payment mails. This is not really obvious and conflicts with what the help text says:

![127 0 0 1_8000_control_event_test_test_settings_email](https://user-images.githubusercontent.com/18755629/192541083-d190e45d-4a4f-4d1e-a883-d58a296a2a7f.png)

In our case, we believed that the template would not be used at all, if we set "Number of days" to 0 and cleared the template instead of customizing it. To our surprise, the banktransfer plugin then sent out a few empty mails regarding incomplete payments.

I'd be happy to contribute a fix for this, if you want. I see three options:
- Extend the help text for the existing setting
- Add a seperate mail template for incomplete payments to the "E-mail" event settings page (that is only used by the banktransfer plugin)
- Add a seperate mail template for incomplete payments to the plugin's payment method settings page

I think the second option has the best user experience and discoverability. What do you think?

### Version

v4.12.0

**Comment by raphaelm** [comment]
Sorry for the silence. I agree that the second option is best!
