### ISSUE TITLE
Unexpected message appears after upgrade to 4.13

### ISSUE THREAD

**Issue by fhoner** [pretix/pretix#2856]
### Problem and impact

After the upgrade from 4.12 to 4.13, on the public list of events view an unexpected message appears. 
However when installing a fresh instance with 4.13 this does not seem to appear. When I restore our database, the message shows up again.
A downgrade to 4.12 (running via docker) caused the message to disappear again.

### Expected behaviour

The public shop view should remain the same like it was before the upgrade.

### Steps to reproduce

1. Having 4.12 running as docker container (maybe its related to specific settings we have?)
2. Replace the container by a new one running 4.13

### Screenshots

![Screenshot 2022-10-15 at 11 53 25](https://user-images.githubusercontent.com/16558026/195980447-ffdc6414-3bb8-4a23-8f0b-163ee7472940.png)

### Browser (software, desktop or mobile?) and version

Chrome, Safari

### Operating system, dependency versions

Ubuntu 20.04, macOS 12

### Version

4.13

**Comment by raphaelm** [comment]
You very likely did non run all steps of the upgrade procedure:
https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#updates

**Comment by fhoner** [comment]
Hi Raphael, thank you very much, that did the trick. keep up the good work with pretix!
