### ISSUE TITLE
After upgrading to the latest version, the app displays a broken popupmodal

### ISSUE THREAD

**Issue by burningtree** [pretix/pretix#2864]
### Problem and impact

I upgraded from version 4.12 to the latest 4.13.1 and all the stores started showing a weird html snippet "popupmodal" at the bottom of the page

I use deploy via Docker 

### Expected behaviour

Normally, I would expect this modal to be hidden and only show up when needed

### Steps to reproduce

It happened when upgrading to 4.13.1, if I downgrade for example to 4.12.9 the problem disappears

### Screenshots

<img width="904" alt="Screenshot 2022-10-24 at 11 23 25" src="https://user-images.githubusercontent.com/67269/197493680-6f468263-c519-4be2-802b-b43c8169e02b.png">

### Link
It's happening at all the stores 

- https://proxy-tickets.ethbrno.cz/
- https://tickets.ethbrno.cz/

### Version

4.13.1

**Comment by burningtree** [comment]
So I temporarily solved it by removing the "sso.js" file in the Dockerfile

Looks like this file will make the modal visible even if it doesn't have

```dockerfile
RUN rm /pretix/src/pretix/static/pretixpresale/js/ui/sso.js
RUN touch /pretix/src/pretix/static/pretixpresale/js/ui/sso.js
```

**Comment by raphaelm** [comment]
Did you run the "pretix upgrade" command?

https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#updates

**Comment by burningtree** [comment]
> Did you run the "pretix upgrade" command?
> 
> https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#updates

Uh. No.

I assumed that Pretix behaves like most Dockerized applications - that is, the migration is triggered automatically.

After running that command, the problem seems to be solved.

So I apologize for the misunderstanding. Thanks

**Comment by raphaelm** [comment]
Yeah, it's not perfect, but it's hard to prevent the migration from running multiple times in a setup where multiple instances of the docker container are running
