### ISSUE TITLE
Download reminder email

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#293]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

It would be nice to -- optionally -- send out emails a few days before the event that remind people to download their tickets.

## How to do this

There are basically three things that need to be done:

* If you go to Settings → Email in the control panel of a pretix event, you see a number of content text snippets that you can configure. You will need to add a new text there, find out how ;) If you don't find it, just ask, I can provide more detailled guidance.
* We need to have a new [model](https://docs.djangoproject.com/en/1.10/topics/db/models/) field in the ``Order`` model that stores if the mail has already been sent out
* We need to actually send out the emails. This can be very done very similar to the ``send_expiry_warnings`` in ``pretix/base/services/orders.py``.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by saurabhgoyaliitr** [comment]
Sure. I would start with this one.

**Comment by raphaelm** [comment]
Hi @saurabhgoyaliitr, have you tried anything yet? Anything I can help with?

**Comment by AV-room** [comment]
Hey @raphaelm - can I give this one a go? :)

**Comment by raphaelm** [comment]
Sure, go ahead! :)

**Comment by SanketDG** [comment]
Hi, I have been [working](https://github.com/SanketDG/pretix/commit/23ea414dac56f4bd11eb38d4532cfff65a2a6986) on this issue, and I haven't been able to figure out how to send the email.

It would be of great help if you can guide me through it. :smile:

**Comment by raphaelm** [comment]
Hi @SanketDG, can you phrase your question a bit more specifically? I already see a call to mail() in your code so I'm not sure from the top of my head where the problem is

**Comment by SanketDG** [comment]
> can you phrase your question a bit more specifically

oops sorry about that

The things is I just copied the previous function `send_expiry_warning`, and renamed it, I haven't changed basically anything inside the functions, so if I could understand what the `send_expiry_warning` is doing, that'd be great.

**Comment by SanketDG** [comment]
Hi, I have updated the [commit](https://github.com/SanketDG/pretix/commit/0b7647c9fd30c0e3bfd06e2787a5c1f75de37ef6), and although it is mostly complete, I am still confused about [this line](https://github.com/pretix/pretix/blob/master/src/pretix/base/services/orders.py#L461). Assuming it is indeed returning an integer, what exactly does it return?

**Comment by AV-room** [comment]
I am also working on this - should I stop and find something else to do?

**Comment by raphaelm** [comment]
Hi @AV-room, you've been here first, so if you're planning to submit a PR, I won't hold you back, @SanketDG didn't asked first (but I also didn't hold him back since I haven't heard from you here for a month) ;)

So, @AV-room, if you're nearly done with this, feel free to submit a PR; but if you haven't really started, letz @SanketDG finish their work. Unfortunately, we're a bit low on easy issues right now, I'll have to see if something comes up again :(

**Comment by AV-room** [comment]
No worries. I have been looking at this issue periodically and had a
solution mapped out, but looks like @SanketDG is much further along than I
am. I'll try to find something else.

**Comment by SanketDG** [comment]
> but looks like @SanketDG is much further along than I
> am. I'll try to find something else.

Thanks! I also saw the last comment's timestamp, and assumed that it's okay to go on with this.

I'll be careful in the future, though!
