### ISSUE TITLE
Gendered texts In "de" (not de-informal) language 

### ISSUE THREAD

**Issue by derBobby** [pretix/pretix#2932]
### Problem and impact

We have the opposite case with one of our customers in comparison to [this issue](https://github.com/pretix/pretix/issues/1421);
In the "de" (not de-informal) translation there should be no gendered german terms, e. g. for "Attendee name".

Is this a bug or has there been a change in how the topic is treated?

### Expected behaviour

Instead "Teilnehmername" should be displayed.

**Comment by raphaelm** [comment]
Yes, this has changed, we now try to gender everywhere in end-user-facing text. (We're not consistent in the backend yet and sometimes opt against it in the backend for brevity.)

If you're self-hosting pretix, you can add your own language files if you prefer.
