### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by martrobb** [pretix/pretix#2948]
### Problem and impact

Hey again!

Looking for some urgent help, our host done a whole server restart on all servers and my server was turned back on but I keep received a Internal Server Error in the pretix style/design but I didn't install it so don't know much about the SSH and docker etc. I'm good with technology but that part confuses me haha!

Any help would be appreciated, I've put an image below:
image

### Steps to reproduce

Only had the server restart.

### Screenshots

![image](https://user-images.githubusercontent.com/117538893/205640763-1000551c-c8fb-4499-a3dc-2e740ede4c39.png)

### Link

https://admin.ravergroup.com

### Browser (software, desktop or mobile?) and version

Chrome

### Operating system, dependency versions

Docker

**Comment by raphaelm** [comment]
Please open a discussion for this, not an issue, and please include logs
https://docs.pretix.eu/en/latest/admin/errors.html
