### ISSUE TITLE
Cloudflare compatibility issue when proxied

### ISSUE THREAD

**Issue by mik-kun** [pretix/pretix#2950]
### Problem and impact
When we use Cloudflare as a proxy for security, we are getting a loading circle displayed at the bottom of our ticket shop.
I already mentioned this in the Discussions section at tried various things myself https://github.com/pretix/pretix/discussions/2724

When accessing the ticket shop directly (disabling the proxy function in Cloudflare) there is no issue.

### Expected behaviour
I expect Pretix to be compatible with Cloudflare as this has become an industry standard.

Cloudflare mentiones on their documentation that they are not modifying the CSP headers
https://developers.cloudflare.com/fundamentals/get-started/reference/content-security-policies/

### Steps to reproduce
Create a Cloudflare account with your domain and enable the orange proxy cloud in Cloudflare for Pretix.

### Screenshots

![pretix-cloudflare](https://user-images.githubusercontent.com/107970619/205843640-7d902a63-f8cf-46e3-99cb-240e82898210.png)

### Browser (software, desktop or mobile?) and version
All, including desktop and mobile

### Operating system, dependency versions
All

### Version
Pretix 4.15 (Small-scale manual deployment on Ubuntu 22.04 LTS)

**Comment by yvovandoorn** [comment]
Hi @mik-kun. As a fellow Cloudflare user, turn off "Rocket Loader" or create a page-rule to turn off "Rocket Loader" for the subdomain that pretix is running on. 

Something inside of Rocket Loader is causing this. When I turned it off, this went away.

**Comment by raphaelm** [comment]
Ah, I see. Turns out Rocket Loader messes with the `script` tags which is not something we test for. Closing this, then. Thanks!
