### ISSUE TITLE
Fix DST issues with expiry

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#296]
If an order is created during daylight-saving time but its expiry date is not, it's expiration won't be exactly at 23:59.

**Comment by rixx** [comment]
This, again, would be in favour of just using dates db-side.

**Comment by raphaelm** [comment]
No, I believe using dates is *still* more complicated, as we can not use a simple ``.filter(expires__lt=now())`` any more because if we have events with different timezones on the same server they all *should* expire at different times.
