### ISSUE TITLE
pretixdroid: Show metrics in the control panel

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#297]
The pretixdroid Android app allows organizers to scan the tickets at the entrance. The date and time of those check-ins are saved and it would be nice to do at least the following things with them:

- [x] Add checkin to order log
- [x] Show list of checkins by ticket
- [x] Show number of checkins on dashboard
- [x] List of people already checked in / not yet checked in

**Comment by raphaelm** [comment]
Hi @jlwt90, if you're interested in this, please tell me if the scope of this is clear, if not, I can sure write one of my lengthier issue descriptions here :wink:

**Comment by jlwt90** [comment]
Hi @raphaelm, sorry for replying late. I just got some time checking the finished tasks in this ticket.
Could I confirm whether my direction is correct?

The api pretixdroid is calling is provided by `src/pretix/plugins/pretixdroid`. The checkin information is stored by using the following code block:
```
op.order.log_action('pretix.plugins.pretixdroid.scan', data={
                        'position': op.id,
                        'positionid': op.positionid,
                        'first': True,
                    })
```
So basically I will play around `OrderPosition`, `Checkin` & `LogEntry` and of course the event dashboard.

Could you mind explaining the last task `List of people already checked in / not yet checked in` in details? I guess it should be a separate page or sth. for admin to keep track of everyone's check-in status. When admin clicks on the `checkins` block in dashboard, he/she will be redirected to the check-in detail page. Is that what you want to achieve?

Thanks!

**Comment by raphaelm** [comment]
Hi,

> So basically I will play around OrderPosition, Checkin & LogEntry and of course the event dashboard.

I believe you won't need ``LogEntry``, ``Checkin`` should already contain all required information.

> Could you mind explaining the last task List of people already checked in / not yet checked in in details? I guess it should be a separate page or sth. for admin to keep track of everyone's check-in status. When admin clicks on the checkins block in dashboard, he/she will be redirected to the check-in detail page. Is that what you want to achieve?

Yep, that's exactly what I imagined. I think there should be a page with the check-in status of all attendees (maybe later it could be searchable etc.) and that would be perfect to link to from the dashboard tile.

This should not need to live in the pretixdroid plugin, as there will probably be more methods to generate ``Checkin`` objects later. It can just be a regular page around here: 
![2017-04-25-092259_255x283_scrot](https://cloud.githubusercontent.com/assets/64280/25373154/cdc3ce54-2998-11e7-8cee-f534d96ef56d.png)
