### ISSUE TITLE
Separate JS file for translation can make at least some pages stop working

### ISSUE THREAD

**Issue by Flameeyes** [pretix/pretix#299]
(Originally reported in a twitter conversation with @nomoketo.)

When the serving side of the app is not reliable (e.g. irregularly collapsing under load) it is possible for only part of the JavaScript to load. This can be a problem in some pages (for example the confirmation page) as the buttons actions are rebound to use AJAX, but the bound functions use interfaces defined in other JS files that might not have loaded.

In particular, during 33C3 launch I observed the "Place binding order" button not working when "/jsi18n/en/" was not loading (due to the webserver timing out.) This file is very small, and not minified, it contains some basic formatting constants and the definition of `gettext()`-style functions. Since the bound function for the AJAX request does use `gettext()`, it won't be able to find it in the loaded JS and will thus fail to execute anything at all.

To compound the issue at least in the 33C3 deployment this is the sole file that is not under `/static/CACHE`, which probably also means it's not cached client-side, so will keep failing even if once it loaded correctly. Unfortunately I didn't take a full request trace so I can't confirm this last part.

**Comment by raphaelm** [comment]
Thanks for reporting! I'll improve on failsafety here.
