### ISSUE TITLE
Order overview: Show net prices

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#301]
The order overview can currently show counts and gross prices. It should also be able to show net prices.

**Comment by rixx** [comment]
So, `[Show number | Show {currency} (gross) | Show {currency} (net)]`?

(On that note, `[Show orders | Show revenue (gross) | Show revenue (net)]` might be better wording.)

**Comment by raphaelm** [comment]
+1 for "[Show orders | Show revenue (gross) | Show revenue (net)]"
