### ISSUE TITLE
Cannot send out vouchers via CSV Email - Generated Codes do not match CSV List

### ISSUE THREAD

**Issue by choseh** [pretix/pretix#3013]
### Problem and impact

Whenever I try to send out via CSV pretix complains with this weird error message. I was trying to split it up into two batches of 100 but didn't help. What could be the issue here?

Du hast 196 Gutscheine generiert, aber nur Empfänger für 19306 angegeben.
Du hast 100 Gutscheine generiert, aber nur Empfänger für 5050 angegeben.

pretty sure the csv is well formatted.

Generated 196 vouchers, then tried to send them out via CSV Email.

"email","number","name","tag"
name@email.foo,1,Sur Lastname,Sur Lastname
name2@email.foo,2,Sur Lastname2,Sur Lastname2
[...]
until 196

### Expected behaviour

vouchers are sent out

**Comment by raphaelm** [comment]
The column number is the number of vouchers to send to this address. So

"email","number","name","tag"
name@email.foo,1,Sur Lastname,Sur Lastname
name2@email.foo,2,Sur Lastname2,Sur Lastname2

is already 3 vouchers, not two.

**Comment by choseh** [comment]
oh sh... i was expecting this to be the voucher number from the list. my bad!
