### ISSUE TITLE
Add time limits to payment providers

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#303]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

In pretix, users often can choose between different payment providers. Some payment providers (most notably bank transfer) are known to take some time. If your event comes very close, you probably want to only enable those that go dast. It would be nice if we had a setting that defines the latest date this payment provider is available, so you could do something like "allow to select credit card payments until 20.12. and bank transfer until 10.12.".

## How to do this

This can be implemented by adding a field to the default implementation of ``BasePaymentProvider.settings_form_fields`` and changing the default implementation of ``BasePaymentProvider.is_allowed()`` and ``BasePaymentProvider.order_change_allowed()`` to check for that date.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by chrisdamba** [comment]
Looking to pick this up if that's ok ;)

**Comment by raphaelm** [comment]
Sure, go ahead!

**Comment by chrisdamba** [comment]
Just a quick one, what would be the ideal label and help text for this field and is this a required field or optional?

**Comment by rixx** [comment]
Maybe something more descriptive for the help text? Such as 'The latest date this payment can be chosen by users.'?

**Comment by raphaelm** [comment]
I'd suggest
* Label: "Available until"
* Help text: "Users will not be able to choose this payment provider after the given date."
