### ISSUE TITLE
Add optional HTML version to emails

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#306]
including event logo etc.

**Comment by jfwiebe** [comment]
Google offers standardized schemas to embed event information (and even ticket data) in a structured way, that will be displayed for the users in their mail client or on their smartphone prior to the event. Maybe have a look at https://developers.google.com/gmail/markup/reference/go-to-action for adding e.g. the order link or https://developers.google.com/schemas/reference/event-reservation#event_with_ticket_no_reserved_seating to even send event information (with or without ticket secret).

**Comment by raphaelm** [comment]
I know and like this, but its not worth the effort as Google won't show them. You need to [register](https://developers.google.com/gmail/markup/registering-with-google) your domain for it and they'll only accept you if you sent on the "order of hundred emails a day minimum to Gmail". I tried already for a different project. :(

**Comment by jfwiebe** [comment]
Oh Google, why? Especially for this kind of decentral system you won't reach "hundred of mails"... My mails will be sent from my mailserver and e.g. the ccc mails will be sent by the ccc mail server.

**Comment by raphaelm** [comment]
The why is probably because they fear that this could make phising mails look more legit. But yes, your point exactly.
