### ISSUE TITLE
NREI export contains wrong paypal transaction code for refunds

### ISSUE THREAD

**Issue by blutonium** [pretix/pretix#3060]
### Problem and impact

While trying to automate our accounting I'm using the NREI export to loop trough all invoices and find the right description for IBAN-payments or the right transactionscode for paypal payments.
During this I encounter the problem, that the handling of the paypal transaction codes seems wrong in pretix. The NREI export contains the same transactionscode for both the order and the refund, which is the transaction code of the refund.

### Expected behaviour

PayPal assigns a unique code for each transaction, which is part of their .pdf or .csv exports. As pretix also saves the transaction codes it should be possible to map the invoices from pretix to the PayPal transactions. I would expect pretix to use this unique transactioncode for every single payment in their NREI exports, instead of storing the latest transactioncode for both the order and the refund.

### Steps to reproduce

Should be happen without any special settings.

### Link

https://HOST/control/event/ORGANIZER/EVENTNAME/orders/export/

### Operating system, dependency versions

Debian 11

### Version

4.14

**Comment by raphaelm** [comment]
It's inherently impossible to do a perfect mapping between invoices and PayPal transactions, as they are not at all related with each other within pretix.

For every order, pretix can have N invoices, N payments and N refunds. There is no simple 1:1 relationship.

So doing this will always be **guessing**. Maybe we could guess better than we currently do, for sure.

(To be honest, this is the first time I've heard of someone using the NREI export in **years**, glad to know it's actually useful :D)

**Comment by blutonium** [comment]
Hi Raphael,
thank you for your quick response.
I probably don't use the NREI export as it's meant to be, as I'm just parsing it with python myself, but it contains all the information I need.

However, I completely understand the tree structure a order have at the moment. As the NREI export contains not orders but "transactions" it also loops sorted trough all invoices generated by pretix, which is exactly what I can work with.
I want to point out why I think that this is not a mapping problem but a bug.

Let's take this order as an example:
![image](https://user-images.githubusercontent.com/30829664/214675028-954f5649-e3e0-4c46-8e6c-5a39edc9a01d.png)
As you can see, there's both the payment and the refund.

On our PayPal export this looks like:
`
"19.04.2022","11:16:36","Europe/Berlin","PayPal Express-Zahlung","EUR","26,00","-1,00","25,00","484,11","9SJ324910V015211D","mail@example.com","Max Mustermann","","","0,00","0,00","",""
"02.05.2022","08:51:59","Europe/Berlin","Rückzahlung","EUR","-26,00","0,65","-25,35","23,60","69W6072741829641H","mail@example.com","Max Mustermann","","","0,00","0,00","","9SJ324910V015211D"
`

While the payment is completely identical there's no payment ID shown in the webinterface for the refund.

The NREI entrys for these transactions looks like:
`
        {
            "IsValid": true,
            "Hdr": {
                "C": "DE",
                "CC": "EUR",
                "City": "Examplehausen",
                "CN": "",
                "DIC": "DE",
                "DIDt": "2022-04-19T09:16:35.245692+00:00",
                "DT": "10",
                "EM": "mail@example.com",
                "FamN": "Mustermann",
                "FN": "Max",
                "IDt": "2022-04-19T08:00:00+01:00",
                "INo": "HARDERHALLS-00295",
                "IsNet": false,
                "ODt": "2022-04-19T09:16:35.245692+00:00",
                "OID": "NGGLL",
                "SID": "harderhalls",
                "SN": "Emergenzy: The Harder Halls Alt",
                "Str": "Examplestreet",
                "TGrossA": 26.0,
                "TNetA": 21.85,
                "TVatA": 4.15,
                "VatDp": false,
                "Zip": "12345",
                "PPEm": "mail@example.com"
            },
            "InvcPstns": [
                {
                    "ADes": "Standard Ticket",
                    "ANetA": 21.01,
                    "ANo": "harderhalls",
                    "AQ": 1,
                    "AVatP": 19.0,
                    "DIDt": "2022-10-29T20:00:00+00:00",
                    "PosGrossA": 25.0,
                    "PosNetA": 21.01
                },
                {
                    "ADes": "Zahlungsgeb\u00fchr",
                    "ANetA": 0.84,
                    "ANo": "harderhalls",
                    "AQ": 1,
                    "AVatP": 19.0,
                    "DIDt": "2022-10-29T20:00:00+00:00",
                    "PosGrossA": 1.0,
                    "PosNetA": 0.84
                }
            ],
            "PmIs": [
                {
                    "PTID": "1",
                    "PTN": "PayPal",
                    "PTNo1": "9SJ324910V015211D",
                    "PTNo2": "PAYID-MJPH3NQ60S23446UP664230M",
                    "PTNo7": 26.0,
                    "PTNo8": "EUR",
                    "PTNo11": "mail@example.com",
                    "PTNo15": "NGGLL-P-1"
                }
            ],
            "ValidationMessage": ""
        },
        {
            "IsValid": true,
            "Hdr": {
                "C": "DE",
                "CC": "EUR",
                "City": "Examplehausen",
                "CN": "",
                "DIC": "DE",
                "DIDt": "2022-04-19T09:16:35.245692+00:00",
                "DT": "30",
                "EM": "mail@example.com",
                "FamN": "Mustermann",
                "FN": "Max",
                "IDt": "2022-05-02T08:00:00+01:00",
                "INo": "HARDERHALLS-00310",
                "IsNet": false,
                "ODt": "2022-04-19T09:16:35.245692+00:00",
                "OID": "NGGLL",
                "SID": "harderhalls",
                "SN": "Emergenzy: The Harder Halls Alt",
                "Str": "Examplestreet",
                "TGrossA": -26.0,
                "TNetA": -21.85,
                "TVatA": -4.15,
                "VatDp": false,
                "Zip": "12345",
                "PvrINo": "HARDERHALLS-00295",
                "PPEm": "mail@example.com"
            },
            "InvcPstns": [
                {
                    "ADes": "Standard Ticket",
                    "ANetA": 21.01,
                    "ANo": "harderhalls",
                    "AQ": -1,
                    "AVatP": 19.0,
                    "DIDt": "2022-10-29T20:00:00+00:00",
                    "PosGrossA": -25.0,
                    "PosNetA": -21.01
                },
                {
                    "ADes": "Zahlungsgeb\u00fchr",
                    "ANetA": 0.84,
                    "ANo": "harderhalls",
                    "AQ": -1,
                    "AVatP": 19.0,
                    "DIDt": "2022-10-29T20:00:00+00:00",
                    "PosGrossA": -1.0,
                    "PosNetA": -0.84
                }
            ],
            "PmIs": [
                {
                    "PTID": "1",
                    "PTN": "PayPal",
                    "PTNo1": "9SJ324910V015211D",
                    "PTNo2": "PAYID-MJPH3NQ60S23446UP664230M",
                    "PTNo7": 26.0,
                    "PTNo8": "EUR",
                    "PTNo11": "mail@example.com",
                    "PTNo15": "NGGLL-P-1"
                }
            ],
            "ValidationMessage": ""
        },
`
As you can see, the transaction ID is stored in [PMIs][PTNo1], but it is, not like on the PayPal side, identical on both transactions. To be honest, I just recognized that PayPal also stores the original transcation ID in the refund transaction, so i can probably do the mapping using this one. Sorry, I haven't seen this before. Still, I would guess that you are either saving the wrong part of the response code from paypal for the refunds or have a mapping-mismatch during the transformation from the database layout to the NREI json.

I hope I could help finding an issue, even if it's a small one like this. Probably I can work around this by recognizing the "old" transactionscodes provided by paypal in the refund line.
I'm happy to help, if there's anything i can check for you feel free to ask!

**Comment by raphaelm** [comment]
Okay, I'm sorry, but if you're using the export for anything other than importing it into the dekodi software, we're not going to make any changes based on your feedback. Their [documentation](https://manuals.dekodi.de/nexuspub/schnittstellenbuch/index.html?neues-topic2.html) does not indicate whether they are even able to handle PayPal refund transaction IDs.

Why are you not just using our API? ;)
