### ISSUE TITLE
crashed BankImportJob blocks further imports

### ISSUE THREAD

**Issue by gwater** [pretix/pretix#3064]
### Problem and impact

When a BankImportJob crashes (with HTTP Code 500), we can usually launch a new job immediately so that the transfers are uploaded.

However, after some time, no further jobs are accepted: The API returns 409 and the page displays "job currently running".

### Expected behaviour

After a few minutes a timeout should kick in, so that the crashed job does not permanently block uploads.

In fact this is also implemented but I suspect with a small typo: The check filters for "LTE" (less than or equal) not "GTE" which means jobs don'T block for 30 minutes and after that become permanently blocking

https://github.com/pretix/pretix/blob/3077292d1552d172d03a4758c579bb195c884706/src/pretix/plugins/banktransfer/api.py#L103

### Steps to reproduce

1. Insert a job with state "running" at least 30 minutes in the past into the DB.
2. Try to launch a bankimport job with banktool or web page.

**Comment by raphaelm** [comment]
Thanks, I believe you are right!

**Comment by gwater** [comment]
Thanks!
