### ISSUE TITLE
Sendmail: Log sent mails

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#307]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

If you activate the "sendmail" plugin in your pretix event, you'll be able to send out emails to all your event attendees at once (or all unpaid orders, etc).
However, you never again see what you sent. It would be nice to save those emails to the database and display them for later reference.

## How to do this

This requires to touch multiples areas of the Django framework. If you have no experience with Django, it will still be doable but probably require you to read up a bit on varios topics.

* Add a custom database model to the sendmail plugin. It should contain the email's subject, content and date as well as a many-to-many relationship to the Order model, specifiying which users exactly it has been sent to.

* Generate a database migration for this model

* Store all sent mails into the database using this model

* Show a list of the sent emails in the control panel, included or linked on the page with the mailing form

If you never heard of those before, read up on Django's models, migrations and views. Also, read how [plugins in pretix can add views](https://docs.pretix.eu/en/latest/development/api/customview.html). Be sure to also read [how to test mails without actually sending them](https://docs.pretix.eu/en/latest/development/setup.html#working-with-mails) in our developer documentation as it will make your life easier.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by FlaviaBastos** [comment]
I am currently working on this.

**Comment by FlaviaBastos** [comment]
Hey, @raphaelm!
I have a question, please: I have [some partial code done](https://github.com/FlaviaBastos/pretix/commit/438c33bbf9a94a688e382710ce0db52490342310) and while I was looking for some info on Views, I found [this doc about Logging](https://docs.pretix.eu/en/latest/development/implementation/logging.html) and now I am wondering if I should have used it to implement this feature - I'm not sure if it applies on this specific case or not....
Thanks

**Comment by raphaelm** [comment]
Hi Flavia,

no worries, everything correct. It would probably have been possible using our logging system, but using a custom model here has a number of advantages, so it's totally fine with me, just continue this way.
I'll leave a few hints in your commit about other things, though :)

Cheers
Raphael

**Comment by raphaelm** [comment]
Uh. There is a "bigger problem" that I haven't thought of before, sorry for that.


As I planned it, there is *one* LoggedSendMail for all that is connected to *all* the orders. Obviously, this wouldn't work, because thanks to your improvements on the feature, the text might be different for all orders.
As you implemented it now, there will be *one* LoggedSendMail *per order* that received one, each one of them connected to *one* order. This works, so you did the right thing. This way we don't need a ManyToMany relation to orders (ForeignKey is sufficiant) but we also have another problem: We can't easily show the list of the last sent mails to reuse, because there will be thousands of them.

My suggestion:

* Keep the model with the ManyToMany relation but store only *one* instance that contains the *template* (in all locales, so in a I18nTextField, but with the raw placeholders like ``{order}`` in it). This is then useful for inspecting re-using the text later.
* Use [our logging mechanism](https://docs.pretix.eu/en/latest/development/implementation/logging.html) that you found in the docs to log the *actual* text for every order into that order's log. This is then useful for actual "auditing".

What do you think?

**Comment by FlaviaBastos** [comment]
> there will be thousands of them

Yeah, I was thinking about that while researching how to display the emails.... It would be crazy to display a bunch of similar emails! The only individual required info would be the list of email addresses, correct? Anyway, I will do as you suggested. :)

Right now I'm not sure I follow everything you wrote. I will try to rephrase and you please correct me if I got it wrong?
* In the view I will log the email twice: 
- once with the raw placeholders and using the new model I wrote
- the second time using the final email text after processing this time using the existing logging function

I will get on with the changes you suggested on your review.
Thanks!

**Comment by raphaelm** [comment]
You rephrased correctly! :)

**Comment by FlaviaBastos** [comment]
Hum, I'm confused now and need another pair(s) of eyes, please.

I was going through what we discussed above and just implemented logging the email sent (final text) using the existing Logging mechanism. Then I checked the database to see what was logged and found out that the sendmail plugin already logs the raw message in all different locales: it's on `pretixbase_logentry` table and the action type is called `pretix.plugins.sendmail.sent` To make sure I wasn't seeing a result from my wip code, I loaded a new pretix installation, fresh from GitHub and the sendmail is also logged there. I'm attaching the data file here. Please check id's 6-8. Note that I only have 'en' enabled on this installation. 
[db.sqlite3.zip](https://github.com/pretix/pretix/files/637431/db.sqlite3.zip)

My question now is: do we still need to log the raw email on a separate table using the new model I wrote? It seems to me that it's unnecessary.... #scratching_head

**Comment by raphaelm** [comment]
> Then I checked the database to see what was logged and found out that the sendmail plugin already logs the raw message in all different locales: it's on pretixbase_logentry table and the action type is called pretix.plugins.sendmail.sent To make sure I wasn't seeing a result from my wip code, I loaded a new pretix installation, fresh from GitHub and the sendmail is also logged there

You are correct. I completely forgot about this line in there :see_no_evil: 

```
self.request.event.log_action('pretix.plugins.sendmail.sent', user=self.request.user, data=dict(
            form.cleaned_data))
```

However, this is on *event*-level, not *order*-level, so I'd still be interested in logging the final texts per order. But you are totally correct, the new model would add some new possibilities, but they are very small and it seems unnecessary now. I'm very sorry that I caused you that effort :cry: 

New plan:

* Keep the event-level logging that already is in there
* Add logging of the final texts on order-level
* Add UI to display and re-use the texts from the event-level logs

Again, sorry for the confusion :( What do you think about the new plan?

**Comment by FlaviaBastos** [comment]
> I'm very sorry that I caused you that effort :cry:

> Again, sorry for the confusion

Oh, there's nothing to be sorry about! It really was a good opportunity for me to write a model and make it work. If you decide to not use it (which is fine by me, honest!), I still got the chance to write it. Sorry if it sounded like I was complaining in my previous message; I didn't mean to. I was (still am) super confused! :stuck_out_tongue: 

Right now I am working on displaying 'stuff' on the UI. I say 'stuff' because I'm not exactly displaying what I expected (:disappointed:) and I still have a few things to figure out. Is it ok if I keep on this track and then you take a look and we fine tune it? This looks like the third step on the new plan. :)

I'm confused about event-level x order-level but since we will display *something* in the UI anyway, I want to get that working and then you help me out display the right thing... 

Thanks for taking the time to explain :)
