### ISSUE TITLE
migrate breaks with setuptools 67.0.0

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#3070]
### Problem and impact

When trying to `python -m pretix migrate` after updating the pip dependencies we encountered what amounts to:

```
  File "/var/pretix/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3095, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/var/pretix/venv/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    pytz (>dev)
```

We traced the breaking change to `setuptools` being updated to 67.0.0 and stumbling on the dependency declared by `celery`. This is probably caused by https://github.com/pypa/setuptools/commit/6510d128c4068fbd6dc31f84ac3548d0bdbed027

We fixed this by `pip3 install setuptools==66.*`.

**Comment by thegcat** [comment]
This is as much a heads-up for the pretix devs as a place for other people stumbling over this issue to find a solution. We are not familiar enough with the Python ecosystem to be able to say this is something Pretix can fix or not.

**Comment by raphaelm** [comment]
Thanks for reporting!

Celery fix is here: https://github.com/celery/celery/pull/8002

so we just wait for the next celery release
