### ISSUE TITLE
Add preview functionality to mail templates

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#308]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

If you go to Settings → Email in the control panel of a pretix event, you see a number of content text snippets that you can configure. For most of those texts, you can use placeholders like ``{total}`` for the order's total price to include individual values. It would be nice to provide a preview for those texts, so users can see that they used the placeholders correctly.

## How to do this

There are multiple approaches on this and I'd happily discuss other ideas, if you have any. The best user interface I've come up with this so far ist the following. It will require some knowledge about both Django and JavaScript/jQuery, but don't be scared, its simple usage of both and I'm here to help if you get stuck.

Add a "preview" button/link near the text that sends the current text in the textarea via AJAX to a to-be-created view that generates a preview by replacing the correct placeholders with sample data and returns the result that is then shown as a preview above or below the textarea.

I'd suggest you implement a first try for *one* of the text fields and create your PR to discuss the general method further,  before we implement it for all of them.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by raphaelm** [comment]
For the record, @jlwt90 is planning to work on this.

**Comment by jlwt90** [comment]
@raphaelm will start working on this task tomorrow (just a heads up). I will make changes in one textfield and create a pull request :)

**Comment by raphaelm** [comment]
Nice! :) Be sure to ask if there are any questions, I believe that this is not trivial on the user interface side, which is why I removed the "easy" label recently. I'm looking forward to your ideas and I'm happy to discuss them with you :)
