### ISSUE TITLE
Postgresql migration fails at covid_certificates_covidcertificateexpiry

### ISSUE THREAD

**Issue by choseh** [pretix/pretix#3108]
### Problem and impact

When trying to migrate from mysql to postgresql pgloader fails with the following message:

```
2023-02-09T11:29:37.683991+01:00 ERROR Database error 42P01: relation "public.pretix_covid_certificates_covidcertificateexpiry" does not exist
QUERY: ALTER TABLE public.pretix_covid_certificates_covidcertificateexpiry DROP CONSTRAINT IF EXISTS pretix_covid_certifi_answer_id_7eea8348_fk_pretixbas CASCADE;
2023-02-09T11:29:37.683991+01:00 FATAL Failed to create the schema, see above.
```

The old database used to make use of the covid certificates plugin, which is now deactivated.

I assume deleting everything covid related from the old database will help, but I'd appreciate your advice here.

### Expected behaviour

Successful migration

### Version

latest

**Comment by raphaelm** [comment]
Is the plugin now *deactivated* or *deinstalled*? The error message would make sense if the covid certficate database tables exist in MySQL but do not in PostgreSQL. The schemas in both databases should be generated from the same set of plugins and versions.

**Comment by choseh** [comment]
It's not currently installed anymore. The table however is still present in the database (pretix_covid_certificates_covidcertificateexpiry)

**Comment by raphaelm** [comment]
Yeah, there is no mechanism to drop old tables when you uninstall a plugin. So yeah, manually deleting it is the best action.

**Comment by choseh** [comment]
same with sofort plugin, but apart from those, everything went smooth. thanks for your effort
