### ISSUE TITLE
Allow to immediately send out vouchers via email

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#312]
It would be nice to add a field to the voucher creation process that says "Send this voucher code via email including a redemption link to address XYZ" and then automatically doing so and adding the email address to the voucher comment.

For bulk create, the form would take an email address.

This would require a new email template to be added.

**Comment by rixx** [comment]
Wouldn't add this until you start a wizard-y interface as per #145, because one more field will just add more clutter.

**Comment by vinibiso** [comment]
Hello! I think I can tackle this if the help is still needed.

Also I have to say this would technically be my first PR to a Open Source project so if you don't want a first timer with the whole PR thing I understand. I have worked with django for 3 years now if that's worth anything 😛.

**Comment by raphaelm** [comment]
Yes, please, go ahead and implement it! Let me know if you need to know anything more specific or need any help.

The wizard-y interface that rixx mentions is still not merged, I will add it in and merge your changes later, should that happen at some point

**Comment by vinibiso** [comment]
Alright! I'm gonna get to it.

It may take a moment for me to get used to the project and all that, but, it will be done.

**Comment by casdidier** [comment]
Hello, 
Is it still possible to work on it ?
If so, what is it about "including a redemption link to address XYZ" what would do this link and which address is it actually ?

**Comment by jaysiyaram** [comment]
Is this issue still open @raphaelm

**Comment by raphaelm** [comment]
Hi @jaysiyaram, feel free to work on this, but to be honest, I just removed the "easy" flag, because I don't think it will be *that* easy. If you're in for a challenge, feel free to give it a spin nevertheless.

I'd recommend setting up pretix locally and familiarizing yourself with how the system works. Especially, you should try creating a few vouchers, and you should try the "Send e-mails" feature. In the end, this ticket is about allowing to send an email easily with a voucher you just created. I could imagine three ways of doing this:

* The voucher creation form gets a new field for the email address and we add a new email template at Settings > E-mail with a pre-defined test.
* The voucher creation form gets a new field for the email address and a field for the email text.
* *After* successful creation of the voucher, you get (optionally) redirected to a second form where you can write a text and chose one or more email adresses to send to.

I'm not even sure what the best is here, I'm leaning towards the second or third option, though, since it's unlikely you want the same text for every voucher (we could still save the text and always pre-fill the one last used). @rixx @pc-coholic Do you have opinions on the UX here?

**Comment by jaysiyaram** [comment]
Hi @raphaelm, thanks for the prompt response.
I'm very new to this project and was just looking for an easy issue to get started. 
Do you guys have an irc or something to ask questions about project if i have any. I should better get started with an easy issue first, can you direct me to one.

**Comment by raphaelm** [comment]
Hi @jaysiyaram 	We don't have many easy issues right now, but feel free to have a look here: #1170

We don't have an IRC, unfortunately.
