### ISSUE TITLE
Paypal credentials only work on event level - not on global level

### ISSUE THREAD

**Issue by cybertschunk** [pretix/pretix#3126]
Hello dear pretix community,
I have an issue setting up PayPal as a payment provider for our pretix shop. We created a PayPal account and an app as stated in the docs. 
However, the gained credentials only work if we enter them in a single event. If we set them as global variables an error occurs.

Here are some technical details:
We use the current stable relase of pretix on a dockerized basis
We have the following extensions installed: pretix-passbook and pretix-pages
We use a dockerized setup

Pretix lists the following error in the logs:
 ```
ERROR 2023-02-16 10:29:12,763 pretix.plugins.paypal2 payment PayPal PartnerReferralCreateRequest: {"name":"NOT_AUTHORIZED","message":"Authorization failed due to insufficient permissions.","debug_id":"198105ca3b901","information_link":"","details":[{"issue":"PERMISSION_DENIED","description":"You do not have permission to access or perform operations on this resource."}],"links":[]}
pretix_app | Traceback (most recent call last):
pretix_app |   File "/pretix/src/pretix/plugins/paypal2/payment.py", line 328, in get_isu_referral_url
pretix_app |     response = pprov.client.execute(req)
pretix_app |   File "/usr/local/lib/python3.9/site-packages/paypalhttp/http_client.py", line 60, in execute
pretix_app |     return self.parse_response(resp)
pretix_app |   File "/usr/local/lib/python3.9/site-packages/paypalhttp/http_client.py", line 81, in parse_response
pretix_app |     raise HttpError(response.text, response.status_code, response.headers)
pretix_app | paypalhttp.http_error.HttpError: {"name":"NOT_AUTHORIZED","message":"Authorization failed due to insufficient permissions.","debug_id":"198105ca3b901","information_link":"","details":[{"issue":"PERMISSION_DENIED","description":"You do not have permission to access or perform operations on this resource."}],"links":[]}

```

**Comment by raphaelm** [comment]
You might need special permission from PayPal partner management to use the feature that allows merchants to connect ("PayPal ISU"). It's not intended for general usage, sorry.

**Comment by derpeter** [comment]
While debugging why paypal did not want to play with our pretix i found this ticket and @raphaelm hint helped me to figure out that i have to disable / remove the global settings to be able to set paypal on event level. It might be useful to other users to add this to documentation as the documentation points you to the global settings.

Thanks for all your work!!
