### ISSUE TITLE
More endpoints for the RESTful API

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#314]

**Comment by jfwiebe** [comment]
Great idea. The API would be great to abstract logic and GUI. Advancing pretixdroid (see @[Issue 4](https://github.com/pretix/pretixdroid/issues/4)) would become very easy, especially for Python-Newbies (like me).

**Comment by raphaelm** [comment]
Sure. But as this API will probably not happen very soon (as it requires either major changes or a lot of duplicate logic), if you want to work on pretixdroid now, there current JSON-API for pretixdroid is not that hard to extend. It currently lives in ``pretix/plugins/pretixdroid/views.py`` (with urls defined in ``pretix/plugins/pretixdroid/urls.py``) and contains an ``ApiRedeemView`` and an ``ApiSearchView``. For pretix/pretixdroid#4, we'd also need some ``ApiStatusView``. If you want to have a try at building this with Python, I'm always happy to help, but if you'd like to only work on the Android app I could also build the API myself and you do the android part :)

**Comment by raphaelm** [comment]
I created a new overview ticket at #654
