### ISSUE TITLE
pretixdroid configuration barcode contains wrong data under specific circumstances

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#315]
Dear devs,

in my scenario, pretix is installed in a docker container strictly following the manual. The ports are not published to the net, instead incoming HTTPS requests will be redirected via Apache mod_proxy as HTTP to pretix. Pretix recognizes this as an HTTP request and the pretixdroid configuration barcode will contain a HTTP url (under which the Api is not reachable in my scenario). Is there a switch where I can manually set the url or can you implement a switch?

Regards
Jan Felix

**Comment by raphaelm** [comment]
Hi,

could you try one of the following options and tell me if it works?

* instruct your Apache to set the header ``X-Forwarded-Proto: https`` on the forwarded request or
* use the ``url`` setting in pretix' [config file](https://docs.pretix.eu/en/latest/admin/config.html#pretix-settings)

Best
Raphael

**Comment by jfwiebe** [comment]
@raphaelm Thanks for your fast answer - the url was set to http, a mistake on my side. sorry for bothering you!

**Comment by raphaelm** [comment]
No problem, glad to help!
