### ISSUE TITLE
Validate the last date of payments

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#316]
If the last date of payments is set to a value *before* the end of the presale period, users can buy tickets but never pay them. This is probably not a situation anyone wants to have :)

We should validate in the settings form that this cannot be set this way.

**Comment by aagarwal-optumsoft** [comment]
Hi,

Could you please explain more about the issue? Specially what is the 'last date of payments'? What do you mean by 'user can buy but not pay for them'?

**Comment by amateurInventer** [comment]
Hi,
Could you please explain more about the issue? 
What is the 'last data of payments'?
What do you mean by 'users can buy tickets but never  pay them'?

Thanks
Abhinav

**Comment by raphaelm** [comment]
Hi @amateurInventer!

The first step ist to [make pretix run locally](https://docs.pretix.eu/en/latest/development/setup.html) to be able to click around and get a feeling for how pretix works.  This ticket in particular is about two settings that any event organizer can make in pretix:

* You can set a "end of presale" data which simply means that after the given date no one can buy a ticket anymore.

* You can set a "last date of payments" which meaans that after the given date no one can bay for their ticket any more.

Normally, you set the last date of payments **after** the end of presale, e.g. "Our event is on the 20th, you need do have your ticket ordered before the 10th but you may pay until the 18th".
However, if you set the last date of payments **before** the end of presale, e.g. "you can order until the 15th but only pay until the 10th", we have a weird situation: On the 13th, you can order a ticket but never pay it, which is a pretty useless thing to do.

So we need to add a validation in the settings form (where you set those dates) to validate that they are in correct order and show an error message otherwise.

If you have any questions, don't hesitate to ask!

Cheers
Raphael

**Comment by Kashyap12** [comment]
Hi @raphaelm , seems the issue is still open , I am new to open source and would love to contribute.

**Comment by raphaelm** [comment]
Hi @Kashyap12, sure, if @amateurInventer is not interested, have a go!

**Comment by abhanshgiri21** [comment]
hey 
i just today decided to see and contribute to some open source projects so i also wanna do something in open source, can i contribute to this one? if yes, what should i do?

**Comment by raphaelm** [comment]
Hi @abhanshgiri21, sure! Is my comment above clear to you? Have you any specific questions? I suggest that you take a quick look at Django's documentation regarding forms and validation :)

**Comment by brandon-pineda** [comment]
If this is still open I'll take a crack at it.

**Comment by brandon-pineda** [comment]
How do you get data from one form into another, as I see that I need to access the general settings data in the payment settings data.

**Comment by raphaelm** [comment]
@brandon-pineda Before you jump onto this, let's ask @abhanshgiri21 if he/she is still working on it?

You can always access the ``settings`` property on the ``Event`` object. To get that in the form, you need to pass the event instance to the form's constructor (which is probably already in there.)

**Comment by abhanshgiri21** [comment]
@brandon-pineda you can do this one, i am having lot of confusions and questions as i am new to open source. so i am gonna clear them up and then i will surely like to contribute as much as i can. thanks for the lovely support.

**Comment by raphaelm** [comment]
@brandon-pineda Happy new year! :) Have you started on this yet?

**Comment by brandon-pineda** [comment]
@raphaelm sorry, I haven't done much cause of all the holidays going on

**Comment by raphaelm** [comment]
@brandon-pineda No problem, hope you had a good time :) I was off here for a few days myself, just wanted to say that I'm here to help again if you get stuck :)

**Comment by abhanshgiri21** [comment]
hi @raphaelm , i am back on this one. can you  please tell me which file i have to look in for this issue.it seems pretty easy to fix i guess. so i thought of giving it a try.

**Comment by raphaelm** [comment]
@abhanshgiri21 I think @brandon-pineda works on this now. Correct, Brandon?

**Comment by abhanshgiri21** [comment]
ok!, i would find some other easy issue! @raphaelm 
but if brandon isn't working on this then i might also give it a try.

**Comment by brandon-pineda** [comment]
@abhanshgiri21 go ahead and do it if you want to, I got multiple things going on rn so it'd take me a whole regardless

**Comment by raphaelm** [comment]
@abhanshgiri21 To do this, you'll need to add some [validation logic](https://docs.djangoproject.com/en/1.10/ref/forms/validation/#using-validation-in-practice) to ``PaymentSettingsForm`` in ``pretix/control/forms/event.py``.

**Comment by scarescrow** [comment]
Hey, @abhanshgiri21 , @raphaelm Is this issue still open? I would like to contribute.

**Comment by raphaelm** [comment]
Hi @abhanshgiri21, we really want to have this done here and @rixx was so friendly to implement it, as we haven't heard from you in a long time. If you already did something, sorry for that :( There are a few really issues currently open, what do you think about #390?

Hi @scarescrow, this is therefore now closed. Would you like to have a look at #379.
