### ISSUE TITLE
"Set up new organizer account" button is not translated

### ISSUE THREAD

**Issue by pReya** [pretix/pretix#3194]
### Problem and impact

My Pretix is set to use German as the UI language, but my browser/OS is set to use English. All of the UI is translated into German except this one single button with the caption "Set up new organizer account"

### Expected behaviour

The button should be in the same language as the rest of the UI.

### Steps to reproduce

1. Set browser to English
2. Set Pretix to German
3. See button

### Screenshots

<img width="1888" alt="Screenshot 2023-03-30 at 09 16 49" src="https://user-images.githubusercontent.com/4677417/228759680-62884ecd-a4b2-427e-8bf5-437991055a58.png">

### Link

https://pretix.eu/control/organizers/

### Browser (software, desktop or mobile?) and version

Firefox latest

### Operating system, dependency versions

 MacOS latest

**Comment by wiffbi** [comment]
Thank you for reporting this! The message is actually part of pretixeu, not pretix itself. Interestingly, it has a fuzzy translation in the po-files. I will forward this internally to fix it.

**Comment by wiffbi** [comment]
P.S.: It is already fixed and will be updated with the next deploy. Thanks again for reporting! :)
