### ISSUE TITLE
PayPal: Listen to WebHooks

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#32]
PayPal can mark payment objects as `pending`. We should check them for completion using web hooks. The same goes for refunds and therefore also for stripe.
https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/
https://stripe.com/docs/api#events

**Comment by raphaelm** [comment]
Implemented, but seems unreliable. But that just might be PayPal's sandbox?

**Comment by raphaelm** [comment]
Okay, their UI and their simulator is just bad, see 56bf3fe4

**Comment by derpeter** [comment]
While debugging why paypal did not want to play with our pretix i found this ticket and @raphaelm hint helped me to figure out that i have to disable / remove the global settings to be able to set paypal on event level. It might be useful to other users to add this to documentation as the documentation points you to the global settings. 

Thanks for all your work!!
