### ISSUE TITLE
Tests should not require compilejsi18n

### ISSUE THREAD

**Issue by FlaviaBastos** [pretix/pretix#322]
Hi!
I ran into a bunch of pytest failures and just to make sure it wasn't my fork or my branches, I cloned directly from pretix master. Pytest is also failing this new installation. 
I get: 
`313 failed, 496 passed, 1 skipped, 1286 pytest-warnings, 939 rerun in 1166.09 seconds` --> yep, it takes a long time!

My env:
`platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
Django settings: tests.settings (from ini file)
rootdir: /home/lala/code/test/pretix/src, inifile: pytest.ini
plugins: warnings-0.2.0, rerunfailures-2.1.0, mock-1.4.0, django-3.0.0
collected 810 items `

This error seems to show up quite frequently (but I didn't check every error though):
`E               ValueError: The file 'jsi18n/de-informal/djangojs.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f78c06227b8>.`

I'm wondering if someone could please confirm if they see this also or if it's just mine. 
Thanks!

**Comment by raphaelm** [comment]
Ouch. The error you mentioned suggests that 
```
python manage.py compilejsi18n
python manage.py collectstatic --noinput
python manage.py compress
```
might help. Can you try that? That might be necessary due to a recent change. If this is the case, I'll find a way to make this not necessary.

**Comment by FlaviaBastos** [comment]
Sweet! It fixes it!
`809 passed, 1 skipped`
Thanks!

**Comment by raphaelm** [comment]
Finally, this should be fixed for new contributors (cc @scabux)
