### ISSUE TITLE
RFC: Smart locking algorithm for better concurrency

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#329]
## Indroduction

If a quota is set to 100 tickets, we need to be absolutely sure that pretix allows *exactly* 100 tickets to be sold and not one more (and, also important) and not less, even under high load and distributed across a number of servers. This means the process of calculating and reducing quota needs to be free of race conditions.

Currently, this is achieved by using a lock whenever we do quota-sensitive operations. We acquire the lock, calculate the available quota, perform the desired operation (if possible) and then release the lock. These lock are event-global, so for every event no two locking operations can be performed at the same time. This works, but waiting for the lock is a major bottleneck when many people try to buy tickets at the same time. 

PR #326 tries to shorten the time the lock is held as much as possible, but in the end, we will need a different solution for this. This proposal gives a possible solution that requires no huge architectural changes to how pretix works. The main source for quota information stays in the database, so we don't need to maintain a "quota counter" in some way and be very careful that it never differs from the real value

## High-level overview

We introduce a two-fold concept of locks. In the following, I will call them "hard locks" and "soft locks". All locks will again be namespaced to be event-global, this will be assumed everywhere in this text for simplicity. They adhere to the following semantics:

* Infinitely many soft locks can be held at the same time
* Only one hard lock can be held at the same time
* A hard lock can only be acquired if **no** lock is active, i.e. neither hard nor soft locks
* A soft lock can only be acquired if no hard lock is active

Therefore, at any point in time, there are three possibilities:

* No locks are active
* One or more soft locks are active
* One hard lock is active

Also, we introduce a global counter that tracks a lower bound of the available quota. We call this counter Q in the following and assume it has an atomic decrement operation and can be set to specific values. In practice, we will need multiple of those counters (one per quota), but to keep this easier to reason about, we assume the case of only one quota.

Whenever we perform an operation that will potentially reduce the available quota, we follow the following algorithm:

1. Calculate the **maximum** number by which the quota could be **decreased** in this operation. If no such calculation is possible, fall back to requiring a **hard lock** for this operation.

2. If the calculation is possible, decrement Q by the calculated amount. If this leads to Q < 0, acquire a **hard lock** for this operation. If not, acquire a **soft lock**.

3. Calculate the quota from the database and perform your operation, if possible.

4. If we hold a **hard lock**, calculate the available quota from the database and set Q to that value *after* performing the operation but *before* releasing the hard lock.

5. Release the lock

If this algorithm is employed by **all** operations that can **decrease** quota without any exceptions, the counter Q is guaranteed to be **less or equal** than the actually available quota at all times. We might be able to reduce the frequency of hard locks by also updating the counter Q after quota-increasing operations, but we are not required to do so. This is an important property of this design, because events like "a vouchers expiry date passes" increase quota but are not really controlled operations in the current design and can not make use of locking.

## Implementation thoughts

We already have this kind of quota calculation in some places and #326 adds it in more places. A nice pattern there is to have a ``collections.Counter`` object named ``quotadiff`` containing the estimated quota difference. We could basically keep our locking context manager but make it take this as an optional argument:

```
with event.lock(quotadiff):
    ...
```

We use redis to store both our locks and our counter Q. Q can just be a simple integer with redis' NATIVE ``DECR`` and ``SET`` operations. The hard locks can be implemented similar like we currently implement locks. Soft locks are stored in a hash table containing unique tokens for each of the threads holding a soft lock (a hash table is used instead of a set because it has a length operation).

The following operations that cannot be represented in a single redis command are represented as pseudo-lua code that could be executed atomically inside redis with slight modifications. The use of Lua scripts is recommended over the use of transactions by the redis documentation.

Acquiring a hard lock:
```
local nlocks = redis.call("hlen", "soft_locks")
if nlocks == 0 then
    redis.call("set", "hard_lock", TOKEN, "NX", "PX", 30000)
else
    redis.error_reply("Soft locks in place")
end
```

Releasing a hard lock:
```
local locked_by = redis.call("get", "hard_lock")
if locked_by == TOKEN then
    redis.call("del", "hard_lock")
else
    redis.error_reply("Could not release lock, timed out or lock stolen")
end
```

Acquiring a soft lock
```
if redis.call("exists", "hard_lock") then
    redis.error_reply("Hard lock active")
else
	redis.call("hset", "soft_locks", TOKEN, "1")
end
```

Releasing a soft lock:
```
HDEL soft_locks TOKEN
```

## Affected Operations
The operations in pretix that are able to reduce the available quota are the following:

* The quota size is changed
* A cart position is created
* An expired cart position is renewed
* An order is created from expired cart positions
* An expired order gets extended
* An expired order gets marked as paid
* An order position is changed to contain different products
* Voucher editing
  * A blocking voucher is created
  * A voucher is made blocking
  * A blocking voucher, that has been expired, gets a new expiration date
  * A blocking voucher is assigned to a different product/quota
  * Once we build multi-use vouchers: A blocking's voucher maximum usage number is increased

## Todo

* Add an expiration mechanism to soft locks, to avoid deadlocks when a machine or thread crashes while holding a lock and the lock is never released.

* Find a nice code pattern to ensure that this algorithm is employed for all operations mentioned above and that makes it hard to forget about this when introducing new operations. For example, new operations will come with the current proposal in the branch for #109.

* Evaluate the safety in the context of a replicated redis setup, see also [the Redlock algorithm](http://redis.io/topics/distlock). (This also applies to our current lock setup.)

**Comment by chrisdamba** [comment]
Very interesting! I've subscribed to see and learn how this is implemented.

**Comment by rixx** [comment]
Having thought about this for a day or two, I didn't run into any major flaws. I'm still not entirely sure about implementing part of this in lua, and making redis a required component is just a design decision you need to make, but other than that - go for it!

**Comment by raphaelm** [comment]
We don't need to require redis. Without redis, we can just fall back to the same hard locking that we do right now. :)

**Comment by rixx** [comment]
Oh, I missed that, apparently. In that case: :sparkles:

**Comment by raphaelm** [comment]
This is not going to happen since it is to easy to get wrong. I've got some other ideas that I want to explore, though.
