### ISSUE TITLE
No emails send to organizers

### ISSUE THREAD

**Issue by holgerm** [pretix/pretix#3295]
### Problem and impact

I've activated notifications, I am organizer of an event in test mode, but when a customer buys a ticket, the customre gets an email notification, but the organizer does not get any email. 

Also, I do not see the sent mails in my smtp account, that I have registered as organizer with pretix. Pretix shows that the mail server works and sends mails to customer, but I would expect to see these mails also in the outbox of the account of my mail provider (ionos).

Do you have any guess what I'm doing wrong?

Thanks a lot!

Holger

I opened a discussion for that subject too (cf. https://github.com/pretix/pretix/discussions/3293), but I guess it is some kind of bug, at least a missing documentation. 

### Expected behaviour

I excpect to get emails about new ticket orders etc. as I activated the events in pretix.

### Browser (software, desktop or mobile?) and version

Chrome, Firefox (recent)

### Operating system, dependency versions

Ubuntu 20.04.5 LTS

**Comment by raphaelm** [comment]
Notifications do not use the per-organizer SMTP, they use the system SMTP. Do you get password reset emails?

**Comment by holgerm** [comment]
I attach a screenshot from the setting for email notification of my test event. Is this not the right place to make smtp settings? It says notification is set up on the organizer level. And I did set it up with the correct data. At least mails to customers are delivered. 

My questions are:

- why do I as orginazer do not get notification emails?
- why are the mails sent to the customer not in the outbox of the account that is used for sending?

<img width="1552" alt="Screenshot 2023-05-08 at 10 13 43" src="https://user-images.githubusercontent.com/60585/236772778-0f3edd4d-a9af-4df2-88f3-f33577dfb4cf.png">

**Comment by holgerm** [comment]
Thank you! That works.

**Comment by holgerm** [comment]
I am still not able to get mails sent to other organizers but me (admin). I entered a bcc address in the event -> email settings page, but it does not work.

**Comment by holgerm** [comment]
Sorry, I was to quick complaining. Works.

**Comment by Konafets** [comment]
Hey, I am facing the same issue. 

> Do you get password reset emails?

@raphaelm Yes, I get them, but not the notification emails. Can I somehow enable a debug mode or so, to see whats happening?

**Comment by raphaelm** [comment]
A failed SMTP connection should be visible in either pretix.log or in the output log of pretix-worker (usually in the systemd journal or docker log)
