### ISSUE TITLE
Stripe Webhook disabled with disabled shop

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#330]
While a shop for a specific event is disabled, the stripe webhook endpoint is also disabled, it returns a HTTP 403 to stripe which contains "Sie haben keine Berechtigung, diese Inhalte aufzurufen. Der ausgewählte Ticket-Shop ist im Moment nicht verfügbar."

Is this the intended behaviour? I would expect the webhook to be available as long as the event exists in pretix.

Regards
Jan Felix

**Comment by raphaelm** [comment]
This is not intended, no. Thanks for reporting.

**Comment by raphaelm** [comment]
Fixing this probably is best done by adding an argument ``require_live=False`` to the ``@event_view`` decorator that allows plugins to specify that this check shall be skipped for thin view.

**Comment by rixx** [comment]
See PR #331
