### ISSUE TITLE
Export does not contain bill numbers

### ISSUE THREAD

**Issue by holgerm** [pretix/pretix#3321]
### Problem and impact

I want to export bill data for my tax consultant. When I use the event -> orders -> export function, I only get the oder numbers, but I need the bill numbers. Same problem when using the organizer export.

Is there a way to include the bill number in the export?

**Comment by raphaelm** [comment]
I suggest to work from the "invoice data" export directly, not the order export.

**Comment by raphaelm** [comment]
Bestellungen > Export > Rechnungsdaten

**Comment by holgerm** [comment]
Thanks a lot! I just did not see that. Had to scroll down further. Embarassing. Sorry.
