### ISSUE TITLE
Wrong translation for "order cancelled" notification

### ISSUE THREAD

**Issue by choseh** [pretix/pretix#3328]
### Problem and impact

Cancellation message says the order was refunded, but refund is happening in the next step.

### Expected behaviour

Message should probably say:

"Die Bestellung wurde als storniert markiert [...]"

### Steps to reproduce

cancel order

### Screenshots

![SmartSelect_20230517_123126_Chrome](https://github.com/pretix/pretix/assets/5830192/6e793057-5a60-45e1-b82d-b93ac0751854)

**Comment by raphaelm** [comment]
Fixed on translate.pretix.eu as it only affected the German version
