### ISSUE TITLE
Rollup not installed

### ISSUE THREAD

**Issue by rhonalindiefolks** [pretix/pretix#3334]
### Problem and impact

Hello,   I am make a rebuild and get it error 

(venv) rhonal@rhonal:~/pretix/pretix-4.19.0$ python src/manage.py rebuild 

processing language de
processing language de-informal
processing language ar
processing language zh-hans
processing language cs
processing language da
processing language nl
processing language nl-informal
processing language fr
processing language el
processing language it
processing language lv
processing language pt-pt
processing language ro
processing language ru
processing language es
processing language tr
processing language uk

19 static files copied to '/home/rhonal/pretix/pretix-4.19.0/src/pretix/static.dist', 940 unmodified, 50 post-processed.
CommandError: An error occurred during rendering pretixcontrol/checkin/list_edit.html: Rollup not installed or pretix not built properly, please run 'make npminstall' in source root.

### Operating system, dependency versions

Ubuntu 22.04.2 LTS

### Version

pretix-4.19.0

**Comment by raphaelm** [comment]
Yes, there is unfortunately a packaging issue in the 4.19.0 release.

Workaround: check out the git repo at the v4.19.0 tag and run `python setup.py install`.

Or use the current development version which already has the fix
