### ISSUE TITLE
Team invitation does not work

### ISSUE THREAD

**Issue by sevenuz** [pretix/pretix#3341]
### Problem and impact

I want to invite team members on my own hosted instance. Mails from the shop are delivered but invitations for teams does not work.

### Expected behaviour

should send an email with invitaion link

### Steps to reproduce

1. host instance
2. invite administrator teammember

### Link

.../control/organizer/

### Browser (software, desktop or mobile?) and version

browser

### Operating system, dependency versions

hosted on uberspace.de

### Version

4.19.0

**Comment by raphaelm** [comment]
(This is very likely not a bug in pretix, so please use a discussion, not an issue, if you need help ☺️)

Did you check that the mail config in pretix.cfg is correct?
