### ISSUE TITLE
Devices need to be connected before they can be revoked

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#3360]
### Problem and impact

Devices that are created but not yet connected cannot be revoked, neither on the device list nor on the device edit view. I understand that creating devices without connecting them on the spot is a corner case, it is one we currently use though and that makes revoking non-used device tokens difficult.

### Expected behaviour

Being able to revoke non-connected Device tokens.

### Steps to reproduce

1. Go to Organizer > Devices
2. "Connect a device"
3. Save the URL and token to connect a device at a later time and go back to "Device overview"
4. Unconnected device can only be connected not revoked.

### Link

`/control/organizer/<slug>/devices`

### Version

4.19.0

**Comment by raphaelm** [comment]
Agreed, that should be possible
