### ISSUE TITLE
Paypal Popup loading stuck and then closing

### ISSUE THREAD

**Issue by yannicschuller** [pretix/pretix#3365]
### Problem and impact

I have a clean dockerized installation of Pretix version 4.19.0. After entering the PayPal credentials and testing them on the shop page, the PayPal popup opens, loads for a minute and then closes.

Basically, the same problem as described here: https://github.com/pretix/pretix/issues/3227

Interestingly, in the network tab, I see a post to /paypal2/xhr/ that times out with a 502 error.

Also, I use Cloudflare. Could this be the problem?

### Expected behaviour

PayPal widget opens and lets the user enter his credentials to pay for the ticket.

### Steps to reproduce

1. Install Ubuntu 22.04.2 LTS
2. Install Dockerized Pretix
3. Enter PayPal Client ID and Secret
4. Try to open PayPal widget on Shop Page

### Screenshots

![CleanShot 2023-05-29 at 13 11 53@2x](https://github.com/pretix/pretix/assets/76843349/0726802d-e139-4763-9cac-f4b2b48fe1d6)

### Version

4.19.0

**Comment by pc-coholic** [comment]
Might be Cloudflare or not - not easy to say. But in the past, Cludflare never did anyone any good ;-)

If you see a an error 500, then there should also be something in your pretix logfile.

Please have a look and provide the output here.
