### ISSUE TITLE
Oder Approval necessary after deleting ordered product.

### ISSUE THREAD

**Issue by navlisilvan** [pretix/pretix#3460]
### Problem and impact

If there is a product in the order that requires manual Approval, the entire order is paused until the order is approved.

If this one product is manually deleted from the order, Approval is still required.

### Expected behaviour

I would expect the order to be automatically Approved when the product requiring Approval is deleted.

### Browser (software, desktop or mobile?) and version

firefox desktop

### Version

2023.6.0

**Comment by raphaelm** [comment]
After an order was submitted, the approval requirement is a property of the order and the order will follow a different workflow. The data model does not allow to derive *why* exactly an order does needs approval and thus any form of auto-approval would be in danger of producing false-positives. I also believe it would be surprising behaviour in many situations, which is something we like to avoid.
