### ISSUE TITLE
Microdata for search engines

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#35]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

Every event organized by pretix gets a small web page representing the event -- it's ticket shop. In the HTML code of this page we want to add microdata markup. Microdata is a structured way to tell search engines what the given page is about and allows them to understand the page better and do fancy things like showing the event location or date directly in the search results.

## How to do this

First, you need to read up a bit about structured data. For example, there is the [JSON-LD](http://json-ld.org/) data format that we probably want to use. Don't get discouraged by complicated-sounding words, just keep to the examples, they should be pretty clear in many cases. Google also has a lot of documentation and tools on the topic, for example:

* [A short JSON-LD guide](https://developers.google.com/schemas/formats/json-ld)
* [A number of examples specifically for events](https://developers.google.com/search/docs/data-types/events)
* [A test tool to check if your structured data is good](https://search.google.com/structured-data/testing-tool/u/0/)

Once you know how it should look like, you basically only have to put it in the right place, which is ``src/pretix/presale/templates/pretixpresale/event/index.html``, and fill it up with the correct data via template variables.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by raphaelm** [comment]
https://developers.google.com/structured-data/testing-tool/
http://json-ld.org/

**Comment by raphaelm** [comment]
https://developers.google.com/structured-data/events/performers
https://developers.google.com/structured-data/events/ticketers

**Comment by harshavamsi** [comment]
Hi @raphaelm, I'm trying to contribute to my first open source project and I think this is something I'm interested in. Can I work on this?

**Comment by raphaelm** [comment]
Hi @harshavamsi! Sure, go ahead! If you have any questions, just ask! :)

**Comment by harshavamsi** [comment]
@raphaelm So as per my understanding, I should be using one script tag inside the index.html page with the JSON template and load variable data. Am I on the right track?

Should I add the tag at the bottom of the page because I don't see any base template being used.

**Comment by raphaelm** [comment]
Sounds good to add it a the bottom of the index.html, yes

**Comment by harshavamsi** [comment]
@raphaelm Does something like this make sense? I'm not sure how the event name is being passed to the template.
```javascript
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "",
  "date": {{ date | safe}},
  "time": {{ time | safe}},
  "url": "https://pretix.eu",
}
</script>
```

**Comment by raphaelm** [comment]
Hi,

yes, that goes into the right direction, but it won't yet work this way.

Maybe have a look at ``src/pretix/presale/templates/pretixpresale/event/base.html`` which uses the event name (``{{ event.name }}``), generates a link (``{% eventurl event "presale:event.index" %}``) and displays date and time. You'll also have to make sure that the date and time are in the correct format.

Looking at the JSON-LD examples it needs to be something like ``"startDate": "2015-02-23T20:30",``. You should have a look at [Django's |date filter](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#date) and then use Google's testing tools (see above) to check if the result is fine.

Cheers
Raphael

**Comment by harshavamsi** [comment]
Hi,

For django to parse json shouldn't I first be sending in parsed data from the view and then use it in the script tag?

**Comment by raphaelm** [comment]
Both ways are possible, but I think generating it in the view and then sending the final JSON to the tempalte is better :)

**Comment by harshavamsi** [comment]
Yeah that's what I thought. I'll work on this!

**Comment by raphaelm** [comment]
Hey @harshavamsi! How is it going? I don't want to build pressure, just check if everything is fine or if I can help :)

**Comment by harshavamsi** [comment]
Hey @raphaelm I've worked on some django apps and this is by far the most complex one I've seen :P Sorry for the delay been flushed with work. But yeah I do need some help in passing data to the template the right way.

**Comment by raphaelm** [comment]
No problem at all. Do you see the ``get_context_data(self, **kwargs)`` method in ``EventIndex`` in ``pretix/presale/views/event.py``? If you add entries to the dictionary constructed there, you should be able to use them as variables in the template.

**Comment by harshavamsi** [comment]
Oh alright. I'll give it a try!

**Comment by raphaelm** [comment]
@harshavamsi Everything alright? No pressure, this is not urgent, just wanted to ask if I can help :)

**Comment by lhhong** [comment]
Hi @raphaelm, is this issue still open?

**Comment by raphaelm** [comment]
> Hi @raphaelm, is this issue still open?


Its assigned to @harshavamsi, but since we haven't heard anything for three months, I guess it isa

**Comment by Joepriesto** [comment]
Hi I am currently looking at this, but don't want to claim it yet. I just want to know whether you would accept the location field becoming a fully fledged set of address fields e.g. Street, Street2, City, Zip/Post Code, Country in order to implement this? It's the only way I can see this working.

**Comment by raphaelm** [comment]
Hi, nope, I don't want the location field to grow like this. If that's the only way to encode the location, we should fall back to only encode the date, time and event name for now, I guess

**Comment by Joepriesto** [comment]
According to [Google events microdata](https://developers.google.com/search/docs/data-types/events) guide location.address is required. But for that we could probably get away with addressLocality, Region and Country. 
Do you have any example data, real user location strings, I could test with?
Also, can I claim this one? Thanks

**Comment by raphaelm** [comment]
> According to Google events microdata guide location.address is required. But for that we could probably get away with addressLocality, Region and Country.
> Do you have any example data, real user location strings, I could test with?

Unfortunately, the field is used very differently. I've seen full adresses, cities only, building names only – and many events do not fill it at all. I'm not really sure how we should handle this, tbh. THis also depends on what Google does if the property is missing… ignore the data altogether or do something useful still. Can you find any information on that?

> Also, can I claim this one? Thanks

Sure!
