### ISSUE TITLE
Docker Hub build failing

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#352]
I do not know if this is a thing but it feels like no new features are coming into the docker image. As seen in the Docker Hub, there are many errors. I am not a docker expert, so maybe you can have a look at this?

**Comment by jfwiebe** [comment]
![image](https://cloud.githubusercontent.com/assets/6865786/21062103/8f587476-be4f-11e6-8754-32066f48237e.png)

**Comment by raphaelm** [comment]
Uh, thanks for noticing. I will look into this.

**Comment by raphaelm** [comment]
Oh, thanks for noticing! I'll look into this!

**Comment by raphaelm** [comment]
Fixed in 765cb09 :)

**Comment by jfwiebe** [comment]
![image](https://cloud.githubusercontent.com/assets/6865786/21073590/e463a114-bee2-11e6-9a8a-391094ca805b.png)
Great, thank you!
