### ISSUE TITLE
Redis 4.5.5 contains a bug, its fixed in 4.6.0

### ISSUE THREAD

**Issue by bk-debug** [pretix/pretix#3530]
### Problem and impact

you can't order products anymore

### Expected behaviour

PR fixing issue:
https://github.com/redis/redis-py/pull/2756

upgrade to 4.6.0:
https://github.com/redis/redis-py/releases/tag/v4.6.0

### Version

\>=4.18

**Comment by raphaelm** [comment]
Dependency updated
