### ISSUE TITLE
Fonts get %22 in URL

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#355]
Dear team,
since today, fonts won't be loaded anymore because a "-Symbol is added to all font domains (see screenshot). I do not know if this correlates with an update I did yesterday. I use a fairly docker-deployment as described in the docs. I am not able to spot the root cause of the issue, everything that has been committed since my last update seems to be not the cause. I am currently thinking about a dependency change...
![image](https://cloud.githubusercontent.com/assets/6865786/21161784/59c8f504-c18a-11e6-90c1-ae0ad1d9ff15.png)
I currently have no resources for reproducing the error. Can you reproduce it?

**Comment by raphaelm** [comment]
Haven't tried with docker yet but can't reproduce it otherwise. Can you show the ``[urls]`` part of your ``pretix.cfg`` if there is any? If there is nothing suspicious in there, I'll try it out with docker myself.

**Comment by jfwiebe** [comment]
There is no [url] tag in the config file.

**Comment by raphaelm** [comment]
Fixed :) new docker container should be available… well, as soon as docker hub has the time for it ;)

**Comment by jfwiebe** [comment]
@raphaelm awesome!
