### ISSUE TITLE
Search orders/go to voucher

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#357]
- When I enter an order code in the input box on the order list, and the order exists, I'll see the detail view of the order.
- When I enter a partial order code, I'll get no matches.
- When I enter a voucher code in the input box on the voucher list, and the voucher exists, I'll see a list view containing that one voucher.
- When I enter a partial voucher code, I'll get all vouchers matching that code.

I'd like to see consistent behavior here; at the very least going to a voucher if the entered code corresponds to a voucher exactly. Substring search for order codes would be nice, too, unless you have security concerns there?

**Comment by raphaelm** [comment]
I'm not a fan of search of forms which *sometimes* take you to the detail page and *sometimes* to a result list. If you look closely, for orders there is a "go to" and a "search" part of the form, while vouchers only have the "search" part. Probably, this is also not a perfect UI. I'm open for ideas here.

Substring search for orders is useful, sure thing. And no, no security concerns there.

**Comment by rixx** [comment]
I am aware of the difference between "go to" and "search", but I really enjoyed going directly to orders and found myself often surprised when copying a voucher would not take me there. But since I prefer the go-to style to remain, I think I'll retract this one - substring search for vouchers might be nice, but not as nice as going directly to a voucher.

**Comment by raphaelm** [comment]
No reason to close this, I absolutely see the point! The title of this issue is still valid:

* Implement substring search for order codes
* Implement **go to** for vouchers
