### ISSUE TITLE
Better error message on empty bank import

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#359]
Trying the bank upload without any given file says

>  We were unable to detect the file type of this import. Please contact support for help. 

I'm fairly sure it'd be possible to see that there is no file at all, and output a corresponding error (or disallow sending the form client-side?)

**Comment by brandon-pineda** [comment]
Hello, I'd like to attempt this but could you give me some more details about the issue please?

**Comment by rixx** [comment]
Sure!

You don't acutally need a deep familiarity with Django here - having worked with Python should be good enough :)

A good first step would be to get pretix up and running locally - you can follow the [developer guide](https://docs.pretix.eu/en/latest/development/setup.html) for that.

This issue is about the bank import functionality which is enabled by the bank transfer plugin - you'll need to enable that plugin in the `/control/` part of the web application to test it. Then you should be able to go to the "Import bank data" page and click "start upload" without providing a file. The page will then say " We were unable to detect the file type of this import. Please contact support for help."

This issue proposes to show a different error message if there was no file provided at all - so you'll want to go to the code part handling the uploaded file (or lack thereof): Around [these lines](https://github.com/pretix/pretix/blob/master/src/pretix/plugins/banktransfer/views.py#L226-L240) there needs to be another additional error handling.

Don't hesitate to ask questions if you run into any problems! Happy to help :)

**Comment by brandon-pineda** [comment]
Ok thanks for the info! I'll try it out.

**Comment by brandon-pineda** [comment]
I have made an appropriate error message, but  I do not know how to get it to not reload the page as if I do not use the redirect_back() function I get an error for not returning an HTTPResponse object. I tried using HTTPResponseNotModified but that caused issues with the error message not showing up. Here is my code and error if I do not return an HTTPResponse. 
![code](https://cloud.githubusercontent.com/assets/10660263/21284450/30b8f248-c3d0-11e6-9b11-8753ca213e87.png)
![error](https://cloud.githubusercontent.com/assets/10660263/21284454/4161b030-c3d0-11e6-8601-8315136a95dc.png)

**Comment by rixx** [comment]
What do you mean by "not reloading the page"? Since this code runs server side, the site will be reloaded, if only to show the new errors.

By the way: it might be easier to see which branch returns which value if you add a `return self.redirect_back()` to `elif self.request.FILES.get('file') is None:` - then every branch of the if/elif/else statement has its own return value. (Logically the same happens by waiting for the fallthrough return, but it's harder to read.)

**Comment by brandon-pineda** [comment]
Woops, I've been learning a lot about front end stuff lately, forgot this was server side XP funnily enough I actually had each have its own return statement earlier, but I thought people may like it more this way. Alright I'll do that.
