### ISSUE TITLE
Ticket issue - No Taxation Bug

### ISSUE THREAD

**Issue by jxs714** [pretix/pretix#3658]
### Problem and impact

Hey guys,

There seems to be a No tax bug when creating a product/ticket. At the buttom the "No Taxation" doesn't work. It forces you to choose a tax option. Not sure if there is another option I am missing somewhere else that is conflicting, but the only way to make it work is to create a zeroed out tax fee.

### Screenshots

![Tax issue](https://github.com/pretix/pretix/assets/4393073/7f36876b-f2bd-460c-b40f-377bd2b21d2c)

### Version

2023.8.0

**Comment by raphaelm** [comment]
This is intentional to avoid accidental misconfiguration. If at least one tax rule exists in the event, the field becomes required. Only if no tax rule exists, it's optional.
