### ISSUE TITLE
Automate or document obtaining PayPal API credentials

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#369]

**Comment by IVI053** [comment]
+1 from my side. I tried to get it to work but could not find anything useful on the Paypal side that looks like ClientID and Secret. Nothing in the docs either :-(
Looks like you need some deep Paypal Dev knowledge to get this to work.

**Comment by raphaelm** [comment]
The basic flow is:

* Sign up at the [PayPal developer dashboard](https://developer.paypal.com/developer/applications/)
* Go to the "REST API apps" sections
* Click "Create App"
* Enter a name for your pretix installation
* Switch the toggle in the upper right to "Live"
* Copy the Client ID and Secret (first box)
* Add a Webhook to the URL specified in pretix (second box)
* Configure pretix
* Done.

If you use Sandbox credentials instead of Live credentials, no real money will be processed but you'll also need special sandbox accounts to test it.

**Comment by raphaelm** [comment]
Its documented now: https://docs.pretix.eu/en/latest/user/payments/paypal.html

PayPal support assured me there is no better way to do it :cry

**Comment by raphaelm** [comment]
There might be a way: https://developer.paypal.com/docs/classic/permissions-service/gs_PermissionsService/

**Comment by raphaelm** [comment]
Not supported via the REST API:
https://github.com/paypal/PayPal-PHP-SDK/issues/165

There is no maintained implementation of the SOAP API for Python either, so no good news for now.
