### ISSUE TITLE
cookie_domain breaks cookie based settings on custom domains

### ISSUE THREAD

**Issue by ethrgeist** [pretix/pretix#3701]
### Problem and impact

Cookie Domain is always set to config's `cookie_domain`, even if custom domains for organizers or events are used.

Workaround is to not set `cookie_domain` in the pretix.cfg, i can not tell if this has security implications.

### Expected behaviour

Cookie domain should either respect the custom domain setting of an organizer or event, or should not be set.

### Steps to reproduce

1. A pretix store is setup as `foo.example.net`
2. The `cookie_domain` is set to `foo.example.net`
3. An event has custom store domain of `bar.example.com`
4. If the language switcher on the store is used, the cookie's domain setting is set to `foo.example.net`
5. Language switcher does not work

### Browser (software, desktop or mobile?) and version

Every browser

**Comment by raphaelm** [comment]
Uh, that does sound like a bug! We actually do not use cookie_domain in production and I'm not sure many others do, but it should probably be ignored when on a custom domain.
