### ISSUE TITLE
Remove Dutch (Belgium) 0% from translations

### ISSUE THREAD

**Issue by PanderMusubi** [pretix/pretix#3730]
### Problem and impact

Translation for Dutch (Belgium) is at 0% and is offered to be completed. However, there is already a Dutch translation at 82% which needs to be completed.

Belgium Dutch, especially written for software interfaces is most of the time identical to Dutch and not efficient to have it translated seperately..

### Screenshots

n/a

### Link

https://github.com/pretix/pretix/

### Browser (software, desktop or mobile?) and version

n/a

### Operating system, dependency versions

n/a

### Version

n/a

**Comment by raphaelm** [comment]
Hm. We have not added it, but a user has, for some reason. So far, it is not exposed in the software, only on the translation portal, so I'm a little undecided here if it does any harm this way

**Comment by bmaster001** [comment]
I agree with @PanderMusubi here. The Belgian Dutch translation has only one translated string, from 6 months ago. And it's exactly the same as in the Dutch translations.

**Comment by raphaelm** [comment]
Resolved in https://github.com/pretix/pretix/pull/3823
