### ISSUE TITLE
Update check incorrectly reports pretix 2023.9 as latest version (expected: 2023.10)

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix#3767]
### Problem and impact

The update check reports 2023.9 as the latest release:

![2023-12-10-pretix](https://github.com/pretix/pretix/assets/55506/cba1362b-2be4-463d-88e9-a9d4361acad5)

But on the blog, I read about 2023.10: https://pretix.eu/about/de/blog/20231129-release-2023-10/

Why does the update check not show 2023.10 as latest release?

**Comment by raphaelm** [comment]
>  Why does the update check not show 2023.10 as latest release?

 Cause I'm not very successful at updating the latest release file and really need tk automate that ;)

**Comment by Wikinaut** [comment]
After update (strictly based upon the instructions) to 2024.02 I still see 2024.01 as version.
