### ISSUE TITLE
Custom fields don't support link rendering in the question

### ISSUE THREAD

**Issue by obsoleszenz** [pretix/pretix#3772]
### Problem and impact

I would like to show a link in a custom question. Currently it only works in the help text.

### Steps to reproduce

1. Create a custom field
2. Add a link (`[blubb](http://pretix.com)`]
3. It wont get rendered

### Screenshots

![grafik](https://github.com/pretix/pretix/assets/94946669/bd7b12e1-c451-4727-a8ad-810d958e382d)

### Version

2023.10.0

**Comment by raphaelm** [comment]
That is intentional. Question titles are used in lots of places where this wouldn't work well (such as export column headers, our Android apps, ...)

**Comment by raphaelm** [comment]
For the use case in the screenshot, consider Settings>General>Texts>Confirmation texts instead

**Comment by obsoleszenz** [comment]
> For the use case in the screenshot, consider Settings>General>Texts>Confirmation texts instead

We considered this, but it gives only one confirmation even if one busys multiple products.

> That is intentional. Question titles are used in lots of places where this wouldn't work well (such as export column headers, our Android apps, ...)

Maybe one could strip links from those places and only render it in the html?
