### ISSUE TITLE
Adding a location field to an event

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#381]
Hey devs!
Adding a location field would be great. Each major ticket reseller prints the location of the venue onto the ticket. It would be great to have such a setting in pretix.
Regards
Jan Felix

(All these past issues of mine are only small things but I think they are all worth mentioning. I hope that you are okay with that, if not, please let me know)

**Comment by raphaelm** [comment]
Yes, good idea!

**Comment by raphaelm** [comment]
(And yes, keep those minor issues coming! They make pretix better, they don't get lost if they are here on GitHub, and they tend to be easy pickings for new contributors)

**Comment by jlwt90** [comment]
Hi @jfwiebe @raphaelm,

can I help on this issue? Basically I just need to add a location field in event settings and the field should be **I18nCharField** (coz venue address should be displayed in event's local language?) 

Thanks!

**Comment by raphaelm** [comment]
Hi @jlwt90 -- exactly! Just give it a try and tell me if you get stuck! :)

**Comment by jlwt90** [comment]
@raphaelm  thanks! I created a pull request. Could you please give me some comments?
#398

**Comment by jfwiebe** [comment]
@jlwt90 thank you!
