### ISSUE TITLE
Breaking issue on credit card payment with Stripe

### ISSUE THREAD

**Issue by KarlKeu00** [pretix/pretix#3810]
### Problem and impact

Since 02.01.2024, credit card payments via Stripe do not work. The following error occurs:

```The statement_descriptor parameter is not supported for the payment_method_type `card`. To continue supporting payment_method_type `card`, please pass in `statement_descriptor_suffix` or remove the `statement_descriptor` parameter altogether. Please see https://support.stripe.com/questions/use-of-the-statement-descriptor-parameter-on-paymentintents-for-card-charges for additional details.```

### Expected behaviour

The bank transfer works

### Steps to reproduce

1. Set up Stripe
2. Pay by credit card
3. Error

### Screenshots

<img width="977" alt="Bildschirmfoto 2024-01-14 um 10 12 29" src="https://github.com/pretix/pretix/assets/47644344/3935a987-6c45-4e4d-9987-e33f0b389c80">

### Browser (software, desktop or mobile?) and version

All browsers

### Operating system, dependency versions

All operating systems

### Version

2023.10.0

**Comment by jerdog** [comment]
Also seeing this in a self-hosted version (tickets.devopsdays.org) and unable to accept payments

Looks like the details from Stripe are found at https://support.stripe.com/questions/use-of-the-statement-descriptor-parameter-on-paymentintents-for-card-charges

**Comment by raphaelm** [comment]
I prepared a fix, but I'm a little confused why we don't see this on Hosted, we have hundreds of Stripe card payments every day.

**Comment by raphaelm** [comment]
We'll try to do a bugfix release with the patch asap!

**Comment by KarlKeu00** [comment]
Is it already clear when the patch will be released?

**Comment by raphaelm** [comment]
pretix 2023.10.1.post1 ist now available on PyPI
