### ISSUE TITLE
SSO missing in community version

### ISSUE THREAD

**Issue by samuk** [pretix/pretix#3818]
### Problem and impact

When trying to link my SSO provider the option is missing https://docs.pretix.eu/en/latest/user/customers/index.html#single-sign-on-sso

Is it a paid feature only?

### Expected behaviour

I was expecting to see the SSO options outlined in the docs

### Steps to reproduce

Install community version, create an organiser, visit the customer accounts page for that organiser

### Screenshots

![oidc](https://github.com/pretix/pretix/assets/400875/1c4ff048-cda0-4268-8746-2bbbe7a0c07b)

### Browser (software, desktop or mobile?) and version

Firefox

**Comment by raphaelm** [comment]
SSO is fully part of the community version. It's a separate option in the main organizer menu under "Customer accounts".

**Comment by samuk** [comment]
![main-organiser](https://github.com/pretix/pretix/assets/400875/332975bf-5e3a-42c0-a721-48c52645e90f)

Could you say a bit more about how to find this option please? In the above screenshot I'm logged in as the main organiser account, I don't see a customer accounts menu item there? I guess I'm looking in the wrong place?

**Comment by raphaelm** [comment]
Navigate to the organizer, then within the organizer to customer accounts :)
