### ISSUE TITLE
Missing German Translation for End of Presale Reason

### ISSUE THREAD

**Issue by choseh** [pretix/pretix#3838]
### Problem and impact

Missing translation for reason for end of presale

### Expected behaviour

translated string :)

### Steps to reproduce

don't set end of presale date

### Screenshots

![image](https://github.com/pretix/pretix/assets/5830192/14119233-64c9-4393-aa9f-7eeddcc66238)

**Comment by raphaelm** [comment]
The technical cause has been fixed. The string is still not translated but will be with the next translation run.
