### ISSUE TITLE
Internal server error after upgrade to 2024.1

### ISSUE THREAD

**Issue by bmaster001** [pretix/pretix#3853]
### Problem and impact

Internal server error after upgrading the docker compose version from 2023.10 to 2024.1
the pretix app log with the error is attached:
[pretixlog.txt](https://github.com/pretix/pretix/files/14128363/pretixlog.txt)

### Steps to reproduce

1) I had a running version 2023.10 with a docker-compose that references the image pretix/standalone:stable
2) docker compose pull
3) docker compose down && docker compose up
4) go to the pretix web site

I'm guessing it has something to do with the languages I have selected only the Dutch language for the one event that I have. I have 1 organizer, with English and Dutch selected. I had customised some translations but I removed it from the config, the error remains.

### Version

2024.1

**Comment by pc-coholic** [comment]
There seems to be an issue with the nl_BE language that was supposed to be removed.

As an immediate solution, please consider pulling pretix/standalone:latest; that should fix the issue until the next release.

**Comment by bmaster001** [comment]
I've gone back to 2023.10 for now. Is the pretix/standalone:latest version stable enough to run in production?

**Comment by pc-coholic** [comment]
It's what we use on pretix.eu - so I'd say: Yes :-)

**Comment by bmaster001** [comment]
Oh, I assumed that would be the stable release... What is the difference between latest and stable then?

**Comment by pc-coholic** [comment]
Latest is the bleeding edge - the latest commit on the GitHub repository; stable is the latest numbered release.
