### ISSUE TITLE
Better feedback after generating a voucher

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#390]
Including the voucher string in the success notification would be a great step. (Without further voucher features, doing the same for bulk creation does not seem as feasible, UX-wise.)

**Comment by rixx** [comment]
Looks good, yep. I guess we have solved the bulk creation thing partially via the "copy to clipboard" feature, so this should be sufficient until the voucher rewrite happens.

**Comment by raphaelm** [comment]
Yep, this looks good! :)
