### ISSUE TITLE
Send mail on cancelled order

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#391]
It would be nice to send a notification if a pending order is cancelled. (Wouldn't do this for expired orders necessarily, but going from a valid pending order to a cancellation should document this change to the user.)

**Comment by SurajGoel** [comment]
Can I take this ?

**Comment by raphaelm** [comment]
Hi @surajgoel, sure, go ahead! There are many similar things in pretix (like the mail for changed orders) that you can copy from. Be sure to ask if you have any questions!

**Comment by shubh-shetty** [comment]
i am newbie.I would like to work on this project.

**Comment by raphaelm** [comment]
@shubh-shetty I believe @SurajGoel is currently working on this

**Comment by raphaelm** [comment]
Hey @SurajGoel, everything going alright? (Don't want to put you under pressure, just check if you have any quetsions here.)

**Comment by SurajGoel** [comment]
Hey @raphaelm , Actually I have been swarmed by other works, and I might take a while on this. Since @shubh-shetty is interested, I suggest that he addresses this issue, while I will tackle another one when I am able to do so. Thanks for your support though, very much appreciated.

**Comment by raphaelm** [comment]
@SurajGoel Alright, thanks for the notice! @shubh-shetty are you still interested?

**Comment by saurabhgoyaliitr** [comment]
@raphaelm   I am new to open source. Can you help me taking this?

**Comment by raphaelm** [comment]
@saurabhgoyaliitr I'm currently not sure if @shubh-shetty is interested to work on this.

**Comment by saurabhgoyaliitr** [comment]
then I could try fixing some other easy bug. but i need to know how to get started .

**Comment by raphaelm** [comment]
There currently aren't that many easy bugs free. #293 is very similar to this one and has a detailled description, wanna look there? :)

**Comment by raphaelm** [comment]
Hi @shubh-shetty, have you tried anything yet? Anything I can help with?

**Comment by danlls** [comment]
Hi @raphaelm, I'm new to this project, would like to have a go at this :D

**Comment by raphaelm** [comment]
Hi, since @shubh-shetty is not replying, I think it's free. Go ahead, and let me know if you need help!
