### ISSUE TITLE
[Suggestion for improvement] OpenIDConnect unique identifier should comprise unique issuer(provider) hash to avoid collisions if more than one SSO provider is set up

### ISSUE THREAD

**Issue by Wikinaut** [pretix/pretix#3922]
### Problem and impact

"External Reference", usually this is SSO identifier "sub" is stored as supplied.

When this is a short number eg. ```11216``` (supplied by the OIDC provider), it could quicly lead to collisions when you add further SSO providers for custom accounts.

### Expected behaviour

What I suggest is to internally **add a prefix** (hash, salt) to the ```sub``` value, so that is has basically the form

```sub@hash(provider)``` or ```sub-hash(provider)``` or ```sub-providerurl```or ```sub-hash(providerurl)```

Example:
sub = 11216
provider = someprovider

store as ```11216-FRXH2OU3627O3```

**Comment by raphaelm** [comment]
I don't think we require external identifiers to be unique across multiple providers currently

**Comment by Wikinaut** [comment]
I have currently a problem with two different providers and (too short) ```sub``` entities à la ```123`` and foresee a collision.
Therefore I suggest a local solution. You can alternatively store the account customer account references ids as ```sub@issuer``` (instead of ```sub```only).

**Comment by Wikinaut** [comment]
From my experience when I coded the OpenID-Extension for MediaWiki: always use identity@provider, just as remark.

**Comment by Wikinaut** [comment]
This issues is not describing a bug, it's more a hint for improvement.

**Comment by raphaelm** [comment]
> I have currently a problem with _two_ (or more) different providers and (too short) ```sub``` entities à la ```123``` and foresee a collision.

You forsee wisely, but in this case wrong, as I read the code. There will not be a collection, a second user will be created and collision will not happen.

**Comment by Wikinaut** [comment]
Prima!
