### ISSUE TITLE
Incomplete mixed taxation documentation

### ISSUE THREAD

**Issue by ginkel** [pretix/pretix#3925]
### Problem and impact

Hi there,

while reading the documentation on mixed taxation (generated from https://github.com/pretix/pretix/blob/master/doc/user/events/guides/mixed_taxation.rst) I noticed that it seems to be incomplete, i.e., the page ends with a colon without the following itemized list I would have expected.

### Steps to reproduce

1. Navigate to https://docs.pretix.eu/en/latest/user/events/guides/mixed_taxation.html
2. Note the incomplete docs

### Link

https://docs.pretix.eu/en/latest/user/events/guides/mixed_taxation.html

### Version

master

**Comment by pc-coholic** [comment]
I looked at the history and apparently this is just a leftover from when the product structure guide was just a very long page with different subsections.

Below the line you're seeing, there was just a list of links to the other product structure guides as can be seen here: https://docs.pretix.eu/en/latest/user/events/structureguide.html

Thank you for flagging this, I'll remove the stray text. But unfortunately, there isn't any more information available...
