### ISSUE TITLE
Buttons not clearing correctly for additional products with an amount limit

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#3967]
### Problem and impact

When selecting an additional product with a limited amount for which a selection was already made, the checkbox of the previous selection is deselected, the button still has the selected styling though.

### Expected behaviour

The button should correctly reflect the state of the select box.

### Screenshots

https://github.com/pretix/pretix/assets/22835/14372cf1-3d15-443c-9869-f56b96155f19

### Browser (software, desktop or mobile?) and version

Safari and Firefox on macOS

### Version

2024.2.0

**Comment by wiffbi** [comment]
Thanks for pointing that out. I will look into this.
