### ISSUE TITLE
Webhooks - pretix.event.checkin, triggered on both Entry and Exit scans

### ISSUE THREAD

**Issue by JMillwood-92** [pretix/pretix#3974]
### Problem and impact

The web hook pretix.event.checkin triggers on both a Pretix Scan 'Entry' scan and a Pretix Scan 'Exit' scan.

I haven't been able to find a description of intended behaviour in the docs or a previous issue entry addressing the issue. 
Given that their is a pretix.event.checkin.reverted trigger and that the received webhook data, always presents the action as 'pretix.event.checkin' with no other entry to differentiate as an Entry or Exit scan, I am assuming that this is not the intended behaviour. 

### Expected behaviour

Trigger webhook pretix.event.checkin when an Entry scan is added
Trigger webhook pretix.event.checkin.reverted when an Exit scan is added.

### Steps to reproduce

Self-hosted Pretix, version: 2024.1.0
Setup a webhook with only pretix.event.checkin ticked.
Scan a ticket as entering event, webhook should be triggered.
Scan the ticket as exiting the event, and the webhook will again be triggered.

### Version

2024.1.0

**Comment by raphaelm** [comment]
This is in fact the intended behavior, reverted is something very different to an exit (reverted deletes a checkin log entry, exit is just another checkin log entry of a different type).

**Comment by JMillwood-92** [comment]
Understood, and thank you for your quick reply and clarification of expected behaviour. 

With this in mind and I appreciate I am now posing a question rather than an issue, (so please redirect me if appropriate). Is there a way to create a custom webhook that only fires on an entry or an exit scan? Or to include the type of scan in the array sent by the webhook?

**Comment by raphaelm** [comment]
I think since we already include the check-in list in the webhook body it would make sense to include the checkin type as well, yes.
