### ISSUE TITLE
Allow setting DISABLE_SERVER_SIDE_CURSORS for PostgreSQL configurations

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#4014]
### Problem and impact

We use Pretix with a PostgreSQL server and a PGBouncer in-between. We observe for example exports (in this case an Excel export) breaking on db cursor errors.

We are currently testing if passing [`DISABLE_SERVER_SIDE_CURSORS`](https://docs.djangoproject.com/en/3.0/ref/settings/#disable-server-side-cursors) solves the problem, it is however currently not possible to pass this to Pretix in the `pretix.cfg` file or (as far as we were able to determine) via an environment variable or equivalent.

Would adding an option for this be possible if the problem is solved with this db setting?

### Expected behaviour

All exports work even when using PGBouncer.

**Comment by raphaelm** [comment]
I'm hesitant – yes, not much of an effort and easily doable, on the other hand there's *so much more* that could break on pgBouncer and I'm not sure we want to go down that route :\

**Comment by thegcat** [comment]
I'm guessing except if you explicitly use PostgreSQL features that wouldn't work with transaction mode (cursors, prepared statements mostly) it should work, and it seems for now at least that we didn't encounter any problems except in that instance where Django/psycopg2 transparently uses cursors for you.

We'd be fine with a requirement for session pooling though if that's the official stance. Too bad for the extra resources we'd have to permanently allocate to Pretix instead of having them be distributed with the other apps using the DB, but nothing we can't handle.

**Comment by raphaelm** [comment]
Yeah. Would you be willing to create PR with the config flag?
