### ISSUE TITLE
Waiting list: Allow to reorder manually

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#406]
Allow the admin to manually move people up or down on the list to enhance their chances to get a ticket.

**Comment by danlls** [comment]
I can work on this. Since the ordering should persist, should I create a new column in `WaitingListEntry` that specific the priority of each entry?

**Comment by raphaelm** [comment]
Hi, yes, that would be required.

**Comment by danlls** [comment]
Should this function be limited to only those entry without voucher yet?

**Comment by raphaelm** [comment]
Yes.

Also, having up/down buttons like in the category/item list might be really cumbersome if you have many many entries. Normally, you probably only want to move important people up. So it might be worth considering actually allowing the user to edit the priority field directly instead of hiding it.

**Comment by danlls** [comment]
How about instead of letting them edit, having an additional button which send an entry to the topmost? Because wouldn't editing the number directly be cumbersome too if the list is huge?

**Comment by raphaelm** [comment]
I also thought about the button to set it to the top, but that gives really little flexibility.

The thing with editing the number directly is that one wouldn't need to fill in "1,2,3,4,5,6…" you could just use it as a real priority field like "1000 for the people I like best, 100 for some other people, 1 for the rest" and keep the natural order (date) within the ones with same priority. We could even give the priorities names (1-very low, 2-low, 3-medium, …) but I think just having an input field works as well if we explain it properly.

**Comment by danlls** [comment]
Alright! I guess allowing them to fill in arbitrary numbers would maximize flexibility. They can use it in all variation: "1,2,3,4,5,6, ..." or grouped like "1000, 100, 10, 1" or mix grouping and individual "1, 10, 100, 101, 1000".

**Comment by raphaelm** [comment]
Yep, I think that's good
