### ISSUE TITLE
Customer address on invoice missing

### ISSUE THREAD

**Issue by holgerm** [pretix/pretix#4097]
### Problem and impact

We had an event without invoices activated. Afterwards we noticed that we needed invoices and tried to create them. This works on a one-by-one basis manually in the backend, but the created invoices do not show the customers addresses, although the address infos had been given by all customers. What can we do about it?d

### Expected behaviour

I expect that for invoice creation the customer addresses are used and shown on the invoice.

**Comment by raphaelm** [comment]
The address is correctly shown as the "invoice address" when opening the order in the backend?

**Comment by holgerm** [comment]
It is shown as "Participants address" in the order. That looks the same as with another event we had earlier, where we had selected to create invoices in advance. In that older case all invoices include the customers addresses.

**Comment by raphaelm** [comment]
Invoice address and participamt address are separate fields. Maybe invoice address is not filled for this event or not even active (see invoice settings)

**Comment by holgerm** [comment]
Ok, I got it. We must enable "ask for invoice address" as well as "invoice address mandatory" (I do not know the exact wording in English). 

My suggestions would be:

1. when we select "ask for invoice address" then the flag "invoice address mandatory" should be true by default
2. the customer should be offered a button to copy the address from participanbt to invoice, so that in many cases she does not to enter the same information again.

Thanks
