### ISSUE TITLE
Embeddable Widget empty/disappears

### ISSUE THREAD

**Issue by richard-vock** [pretix/pretix#4102]
### Problem and impact

I have a widget (normal or compat) embedded linking to a shop in test mode (but open) and it shows as an empty div in Firefox and Vivaldi (while in the latter it even disappears after a few seconds in a dev deployment).

Neither browser logs, nor journalctl or `/var/pretix/data/logs/*.log` on the ticket server, nor the backend log of the website show *any* errors.

### Expected behaviour

Get an embedded widget or at least an error message.

### Steps to reproduce

My main HTML:
```
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="%sveltekit.assets%/favicon.png" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="https://tickets.bonner-brauschau.de/bonner-heimbrauer/testevent/widget/v1.css">
    <script type="text/javascript" src="https://tickets.bonner-brauschau.de/widget/v1.de.js" async></script>


    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
```

My relevant svelte component:
```
<script lang="ts">
</script>

<section class="relative overflow-hidden bg-amber-100 pt-16 sm:pt-24">
    <!-- Heading Container -->
    <div class="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
        <div
            class="mx-auto flex max-w-lg flex-col items-center sm:max-w-xl md:max-w-2xl lg:mx-0 lg:max-w-none"
        >
            <h1
                class="text-center text-4xl font-semibold leading-snug text-slate-900 sm:text-5xl sm:leading-snug md:mx-auto md:max-w-4xl xl:mx-0"
            >
                Ticketshop
            </h1>
        </div>
    </div>

    <div class="pretix-widget-compat" event="https://tickets.bonner-brauschau.de/bonner-heimbrauer/testevent/" single-item-select="button"></div>

    <div class="relative pt-16">
        <!-- Background -->
        <div class="absolute inset-0 flex flex-col" aria-hidden="true">
            <div class="flex-1 bg-amber-100"></div>
            <div class="w-full flex-1 bg-vanilla"></div>
            <div class="flex-1 bg-vanilla"></div>
        </div>


    </div>

    <div class="h-16 bg-vanilla sm:h-24"></div>
</section>
```

I tested diabling all my CSS selectors and browser extensions.

### Link

https://bonner-brauschau.de/tickets

### Browser (software, desktop or mobile?) and version

Firefox 124.0.1 and Vivaldi 6.6.3271.48

### Version

2024.3.0 (happened in older versions as well though)

**Comment by wiffbi** [comment]
You do not have any products/tickets to sell in your event, so the widget does not show anything. Not sure we should change that behaviour. But I guess we could log a message to the browser console. I will discuss with the team.

**Comment by wiffbi** [comment]
Huh, it did show the „powered by pretix“ when I looked at it yesterday!? Strange.

**Comment by wiffbi** [comment]
It gets better: when I reload, it shows the box with „powered by pretix“. Reload again, it does not. I will look into this.

**Comment by wiffbi** [comment]
I think it has something to do with docReady and how svelte sets up things. Whenever the widget is not loaded and I execute `window.PretixWidget.buildWidgets();` on the console, everything works. You might want to try to not automatically build the widgets, but do it manually in your svelte mounted callback (or whatever that is called). For how to manually build the widgets, see https://docs.pretix.eu/en/latest/user/events/widget.html#dynamically-loading-the-widget

**Comment by richard-vock** [comment]
Having a ticket available indeed fixes it.

The visibility of the empty box (it does have the "Event-Ticketing-Software von pretix" link at the bottom) depends on the browser and my guess is that it is due to the DOM tree shaking frameworks like svelte or vue do. That is just a wild guess though. I will give the manual setup a try.

Having an empty box as soon as contingents run out or deadlines pass really limits the versatility of the widget, so having at least some "There are no available tickets at the moment, if you have a voucher code click here..." message would greatly improve things from the user perspective.

**Comment by richard-vock** [comment]
Manually building on mount indeed circumvents this problem in my case - the widget no longer disappears.

For my specific needs this issue is resolved and can be closed. Tell me if you need further tests.
