### ISSUE TITLE
Time machine problem with product variants

### ISSUE THREAD

**Issue by KarlKeu00** [pretix/pretix#4201]
### Problem and impact

My aim is to create two product variants and to display one variant at a lower price until a certain date, and then the other. This also works, but not with the time machine.

### Expected behaviour

The time machine works.

### Steps to reproduce

1. Create at least 2 product variants.
2. Make one available until day X, the other from day X.
3. Set both product variants to be hidden if they are not available.
4. Go to the shop and set the time machine to day X.
5. The product that is available until day X is still there, the other does not appear at all.

### Operating system, dependency versions

Docker

### Version

2024.5.0

**Comment by raphaelm** [comment]
@luelista could you have a look if you can reproduce this, if you have the time?
