### ISSUE TITLE
Please more details in Docker-plugin-installation documentation

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#421]
I would like to install some plugins, but I need more informations about the process. Think of me as a user, who needs to know every step, especially when you write: "create a new directory": But where should the Dockerfile be placed? And do I need to create a dockerfile for every plugin? :)

**Comment by raphaelm** [comment]
Hi,

thanks for the feedback! :) I'd be happy to try to make it clearer, however I'm not yet sure how. Maybe we can first try to make it work for you and then you suggest a better wording?

> Think of me as a user, who needs to know every step, especially when you write: "create a new directory"

Well, you just need a directory. Any directory. Doesn't matter how its named, where it is, just that its an empty directory.

> But where should the Dockerfile be placed?

The docs currently say "create a new directory and place a file named Dockerfile in it".

> And do I need to create a dockerfile for every plugin?

No, you can change the ``RUN pip3 install pretix-passbook`` line in the Dockerfile as you want, for example ``RUN pip3 install pretix-sepadebit pretix-pages``

**Comment by saschafoerster** [comment]
See! Linux has thousands of folders for special purposes: I don't want to break anything and I am shure there is a file path just made for this kind of files. So please give me advice. :)

**Comment by raphaelm** [comment]
No, there is not, you can really just choose *any* directory. You can even throw it away later (although I'd advise you to keep it to save time on the next update)!
Docker just needs a Dockerfile with rules to build the image and that Dockerfile needs to be in a directory together with all other files that docker needs for the image. In our case, no other files are needed.

```
$ mkdir ~/pretix-with-plugins
$ cd ~/pretix-with-plugins
$ nano Dockerfile
$ docker build -t mypretix .
```

**Comment by saschafoerster** [comment]
Okay okay... :) But now at least I know the user folder is fine. ;)

**Comment by saschafoerster** [comment]
Hm; I don't know, what s wring: 
`docker build -t mypretix .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM pretix/standalone
 ---> cf7a14c55f53
Step 2/5 : USER root
 ---> Using cache
 ---> 794ae587ee9f
Step 3/5 : RUN pip3 install pretix-passbook
 ---> Using cache
 ---> 0c05d2f915b5
Step 4/5 : USER root
 ---> Using cache
 ---> f1105759c0d4
Step 5/5 : RUN make production
 ---> Running in d67a42187687
make: *** No rule to make target 'production'.  Stop.
The command '/bin/sh -c make production' returned a non-zero code: 2`

**Comment by raphaelm** [comment]
Hmm. Try replacing ``make production`` in the Dockerfile with ``cd /pretix/src && sudo -u pretixuser make production make production``. Does that help? might be a documentation bug that happened after we improved the docker file some time ago

**Comment by saschafoerster** [comment]
```
Step 5/5 : RUN cd /pretix/src && sudo -u pretixuser make production make production
 ---> Running in e7b3a54c45b8
Sorry, user pretixuser is not allowed to execute '/usr/bin/make production make production' as pretixuser on 33842653d6db.
The command '/bin/sh -c cd /pretix/src && sudo -u pretixuser make production make production' returned a non-zero code: 1
```
Seems not to work either.

**Comment by saschafoerster** [comment]
This seemed to work: I removed the second make production and used "USER root" in the 4th line. I hope this doesn't mean, that I created something with to many user-rights? 

```
FROM pretix/standalone
USER root
RUN pip3 install pretix-passbook
USER root
RUN cd /pretix/src && sudo -u pretixuser make production
```

**Comment by raphaelm** [comment]
Should be fine. I'll look into updating the documentation.

**Comment by raphaelm** [comment]
Ah, no, better try
```

FROM pretix/standalone
USER root
RUN pip3 install pretix-passbook
RUN cd /pretix/src && sudo -u pretixuser make production
USER pretixuser
```
Otherwise, pretix might be running with root permissions

**Comment by raphaelm** [comment]
I updated the documentation with the simplest solution that should also work: https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#install-a-plugin
