### ISSUE TITLE
RestAPI: Getting orderpositions by voucher_code returns all orderpositions

### ISSUE THREAD

**Issue by SqyD** [pretix/pretix#4253]
### Problem and impact

With the [endpoint for orderpositions](https://docs.pretix.eu/en/latest/api/resources/orders.html#get--api-v1-organizers-(organizer)-events-(event)-orderpositions-), using a query with 'voucher_code" doesn't filter by this voucher_code but instead returns all orderpostions. Using the voucher by id through the query "voucher" instead does work fine.

### Expected behaviour

orderpositions should be filtered by the voucher_code.

### Steps to reproduce

1. Create a voucher.
2. Create an order that uses the voucher and a least on other order that doesn't use the voucher.
3. Use the restapi orderpositions endpoint to query for the voucher using the 'voucher_code".
expected: only the order where the voucher_code was used is returned.
actual: all orderpositions are returned.

**Comment by wiffbi** [comment]
I am not sure whether that is due to some auto-formatting, but in your example you provide `voucher_code` (one underscore), but you need to provide `voucher__code` (two underscores) for the code-matching to work.

**Comment by raphaelm** [comment]
The docs might be wrong then

**Comment by SqyD** [comment]
It was the double underscore indeed. The documentation was right all along and I didn't spot the second underscore character. Closing this issue. Thanks!
