### ISSUE TITLE
Time machine not working for product related time settings in an event

### ISSUE THREAD

**Issue by ElectricDevDucK** [pretix/pretix#4271]
### Problem and impact

**General problem**
I wanted to create two products for events with personal meeting. Both products should be identical, just one of them should require approval and replace the other one 24 hours before the event. Since I offer multiple of those meetings, I therefore can not configure the time limits of availability within the product settings. Instead I used the "product settings" options within the event settings (below quotas). When doing so, the configured limits do not listen to time machine (in testing mode) but (only) behave accordingly to real time.

**Visibility vs. availability**
More exactly it has to be mentioned that only the visibility of those two products seems not to correspond to time machine, while the availability seems to correspond: If you set up the test case (see "Steps to reproduce"), you can notice that a product is shown as soon as real time is >x, while it cant be booked until time machine time is >x as well

### Expected behaviour

**General Problem**
Say x is time configured for end of product A and begin of product B: Then product B must be and should only be visible when time machine is set to >x. The same applies for product A when time machine is set to <x. Therefore in the general test scenario A should have become inactive, while B should have become active. 
Real time and its difference to x should never have any influence on the result.

**Visibility vs. availability**
Same principles apply here, therfore there should have been no change while waiting (and still only product A should be available). After change of time machine time to x+1 the should only product B be available and it must be bookable (which it is already).

### Steps to reproduce

**General Problem**
1. Create two products A & B
2. Create Event in the past (or future)
3. Activate both products in a quota (which is set to 1 in my example)
4. Below quota section use "product settings" section (inside event settings)
    - Set availability of product A to end at some time x before the event starts
    - Set availability of product B to start at the same time x
5. Open the shop in testmode and set time machine to x-1 minute and x+1 minute
     - Notice: No difference in event booking page!

**Visibility vs. availability**
1. Repeat all the steps with an event in past (or future)
2. Choose x only five to ten minutes in the future of current real time
3. Open the shop (in test mode) with time machine set to some time before x
4. Instead of Step 5 wait until real time x+1 
    - see that product visibility changes (A gets invisible while B gets visible) [requires refresh]
6. Notice that product B is visible but "not yet available".
7. Set time machine to x+1 again, see that product B has become available

### Operating system, dependency versions

unknown

**Comment by ElectricDevDucK** [comment]
This may be related to #4201

**Comment by luelista** [comment]
Thanks for the thorough bug report, PR #4371 should fix this.
