### ISSUE TITLE
Event time with timezone

### ISSUE THREAD

**Issue by jlwt90** [pretix/pretix#428]
It's actually a follow-up for #413.

>The rule of thumb in pretix (and Django) is: The database contains always UTC, the user always is shown and enters local time.

I asked this question because I found something interesting when creating event.
The scenarios are as follows:
1) Create new event using timezone `Asia/Tokyo`
![create-tokyo](https://cloud.githubusercontent.com/assets/25281597/23635820/37274f74-0315-11e7-86dd-806d867e7323.png)
After save:
![saved-tokyo](https://cloud.githubusercontent.com/assets/25281597/23635825/412aecc4-0315-11e7-90a7-51f940b411b0.png)
Both start and end time were changed with respect to the timezone I set. 
From **11:19:59 (GMT+9)** to **20:19:59 (GMT+9)**.
I guess we consider the start and end time as UTC time by default regardless of the timezone we set.

2) Change time only
![timezone-unchanged](https://cloud.githubusercontent.com/assets/25281597/23635947/feb85506-0315-11e7-9a84-cd9fc51c33e3.png)
As expected, it works well.

3) Change timezone of an existing event
![change timezone](https://cloud.githubusercontent.com/assets/25281597/23635955/0df7829e-0316-11e7-9ccb-60d0fb54efb2.png)
This time I changed the timezone from `Asia/Tokyo`(GMT+9) to `Asia/Singapore`(GMT+8).
![saved timezone](https://cloud.githubusercontent.com/assets/25281597/23635976/2da3fff0-0316-11e7-8f6a-2ddcce9f21c3.png)
Both times were changed from **08:50:56** to **07:50:56**.

I am quite new to pretix and not sure whether this kind of behaviour is expected.
From my opinion, I think user will only set event time using local time, which means it's better to include timezone value before we save data to database.

**Comment by raphaelm** [comment]
No, this is certainly not wanted and a bug. Thank you for finding and reporting this. The user should only ever see local time in the timezone the user wants.

**Comment by jlwt90** [comment]
I think I can help fix this bug but probably need some directions.
I went through the code related to the above behaviour:
```
url(r'^events/add$', main.EventWizard.as_view(), name='events.add'), # add event

url(r'^event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/', include([
     url(r'^settings/$', event.EventUpdate.as_view(), name='event.settings'), # update event
```

Apparently, there are 2 ways to fix the issue.
1) Modify `EventWizard` (probably `done` method) and `EventUpdate` (`post` method) for handling timezone switching
2) Update the `def save(self, *args, **kwargs):` in Event` module. I'll modify the datetime value with respect to the timezone in settings. I'm not sure whether it's a good practice to put some magic inside the model. 

Could you give me some hints?

Regarding the modification of timezone, I think the code below works.
Since we want to keep datetime value but `tzinfo`, I think I need to change it back to naive timezone, followed by `localize` (new timezone).
```
self.date_from = timezone(self.settings.timezone)
                             .localize(self.date_from.replace(tzinfo=None))
```

Thanks!

**Comment by raphaelm** [comment]
Hi! 

> Apparently, there are 2 ways to fix the issue.

From the top of my head, I would go neither for option 1 nor for option 2. ``EventWizard`` and ``EventUpdate`` are views, which are rather to high-level for this kind of thing and ``Event`` is a model which is rather to low-level for this. In my opinion, the golden middle road would be the **forms** involved, which are ``EventWizardBasicsForm`` and ``EventUpdateForm``. We could do it in the ``save()`` methods there but I think an even better way might be the ``clean()`` method in Django's validation cycle.

> Regarding the modification of timezone, I think the code below works.

It looks correct on first sight. A few tests will tell us later, if it was ;)

Cheers
Raphael
