### ISSUE TITLE
PDF ticket Unable to display Chinese

### ISSUE THREAD

**Issue by lipind** [pretix/pretix#4340]
### Problem and impact

The ticket given to the user does not display Chinese
![image](https://github.com/user-attachments/assets/00456cf5-0673-478a-8257-1582f34564a9)

### Expected behaviour

![image](https://github.com/user-attachments/assets/e9da8646-ebe6-45aa-8492-a5d859b83c68)

### Steps to reproduce

in PDF editor use chinese

### Version

Just installed, I think it should be the latest

**Comment by raphaelm** [comment]
it's a problem of the default font we use. You can install the plug-in pretix-fontpack-free. It adds fonts to your system and at least one of them should support Chinese.

**Comment by lipind** [comment]
Is my installation method incorrect? It shows that pretix fontpack free is installed, but the plugin folder cannot find it, so it still cannot display Chinese fonts.
```
root@debian:/home# source /var/pretix/venv/bin/activate
(venv) root@debian:/home# pip install pretix-fontpack-free
Requirement already satisfied: pretix-fontpack-free in /var/pretix/venv/lib/python3.9/site-packages (1.11.0)

python -m pretix migrate
python -m pretix rebuild

systemctl restart pretix-web pretix-worker
```

**Comment by lipind** [comment]
I noticed that Chinese tickets cannot be output on pretix.eu. pretix.eu installed pretix-fontpack-free?

**Comment by raphaelm** [comment]
Sorry, two misunderstandings here, I wasn't too elaborate on my phone over the weekend ;)

- The plugin only needs installation, no activation within the event
- In the ticket layout designer, you need to select a font for the text box that supports chinese character, such as "Noto Sans Simplified Chinese": ![image](https://github.com/user-attachments/assets/4fee1c8c-0f2e-4e85-86ff-095fd0e27a2a)

**Comment by lipind** [comment]
oh， Thank you for solving this problem perfectly.

I thought that in the ticket layout designer, I could change the font of all text objects, so I couldn't find it. 

**Clicking on a certain text object would bring up the Font option**
