### ISSUE TITLE
Cancellation and rebooking date is not displayed correctly

### ISSUE THREAD

**Issue by KarlKeu00** [pretix/pretix#4365]
### Problem and impact

The date until which rebookings can be made is not displayed correctly on the overview page. I don't know whether this error also affects the actual expiry date.

### Expected behaviour

If I set a different expiry date for cancellations or rebookings, I would also like it to be displayed correctly in the overview.

### Steps to reproduce

1. Set a different date until when cancellations and rebookings should be possible.
2. Go to the overview page.
3. The date of rebookings is not displayed correctly.

### Screenshots

<img width="670" alt="bsp-1" src="https://github.com/user-attachments/assets/7b8d7afc-fb9b-40cd-8f44-6d735bfa7621">
<img width="1159" alt="bsp-2" src="https://github.com/user-attachments/assets/d64f2592-0cf2-4999-b184-afea9ddd54a3">
<img width="1171" alt="bsp-3" src="https://github.com/user-attachments/assets/e453ad86-48f4-4c35-8483-49e50db2728d">
<img width="1181" alt="bsp-4" src="https://github.com/user-attachments/assets/5a6f0a68-585b-4669-a73f-ee285f8526cd">

### Operating system, dependency versions

Docker pretix/standalone:stable

### Version

2024.7.0

**Comment by raphaelm** [comment]
The "Umbuchungen" one is acutally missing in the timeline, the "nicht mehr bearbeiten" refers to modifying question answers. Still, we'll fix the bug.
