### ISSUE TITLE
Exports from event end with error (sales_channel column missing)

### ISSUE THREAD

**Issue by albwe** [pretix/pretix#4378]
### Problem and impact

When trying to perform any export from the Event -> Orders -> Export list, I get an error message:

Ein interner Fehler ist aufgetreten, bitte später erneut versuchen.

I've tried Abrechnungsbericht, Bestelldaten, Rechnungsdaten and "Alle Rechnungen". Before the update to 2024.7.0 I was able to do the "Alle Rechnungen" PDF export (others not tested). 

The logs state this error:

ERROR 2024-08-05 07:32:18,778 pretix.base.tasks tasks Unexpected exception: ProgrammingError('FEHLER:  Spalte pretixbase_event.sales_channels existiert nicht\nLINE 1: ...ing_plan_id", "pretixbase_event"."last_modified", "pretixbas...\n   

### Steps to reproduce

1. Select export type from Event -> Orders -> Export
2. Leave all options to default.
3. Click export.

### Screenshots

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/7a9f8881-069f-4186-b38e-317f8484448a">

### Browser (software, desktop or mobile?) and version

Safari

### Operating system, dependency versions

Uberspace 7

### Version

2024.7.0

**Comment by raphaelm** [comment]
You have likely not followed all scripts to update pretix to this version.

**Comment by albwe** [comment]
Thanks very much, I was likely following an incomplete tutorial to update. Sorry for your troubles.
