### ISSUE TITLE
Pretix fails to complete product reservation

### ISSUE THREAD

**Issue by nemanja-z** [pretix/pretix#4399]
### Problem and impact

Pretix can't process any order.

I followed the installation guide from [Pretix Documentation](https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html).

### Relevant Logs:

```Gunicorn Log:

gunicorn[237314]: WARNING 2024-08-15 11:40:34,408 django.request log Not Found: /coinsnap/summer24/&ajax=1

Nginx Log: recv() failed (104: Connection reset by peer) while reading response header from upstream
```

Similar to the issue reported here: (https://github.com/pretix/pretix/issues/4227), the only difference is that it occurs intermittently in his store, while it never works in mine. Additionally, he used Docker for deployment.

### Expected behaviour

The order should be processed.

### Steps to reproduce

1. Click Add to cart

### Link

https://pretix.coinsnap.org/coinsnap/summer24/

### Operating system, dependency versions

Ubuntu 20.04.6 LTS

### Version

2024.7.0

**Comment by raphaelm** [comment]
Is the pretix-worker component running? Can you check its logs?
