### ISSUE TITLE
Evaluate (and improve?) performance impact of metrics

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#441]
We should measure how large the performance impact of metrics is due to the redis latency and we should evaluate options to queue the redis commands and do them asynchronously after the request is processed -- or at least do them all at once a the end of the request.

**Comment by raphaelm** [comment]
Not urgent, as we currently only have two metrics per request at max, but nevertheless worth looking into.

**Comment by cherti** [comment]
@raphaelm 
Didn't a4ead5bd072d0432ebd973d48c6a57fea3faa415 already fix this?

**Comment by raphaelm** [comment]
@cherti For now, as we only do one histogram per request and as we pipeline histogram. Once -- if -- we add more metrics, it would be nice to have a generalized mechanism pipelining *all* redis queries within a request.

**Comment by cherti** [comment]
ah, IC. That's indeed true.

**Comment by raphaelm** [comment]
Hasn't shown to be a problem.
