### ISSUE TITLE
2FA setup wizard: Show private key

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#443]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

pretix supports [two-factor authentication](https://en.wikipedia.org/wiki/Multi-factor_authentication). You can find the according settings by clicking on your username in the top-right menu and then click "Enable" next to the "Two-factor authentication" item. If you click "Add a new device" and choose "Smartphone with the Authenticator application" as the device type, you are presented with a QR code that you can scan with the Authenticator [Android-](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2) or [iOS-App](https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8).

However, some devices might not have a (working) camera. For this reason, the Authenticator app also allows the user to manually insert the private key that is contained in the QR code. We currently do not show this code and the task of this issue is to make pretix show it.

## How to do this

Go to the template ``pretix/control/templates/pretixcontrol/user/2fa_confirm_totp.html`` and output the ``{{ secret }}`` variable in a nice way. Some applications like to hide the key by default and only have a (javascript-based) button to show it, but I think thats optional and does not need to be part of this issue.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by desponda** [comment]
@raphaelm Giving this one a try!

**Comment by raphaelm** [comment]
@desponda Have fun and say so if I can help!

**Comment by aph3rson** [comment]
@raphaelm Could I take a crack at this as well?

**Comment by raphaelm** [comment]
Hi @aph3rson, let's check with @desponda first if he is still working on it or busy with other stuff :)

**Comment by raphaelm** [comment]
Hi @aph3rson, would you be interested in #456?

**Comment by aph3rson** [comment]
@raphaelm I can take a crack at this if you're interested, now that I'm done with that other issue.

**Comment by raphaelm** [comment]
@aph3rson Sure, sounds good :)

**Comment by aph3rson** [comment]
I've submitted PR #490, which should handle this functionality.
