### ISSUE TITLE
Static files are not served

### ISSUE THREAD

**Issue by joa77** [pretix/pretix#4432]
### Problem and impact

Before 2024.8 the /media and /static files were served by pretix. Now these files are missing and resulting in a 404 (but they are generated properly and can be accessed by the file system).

Unfortunatly I'm unable to configure a reverse proxy, that points to the directory as explained in the documnentation.

### Version

2024.8

**Comment by raphaelm** [comment]
We used to integrate [dj-static](https://github.com/heroku-python/dj-static) which provided a fallback way to serve static files and media files. However, dj-static is no longer maintained, and as of recent Python toolchain upgrads, can no longer be installed. The recommended replacement is [WhiteNoise](https://whitenoise.readthedocs.io/en/latest/), however whitenoise is designed in a way that it can only be used for static files, [not media files](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files), since it only serves files already present at server start. There currently seems to be no solution for this in Django-land, as the recommended way is to use the reverse proxy – which has always been a part of all the official ways to install pretix.

May I ask why you are unable to configure a reverse proxy?

**Comment by felixrindt** [comment]
Ran into this as well. I'm running a pretix instance on uberspace and iirc their lab guide doesn't (yet) include instructions to explicitly serve the static and media files.

I just couldn't find out why pretix wasn't serving the static files anymore ore rather why it did at all before 2024.08. Now I know. ^^

**Comment by Wikinaut** [comment]
After upgrading just right now I ran into to very same problem using Apache2 reverse proxy. css and js files throw `404` errors. 

Is there a suggested way to fix this?

**Comment by deviserops** [comment]
Hi @joa77 

If you are only looking to serve static files might I suggest using django way to serve static file instaed of making changes with server and proxy config. This work in development and production both.

`You can also prefere this to serve static files. ` https://docs.djangoproject.com/en/5.0/howto/static-files/

## There are serveal ways to serve static files.

### Using github pages
If your static files don't have any dynamic dependency like uploading a file from app to `/media` or any code that you don't want to sahre. you can use github pages with setting up subdomain. like `static.web.com`

### Using another server
wherever you upload your project on server, I think that server also provide static file serve service. use that and it's free of cost.

Here is my config I used to serve static file on local development and on production server.

```python

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') != 'False'

# In your settings.py
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

if DEBUG:
    STATICFILES_DIRS = [
        Path.joinpath(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = os.getenv('STATIC_URL') if os.getenv('STATIC_URL') else 'static/'

MEDIA_ROOT = Path.joinpath(BASE_DIR, 'media')
MEDIA_URL = 'media/'
```

Also update your `urls.py`

```python

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

Template example:

```python
{% load static %}
<link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}" crossorigin="use-credentials">
```

Hope I understand right.

**Comment by Wikinaut** [comment]
Solution (upgrade from 2024.04 to 2024.11):

The two new lines make the proxy directive excluding these to subdirectories:

```
ProxyPass /static/ !
ProxyPass /media/ !
```

	

The new Apache2 proxy configuration serves static files directly, i. e. without the proxied pretix (pretix > 2024.7):

```

<IfModule mod_ssl.c>

# Apache2 configuration for pretix (tickets)
# 20241211
#
# IMPORTANT after having updated your pretix
# Always adapt the pythonX.Y version below to your configuration

<VirtualHost *:443>

	ServerName tickets.example.com
	ServerAdmin admin@example.com
	DocumentRoot /var/pretix/data/media/

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

	Include /etc/letsencrypt/options-ssl-apache.conf

        SSLEngine on

        ProxyVia On
        ProxyRequests Off
        ProxyPreserveHost on

	ProxyPass /static/ !
	ProxyPass /media/ !
        ProxyPass / http://localhost:8345/ retry=0 timeout=30
        ProxyPassReverse / http://localhost:8345/

	Alias /media "/var/pretix/data/media/"

	#
	# Always adapt the pythonX.Y version below to your configuration
	#
	Alias /static "/var/pretix/venv/lib/python3.9/site-packages/pretix/static.dist/"

	RequestHeader set X-Forwarded-Port "443"
	RequestHeader set X-Forwarded-Proto "https"

        <Directory /var/pretix/data/media/>
            AllowOverride All
            Require all granted
        </Directory>

        <Directory /var/pretix/venv/lib/python3.9/site-packages/pretix/static.dist/>
            AllowOverride All
            Require all granted
        </Directory>

	<Directory /var/pretix/data/media/cachedfiles>
	    order deny,allow
	    deny from all
	</Directory>

	<Directory /var/pretix/data/media/invoices>
	    order deny,allow
	    deny from all
	</Directory>

</VirtualHost>
</IfModule>

```
