### ISSUE TITLE
Add alternative text to the top-right navigation

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#444]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

If you look at pretix' backend (at /control/), you see in the top-right corner a link to your profile settings and a logout link. Also, plugins can add more links there. Currently, only the Log Out link has a ``title=""`` attribute that helps users who do not understand the icons (or screenreaders) to understand where the link goes. It would be nice to have this for all of them!

## How to do this

* Go to ``pretix/control/templates/pretixcontrol/base.html``. As a warm-up, add a title attribute to the user page link.
* Look at the ``{% for nav in nav_topbar %}`` loop. Change it such that the ``<a>`` tags have a ``title`` attribute based on the ``nav.title`` property.
* Go to ``pretix/control/signals.py`` and change the documentation of ``nav_topbar`` to indicate that this attribute can now be set by plugins.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by morrme** [comment]
Hi @raphaelm  !!!  Perhaps I could try this one?

**Comment by raphaelm** [comment]
Hi @morrme sure, go ahead! :)

**Comment by morrme** [comment]
@raphaelm great! excited to finally contribute! :)

**Comment by morrme** [comment]
@raphaelm what should the title of the User page be? "User Settings"?  "User settings" ?

**Comment by raphaelm** [comment]
I'd suggest it to be "Account settings" since this is the headline you get if you click on it 😉

**Comment by morrme** [comment]
@raphaelm OK that's done, now I am on to the documentation.  Do I simply add that the title  can be set by plugins, or is there something else you'd want to place here? I don't see a similar statement anywhere in the documentation, so I just want to be sure.

**Comment by raphaelm** [comment]
> Do I simply add that the title can be set by plugins, or is there something else you'd want to place here? I don't see a similar statement anywhere in the documentation, so I just want to be sure.

In signals.py, you see a commend with the following text:
```
This signal allows you to add additional views to the top navigation bar.
You will get the request as a keyword argument ``return``.
Receivers are expected to return a list of dictionaries. The dictionaries
should contain at least the keys ``label`` and ``url``. You can also return
a fontawesome icon name with the key ``icon``, it will be respected depending
on the type of navigation. If set, on desktops only the ``icon`` will be shown.
```

It should be enough to extend this text by saying that the ``title`` property can be used to set the alternative text.

**Comment by morrme** [comment]
@raphaelm Thanks so much for your support!
