### ISSUE TITLE
Lightbox visable when it shouldn't, Image Preview failed / Disable Image Loader

### ISSUE THREAD

**Issue by MrJico** [pretix/pretix#4440]
### Problem and impact

when using a self hosted version of pertix, if you enable custom domain, the lightbox container shows up in every page, which is not enabled by as. and we don't event know what is the purpose or how to enable the functionality.
i could trace back the element back to [lightboxjs](https://github.com/pretix/pretix/blob/v2024.8.0/src/pretix/static/lightbox/js/lightbox.js#L96) but couldn't figure out why it was trigered, when using a custom domain for the organizer.

this issue is very similar to #1219 

### Expected behaviour

the lightbox container should not be visible.

### Steps to reproduce

1. create an organisation
2. visit organisation seeings
3. add Custom domain
4. save
5. visit any page in the new custom domain or subdomain

### Screenshots

![image](https://github.com/user-attachments/assets/7501bd18-a3c7-4228-ac4b-f63e18f1bb71)

### Link

every page related to the organisation and events

### Browser (software, desktop or mobile?) and version

all browsers

### Version

v2024.8.0

**Comment by wiffbi** [comment]
Do you by chance use a CDN in front of your installtion? I remember seeing this behaviour with relation to using a CDN once. I do not know though what it triggered. I think the div#lightboxOverlay was created twice.

**Comment by MrJico** [comment]
its behind cloudflare reverse proxy, but i doubt that this causes the problem, because i already have a another organisation in the same install that doesn't have this issue.

**Comment by wiffbi** [comment]
Would you mind sharing a URL so we can have a look? I remember that the HTML served in the linked ticket already had the div#lighbox in it, which was odd as that should only be added through the lightbox js dynamically – so even with js disabled the spinning loader was visible.

**Comment by MrJico** [comment]
unfortunately i can't for now, because we are currently have an ongoing event, and we can't send the event link looking like that.
i can confirm that disabling JavaScript remove the container.

this is a snap shot when using the custom domain functionality, the only modifications are we removed any mention of our organisation.
the snap shot is taken using `wget -r link`
[sample.zip](https://github.com/user-attachments/files/16848172/sample.zip)

**Comment by raphaelm** [comment]
Search on the pretix issues for "cloudflare" and you'll quickly find that it is because of cloudflare and which cf option to disable :)
