### ISSUE TITLE
Enforce currencies to be a valid ISO code

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#446]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

Currently, when creating or editing an event, there is a free text field to enter a currency that accepts any inputs, for example one could enter both ``EUR`` and ``€``. However, when we communicate with APIs like PayPal, ``€`` will fail and only ``EUR`` will work. Therefore, the user also should only be able to input [ISO-4217](https://www.iso.org/iso-4217-currency-codes.html) codes.

## How to do this

Go to ``pretix/base/models/event.py`` and add a [choice attribute](https://docs.djangoproject.com/en/1.10/ref/models/fields/#choices) to the ``currency`` field of the ``Event`` model. Make sure the forms behave correctly when creating and modifying events. You could base the choices on [pycountry](https://pypi.python.org/pypi/pycountry), so we don't need to keep a list of our own.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by emersonmde** [comment]
I would love to give it a shot. I've been looking for a way to get into open source but a lot of projects have a high barrier to entry.

**Comment by raphaelm** [comment]
Hi @emersonmde, sure, go ahead and tell me if there are any problems!

**Comment by emersonmde** [comment]
I think I've got it, so I created a PR #452.

I forgot to run the tests/checks so I added a 3rd commit to clean up the first 2. Please let me know if it's better to just re-create the branch and pull request so there is only 1 commit.

Thanks for the info too! It was really helpful.

**Comment by raphaelm** [comment]
Hi @emersonmde alright, I'll look at the PR.

> I forgot to run the tests/checks so I added a 3rd commit to clean up the first 2. Please let me know if it's better to just re-create the branch and pull request so there is only 1 commit.

No worries, GitHub is able to squash that while merging, so that doesn't cause any issues.
