### ISSUE TITLE
[PDF Layouteditor] Text items: Questions which are assigned to Add-on products are selectable, but will not be printed

### ISSUE THREAD

**Issue by Wikinaut** [pretix/pretix#4460]
### Problem and impact

I noticed, reproducible:

When I assigned a question to an Add-on product, the question as such will be in the list of text items in the PDF Layout editor. So far, so good.

#### Problem ####
But when having selected an answer to that question and creating a ticket, t**he selected answer is not printed in the PDF.**

### Expected behaviour

When an text item (Variable) is selectable and selected to be part of the PDF, I expect that the answer is printed. But is not.

When I select the Main product (parent of the add-on), the answer is printed.

### Version

2024.7.1

**Comment by raphaelm** [comment]
This is not a bug, no field in the layout editor (except the list of add-ons) refers to the add-on or is supposed to do so.

For feature requests, please open a discussion, although I think this is not likely to be implemented. For example, what would happen if the question has different answers on the multiple add-ons a ticket can have?

**Comment by Wikinaut** [comment]
It appears to me, that I did not correctly describe my problem or you did not understand.

Let me explain again:

1. I have a Basis-Ticket (Conference)
2. The Basis-Ticket has one Add-on product the booking person can optionally book: a Workshop

When I define a Question (example): "How would you call the workshop?", I can assign the question to 1, or 2 or to 1 and 2.

The variable  "Answer to Question" is always selectable in the PDF Layout editor - please can you confirm this?
So I select and placed the "Answer to Question" somewhere in the PDF.

Now:

When you assign the Question to 1 (Basis-Ticket), the answer will be printed in the ticket pdf.
When you assign the Question to 1 and to 2, the question will be shown twice while booking (I did not check the answer-printing in the ticket pdf.

And now the bug:
When you assign the Question to 2 only, the given answer is not printed in the ticket pdf.

So for me it is a bug, when a question assigned to sub-product is selectable as variable in the PDF Layout but its answer is not printed in the ticket. Please try it.

**Comment by raphaelm** [comment]
I understood your situation. It is not a bug. The layout editor always unconditionally shows all questions. Layouts are created without knowledge of which products they later may or may not be assigned to.
