### ISSUE TITLE
Placing Emoji(s) 🎉 as part of an Add-on product description title prevents this Add-on product from being printed in the list of add-on products on ticket pdf

### ISSUE THREAD

**Issue by Wikinaut** [pretix/pretix#4466]
### Problem and impact

Placing Emojis as part of Add-on products prevents them from being printed in the list of add-on products on tickets 🎉

### Expected behaviour

Print the text of Add-on products exactly as assigned, or show an error message, if non-acceptable character sequences are part of the Add-on product title

### Version

2024.7.1

**Comment by raphaelm** [comment]
Can you share
- the text (incl. emojis) you are expecting in the list of add-on products
- a screenshot of the actual result
with us?

**Comment by Wikinaut** [comment]
You can try it at your office and will see, that "list of add-ons" is then empty.

**Comment by raphaelm** [comment]
Not reproducible.

Order looks like this:

![image](https://github.com/user-attachments/assets/111301da-68dd-4d63-a236-0702437e69c2)

PDF rendered like this:

![image](https://github.com/user-attachments/assets/ce515eec-a051-4dff-bc8e-026584e855dc)

Emojis are not supported by the PDF editor, but they also not break the rendering.
