### ISSUE TITLE
Manual payment: Deadline issue: deadline is taken from a global setting. Much more useful: separate distinct deadlines for distinct payment methods

### ISSUE THREAD

**Issue by Wikinaut** [pretix/pretix#4468]
### Problem and impact

"Eine Zahlung von 20,00 € steht für diese Bestellung noch aus. Bitte schließe deine Zahlung bis zum 30.09.2024 ab.
Barzahlung am Veranstaltungstag (11.11.2024)"

The text is misleading, a contradiction.
For "manual payment" method, a separate deadline setting is needed.

### Expected behaviour

For "manual payment" method, a separate deadline setting is (may be) needed.

### Version

2024.7.1

**Comment by raphaelm** [comment]
It is not a bug if you use a free text field to enter text that is contradictory to the system configuration.

We purposefully do not support different payment deadlines per payment method.

https://docs.pretix.eu/en/latest/user/faq.html#can-i-have-different-payment-deadlines-for-different-payment-methods

**Comment by Wikinaut** [comment]
Okay! Fine for me.
