### ISSUE TITLE
Auto-detect wrong placeholders in mail texts

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#448]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

There are two places in pretix where the event organizer can configure texts for emails. First, in the event settings the templates for various emails can be changed. Second, if you activate the "Sendmail" plugin for an event, there will be a navigation option allowing you to send mails to all users.

In both of these cases, there is a set of placeholders specified in the ``help_text`` of the form fields that allows organizers to include text snippets that are generated differently for every user, for example a link to the order.

The sendmail plugin already has a preview feature, the email settings are currently getting one (#308 #438). However, to prevent organizers from making embarrassing mistakes by sending out emails with invalid placeholders, we should try to validate them.

## How to do this

Create a [validator class](https://docs.djangoproject.com/en/1.10/ref/validators/) that validates that only the placeholders are used in a field, that are allowed in this field. This will require a bit of thinking and maybe some tinkering with regular expressions, but I'm sure you can do it and if you have trouble on the way, we are here to help.

Then, add this validator with appropriate arguments to the appropriate fields of ``MailSettingsForm`` (``pretix/control/forms/event.py``) and ``MailForm`` (``pretix/plugins/sendmail/forms.py``).

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions

**Comment by Alexeyisme** [comment]
Hi I'm just starting with Python and Django, and never contributed to Open Sorce. May I try to create that validator? 😄

**Comment by raphaelm** [comment]
Hi @Alexeyisme! Sure, go ahead! While this only requires you to touch very small parts of pretix (that's why it's great to get started), it is certainly not trivial, so please don't get demotivated too quickly and just ask if I can help :)

**Comment by Alexeyisme** [comment]
Hi, @raphaelm! I have a validator, that uses field's help_text's placeholders. Please take a look at it?
But I also still have open question about how to make it reusable using class based validator. Need some more time.
```python
class MailSettingsForm(forms.Form):
    text = forms.CharField(
        required=False,
        widget=forms.Textarea,
        help_text="Available placeholders: {event}, {url}, {invoice_name}, {invoice_company}, {payment_info}"
    )

    def clean_text(self):
        data = self.cleaned_data['text']
        allowed_placeholders = list(re.findall(r'({[\w\s]+})', self.fields['text'].help_text, re.X))
        data_placeholders = list(re.findall(r'({[\w\s]+})', data, re.X))
        invalid_placeholders = []
        for placeholder in data_placeholders:
            if placeholder not in allowed_placeholders:
                invalid_placeholders.append(placeholder)
        if invalid_placeholders:
            raise ValidationError(
                'Invalid placeholder(s): %(value)s',
                code='invalid',
                params={'value': ", ".join(invalid_placeholders)},
            )
        else:
            return data
```
Best regards and thank you again for such an opportunity!

**Comment by raphaelm** [comment]
Hi,

on first sight, this looks good! I did not test it in detail so far, though. Do you need help with the class-based validator?

Few thoughts:

* You got rid of the ``_(…)`` around the ``help_text``, which needs to stay there for translation. If you need to use it as a string later, just cast it to a string using ``str(…)``.
* Parsing the placeholders from the ``help_text`` is a clever idea. However, it will make the class-based validator harder. For me, it would be okay to drop that and make the class-based validator take a list of available placeholders as an argument. This would require them to be specified twice in the code, but that's okay, I'd rather auto-generate the help_text automatically at a later point in time.
* You also need to make the error message translatable, e.g. ``_('Invalid placeholder(s): %(value)s')``.

**Comment by Alexeyisme** [comment]
Hi, @raphaelm, You saved my life with second thought!) Because I have found no way to get to form field's help_text from validator yet!

Well then I got this. It takes list of valid placeholders as an argument:

```python
class PlaceholderValidator(BaseValidator):
    def __init__(self, limit_value):
        super().__init__(limit_value)
        self.limit_value = limit_value

    def __call__(self, value):
        data_placeholders = list(re.findall(r'({[\w\s]*})', str(value), re.X))
        invalid_placeholders = []
        for placeholder in data_placeholders:
            if placeholder not in self.limit_value:
                invalid_placeholders.append(placeholder)
        if invalid_placeholders:
            raise ValidationError(
                _('Invalid placeholder(s): %(value)s'),
                code='invalid',
                params={'value': ", ".join(invalid_placeholders)},
            )

    def clean(self, x):
        return x
```
What do you think?

**Comment by raphaelm** [comment]
Looks good :) Could you try integrating this for at least 1-2 form fields and create a pull request? This makes it easier to review and test the changes.

If you have trouble with the PR process, I'm here to help.

**Comment by Alexeyisme** [comment]
Integrated `PlaceholderValidator` into `MailForm` at (`pretix/plugins/sendmail/forms.py`). Checked locally, it works.
Made (my first) pull request. You've probably already seen it and I shouldn't write this here.
Ready to integrate to `MailSettingsForm` at (`pretix/control/forms/event.py`).

**Comment by raphaelm** [comment]
Congrats for your first PR! *high-five* Let's go over there to discuss details. 😉
