### ISSUE TITLE
Voucher quantity limits to 10 even though Maximum amount per order is blank

### ISSUE THREAD

**Issue by jxs714** [pretix/pretix#4485]
### Problem and impact

When I setup a voucher code to have 15 uses, when checking out the check out only allows 10 uses on one order. The setting "Maximum amount per order" is left blank for the specific ticket. The only way to bypass the limit is to enter a number like 15 or higher (in my case) in the "Maximum amount per order" section.

### Expected behaviour

As the description says in "Maximum amount per order", leaving it blank should work without having to enter a number for limits

### Version

2024.8.0

**Comment by raphaelm** [comment]
There is a "maximum tickets per cart" in the Settings > General > Cart part of an event which defaults to 10.
