### ISSUE TITLE
Show and change the locale of an order

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#449]
**Hey!** If you ever wanted to contribute to an Open Source project, but didn't know how, you just found a perfect place to start. We try to write this issue as instructive as possible, but as we're humans we almost certainly forgot to write something important in here. If you want to try to tackle this issue and get stuck at _any_ point, please do not hesitate and ask us, either here on GitHub or via email at support@pretix.eu. We'll be very happy to help! 

We think this issue is very suitable to people who are just starting with Python or Django development or who never contributed to Open Source before. We'd like to ask people with wide experience in these areas to leave this issue to beginners. Thanks! (If you want something more advanced, just drop us a line, we'll find something :wink:)

## How to get started

First of all, you need pretix running locally on your machine. We have a guide on the developer installation [over here](https://docs.pretix.eu/en/latest/development/setup.html). Play around with it and get a feeling for what pretix is and how it works :) Try to find the places in the interface mentioned in this issue where something needs to change. Maybe try to find the same places in the code? Just searching for characteristic words can be a powerful tool to find your way around.

## What this is about

Every ticket order in pretix has a locale associated. This is the language that was active for the user when the user created the order and it is the language that will be used whenever emails are sent to the user etc.

Currently, it is neither possible for the organizer to know which language that is, nor to change it. Both would be very useful, for example if the organizer wants to communicate with a user through another channel.

## How to do this

* Display the order locale in the order details section of ``pretix/control/templates/pretixcontrol/order/index.html``.
* Create a new view and a new form that allow to change the locale. You can get inspiration from ``OrderContactChange`` (``pretix/control/views/orders.py``) which changes the email address of an order and is therefore quite similar.

## I want to give it a try!

You're still reading, nice! If you want to try working on this, please comment below, so everyone else knows this is being looked at and can search for a different place to contribute. 

First, [fork](https://github.com/pretix/pretix/fork) the repository to your own GitHub account. Then clone it locally (or [set it as your remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) if you already cloned it earlier) and prepare your pull requests. There are a number of tutorials on the Pull Request workflow online, for example this [short version](https://guides.github.com/introduction/flow/) by GitHub itself and this [more in-depth tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). We're excited to see your pull request! 

And don't forget: If you get stuck, don't hestitate to ask. We bound ourselves to a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html) and we're committed to providing a welcoming experience and giving constructive, friendly and useful feedback on your contributions.

**Comment by raphaelm** [comment]
Good choice, give it a try and let me know if there are any problems.

FYI, I'll travel to DjangoCon Europe on Sunday, so I might be a bit slow with replying but I will reply ;)

**Comment by alainrk** [comment]
Hi @raphaelm, I am recently approaching to bigger open source projects to collaborate on in my free time, and I am coming here from a couple of article about first-timers-only github tag. My congratulations for pretix! :)

Currently, I am setting up the requirements in the virtual environment, but I got stuck on the following error executing `pip3 install -r requirements.txt -r requirements/dev.txt`

` Running setup.py install for rjsmin ... error
    Complete output from command /home/narko/code/pretix/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0xoef12w/rjsmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tjtgmfd2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/narko/code/pretix/env/include/site/python3.4/rjsmin:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    copying ./rjsmin.py -> build/lib.linux-x86_64-3.4
    running build_ext
    building '_rjsmin' extension
    creating build/temp.linux-x86_64-3.4
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/home/narko/code/pretix/env/include -I/usr/include/python3.4m -c rjsmin.c -o build/temp.linux-x86_64-3.4/rjsmin.o
    In file included from rjsmin.c:18:0:
    _setup/include/cext.h:34:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Thank you in advance!

**Comment by raphaelm** [comment]
Hi @alainrk, welcome to pretix! For problems like this the best is you open a seperate issue with this, so we don't spam @rahmonov and we can keep track of that we improve our documentation. For your issue, can you try installing the packe ``python3-dev`` if you are on Debian or the equivalent if you are on a different distribution?

**Comment by alainrk** [comment]
Sorry @raphaelm, and thank you for your help, the installation of `python3-dev` solve the problem. I am on Debian based system.

**Comment by raphaelm** [comment]
No worries, glad I could help :)

**Comment by raphaelm** [comment]
@alainrk Would you mind making your first pull request to the project by adding it to the package list in the developer documentation? ;)

**Comment by asv-hungvt** [comment]
Hi, @raphaelm! 
How is this issue going? I also would like to try this task. :)

**Comment by rahmonov** [comment]
@raphaelm @asv-hungvt sorry for the delay. I am planning to work on it today. Thanks

**Comment by raphaelm** [comment]
@asv-hungvt are you interested in #454?
