### ISSUE TITLE
Reauth with Redirection Auth Backend does not work

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#4498]
### Problem and impact

Using OIDC Authentication using a pluggable authentication backend users will get thrown into a loop when they need to reauth, i.e. reauth page > OIDC authenticator > oidc callback > reauth page.

The logs suggest that the login was successful:

```test
INFO 2024-10-01 17:28:02,653 pretix.control.views.auth auth Backend login successful for user 7.
```

But the session seems to lack some information to get out of the reauth.

### Expected behaviour

The successful login after the reauth should lead to a working sessions.

### Steps to reproduce

1. Login using https://github.com/thegcat/pretix-oidc
2. Wait 3 hours and a bit
3. Reload a Pretix page
4. Click on the "Continue" button on the reauth page
5. Some OIDC dance
6. Be back on the reauth page.

I have followed the different URLs/redirection in my browser. The order is:
1. GET https://pretix/control/reauth/
2. GET https://oidc-provider/authorize
3. GET https://pretix/oidc/callback/ (from I can gather the "Backend login successful" happens here)
4. GET https://pretix/control/
5. GET https://pretix/control/reauth/

### Version

2024.9.0

**Comment by thegcat** [comment]
I'm not quite sure this is something that is a bug in the OIDC plugin or in Pretix. From my understanding of the Authentication plugin docs the OICD plugin works as expected.

I have followed the reauth problem up to https://github.com/pretix/pretix/blob/master/src/pretix/helpers/security.py#L78 where the `pretix_auth_last_used` us checked, but it seems to not get explicitly updated in https://github.com/pretix/pretix/blob/master/src/pretix/control/views/auth.py#L75. `pretix_auth_login_time` is updated there, I don't know if `pretix_auth_last_used` should also be updated or gets updated there but in some other method.

**Comment by raphaelm** [comment]
Yes, I believe setting `pretix_auth_last_used` in `auth.py` would be the correct solution. Would you interested in testing if that helps and preparing a PR?

**Comment by thegcat** [comment]
It helps in our setup. I was trying to write a test and call `process_login` directly in the test to check the session afterward, but I don’t know how’d I access a request I object for the method in 3deb833f9. I guess I‘d need to create a mock view that a `self.client.get` could exercise in full?

**Comment by raphaelm** [comment]
Yeah, that's a weird layer to test at. You could try if you can solve it with https://docs.djangoproject.com/en/5.1/topics/testing/advanced/#the-request-factory

**Comment by thegcat** [comment]
I'll have a look thanks. And I'd be open to pointers on how to better test it, either another place where it would fit better or as a test with a fake authentication plugin instead of trying to look specifically into the session.

**Comment by thegcat** [comment]
See #4512. The test is probably far from good, but it's a test at least.
