### ISSUE TITLE
Improve color scheme

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#450]
Currently, we are using the following three shades of our brand color within the UI:

![c_b](https://cloud.githubusercontent.com/assets/64280/24543694/cae8bda8-1600-11e7-971b-da40eb17e79e.png)

I want to keep the brand color as it is and I want to keep it for the top navigation bar. However, I'd be looking for a different (darker?) shade as a link color because the current one feels a bit aggressive.

The bigger problem is that we currently still use Bootstrap's default colors for accents:

![c_a](https://cloud.githubusercontent.com/assets/64280/24543729/ea510a1a-1600-11e7-89b0-bd00dafe98fc.png)

They are not fitting our brand color at all and I'd love to change them for something better. Any comments or suggestions are welcome. I'll try to come up with a suggestion of my own as soon as possible.

Thanks to @janx2 for pointing this out to me again :)

**Comment by raphaelm** [comment]
I played around a bit in [HCL space](https://www.vis4.net/blog/posts/avoid-equidistant-hsv-colors/).
![2017-03-31-124424_912x222_scrot](https://cloud.githubusercontent.com/assets/64280/24547406/e2a53fe8-160f-11e7-981a-374b1146f024.png)

If you want to play yourself: https://jsfiddle.net/orp3pknx/9/

**Comment by debugduck** [comment]
I know you've already played around with this, but I'd like to give it a try too, if you haven't already decided to change it?

**Comment by raphaelm** [comment]
Well, I have decided that it should be changed, but I'm not happy with my color proposals yet. Feel free to come up with new ones, I'd be more than happy!
