### ISSUE TITLE
Pytest fails on test_updatecheck.py on fresh install

### ISSUE THREAD

**Issue by alainrk** [pretix/pretix#453]
I get this error on `python3 -m py.test` for the fresh pretix clone:

`ERROR collecting tests/base/test_updatecheck.py`

`tests/base/test_updatecheck.py:5: in <module>
    import responses
E   ImportError: No module named 'responses'
==== 926 passed, 1 skipped, 1 error in 107.04 seconds`

Thanks!

**Comment by rixx** [comment]
Did you install the dev dependencies? Try `pip install -U requirements/dev.txt`, this pulls in responses, which has been added less than a day ago.

**Comment by alainrk** [comment]
Oh thank you, it works!
