### ISSUE TITLE
Admin email getting set to empty string, breaking login

### ISSUE THREAD

**Issue by lutoma** [pretix/pretix#454]
One of the admins of our pretix instance recently complained about not being able to log in anymore. After a bit of testing I had a look at the database and noticed the `email` field for the user was empty. Since the login is email-based, that of course breaks it.

![2017-04-04-17 22 13](https://cloud.githubusercontent.com/assets/179393/24664723/affa6362-195b-11e7-967d-acf2fa2d32a6.png)

I definitely didn't manually remove the email using the Django shell or in the database, so I'm not really sure how it happened. If you have any ideas, I'm happy to debug. After manually setting the email in the database the login worked again.

Potentially relevant:
* That account was the only one that had 2fa enabled.
* We have multiple superusers / accounts with `is_staff` set to true. I'm not sure if that's supported, but it worked so far.
* That account was the only one with a `fullname` set.
* I run pretix with Postgres

**Comment by lutoma** [comment]
Upon further investigation, it seems you can just set your email to emptystring by going to `/control/settings`, clearing the email field and entering your password.

**Comment by raphaelm** [comment]
Well, that's a bug. Thanks for reporting!

**Comment by AV-room** [comment]
I'm new to github and would like to have a go at this if it's still available!

**Comment by raphaelm** [comment]
Sure @AV-room, go ahead!
