### ISSUE TITLE
Change name of ticket owner within pretixcontrol

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#472]
Hi,
it would be great to have the possibility for the event organizers to change the name of ticket owner within pretixcontrol.
![image](https://cloud.githubusercontent.com/assets/6865786/25273979/73c98eaa-268e-11e7-9549-5e9de91a5455.png)
I know that there already exists a possibility to change the name via the customers order page, but I think this is disabled after the `last_order_modification_date`, isn't it?

I could imagine that this is a good task for first-timers.

Thanks and best regards,
Jan Felix

**Comment by raphaelm** [comment]
Yep, that would be useful.

> I know that there already exists a possibility to change the name via the customers order page, but I think this is disabled after the last_order_modification_date, isn't it?

Yes. In as sense, this is therefore related to #190.

> I could imagine that this is a good task for first-timers.

I'm unsure here, for two reasons:

* It makes only that much sense to add changing the name without changing the answers to event-specific questions, and questions are not easy
* Despite all my tries to keep it simple, I fear that ``OrderChangeManager`` not a good way to start into the project :see_no_evil:
