### ISSUE TITLE
Assign questions to product variations, not only products

### ISSUE THREAD

**Issue by codingcatgirl** [pretix/pretix#474]
Some variations may require additional questioning. Currently I have to add each variation as its own product instead.

**Comment by niklasberlin** [comment]
Any news on this this Topic? we would also be very intrested in questions for variants

**Comment by raphaelm** [comment]
No, not so far. This is one of those hard trade-offs between usefulness and simplicity. Our backend interface is already swamped with options and our code already contains lots and lots and lots of special cases, so we're always hesitant to add more. I assume this will need to happen at some point, though.
