### ISSUE TITLE
Enforced base version constraints for plugins

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#480]
Plugins should be able to specify a minimal version of pretix they are compatible with.

**Comment by dnsmichi** [comment]
I can see that the banktransfer plugin implements the compatibility_warnings method where plugin authors could implement this on their own, with the little help of `from packaging import version`. Works quite good and is enough for me - I don't care about dev versions :)

![Screen Shot 2019-03-20 at 14 06 01](https://user-images.githubusercontent.com/382049/54687628-5a707e00-4b1c-11e9-91af-02d305c44ecd.png)

**Comment by raphaelm** [comment]
That's great! The only problem with it is that it works on pretix-level, i.e. if there is a hard incompatibility (e.g. the plugin imports a thing that doesn't yet exist), pretix will not start and you never get to see the message. When creating this bug, I was more thinking of a solution on python-package level.

**Comment by dnsmichi** [comment]
Yep, agreed. I thought about this while playing around with it too. We would need to extend the `required_packages` in setup.py ... 

```
install_requires = [ "pretix>=2.5.0", "packaging" ],
```

The main problem is that `python3 setup.py install` will then automatically upgrade the pretix package, which isn't really what we want here. 

Instead, plugin authors could put something like this into their setup.py

```
from packaging import version
from pretix import __version__ as appVersion

required_core = '2.5.0'

if version.parse(appVersion) < version.parse(required_core):
    raise Exception("Pretix version %s is too old. Minimum required is %s." % (appVersion, required_core))
```

This requires a hard dependency on the `packaging` library though with `install_requires = [ "packaging" ],`.

Still, a simple field in the `PretixPluginMeta` would be more sufficient, with code then checked in base/plugins on a more generic basis, hiding this from plugin devs.

**Comment by raphaelm** [comment]
Agreed

**Comment by raphaelm** [comment]
Turns out, there is an easy solution, just place 

```
import pkg_resources
pkg_resources.require("pretix>=2.7.0")
```

in your ``__init__.py``. However, since I like nice error messages, I even made this an explicit thing through a ``compatibility`` property of ``PretixPluginMeta`` starting in pretix 2.7.

**Comment by dnsmichi** [comment]
Thanks for taking care - I lost the time battle against Icinga issues ;-)
