### ISSUE TITLE
Handle vouchers with expired items

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#489]
Hi! When redeeming a voucher for a product where `available_until` is before today, the list for available products is empty and there is no error message.
![image](https://cloud.githubusercontent.com/assets/6865786/25973976/b4a79a5c-36a6-11e7-8d94-9a495951e971.png)
As a user, I would expect
- to buy the ticket regardless of `available_until`, or
- to get an error message

Thanks for your awesome work and with best regards,
Jan Felix

**Comment by raphaelm** [comment]
Hi Jan Felix,

good point. I see that alternative (1) could be useful, but giving an error message seems more appropriate as it doesn't come as a (unwelcomed) surprise to organizers. So we should probably give an error message for now.

This should be a non-trivial, but fairly easy fix and I therefore mark this as an easy ticket. If anyone would want to take this on and needs more information, feel free to ask or contact me.

Cheers
Raphael

**Comment by captaincrunch21** [comment]
Hey I want to fix this Can you assign this to me and help me

**Comment by raphaelm** [comment]
Hey @captaincrunch21, sure, go ahead, I marked this as assigned. What kind of help do you need? Did you unterstand what this is about or do you have more questions on this? A good start is to get pretix running locally on your computer: https://docs.pretix.eu/en/latest/development/setup.html

**Comment by chadapohn** [comment]
Hello, @raphaelm. Can I give this one a try? :)

**Comment by raphaelm** [comment]
Hi @chadapohn, let's see if @captaincrunch21 is still working on this?

**Comment by raphaelm** [comment]
@chadapohn if you're still interested, I think it would be free…

**Comment by sambit-m** [comment]
Hey @raphaelm! I'm a first timer and want to fix the issue. I'm going to read the developer documentation.

**Comment by chadapohn** [comment]
Hi @raphaelm, I'm really sorry for late reply. Now I'm reading the developer documentation and trying to run Pretix on my computer.

**Comment by sambit-m** [comment]
@chadapohn I guess, you're doing it then!

**Comment by raphaelm** [comment]
Hi @sambit-m and @chadapohn, this gets to confusing for me to decide who's doing what now. If one of you wants to look at something else #629 might be fitting

**Comment by BenHagan** [comment]
![image](https://user-images.githubusercontent.com/2807012/32208985-e809e18e-bdd3-11e7-8449-3ba2961266d9.png)

This what I came up with #659.

Currently the patch handles when the current date is past `Items.available_until`, shouldn't we also have it handle when the current date is before `Items.available_from`?

**Comment by jfwiebe** [comment]
Lovely, thank you @BenHagan !
