### ISSUE TITLE
Add CheckIn-lists

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#515]
As discussed over in https://github.com/pretix/pretixdroid/issues/12, it would be nice to have some kind of checkin-lists that can then be used by pretixdroid.

## Concept
As of pretix 1.4, you can get a nice overview of people that have already been checked in (using pretixdroid) by navigating to Orders > Check-ins. You can even filter the list by a single product.

For the future, it might be nice to be able to have "views" of multiple products that can be defined by the user. Each group of multiple products that are grouped together is a CheckIn-list.

For example, one could create a CheckIn-list by the name of "Merchandise" which includes all merchandise-related products.

Such a list can also be printed out for checking in people by hand.

In a second step (which can be implemented once this is working), we can tie the Authorization-Token generated for Pretixdroid to one of the checkin-lists. I will outline this in a separate issue.

**Comment by raphaelm** [comment]
It should probably be more than just a "view", it should be some first-class object that check-ins are attached to. This allows you to have e.g. two check-in lists featuring the same products, for example one for the entry and one for the badges (see e.g. CCC Camp). Then, you can use pretixdroid to scan tickets and every ticket can be scanned exactly once at the entry and once for the badge.

**Comment by pc-coholic** [comment]
Oh, okay... That is going even further than what I anticipated...

In my mind, I would have kept the "one order position can only be scanned once". For your example that would mean though, that you would need to give every participant two tickets: one entry-ticket and one badge-ticket...

Not to argue - but I feel like allowing to have a single item to be checked in multiple times could cause some confusion...

**Comment by raphaelm** [comment]
> In my mind, I would have kept the "one order position can only be scanned once". For your example that would mean though, that you would need to give every participant two tickets: one entry-ticket and one badge-ticket...

Hmm. I think the level of abstraction that I suggested is not that confusing as you have a very powerful metaphor available: It works the same way as if you would print out two lists and check them sepeartely by hand.

(Also, it's what Tito is capable of… :D)

**Comment by raphaelm** [comment]
pretix has been accepted as a finalist into the [prototype fund](https://prototypefund.de/). If everything goes well, this will be part of the project scope and therefore most likely happen while I'm funded by them (September–February).

**Comment by pc-coholic** [comment]
That's great news :)

Congrats :)
