### ISSUE TITLE
Prevent gaps in plugin list

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#516]
flexbox in column direction would be nice, but would kind of destroy ordering.

![2017-06-11-151115_1457x420_scrot](https://user-images.githubusercontent.com/2657547/27011266-6bf96446-4eb8-11e7-8217-95c02774c01c.png)

**Comment by raphaelm** [comment]
Why don't we do it like in the event dashboard? Does that break for varying heights?

**Comment by aph3rson** [comment]
How are these ordered at the moment?

I know I've seen [driveway](https://github.com/jh3y/driveway) used before, but I don't know if that's a hammer-for-a-fly level of overkill.

**Comment by raphaelm** [comment]
> How are these ordered at the moment?

Currently, this is a standard Bootstrap ``row`` with many many ``<div class="col-md-6 col-sm-12">`` elements. The order is more or less arbitrary (which is a similar problem to #492).

Driveway looks amazing but yes, it seems like a little bit overkill.

As long as the ordering is arbitrary, distributing them to two columns would work fine. But at some point, we'd probably like to have some ordering among them. We could use a new ``row`` for every other plugin, which would lead to to different, more predictable gaps (but still gaps). Or we could trop the two-column layout altogether. Or set a maximum height. So many options… :D

**Comment by danlls** [comment]
Depends on browser support requirement, using flexbox can fix this problem, but IE<10 doesn't support flexbox.
See http://caniuse.com/#feat=flexbox to see full list of browser support

Without flexbox:
![beforeflex](https://user-images.githubusercontent.com/28383090/28103012-e1be0d98-6705-11e7-89a3-ce6fd047196b.png)

Using flexbox:
![afterflex](https://user-images.githubusercontent.com/28383090/28103013-e9859514-6705-11e7-8faf-9733587627cd.png)

**Comment by rixx** [comment]
pretix is already using flexbox in other places, so I don't think compatibility is an issue.

**Comment by raphaelm** [comment]
Yes, I believe in this place flexbox is fine. Would you like to create a PR?

**Comment by danlls** [comment]
Alright, I'll submit a PR for this.
