### ISSUE TITLE
Change navpill look in email template editor

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#517]
When editing email templates, there are nav pills provided below the i18n input, to switch between edit and preview mode.

To me, they looked like buttons, and I assumed at first that the "Edit" button was meant to save progress. I think this is because normally a very similar looking button is provided at the same relative location (lower right hand corner), and nav pills are normally left-aligned and to the top.

Off the top of my head, I'd probably expect an explicit switcher/toggle button between the two modes.

![2017-06-12-152940_1342x260_scrot](https://user-images.githubusercontent.com/2657547/27036069-f8a3d3a6-4f83-11e7-974f-e6a660fa00ed.png)

**Comment by raphaelm** [comment]
Of something tab-like *above* the input

**Comment by tydonk** [comment]
I'd like to give it a try.  I'm running in dev mode but I couldn't find this page, in browser or source code.  Could someone point me in the direction to start?  Thanks

**Comment by rixx** [comment]
Under Settings > E-Mail > E-Mail content you can edit and preview the templates; that is where my screenshot is from.

The template is at `control/templates/pretixcontrol/event/mail_settings_fragment.html`

**Comment by tydonk** [comment]
Thanks for the path.  I'm still not sure how to view this in the browser.  When I run the server in development mode and login at `localhost:8000/control/login` it takes me to the dashboard.  How do I view the front end in dev mode?  Sorry for the stupid question, I read through the Dev docs and didn't see an answer.

**Comment by rixx** [comment]
It's not a stupid question at all! Since this is an event specific setting, you'll need to create a test event from the dashboard. You can use `python make_testdata.py` to generate an event with reasonable settings, products etc configured.

Also, if you see a way to make this clearer in the docs, don't hesitate to put it in a pull request!

**Comment by tydonk** [comment]
As usual, user error was the issue :) I wasn't logging in as admin@localhost.  Should be good to go now.  Thanks!

**Comment by tydonk** [comment]
Which do you like better?  IMO with the positioning in the top left, the nav pills look better than the tabs.

Tabs - ![screen shot 2017-06-21 at 11 49 02 pm](https://user-images.githubusercontent.com/13215301/27420821-7f10e5dc-56dc-11e7-986e-0d0f132ae1d3.png)

Pills - ![screen shot 2017-06-21 at 11 49 33 pm](https://user-images.githubusercontent.com/13215301/27420825-81b0b3e4-56dc-11e7-882c-2b163ae7200e.png)

**Comment by raphaelm** [comment]
I agree, in your example, the pills look better. I asked for tabs, because something put them right in my face when I wrote this ;)
![2017-06-22-110229_815x273_scrot](https://user-images.githubusercontent.com/64280/27425933-54dba730-573a-11e7-8bba-495f8f22fed5.png)
I think tabs *might* still look better, but it'd require some CSS magic to make their borders merge with the textarea. If you have fun playing with that, go ahead, if not, do a pull request with pills :)

**Comment by rixx** [comment]
Hmm, I guess navpills are also more in line with pretix's look in general.

**Comment by tydonk** [comment]
I'll play with the CSS and try to make the tabs look better

**Comment by tydonk** [comment]
Is this close to what you had in mind?
![screen shot 2017-06-22 at 2 35 50 pm](https://user-images.githubusercontent.com/13215301/27458091-3c981eb6-575c-11e7-9ab2-a56390520e42.png)

**Comment by raphaelm** [comment]
Yep, that looks good!
