### ISSUE TITLE
Document the cookiecutter template for plugins

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#521]
Plugins follow a fairly rigid structure, and a cookiecutter template would reduce set up time when starting a new plugin. (At the moment, I just copy an existing plugin, delete unused files and grep for that plugin's name repeatedly … 😨 )

**Comment by raphaelm** [comment]
*cough* https://github.com/pretix/pretix-plugin-cookiecutter *cough*

**Comment by rixx** [comment]
*cough* https://docs.pretix.eu/en/latest/development/api/plugins.html#pluginsetup *cough*

Reopening as documentation issue.

**Comment by raphaelm** [comment]
Fixed as part of https://github.com/pretix/pretix/commit/4b12678fa4c2af31dc0dd47e8ef1503c29d3a1f6 :)
