### ISSUE TITLE
Ordering tickets after payment period

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#522]
In my test setup, I ran into this issue:

 - I was within my presale period, but outside my accepted payment period
 - I bought a ticket with a voucher
 - After successful ordering, my order page showed the order status as 'Pending' and notified me, that my chosen payment method (`None` when I used a voucher with price 0, by the way) should have already been completed and could not be accepted anymore.

While this configuration is unlikely to appear in the wild, I'd call this at the very least a UI bug, regarding the "None Please complete your payment before <date>." when redeeming a free voucher.

Imo, a payment provider that is not usable anymore should not be selectable in the payment process.

![2017-06-18-143358_1188x920_scrot](https://user-images.githubusercontent.com/2657547/27260716-8cdcc380-5433-11e7-98aa-cfe0d0d7bc78.png)

**Comment by raphaelm** [comment]
This is somehow what we should have already prevented when we fixed #316. Probably, we should close the shop down completely at the last date of payments to avoid confusion.
