### ISSUE TITLE
Webhook API

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#526]
pretix should be able to send webhooks to external services e.g. on new orders or payment events.

**Comment by raphaelm** [comment]
This could also live in a plugin completely :)

**Comment by saschafoerster** [comment]
+1 -> This would allow to integrate Pretix into RocketChat very easily: RocketChat has incoming webhooks, so many other people can become independent from slack and still use pretix: https://rocket.chat/docs/administrator-guides/integrations/

**Comment by saschafoerster** [comment]
Just as an addition for other people, who like to use webhooks for Pretix in RocketChat, here is a script, useful to add in the webhook-integrations of Rocket.Chat: 

Step 1: New webhook (fill in everything as you like)
Step 2: Activate script: 

```
class Script {
  process_incoming_request({ request }) {
    // console is a global helper to improve debug
    console.log(request.content);
    return {
      content:{
        attachments: [{
          title: "Ticket " + request.content.code,
          title_link: 'https://ticket.bonn.digital/control/event/' + request.content.organizer + "/"+ request.content.event + "/orders/" + request.content.code +"/",
          text: "Bestellung eingegangen",
          fields: [
            {
              title: "Veranstaltung",
              value: request.content.event
            },
            {
              title: "Veranstalter",
              value: request.content.organizer
            }
          ]
        }]
       }
    };
    return {
       error: {
         success: false,
         message: 'Error'
       }
    };
  }
}
```
Step 3: After saving, you will get a webhook-URL, which you have to copy. 
Step 4: Log in to pretix: https:/[YOUTPRETIXURL]/control/organizers/ (You need to be admin and organizer for the events you want to add to the webhook). 
Step 5: Add target-webhook-URL. 

Right now, only new orders work well. If someone knows how to deal with the REST-API, more informations can be added to the chatbot, but be careful with personal data you save in the chat (#GDPR).
