### ISSUE TITLE
Typo in Helptext

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#527]
Here is a nice and easy one for first time contributors (I think ;-))

https://github.com/pretix/pretix/blob/master/src/pretix/base/models/items.py#L217

allo wit -> allow it

**Comment by tydonk** [comment]
I'll take it if still open.  It's tough but I think I can manage ;)

**Comment by raphaelm** [comment]
Go ahead @tydonk and let me know if you need help :P
