### ISSUE TITLE
Placeholders in subjectline are not replaced

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#531]
When sending custom mails using ``/control/event/<organizer>/<event>/sendmail/``, the placeholders ({due_date}, {event}, {order}, {order_date}, {order_url}, {invoice_name}, {invoice_company}) are not replaced when placed in the subject line.

**Comment by rahmonov** [comment]
Hey, can I be assigned to this?

**Comment by raphaelm** [comment]
Sure, go ahead!

**Comment by raphaelm** [comment]
Hi @rahmonov, did you already have time to take a look at this? :)

**Comment by rahmonov** [comment]
@raphaelm hey, I am sorry but I haven't had a chance. I should have informed earlier. Sorry once again. Please, remove the assigned label so that another person can fix this issue. Apologies.

**Comment by SanketDG** [comment]
Can I take this up?

**Comment by raphaelm** [comment]
@SanketDG Sure!

**Comment by SanketDG** [comment]
Hi, due to the limited capabilities of testing locally, I am not able to replicate this. Can I get some help on this?

**Comment by raphaelm** [comment]
Hi, in what way can you not test this locally? You just need to somehow create an order, then you should be able to try this out. There is a note in the developer docs regarding sending emails locally without actually sending them. Let me know if you need more help, though I am on vacation for a week from today and will answer slowly. :)
