### ISSUE TITLE
Moving multiple elements at the same time screws with PDF-output

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#532]
When selecting multiple elements in the PDF-editor and moving them collectively (with the arrow-keys), they will move as expected.

However upon previewing, the moved objects are placed completely at a wrong place.

Saving the whole thing again however (without refreshing; with the fields placed correctly in the editor), and then running a new preview, everything is fine.

This whole thing gets only cumbersome, when the objects are moved (internally) off-canvas, the editor is reloaded and the fields are not reachable anymore. (Hint: ``editor.fabric.dispose()`` gets rid of everything and resets to the default Pretix-layout. Perhaps we should add that as a "Reset ticket"-button).

**Comment by raphaelm** [comment]
Thanks a lot! Thats a weird definition inside FabricJS… as soon as something is in a group, its coordinates are then relative to the center of the group…

**Comment by raphaelm** [comment]
A reset button would be a useful addition, yes, but I think not to editor.fabric.dispose() but to pretix' default layout
