### ISSUE TITLE
An error occured while contacting the SMTP server: [Errno -2] Name or service not known 

### ISSUE THREAD

**Issue by nmarjanovic** [pretix/pretix#535]
Hi,

I got this error when i try to add personal SMTP server. I use last stable docker image build. All was set using your docks (with systemd), and everything is working for now. I tested to add gmail SMTP relay as well, just to be sure if error comes from my personal mail server settings or not.

I will ask as well for pretix docker container root password?

From logs i could grab without root permission, only one error, other things are warnings:

**django.security.DisallowedHost exception Unknown host: 'x.x.x.x'**

This is docker logs output:

https://paste.lugons.org/?fc97293953b9ca57#ZiUXczBI9UMvHuCuoomH/aE5kAHxKDQHHYAciykfyDI=

Ideas?

Thanks.

**Comment by raphaelm** [comment]
> [Errno -2] Name or service not known

Did you add the SMTP server in the event settings? 
Can you tell me what exactly you entered into the form field "Hostname"?

If you're using a system-wide SMTP server, what's the value of ``host`` in the ``[mail]`` section of pretix.cfg?

> I will ask as well for pretix docker container root password?

Hm? There is none, why would you need it? You can jump into docker as root e.g. with ``docker exec --user root -it pretix.service /bin/bash``

**Comment by nmarjanovic** [comment]
Hi @raphaelm 

1. Yes i wanted to set SMTP on event settings.
2. mail.xxxxxx.com
3. From mail@xxxxxx.com and host host=172.17.0.1

I tested to add other variables about mail server in pretix.cfg, removing same from event setting, thanks to information i have found here: https://docs.pretix.eu/en/latest/admin/config.html#email, didn't help. I tested with postfix on same server, setting SMTP relay, and i authorized docker ip range in postfix, getting same error.

4. About root login, i just wanted to try to check Django code and see to grab more logs with debug mode enabled, but that was not important because i tested pretix on my local machine.

Thanks.

**Comment by raphaelm** [comment]
> mail.xxxxxx.com

And you are absolutely sure that is correct? You said something about Gmail, why don't you use smtp.gmail.com?

The error mesage basically says you entered the wrong hostname.

**Comment by nmarjanovic** [comment]
Tested with gmail as well, same error.

**Comment by raphaelm** [comment]
Sorry, but the error message ist crytal clear that the network connection to the SMTP server is failing :( You can try setting ``host=172.17.0.1`` to ``host=smtp.gmail.com`` if that might be the error (you should get a different one, then), but otherwise, I can't see how this could be a bug in pretix, Sorry.
