### ISSUE TITLE
Issue while updating pretix

### ISSUE THREAD

**Issue by td00** [pretix/pretix#537]
While updating pretix (Small-scale manual deployment) from Version 1.4.0 to 1.5.0 some pip packages won't install automatically and need to be installed manually.

Otherwise there are errors while migrating to 1.5

``(venv) pip3 install djangoframework``
``(venv) pip3 install django-filter``

fixes the issue for me.

Debian 8 Kernel 3.16.0-4

**Comment by raphaelm** [comment]
Ouch, thanks, that will probably require a 1.5.1

**Comment by raphaelm** [comment]
1.5.1 is on PyPI now. Thanks again!
