### ISSUE TITLE
Allow to delete Waiting list entries

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#541]
Nothing special - just a delete-button next to every entry in the waiting list overview.

While silently deleting someone from the waiting list is not nice, it might be a useful feature for admins wanting to clean up: For example delete entries that have been added as a result of testing the waiting list.

**Comment by raphaelm** [comment]
Good idea!

**Comment by danlls** [comment]
May I work on this? :D

**Comment by raphaelm** [comment]
Sure, go ahead! :)
