### ISSUE TITLE
Allow to send email from order

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#543]
Currently, we can send emails automatically (e.g. on payment) or to many buyers at once (via the sendmail plugin). However, it would also be very useful to send emails directly to one buyer.

This could be a new button in the backend's order detail view, e.g. next to the "mark as paid" or "refund order" buttons, or next to the "change email address" button. The button would take you to a new page with a new form, similar to the form in the sendmail plugin, and allow you to send an email to the user.

**Comment by danlls** [comment]
I'll work on this :)
