### ISSUE TITLE
Ticket layout in editor does not match output

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#545]
OK... This one might be a bigger one, potentially causing some headaches ;-)

I noticed, that the layout done in the visual editor does not always yield exactly the same output on the PDF: the positions of the items are just not the same.

I can't really put my finger on it, but I have a feeling, the larger the font-size, the more the editor-placement and the real placement diverge.

Attached are two samples - the top one is always the editor view, the lower one the PDF-output. On the first sample I added a red line to show the discrepancy in more detail.

![image](https://user-images.githubusercontent.com/654548/27955023-f6058796-6312-11e7-8ba0-ffbf9d01fe0f.png)
![image](https://user-images.githubusercontent.com/654548/27955030-fdf20484-6312-11e7-956c-54bf34ccddca.png)

Used font: Roboto, 60 and 25pt respectively.

**Comment by raphaelm** [comment]
Since it's two completely different rendering engines (your browser and reportlab), *some* differences are expected, though it shouldn't be that major

**Comment by raphaelm** [comment]
Also, can you have the instance upgraded to 1.5 and share the now-copyable JSON source of the design here?

**Comment by pc-coholic** [comment]
Sure :-)

`[{"type":"textarea","left":"55.00","bottom":"175.00","fontsize":"20.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"142.57","content":"itemvar","text":"Sample product – sample variation","align":"left"},{"type":"textarea","left":"172.00","bottom":"28.00","fontsize":"10.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"30.00","content":"order","text":"A1B2C","align":"right"},{"type":"textarea","left":"129.00","bottom":"23.00","fontsize":"10.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"72.92","content":"secret","text":"tdmruoekvkpbv1o2mv8xccvqcikvr58u","align":"right"},{"type":"barcodearea","left":"140.00","bottom":"30.00","size":"70.00"},{"type":"textarea","left":"85.00","bottom":"259.00","fontsize":"60.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"73.53","content":"other","text":"SHA","align":"left"},{"type":"textarea","left":"85.00","bottom":"245.00","fontsize":"53.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"64.95","content":"other","text":"2017","align":"left"},{"type":"textarea","left":"165.00","bottom":"235.00","fontsize":"30.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"41.74","content":"other","text":"+2017","align":"right"},{"type":"textarea","left":"5.00","bottom":"246.26","fontsize":"30.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"41.74","content":"other","text":"4-8","align":"left"},{"type":"textarea","left":"10.74","bottom":"240.34","fontsize":"20.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"29.27","content":"other","text":"AUGUST","align":"left"},{"type":"textarea","left":"5.00","bottom":"236.92","fontsize":"8.0","color":[255,255,255,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"44.07","content":"other","text":"ZEEWOLDE, THE NETHERLANDS","align":"left"},{"type":"textarea","left":"55.00","bottom":"152.00","fontsize":"13.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"111.12","content":"shatax","text":"Camping: 183.68 EUR (6% BTW)\nEvent: 61.22 EUR (21% BTW)\nToeristenbelasting: 5.10 EUR (BTW vrijgesteld)\nSupporter Donation: 50.00 EUR (BTW vrijgesteld)","align":"left"},{"type":"textarea","left":"0.00","bottom":"12.98","fontsize":"7.4","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"209.81","content":"other","text":"IFCAT Foundation          IBAN: NL42 RABO 0166 8900 30          VAT ID: NL851125049B01          CoC nr: 54030498","align":"center"},{"type":"barcodearea","left":"1.00","bottom":"148.00","size":"50.00"},{"type":"textarea","left":"155.00","bottom":"210.00","fontsize":"10.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"50.00","content":"other","text":"Stichting IFCAT Foundation\nGraan voor Visch 18515\n2132 GW Hoofddorp\nThe Netherlands","align":"right"},{"type":"textarea","left":"5.00","bottom":"215.00","fontsize":"20.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":true,"italic":false,"width":"79.60","content":"other","text":"Welcome to SHA 2017!","align":"left"},{"type":"textarea","left":"5.00","bottom":"205.00","fontsize":"13.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"156.02","content":"other","text":"Please print this ticket and bring it with you to the venue.","align":"left"},{"type":"textarea","left":"55.00","bottom":"185.00","fontsize":"13.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"50.00","content":"other","text":"This ticket is good for:","align":"left"},{"type":"textarea","left":"5.00","bottom":"45.00","fontsize":"13.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"127.73","content":"other","text":"If this your parking- or camper/caravan ticket, please fill out your name, phone and/or DECT-number in the space above and place it under your windshield.\n\nPlease enjoy SHA2017 and stay safe!\n\nIn case of emergency, please dial\nDECT 2222 or +31 622005297","align":"left"},{"type":"textarea","left":"28.00","bottom":"102.50","fontsize":"25.0","color":[0,0,0,1],"fontfamily":"Roboto","bold":false,"italic":false,"width":"50.00","content":"other","text":"I belong to:\nPhone:\nDECT:","align":"left"}]`

**Comment by raphaelm** [comment]
Well, technically this is probably still not fixed :(

**Comment by pc-coholic** [comment]
I work here and it didn't bother me since 2017 - so it can't be that bad anymore ;-)
