### ISSUE TITLE
CVC for Stripe-payments is limited to 3 chars

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#547]
When using the inline-form to process Stripe-payments, there is a tiny issue with the CVC:

While most CC-companies agreed on 3 digits for the CVC, Amex has to roll their own way and actually sets their CVCs to 4 digits.

Right now, the form will not allow the user to enter that 4th digit.

IIRC, right now pretix is using the v2-API... This problem could probably be solved by either upgrading to v3 and using the "Stripe Elements" that do all kind of animations and magic (such as correctly limiting the CVC-field based on the card brand) or by implementing a filter, that allows 4-digits if the PAN starts with either 34 or 37.

**Comment by raphaelm** [comment]
Good point. Quick fix: Change the Stripe UI to "Stripe Checkout" in the settings to switch to a interface by stripe itself

**Comment by raphaelm** [comment]
The stripe integration will change for #407 anyways
