### ISSUE TITLE
Add icons to expansible panels

### ISSUE THREAD

**Issue by danlls** [pretix/pretix#552]
Currently, expansible panels headers has the same style as the non-expansible except having strong text. It could mislead users thinking it is just a normal header.

Suggestion:
-  `fa-angle-down` icon can be used as indication
![panel-collapsed](https://user-images.githubusercontent.com/28383090/28199910-a30f6c44-689b-11e7-8c95-f2beca8dbd5d.png)

- rotated when expanded
![panel-expanded](https://user-images.githubusercontent.com/28383090/28199919-ab0ac9fc-689b-11e7-8e4b-8a671b514120.png)

- make the whole block of header clickable instead of just the text

Collapsible panels are currently used in multiple pages: 
`event/mail_setting_fragment`, `event/payment` , `presale/event/checkout_questions` and more ..

**Comment by raphaelm** [comment]
Sounds great! Do you want to create a pull request yourself?

(There is the other topic of expanding it automatically whenever there is a form error inside it. checkout_questions does it, but mail_setting_fragment and payment do not, and I'm not sure what a good way to do this might be)

**Comment by danlls** [comment]
Yeah, I'll work on this. 

The last time I tried, the forms in `checkout_questions` doesn't expand upon error. It display error messages only when the panel is not collapsed. Maybe you meant the invoice panel will expand if it is set as required instead of optional. I have no good way to do this atm, gotta research.

**Comment by raphaelm** [comment]
>  The last time I tried, the forms in checkout_questions doesn't expand upon error. It display error messages only when the panel is not collapsed. Maybe you meant the invoice panel will expand if it is set as required instead of optional. I have no good way to do this atm, gotta research.

Hmm, ok. You can also leave the error handling part to me or for a separate PR and get started with the symbol first, it is helpful in itself already.
