### ISSUE TITLE
Preselect Addons if they have to be bought

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#555]
Using AddOns, we can already force a customer to buy an AddOn...

Even though this specific usecase might be outdated when CheckIn-lists arrive (#515), this could be used (for example) to give users a second ticket for swag-redemption (badges, T-Shirts, etc.).

`if (minAddons == maxAddons) && num(AddOns) == (minAddons || maxAddons)`, I would propose to either skip the AddOns-page completely and silently add the items to the cart or at least set the `checked`-property for the items...

If we are forcing the users to take the items, we might as well save them a few clicks ;-)

**Comment by rixx** [comment]
Maybe we should present the page as an information ("Your choice of <foo> comes with <bar>.") instead.

**Comment by raphaelm** [comment]
We'd somehow need to already add it to the cart when the base product is added to the cart, in which case the user already sees it before coming to the addon page. Also, it makes CartManager even more complicated (but it certainly is possible).

The problem (which is a general problem with the ``min_count`` field, even without this feature) is that it's easy to shoot yourself in the foot if the addon is sold out earlier than the base product. I'm not really sure what the solution here is.

**Comment by rixx** [comment]
Well, we could put the information about the addon product on an intermediary page (as it is now), and just hide the form? The backend would keep on validating the choices, and UI wise it's only a *bit* clumsy to have a separate page tell you about included options. This way it's more or less only a presentation fix.

**Comment by raphaelm** [comment]
Well, the easiest way would be to just preselect the checkbox. That would be a no-brainer to merge ;)
