### ISSUE TITLE
Voucher not being counted correctly

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#556]
In the voucher by tag overview, the number sometimes just don't add up ;-)

![image](https://user-images.githubusercontent.com/654548/28206928-1c7ff030-6888-11e7-8891-14e5c794e730.png)

So the progressbar is showing nothing, because it's class is set to 200%. Okay, that's kinda expected to not work ;-)

Explanation for the numbers:
- 2: Two vouchers are created with this tag
- 4: Those two vouchers have been redeem twice each.

So I guess we have to decide if the overview should show the amount of vouchers or the amount of possible voucher redemptions.

**Comment by raphaelm** [comment]
We should probably show redemptions, not vouchers.
(This view is older than multi-use vouchers, so …)
