### ISSUE TITLE
metisMenu.min.css not in Cache

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#557]
I tried to fix that one myself - but I can't get quite the gist of the caching-system... ;-)

On every pretix-instance I have seen so far (including pretix.eu), metisMenu.min.css is 404ing...

Expected locations seems to be `/static/CACHE/css/metisMenu.min.css` - but it actually is in `/static/pretixcontrol/css/metisMenu.min.css`

**Comment by raphaelm** [comment]
You are right but… if that's 404ing everywhere and missing for years then… I guess we can just delete it? I'll look into that.
