### ISSUE TITLE
Render linebreaks in payment info in HTML email

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#576]
When rendering payment information in HTML emails, line breaks are swallowed. Works fine in text mals (and regular front end display, of course).

**Comment by raphaelm** [comment]
Yep, that's a side-effect of using Markdown there since markdown ignores single linebreaks. I'm unsure what the best fix is.

**Comment by rixx** [comment]
Maybe just rendering markdown isn't the best idea then? Because adding in blank lines would look fairly stupid in plain text mails … The quick'n'dirty workaround is making the payment information an unordered list, I guess.

**Comment by raphaelm** [comment]
Dropping markdown is one option, changing its rendering of linebreaks in this place is another. Displaying the payment information as a code block in the markdown would work as well... I'll think harder…
