### ISSUE TITLE
When creating an invoice after an order has been refunded, the invoice is not zero and can not be canceled

### ISSUE THREAD

**Issue by nomoketo** [pretix/pretix#585]
So you're left with an invoice that is not correct, was maybe just created for testing, and cannot be canceled.

**Comment by rixx** [comment]
Imo correct behaviour would to forbid creating invoices for refunded orders. (Alternatively, cancelling them should of course be allowed.)

**Comment by raphaelm** [comment]
IMO correct behaviour could also be to create an invoice and a cancellation at the same time, such that formal documentation for the order can be generated
