### ISSUE TITLE
UnicodeDecodeError when exporting all invoices

### ISSUE THREAD

**Issue by nafur** [pretix/pretix#595]
We have a pretix 1.5.1 instance and when we try to export all invoices the page tells me `An unexpected error has occured.`
The error log shows the following:
`pretix.base.async async Unexpected exception: UnicodeDecodeError('ascii', b'%PDF-1.4` followed by a big bunch of binary data...

I already went through our orders and removed some of the more obscure special characters, but still could not fix this. How can I figure out which order actually triggers this error?

I see that a new pretix version was released. Is there a chance that the new version would fix this issue?
(As we use pretix for a presale for an event starting this weekend, I'm rather reluctant to try an update now...)

**Comment by raphaelm** [comment]
Hi! Yes, this is fixed in pretix 1.6 (commit 9bf9dca88aee6af3f500bd50e3c9178b0628d6ea to be specific, if you would want to apply a patch manually).
