### ISSUE TITLE
Mention event title in download file names (pkpass, pdf)

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#600]
# Current status
- Download files for do not mention the title of the event in the their name, e.g. `2017-ABCDE-1-passbook.pkpass`, `2017-ABCDE-1-pdf.pdf`

# Proposed change
- Prefix the file name with the title of the event, e.g. `MRMCD-2017-ABCDE-1-passbook.pkpass`, `MRMCD-2017-ABCDE-1-pdf.pdf`

**Comment by raphaelm** [comment]
Welps, the thing is, that the ``2017`` in this case is the event title. It's therefore more of a "mis"configuration issue than a code problem. :wink:
