### ISSUE TITLE
Provide a setter for OrderPosition.meta_info_data

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#601]
… I might have just tried to set `meta_info_data` twice before looking it up. m)

**Comment by Marlysson** [comment]
There are more description to do this?

**Comment by rixx** [comment]
An OrderPosition's user generated information (answers to questions, that is) is accessible via OrderPosition.meta_info_data, which is a property loading the stored json data from OrderPosition.meta_info. It would be nice if there was also a property setter which would dump the received json data to a string and set it on the OrderPosition object.

**Comment by Marlysson** [comment]
Doing this setter to dumping the text received, then the ```meta_info_data``` property just would return the ```meta_info``´ attribute model? 

Or after this would remove the ```meta_info_data``` already that the ```meta_info``` already would have the json content.

The ```meta_info``` already would have the json dumped into them.
