### ISSUE TITLE
Product - Check-in - Missing German translation

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#604]
I configured German as the language for the user interface. I noticed that at the end of a **Product** page the **Check-in** section is not translated as shown in the screenshot:

![image](https://user-images.githubusercontent.com/144518/29745581-16df3ef2-8abf-11e7-973a-ad59631b4878.png)

**Comment by raphaelm** [comment]
This is just the case because the feature was added to master yesterday and I only add in translations every few days in batch and before releases -- pretix.eu is running the master branch most of the time ;) But thanks for the heads up!
