### ISSUE TITLE
UnexpectedResponseException: Unexpected server response (0) while retrieving PDF

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#606]
I successfully customized the ticket background using Chromium v.60.
Later I came back to update the background PDF. When I open the **PDF editor** in a new tab the following error is output:

> The PDF background file could not be loaded for the following reason: UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "https://usercontent.pretix.space/media/event-settings/704/ticketoutput_pdf_layout.JIXKjEgZ.pdf".

The editor does not stop `loading...`

The browser console outputs:

> Refused to connect to 'https://usercontent.pretix.space/media/event-settings/704/ticketoutput_pdf_layout.JIXKjEgZ.pdf' because it violates the following Content Security Policy directive: "connect-src 'self' https://pretix.eu https://checkout.stripe.com".

I cannot reset the background PDF to the default.

**Comment by rixx** [comment]
> Content Security Policy directive: "connect-src 'self' https://pretix.eu https://checkout.stripe.com".

It appears you have not set `SITE_URL` to your domain.

**Comment by johnjohndoe** [comment]
I am using an instance hosted by you. Where would I set this variable?

**Comment by rixx** [comment]
Ahh, I should have written "your administrator" instead of "you", sorry.

**Comment by raphaelm** [comment]
Hi,

this is a bug introduced by a recent configuration change on pretix.eu during the security fixes of 1.6.2. I will try to fix this until tomorrow.

Cheers
Raphael

**Comment by raphaelm** [comment]
Fixed in 557a0513
