### ISSUE TITLE
Show useful message if no ticket output is active

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#614]
I am trying to test the ticket ordering and ticket download before I add pretix to the website of the event.  
- Therefore, I "activated" my pretix.eu instance. 
- In the administration backend I set the ticket download date to **yesterday**. 
- I ordered a "free" product (0€) and pretix shows this:

> Du kannst deine Tickets hier ab 30.08.2017 herunterladen. 

![download-ticket-date](https://user-images.githubusercontent.com/144518/29944653-9d4d28f4-8e9e-11e7-940d-51313f69013b.png)

Although, the date is set to yesterday there is **no** ticket download link.

**Comment by pc-coholic** [comment]
Might sound like a stupid question - but did you also enable one of the ticket-generating plugins?

**Comment by johnjohndoe** [comment]
There is no stupid questions! Thank you for solving the problem!
Interesting is that tickets which have been downloaded are not regenerated when the layout is changed.

**Comment by pc-coholic** [comment]
Yes, that is true...

There is however a workaround for this: For individual ticket files, you can purge the cache-information from pretixbase_cachedticket, for combined ticket-downloads pretixbase_cachedcombinedticket... Upon next download-request, the file will be regenerated.

**Comment by johnjohndoe** [comment]
I am using a hosted instance on pretix.eu. I guess there in cannot purge the cache.
