### ISSUE TITLE
Formal German in order email

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#615]
I configured my prefix.eu instance to use **informal** German. When I received an email for a test order I noticed that there is one sentence which uses **formal** German.

> Sie können Ihre Bestellung unter folgender Adresse ändern und einsehen:

![Order email](https://user-images.githubusercontent.com/144518/29945096-222b749e-8ea0-11e7-9ce6-512f5d5c0b4a.png)

Further, `Das` in `Viele Grüße, Das XXX Team` can be lowercase.

**Comment by raphaelm** [comment]
This has been fixed in 77a8726a. However, as this unfortunately only fixes the default values, you might still need to correct the values for your event by changing the texts at Event > Settings > Emails.

**Comment by johnjohndoe** [comment]
@raphaelm Thank you. I manually updated the email templates in my instance.
