### ISSUE TITLE
maintainance mode

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix#626]
Whats the best way to bring pretix into a maintainance mode?
I don't want to break any payment in process (e.g. paypal).

**Comment by raphaelm** [comment]
Currently, there is no such thing directly in pretix. The easiest way is probably on the event-level, i.e. taking an event "offline"/"not live" using the first tile on the event dashboard. PayPal/Stripe webhooks will still arrive but all users will see a "not found" and all users currently doing a checkout/payment will be interrupted.

If you want to take it offline completely, just stop the pretix process on the server. All pages will show an error and webhooks won't be received (at least Stripe will retry them, though, after a while).

I'm actually not sure what a dedicated maintainance mode (if we'd add it) should block and what it shouldn't.
