### ISSUE TITLE
[Plugin idea] Native giropay support

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix#627]
What do you think about offering a giropay payment method?
The API looks kinda straight forward: [http://api.girocheckout.de/en:girocheckout:giropay:start](http://api.girocheckout.de/en:girocheckout:giropay:start)
Especially [http://api.girocheckout.de/en:girocheckout:paypage:start](http://api.girocheckout.de/en:girocheckout:paypage:start)

€dit: Just noticed the pricing of griopay - maybe not realy worth for the custom user ;)

**Comment by luto** [comment]
Stripe [supports giropay](https://stripe.com/docs/sources/giropay) and pretix supports stripe :) Or are you looking for direct support?

**Comment by Speedy1991** [comment]
Ah awsome!
Just read the docs and there was only 

> Stripe is a US-based company that offers you an easy way to accept credit card payments from all over the world. 

Didn't notice there are more payment methods in the background.

**Comment by raphaelm** [comment]
I love giropay as a concept since it's basically SOFORT done the right way. Therefore, yes, it is already supported via Stripe, but I'd like to see native support as well, even though the minimum fee makes it only interesting to large users.

**Comment by pc-coholic** [comment]
pretix-girosolution is a thing now \o/
