### ISSUE TITLE
Export Check-in list (CSV): Add column for company name

### ISSUE THREAD

**Issue by MacLake** [pretix/pretix#629]
Hello,

It would be useful to add the company name to the CSV check-in list. I think we can assume that the company name that is entered for the invoice information applies to all participants of that order.

We need the company name for name tags, but also when using the check-in list for its main purpose it’s useful to have the company name on the list.

**Comment by raphaelm** [comment]
> It would be useful to add the company name to the CSV check-in list. I think we can assume that the company name that is entered for the invoice information applies to all participants of that order.
> We need the company name for name tags, but also when using the check-in list for its main purpose it’s useful to have the company name on the list.

I understand the intention why this would be useful. I think that your assumption is valid enough. However, from my experience both as a conference organizer as well as an attendee, I find it more polite to add a question "What should we print on your badge?" since there are many legit cases where one wants to have the company name formatted differently on invoice and badge (or have a brand name on the badge etc.). This obviously does not render this issue invalid, but it might be a workaround that is even better ;)

**Comment by MacLake** [comment]
Yes, sure, a solution like that would also solve our problem. Btw, that’s how it was done for PyConWeb with another ticket system. And that’s also better for cases when in one order there are participants of different departments or even companies.

**Comment by darrenwee** [comment]
I'm a first-timer for contributing to an OSS project. Can I take this?

**Comment by raphaelm** [comment]
@darrenwee Sure, go ahead! :)

**Comment by raphaelm** [comment]
Sorry for the late reply. Let me know if you have any questions!

**Comment by darrenwee** [comment]
I've been playing around with Pretix for a while and I cannot figure out how to check in a person? I can't find documentation for it either in the user guide. I assume that because no one is checked in, there's no option to export the check-in list, right?

**Comment by koebi** [comment]
As of now, checkins are only done via the pretixdroid-app. A manual checkin is currently being built, the corresponding PR is #642 - although not merged yet, this should work.
The check-in list exporter is a plugin, maybe you haven't enabled it? For me, even with no orders, I can click on the export button. That gives me a 405 - Method not allowed error, but it works ;)

**Comment by koebi** [comment]
As of [this commit](https://github.com/pretix/pretix/commit/1a894d71b860fc1c787f74a9d299c4fa70e8acce), this feature is implemented, so you can now easily manually check in people :))

**Comment by darrenwee** [comment]
Awesome, thanks!

**Comment by MacLake** [comment]
Thank you! So I close this issue.

**Comment by darrenwee** [comment]
You closed the wrong issue! #629 isn't implemented, @koebi was saying that #630 (manual check-in) is implemented.

**Comment by raphaelm** [comment]
No, that's a misunderstanding as @darrenwee points out :) #630 implemented by koebi has nothing to do with this.

@darrenwee The "check-in list" is just badly named it has nothing to do with who is already checked in, it is more a list that could be used for printing it out and checking in manually on paper.

**Comment by MacLake** [comment]
Okay, sorry, I didn’t read it so carefully.

**Comment by raphaelm** [comment]
Fixed by now
