### ISSUE TITLE
Manual check-in of attendees

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#630]
It is useful e.g. for statistical reasons to be able to mark participant as checked-in manually after the event, e.g. when check-in was done offline with a paper list.

I imagine the best way to do this would be to have checkboxes in the first column of the view at "Orders" -> "Check-ins" in the event admin interface that allow to bulk-change the check-in status of attendees.

**Comment by saschafoerster** [comment]
+1

**Comment by koebi** [comment]
Hey, 

I'd like to give this a shot. I'll let you know when I come up with something :)
