### ISSUE TITLE
Timezone inside the docker container

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#632]
Hi!
Currently, the pretix docker container uses its own timezone setting, which can leads into some unexpected results. I am living in Germany (currently GMT+2), so when setting a presale-start to 0 o'clock inside the application, tickets will be available at 2 o'clock. This behavior is expected because of the docker concept ([see discussion in the moby project](https://github.com/moby/moby/issues/3359)).

We should consider redirecting the `/etc/localtime` to the host machine or at least add a notice to the `Small-scale deployment with Docker` page.

With best regards
Jan Felix

**Comment by raphaelm** [comment]
Hi!

> We should consider redirecting the /etc/localtime to the host machine or at least add a notice to the Small-scale deployment with Docker page.

No, that is the wrong approach to the problem. The server timezone should be irrelevant as multiple events on the same server have different timezones and all dates will be stored in the database as UTC. All that should matter is setting the timezone of your event. Is this correctly set?

**Comment by jfwiebe** [comment]
> Is this correctly set?

No, I assumed that it was. You are totally correct, sorry for bothering you!
