### ISSUE TITLE
Error message if an event series has no date

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#634]
Hi!

I am using the latest "stable" pretix release from today. When an event series has no scheduled dates, opening the "event selector" (top left corner) leads into an "internal server error".

![image](https://user-images.githubusercontent.com/6865786/31251718-3ffd282e-aa1f-11e7-9288-7efbd30c3a68.png)

![image](https://user-images.githubusercontent.com/6865786/31251655-00bd4c2a-aa1f-11e7-9a57-e3370bb292e7.png)

With best regards
Jan Felix

**Comment by aimanparvaiz** [comment]
@raphaelm Should I take a shot at this?

**Comment by raphaelm** [comment]
@aimanparvaiz Sure, go ahead! :)

**Comment by aimanparvaiz** [comment]
Hey @jfwiebe 
I am trying to reproduce this issue but haven't been successful yet, I will share the steps I have taken please let me know if I am missing something here.
1. I created a series of events (event 7, event 7.2, event 7.3)with a start date and no end date.
2. I clicked on Dates in the left column and also at the top left and it didn't throw any kind of error.
3. I also tried the same when there was only 1 event in the series (only event 7) and I didnt see any errors either. 
I am attaching a screenshot here, I believe I might be missing some steps here to reproduce this error please throw some light on it if possible. 
I am using latest master for this code as of 10/23/2017.
![screen shot 2017-10-23 at 10 03 59 am](https://user-images.githubusercontent.com/671161/31902620-4cd6571e-b7da-11e7-9437-8be9fbc5c9e8.png)

**Comment by jfwiebe** [comment]
Hi,

sorry if my report was not clear enough. To reproduce the error, create an event series and then delete all dates. Now click on the event selector and you‘ll get the error.

With best regards
Jan Felix

**Comment by aimanparvaiz** [comment]
Thanks for getting back @jfwiebe. Ok, trying what you mentioned didnt produce error but something else did, let me list my steps. 
1. I deleted all dates under event7.
2. Clicked on Dates in the left menu and also on the top left, none of this broke anything (see screen shot attached)
3. On clicking pretix.de (at the top left corner) though led to this error:
`ERROR 2017-10-23 21:13:15,141 django.request exception Internal Server Error: /control/
Traceback (most recent call last):
  File "/Users/aimanparvaiz/PycharmProjects/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/aimanparvaiz/PycharmProjects/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/aimanparvaiz/PycharmProjects/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aimanparvaiz/PycharmProjects/pretix/src/pretix/control/views/dashboards.py", line 415, in user_index
    for r, result in user_dashboard_widgets.send(request, user=request.user):
  File "/Users/aimanparvaiz/PycharmProjects/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/Users/aimanparvaiz/PycharmProjects/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/aimanparvaiz/PycharmProjects/pretix/src/pretix/control/views/dashboards.py", line 339, in user_event_widgets
    (event.min_from).astimezone(tz),
AttributeError: 'NoneType' object has no attribute 'astimezone'`

Is this what we are trying to reproduce and fix?
![screen shot 2017-10-23 at 2 13 04 pm](https://user-images.githubusercontent.com/671161/31913707-d68bfd70-b7fc-11e7-9e83-3d3592ecbcb2.png)
![screen shot 2017-10-23 at 2 13 18 pm](https://user-images.githubusercontent.com/671161/31913712-d9994b58-b7fc-11e7-92c4-c7c4889c1ff5.png)

**Comment by jfwiebe** [comment]
Yes indeed, this is the error I am talking about.
(In my first report, I stated that it happens on the date selector, but that was wrong - I'm sorry!)

**Comment by aimanparvaiz** [comment]
No worries, now since I have reproduced it, I will start working on it.
Thanks

**Comment by aimanparvaiz** [comment]
PR Submitted, all checks are passing.

**Comment by aimanparvaiz** [comment]
@raphaelm please let me know if I am missing something in the fix, really excited about this PR.
