### ISSUE TITLE
Date/time picker for cart sharing

### ISSUE THREAD

**Issue by domke** [pretix/pretix#650]
Everywhere in pretix there is a date/time picker when there's a date/time to be entered. Except in the "Share a cart" feature for the expiry date where it's a text box.

I'd like to recommend to change this into a date/time picker as well.

**Comment by BenHagan** [comment]
I'd take this on if approved.  I can't find this feature in the app though.  @domke could you add some screenshots or walk me though how to access the feature?

**Comment by raphaelm** [comment]
This ticket rightfully belongs to the https://github.com/pretix/pretix-cartshare plugin :) GitHub unfortunately does not allow moving issues

**Comment by domke** [comment]
I re-created the issue in pretix-carshare. See issue 6 there.
