### ISSUE TITLE
Question: Add automatic spell checking?

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#663]
The last three commits I made were born by running aspell on the .po-files. I quite enjoyed this and would maybe like to work on this some more - If the changes are merged, I'll definitely run the same "tests" on the informal german translation.
Apart from this, would it be an idea worth pursuing to add automatic spell checking to the project?

**Comment by raphaelm** [comment]
> The last three commits I made were born by running aspell on the .po-files. I quite enjoyed this and would maybe like to work on this some more - If the changes are merged, I'll definitely run the same "tests" on the informal german translation.

Please do so!

> Apart from this, would it be an idea worth pursuing to add automatic spell checking to the project?

Yes! I edit the translation files with [Poedit](https://poedit.net/) which already sort-of spellchecks but apparently not good enough or not visible enough ;) 

Django itself uses a [Spelling check](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#spelling-check) for their documentation that we could use as well for our docs. Would you like to set this up? We could then think about generalizing this to the .po files as well.

**Comment by koebi** [comment]
Yes, I'd like to take a look into this :)

**Comment by koebi** [comment]
I have been working on this for the last few days (finally ;) ) and there are a few choices that have to be made about how stuff is to be done:

1. Is pretix using UK or US english?
    This comes up in things like (behaviour vs behavior) or (favour vs favor)
2. There are two ways of defining custom words: 
     a) listing them in the respective file using
         `.. spelling:: Customword1 Customword2`
     b) listing them in a `wordlist.txt`-customword-file
     My preferred approach would be to list words that are only used in one particular file in that file and to put all words that are used in at least two files into customword file. Does this seem ok? What should the customword-file be called? (sphinx-spelling calls it `spelling_wordlist.txt` by default)
3. should the spell checking be included in the travis build?

**Comment by raphaelm** [comment]
Ah, sorry, I missed this, too many GitHub notifications currently.

> Is pretix using UK or US english?

I think we settled on US, even if I like British English more, US English is just the way to go in technology and makes things easier.

> My preferred approach would be to list words that are only used in one particular file in that file and to put all words that are used in at least two files into customword file. Does this seem ok? What should the customword-file be called? (sphinx-spelling calls it spelling_wordlist.txt by default)

Agreed, although I'd always err on the side of putting it into the customword file if it is at least likely that the word will be reused. ``spelling_wordlist.txt`` sounds fine to me.

> should the spell checking be included in the travis build?

I think so, yes.
