### ISSUE TITLE
Question: Naming plugins and using MultipleChoiceField

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#665]
Hi,

I'm playing around with developing a plugin and have a couple of questions: 

1. Should I include "pretix" in the unique plugin key, e.g. "pretix_notifyadmin", or is this prefix reserved for core plugins?
2. I cannot make a `MultipleChoiceField` show currently selected values (from the database) in my plugin settings. I can check values and they are saved correctly in the database (I think) on save, but when I display the form again no values are checked.

    I've been Googling for hours to find a solution, but have only learned that others have similar issues – and no solution that works (for me).

    And have also been looking at `__init__` in [src/pretix/control/forms/event.py](https://github.com/pretix/pretix/blob/master/src/pretix/control/forms/event.py#L101-L116) where a `MultipleChoiceField` is used for the `locales` field, but I haven't been able to make my field work using similar tricks.

    Any pointers on how to make it work will be much appreciated.

Best regards,
Mikkel

**Comment by raphaelm** [comment]
> I'm playing around with developing a plugin and have a couple of questions:

Sure! :)

> Should I include "pretix" in the unique plugin key, e.g. "pretix_notifyadmin", or is this prefix reserved for core plugins?

Yes, you can use the ``pretix_`` prefix for the plugin key and/or the ``pretix-`` prefix for the python package to show that is a plugin for pretix. I believe it to be a good idea that you can find all installed pretix plugins with ``pip freeze | pretix`` etc., so I'd vote in favor of the prefix.

Some people prefer to choose a shorter [label](https://docs.djangoproject.com/en/1.11/ref/applications/#django.apps.AppConfig.label) for their app on a Django-level (like only ``notifyadmin``) in your case to prevent repetitive typing of pretix_ in URL configurations etc. I don't :)

That said, I'd choose a different name than "pretix_notifyadmin". First of all, I'd go for a noun, so if you are building a generalized and configurable notifications plugin, I'd call it "pretix_notifications", but if you are building something more specific I'd give it a name like "pretix_mailnotifications" or whatever type of notifictions you issue.

> I cannot make a MultipleChoiceField show currently selected values (from the database) in my plugin settings. I can check values and they are saved correctly in the database (I think) on save, but when I display the form again no values are checked.
>
> I've been Googling for hours to find a solution, but have only learned that others have similar issues – and no solution that works (for me).
>
> And have also been looking at __init__ in src/pretix/control/forms/event.py where a MultipleChoiceField is used for the locales field, but I haven't been able to make my field work using similar tricks.

This is really hard to say without looking at your code. Would you show me the respective code (snippets)? I'd be happy to have a look at it.

I'm excited to see what you build, admin notifications are certainly something that is wished often :)
