### ISSUE TITLE
Portable Barcode Scanner 

### ISSUE THREAD

**Issue by ZEROF** [pretix/pretix#666]
Hi,

I need advice for buying some portable barcode scanner(s) for better work-flow. Scanner must work with pretix android application. P.S.Phone scanning is ok, but slow in some cases.

Would like to here from your experiences ;)

Thanks

**Comment by raphaelm** [comment]
Hi,

> I need advice for buying some portable barcode scanner(s) for better work-flow. Scanner must work with pretix android application. P.S.Phone scanning is ok, but slow in some cases.

Hard to say. I have no experiences with bluetooth-based mobile barcode scanners so far. I have experience with [this china-sourced handheld device](https://lecom.en.alibaba.com/product/60501076709-805287995/A.html) (make sure to get the 2D-scan-version!) that has a good scanning module but bad overall quality and breaks fast if it falls down… There are [way more expensive products](https://www.zebra.com/us/en/products/mobile-computers/handheld/tc20.html) in this range that could probably easily be made compatible with pretixdroid but are not yet.

That said, we will start soon with a desktop-based scanning app for windows and linux and plan to release it in January the latest. You'll then be able to use any USB-based handheld scanner from cheapo to [high-end](https://www.honeywellaidc.com/products/barcode-scanners#handheld).
