### ISSUE TITLE
Deletion of data 

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#678]
I created some test-events and test-organisations, which I only can delete via SQL, but which I never do, because I fear breaking things. But this is not really problematic, just a bit disturbing for me. 

But in the advent of stronger data protection laws, it should be possible to delete all email-adresses and customer-data easily, so there will be a small footprint of user data collected. Thats why I would like deletion tools to be integrated, on the level of events, organisations and tickets. On the other hand, they should really explain which consequences can follow from their usage and not be easy to use by accident

**Comment by raphaelm** [comment]
Yes, I have such a "shred personal data" feature in mind for at least a year but have never written it down what I imagine it to be like… it will come! :)

**Comment by raphaelm** [comment]
However, it would still only delete the personal data like email addresses and answers (as you suggested), not the "financial" data. I thought about allowing deletion of events that have no orders, but I'm really not willing to allow deleting orders (i.e. financial records)

**Comment by saschafoerster** [comment]
So you prefer me to go into the database? To delete all the paypal-sandbox-transactions? 💃 And then break everything, because I don't know... 👹

**Comment by raphaelm** [comment]
I prefer that financial transactions can not be deleted, see e.g. https://de.wikipedia.org/wiki/Revisionssicherheit :)

**Comment by saschafoerster** [comment]
Okay, how about an Archive?

**Comment by raphaelm** [comment]
Yep, some kind of archiving would be more appropriate. So that would just be a simple flag that hides the event?

**Comment by saschafoerster** [comment]
And maybe a second step to remove all personal data (besides transactions). Yes!

**Comment by raphaelm** [comment]
I've see those as separate features so fare (archive and shredder), but it might also make sense to combine it.

**Comment by saschafoerster** [comment]
Maybe shredding is only allowed after at least 30 days of archival?

**Comment by Speedy1991** [comment]
> So you prefer me to go into the database? To delete all the paypal-sandbox-transactions? 💃 And then break everything, because I don't know... 👹

I have a similar problem. I created a testevent but i am unable to delete it in a clean way.
Maybe it's a good idea to create a django-admin command? This can only be used by the server-admins (having anyway access to the database).

**Comment by raphaelm** [comment]
As of 0b12b7a, you can delete events that have not yet received any orders or created any invoices.
Just to be clear, here are my future plans:

* There **might** be a "shred personal data" mode which anonymizes all data but does keeps all numbers intact, if that seems to be legally possible.

* The **might** be a way to "archive" an event, making it read-only and hiding it from some lists, although I don't really see much use in this as you can just turn the shop offline and most lists have an option to exclude offline shops already.

* There **will never** be a way to get rid of orders in the software. You will alway need to meddle with the database to do this – or better, don't do it at all. The mere **existance** of such a feature would be a reason for financial authorities to stop believing in any numbers calculated by the software.

**Comment by raphaelm** [comment]
Now work-in-progress at #817
