### ISSUE TITLE
Filters on orders page look crammed for some window sizes

### ISSUE THREAD

**Issue by blinry** [pretix/pretix#680]
For a browser window with a width of 1600 pixels, and a DPI setting of 144, the filters row on the orders page looks like this, making it unclear what the first box is supposed to be used for:

![pretix-width](https://user-images.githubusercontent.com/81277/32693254-01241484-c728-11e7-9f56-8660dc14d0cd.png)

**Comment by rpirritano** [comment]
@blinry , Is this issue still available?  Is so, I can take it.

**Comment by rixx** [comment]
@rpirritano Nobody is currently working on this issue, feel free to tackle it! :)

**Comment by rpirritano** [comment]
@blinry,  Is this the same page as the Order Search? (see screenshot).  If so, it looks different from my page on the developer environment.  Also, should the above DPI be 1440?  The below page seems to be responsive.

![screen shot 2017-11-30 at 9 41 05 pm](https://user-images.githubusercontent.com/8380531/33469423-a03121c2-d617-11e7-8181-da43d8e5a26d.png)

**Comment by blinry** [comment]
That's the one! I notice you have four search fields instead of my five – are we using the same versions? I'm on 1.9.0.

**Comment by rpirritano** [comment]
I'm using the latest version, v1.10.0.

Maybe the issue is no longer occurring?  Can you check Master?  Thanks!!

**Comment by raphaelm** [comment]
I think @blinry is thinking of another page, namely the list of orders when you're *inside* an event. It is very similar, though.

**Comment by rpirritano** [comment]
oh ok, let me look for that one....thanks!

**Comment by blinry** [comment]
I'm closing this issue until I find time to reproduce it with the latest version. :)
