### ISSUE TITLE
Waiting list voucher created despite payment timeframe already closed

### ISSUE THREAD

**Issue by tiefpunkt** [pretix/pretix#681]
Not sure whether this is a bug, a missing logic check or plain user error.

I had an event with a waiting list, and a last day of payments set up. Now one order expired after said date, and a new voucher for the next one on the waiting list was generated and sent out.

Is there a scenario in which that makes sense? Why would I sell a ticket, when someone is not allowed to pay for it anymore?

**Comment by raphaelm** [comment]
Good point, this does not make that much sense. While we're at it, the waiting list also should not be served if the general presale period is over or the requested product is no longer available.

**Comment by raphaelm** [comment]
In 67678e35 we check that the waiting ist onyl served until the end of presale, so that should be good enough
