### ISSUE TITLE
Mention code of conduct on github

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#689]
Browsing the pretix github, I found that although the project has a [Code of Conduct](https://docs.pretix.eu/en/latest/development/contribution/codeofconduct.html), the [Community Page](https://github.com/pretix/pretix/community) doesn't mention it - because there is no `CODE_OF_CONDUCT.md`-file anywhere. 

I'd propose to add that file in the same style of the `CONTRIBUTING.md`-file - even if just to make the COC a little more visible :)

**Comment by raphaelm** [comment]
Agreed. By same style do you mean to just put a link to the docs there? I think that makes most sense.

**Comment by koebi** [comment]
yes, pretty much :) 
One could consider removing the CoC-Mention in the CONTRIBUTING.md-file, or changing the link to link to the new COC.md-file, and whether the CoC should be mentioned in the README.
As for the first, I wouldn't, because a Code of Conduct can't be mentioned enough.
As for the second, it increases the time it takes people to get to the CoC, so I wouldn't.
As for the third, I think that, corresponding to the first, it wouldn't do harm to do so.

**Comment by raphaelm** [comment]
> As for the first, I wouldn't, because a Code of Conduct can't be mentioned enough.

ACK.

> As for the second, it increases the time it takes people to get to the CoC, so I wouldn't.

ACK.

> As for the third, I think that, corresponding to the first, it wouldn't do harm to do so

ACK.

❤️
