### ISSUE TITLE
<pre> </pre> HTML Tag in ordering Mail is shown as plaintext

### ISSUE THREAD

**Issue by shokinn** [pretix/pretix#699]
The `<pre> </pre>` Tag is shown as plaintext in the ordering mail.

<img width="794" alt="screen shot 2017-12-06 at 11 25 07" src="https://user-images.githubusercontent.com/10045300/33657133-9a139eb8-da78-11e7-8964-ea04da71ced7.png">

**Comment by raphaelm** [comment]
Thank you! Fixed in https://github.com/pretix/pretix/commit/1011b67f0abbb71a9550ccca7635487f99799000
