### ISSUE TITLE
Pycups fails during update

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#704]
Hi Raphael, I tried to update, but there seems an problem with pycups. 
I tried 'apt-get install libcups2-dev', but it didn't help. 

Kind regards
Sascha

`root@sfvm01:/home/pretix# docker build -t bonndigital/pretix .
Sending build context to Docker daemon  6.144kB
Step 1/9 : FROM pretix/standalone:stable
 ---> f0793b024bb7
Step 2/9 : USER root
 ---> Using cache
 ---> 1250f3069939
Step 3/9 : COPY id_pretix_enterprise /root/.ssh/id_rsa
 ---> Using cache
 ---> 82331ce3ed5e
Step 4/9 : COPY id_pretix_enterprise.pub /root/.ssh/id_rsa.pub
 ---> Using cache
 ---> 749ddb57a675
Step 5/9 : RUN chmod -R 0600 /root/.ssh
 ---> Using cache
 ---> 978d3fa01f2c
Step 6/9 : RUN pip3 install pretix-passbook pretix-sepadebit pretix-cartshare pretix-pages pretix-fontpack-free pretix-newsletter-ml pretix-wirecard pretix-printtool pretix-bounces
 ---> Running in 13808e0a21cb
Collecting pretix-passbook
  Downloading pretix_passbook-1.2.0-py3-none-any.whl
Collecting pretix-sepadebit
  Downloading pretix_sepadebit-1.2.2-py3-none-any.whl
Collecting pretix-cartshare
  Downloading pretix_cartshare-1.2-py3-none-any.whl
Collecting pretix-pages
  Downloading pretix_pages-1.2.2-py3-none-any.whl (158kB)
Collecting pretix-fontpack-free
  Downloading pretix_fontpack_free-1.0.2.post1-py3-none-any.whl (4.1MB)
Collecting pretix-newsletter-ml
  Downloading pretix_newsletter_ml-1.1.0-py3-none-any.whl
Collecting pretix-wirecard
  Downloading pretix_wirecard-0.5.2-py3-none-any.whl
Collecting pretix-printtool
  Downloading pretix_printtool-0.1.1-py3-none-any.whl
Collecting pretix-bounces
  Downloading pretix_bounces-1.0.0-py3-none-any.whl
Collecting googlemaps (from pretix-passbook)
  Downloading googlemaps-2.5.1.tar.gz
Collecting wallet-py3k (from pretix-passbook)
  Downloading wallet-py3k-0.0.3.tar.gz
Collecting sepadd>=1.1.0 (from pretix-sepadebit)
  Downloading sepadd-1.2.0-py3-none-any.whl
Collecting django-localflavor (from pretix-sepadebit)
  Downloading django-localflavor-1.6.1.tar.gz (4.1MB)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from pretix-printtool)
Collecting click==6.* (from pretix-printtool)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
Collecting pycups (from pretix-printtool)
  Downloading pycups-1.9.73.tar.bz2 (52kB)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from wallet-py3k->pretix-passbook)
Requirement already satisfied: django>=1.8 in /usr/local/lib/python3.6/site-packages (from django-localflavor->pretix-sepadebit)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->pretix-printtool)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->pretix-printtool)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->pretix-printtool)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->pretix-printtool)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from django>=1.8->django-localflavor->pretix-sepadebit)
Building wheels for collected packages: googlemaps, wallet-py3k, django-localflavor, pycups
  Running setup.py bdist_wheel for googlemaps: started
  Running setup.py bdist_wheel for googlemaps: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/04/e8/d1/ae5577b5339873e6a5dd55141d56e507cf281b137ef09ba924
  Running setup.py bdist_wheel for wallet-py3k: started
  Running setup.py bdist_wheel for wallet-py3k: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/85/16/6a/ecc0f0b2359d7dbd680a150baa853b6eef44f6d3474fcd0206
  Running setup.py bdist_wheel for django-localflavor: started
  Running setup.py bdist_wheel for django-localflavor: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/6f/61/b5/b237749ea1eddebca5fa2c680a44e8a26d22e0c2411950f49f
  Running setup.py bdist_wheel for pycups: started
  Running setup.py bdist_wheel for pycups: finished with status 'error'
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a465efdn/pycups/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpj7sh9lpapip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'cups' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/local/include/python3.6m -c cupsmodule.c -o build/temp.linux-x86_64-3.6/cupsmodule.o
  cupsmodule.c:23:23: fatal error: cups/cups.h: No such file or directory
   #include <cups/cups.h>
                         ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pycups
  Running setup.py clean for pycups
Successfully built googlemaps wallet-py3k django-localflavor
Failed to build pycups
Installing collected packages: googlemaps, wallet-py3k, pretix-passbook, sepadd, django-localflavor, pretix-sepadebit, pretix-cartshare, pretix-pages, pretix-fontpack-free, pretix-newsletter-ml, pretix-wirecard, click, pycups, pretix-printtool, pretix-bounces
  Running setup.py install for pycups: started
    Running setup.py install for pycups: finished with status 'error'
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a465efdn/pycups/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1h92wk_n-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cups' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DVERSION="1.9.73" -I/usr/local/include/python3.6m -c cupsmodule.c -o build/temp.linux-x86_64-3.6/cupsmodule.o
    cupsmodule.c:23:23: fatal error: cups/cups.h: No such file or directory
     #include <cups/cups.h>
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a465efdn/pycups/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1h92wk_n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-a465efdn/pycups/
The command '/bin/sh -c pip3 install pretix-passbook pretix-sepadebit pretix-cartshare pretix-pages pretix-fontpack-free pretix-newsletter-ml pretix-wirecard pretix-printtool pretix-bounces' returned a non-zero code: 1`

**Comment by raphaelm** [comment]
> Step 6/9 : RUN pip3 install pretix-passbook pretix-sepadebit pretix-cartshare pretix-pages pretix-fontpack-free pretix-newsletter-ml pretix-wirecard pretix-printtool pretix-bounces

Why do you try install pretix-printtool on the server? Your server probably does not have a printer, so this doesn't make too much sense.

**Comment by saschafoerster** [comment]
Sorry for not reading the whole documentation (as I should have done): in consequence the export as PDFs don't work anymore: pretix.log shows 
'ERROR 2017-12-10 22:00:30,888 pretix.base.async async Unexpected exception: NotRegistered("'pretix.base.services.export.export'",)
'
Is there anything I can do, besides creating docker-compose from new (which I tried)?

**Comment by raphaelm** [comment]
> Sorry for not reading the whole documentation (as I should have done): in consequence the export as PDFs don't work anymore: pretix.log shows
> 'ERROR 2017-12-10 22:00:30,888 pretix.base.async async Unexpected exception: NotRegistered("'pretix.base.services.export.export'",)

This is completely unrelated to the problem above… I currently don't know what this is, I haven't seen this exception before
