### ISSUE TITLE
Consistence in spelling checkin/check-in

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#708]
So far, it seems as both checkin and check-in are used throughout the pretix.
This should be made consistent, though I don't know yet how. I'll check for how inconsistently this is currently used and maybe this will help in making a decision. 

For reference, compare #688 where this came up first.

**Comment by koebi** [comment]
`make spelling` finds 7 occasions where checkin is used. A short online search revealed, that 
- if used as a verb, it should be spelled `check in`, e.g. "I already checked in yesterday."
- if used as a noun or adjective, it should be spelled `check-in`, e.g. "I'm currently in line at check-in."
- the single word `checkin` is in use in some places, but hasn't gained an as widespread use as for example `checkout` has
Therefore, I'd suggest using `check-in` or `check in`, but use `checkin` for code, as it is currently done.

**Comment by raphaelm** [comment]
This sounds reasonable! Thanks for doing the research.
