### ISSUE TITLE
Typo in German translation

### ISSUE THREAD

**Issue by CarstenG** [pretix/pretix#709]
In [de/LC_MESSAGES/django.po, line 11351](https://github.com/pretix/pretix/blob/cf1883a039c868595d588fcffc867d36e4072457/src/pretix/locale/de/LC_MESSAGES/django.po#L11351) and [de_informal/LC_MESSAGES/django.po, line 11322](https://github.com/pretix/pretix/blob/cf1883a039c868595d588fcffc867d36e4072457/src/pretix/locale/de_Informal/LC_MESSAGES/django.po#L11322) should be the last word »wurden.« instead of »worden.«

**Comment by felixrindt** [comment]
This issue could be closed I guess.

**Comment by raphaelm** [comment]
Yep, thanks!
