### ISSUE TITLE
Product-Questions Statistics still include data from canceled orders

### ISSUE THREAD

**Issue by Ahrdie** [pretix/pretix#712]
The summary statistics, that can be found at every question still include the data from canceled orders. The same is the case in the Statistics Plugin.
Maybe the ability to switched canceled orders on or off would be a solution.

**Comment by raphaelm** [comment]
Hi :) For the questions, there is a filter directly above the chart. Do you have an idea how to make this more obvious?

**Comment by Ahrdie** [comment]
Ok, I found it. Don't know how I missed it..
The only minor issue I have is, that there is no way for me to select all orders, that are not canceled.
In my usecase of pretix I'm pretty sure, that sooner or later everyone in my event will pay.

**Comment by raphaelm** [comment]
I added a new option and even made it the default, as I believe it is the same for most events.
