### ISSUE TITLE
Change of user settings (language or timezone) triggers two "mail-address changed" mails

### ISSUE THREAD

**Issue by Ahrdie** [pretix/pretix#714]
At changing the user language settings, there are two identical mails send, that inform you, that your mail address has been changed, although the mail address stayed the same and only the language setting changed.

**Comment by raphaelm** [comment]
Can you reproduce this? It doesn't happen for me at the moment.

**Comment by Ahrdie** [comment]
Yes, I just tried it again; its reproducible. The same also happens, if you change your user timezone, one field below.

**Comment by raphaelm** [comment]
Okay, I was testing with the wrong form. This explains why the mail is sent twice: If it detects an email address change, it sends the email to both the old and the new address, which is on purpose.

However, if I only change the language, I don't get any email at all, so I still can't reproduce and I'm really unsure why it detects the email address as changed.
