### ISSUE TITLE
Staticfiles Update while updating Docker Container

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#718]
Hi!

It seems that when upgrading a docker container as described in the docs, the staticfiles (I am not a django expert but I assume that is the mechanism used?) won't be refreshed, so e.g. the newly introduced progress bar is not shown correctly. A simple `./manage.py collectstatic` (even with removing the old statics first) will result in generating new files but the links in the html-output will still point to the old files.

What is the correct thing to do for updating the files? Can we fix that issue within the docs, pretix or the Dockerfile?

Thanks for your very awesome work!
With best regards, Jan Felix

**Comment by raphaelm** [comment]
Hi,

as soon as you set your own color for an event, event CSS is no longer processed using the ``staticfiles`` mechanism, no.

Does ``./manage.py updatestyles`` help? This command is responsible for generating the stylesheet. It is also run automatically when you do ``docker exec -it pretix.service pretix upgrade``.

**Comment by raphaelm** [comment]
I was able to reproduce the problem and just released 1.10.1 which should fix the problem. Make sure to read the notes on docker installations at the end of the blogpost:
https://pretix.eu/about/de/blog/20171216-release-1101/

**Comment by jfwiebe** [comment]
Worked! Thank you!
