### ISSUE TITLE
CSS for widgets seems incomplete

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#720]
We started our shop and used this plugin: https://github.com/jfwiebe/pretix-wp-plugin
We added CSS, JS and link to the ticket shop to sell tickets for Barcamp Bonn. 
By mistake I have added the CSS from an earlier event (which seemed to work). But when I added the correct link, the CSS seems broken: 
Here is the link to the old event (wrong link, but working css): 
https://ticket.bonn.digital/bonndigital/fuckupnights/widget/v1.css

Here is the link, which is created by pretix for the event (right link, wring css): 
https://ticket.bonn.digital/bonndigital/barcampbonn2018/widget/v1.css

Here is the link to the event (no with css from another event)
https://barcampbonn.de/tickets/

**Comment by raphaelm** [comment]
Weird. Can you try changing the primary color of the event to see if it helps to re-generate that CSS?

**Comment by saschafoerster** [comment]
Problem solved! Thanks!
