### ISSUE TITLE
Email check seems to run wild

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#721]
I don't know how the email-check works, but it makes our customers wonder. ;) We got two such reports today: 
https://twitter.com/dailypia/status/942839885043552256

**Comment by raphaelm** [comment]
The email check tries to find if e.g. the name of the customer is misspelled in the address, i.e. it takes the content of the name field, splits it into words, generates permutations of these words and checks for them in the email address.

I'm really unsure what goes wrong for your customers here, I haven't seen reports *that* crazy so far, I believe they appear now after my latest readjustments of the algorithm. I now lean towards just disabling it completely in pretix 1.11 until we come up with a better algorithm.

**Comment by koebi** [comment]
I can't reopen this, but I'd like/am in the process of investigating here. This seems like a fun bug to hunt down, and the algorithm intrigues me :)
