### ISSUE TITLE
[Plugin-Idea] Apple Pay

### ISSUE THREAD

**Issue by Ahrdie** [pretix/pretix#724]
As [Apple Pay](https://en.wikipedia.org/wiki/Apple_Pay) is an (for the consumer) easy desktop payment method, I would like to include the possibility to pay with it to the ticketshop.

Apple Pay: https://support.apple.com/en-us/HT201239

Example use of Apple Pay at [iPhoneblog](https://iphoneblog.memberful.com/checkout?plan=11485) by [memberful](https://memberful.com/help/how-to/enable-apple-pay/).

I know that this isn't urgent and there are plenty of other good, more open payment methods - this would just be a _nice to have_ sometime in the future.

**Comment by raphaelm** [comment]
Yes, that'd be great to have as a plugin!

**Comment by raphaelm** [comment]
It even could be implemented as part of the Stripe plugin pretty easily into pretix core, probably: https://stripe.com/docs/apple-pay

**Comment by raphaelm** [comment]
Currently supported through Stripe
