### ISSUE TITLE
Consistent spelling of Add-on or addon

### ISSUE THREAD

**Issue by koebi** [pretix/pretix#727]
As of now, this doesn't seem to be too consistent. I'll have a look into this and report back with viable options :)

**Comment by raphaelm** [comment]
In an offline discussion, @koebi and I decided that "add-on" would be correct.

**Comment by koebi** [comment]
If add-on is capitalized, would you capitalize it Add-on or Add-On?

**Comment by raphaelm** [comment]
I'm leaning towards Add-on. Do we have native English speakers reading here? :)

**Comment by loceur** [comment]
Yeah. If capitalized, then just the first word, not both. Eg.  Add-on.

**Comment by loceur** [comment]
But I'm American, so it's always questionable if I'm actually speaking
English or not :)

**Comment by raphaelm** [comment]
Thanks!

> But I'm American, so it's always questionable if I'm actually speaking
> English or not :)

Well, in the past we always decided for en_US when we discussed such things, so that's fine ;)

**Comment by raphaelm** [comment]
I can't find any more user-visible usages of Add-on without the hyphen, so closing this
