### ISSUE TITLE
Update via Docker does not work

### ISSUE THREAD

**Issue by loelkes** [pretix/pretix#728]
# Context

Installed pretix with docker following the installation guide by the letter. For some reason i got the Version 1.9.0.dev0.

# What I did
Following the update guidelines I did
`# docker pull pretix/standalone:stable`

> stable: Pulling from pretix/standalone
> Digest: sha256:7983d6ae13d0908c0f5d966628d2c9f7f64d49fe18c0bcfbdde872140ff1fd26
> Status: Image is up to date for pretix/standalone:stable

`# systemctl restart pretix.service`

`# docker exec -it pretix.service pretix upgrade`

> System check identified some issues:
> 
> WARNINGS:
> ?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
> 	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
> Operations to perform:
>   Apply all migrations: auth, banktransfer, contenttypes, easy_thumbnails, otp_static, otp_totp, paypal, pretixbase, pretixdroid, pretixmultidomain, sessions, stripe
> Running migrations:
>   No migrations to apply.
>   Your models have changes that are not yet reflected in a migration, and so won't be applied.
>   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

Running the migration didn't change anything.

# What I got
Nothing changed.
<img width="1509" alt="screen shot 2017-12-30 at 15 56 46" src="https://user-images.githubusercontent.com/231909/34455204-1f11c130-ed7a-11e7-9884-5e48d090f030.png">

# System
> Linux eventvm 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux
> Docker version 17.09.1-ce, build 19e2cf6

**Comment by raphaelm** [comment]
You probably are affected by a tutorial bug that we explained in more detail here: https://pretix.eu/about/en/blog/20171216-release-1101/ in the section "Documentation bug in the Docker installation tutorial". Feel free to reopen this issue if that is not the reason.

**Comment by loelkes** [comment]
Yup, thanks. Fixed it.
