### ISSUE TITLE
Payment fee formatting in payment selection form

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#731]
When the user is in checkout and selects a payment method, if a payment fee is negative, e.g. -4.00, it is dislayed with a prefixed + sign. It should just be a minus. 

Also I think that the '+ 0.00 EUR' looks very bulky and numbery. Maybe the font for these fees could be a little smaller?

![screenshot from 2017-12-31 12-10-19](https://user-images.githubusercontent.com/5970076/34461152-9f8c004c-ee23-11e7-9c3b-b42d3dd049d7.png)

**Comment by raphaelm** [comment]
The "+ -" thing is obviously a bug. The formatting looks indeed weird on your screenshot, the baseline should match with the name of the payment method and be aligned to the right. What browser are you using?

**Comment by felixrindt** [comment]
Recent Chrome and firefox-developer aswell as chrome on Android.

**Comment by raphaelm** [comment]
Does it look the same on https://pretix.eu/demo/democon/ ? Using Chrome, I get
![download](https://user-images.githubusercontent.com/64280/34462410-a579cad2-ee43-11e7-9984-203ec4e87aa3.png)

**Comment by felixrindt** [comment]
Just checked out a fresh pretix copy. Formatting was like in your screenshot, so I must have gotten something wrong there. So there's just the +/- thing.

**Comment by felixrindt** [comment]
Here"s what I've found regarding the alignment.

I had installed a copy of pretix on an uberspace and created an event around 2 weeks ago. From the beginning, payment fees weren't right-aligned. Now, when using a freshly cloned version of pretix (but same database, data and setting) the fees are still not right aligned. I created a new event, and it had the correct alignment.

I can't see how something other than the templates/JS/python in the pretix repo could relate to the buggy alignment, but I'm getting two different results using the same running instance of pretix. The difference is just the event being displayed.

The screenshot below is from two event payment pages being served from the same instance:
![screenshot from 2017-12-31 18-01-21](https://user-images.githubusercontent.com/5970076/34463206-a2063e74-ee54-11e7-9e61-e33c41ae0ec0.png)

Also notice that on the left side the panel title doesn't have the grey background. I can't reproduce the error sadly.

**Comment by raphaelm** [comment]
As soon as you change the "display settings" of an event, the event shop will no longer load the CSS that shipped with pretix, but a CSS file that is generated specific for that event. Therefore, after every upgrade of the pretix codebase, these CSS files need to be re-rendered manually with ``python manage.py updatestyles``

**Comment by felixrindt** [comment]
Regarding the alignment errow: I regenerated the css in the data/media directory by changing the organizer color. Looks fine now, although I still don't know how it got corrupted.

**Comment by raphaelm** [comment]
> although I still don't know how it got corrupted

I do, it's simple. The old CSS file was created with an older version of pretix, and the markup and default CSS of this part has recently changed ;)
