### ISSUE TITLE
listing of event with subevents on organizer page irritating

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#735]
When creating an event with subevents you need to provide a `date_from` date. Since there are multiple dates, this can be used for the timespan the workshops take place in. For example, an art club does 4 painting workshops every February, it could set the event date from Feb 1st to Feb 28th and have the individual workshops as subevents with the actual start times. 

On the organizer page, events can be publicly listed. The issue is, that if you look at that page after the event `date_from` date, this event does not get listed as a future event, even though there might be subevents still in the future you want to sell tickets for. 

Similarly, this page does not list the event in "past events" when loading the page before `date_to`, even though there might be subevents in the past.

In this screenshot, the conference does not have subevents, but the workshop has multiple subevents in February.

![screenshot from 2018-01-03 18-08-13](https://user-images.githubusercontent.com/5970076/34530986-15af82d2-f0b1-11e7-950b-f986e948f426.png)

To fix this issue, the conditions when to show events with subevents in the future and past events lists need to be changed. Also there should be a way for a customer to see that there are multiple dates available.

**Comment by raphaelm** [comment]
Yeah, this is one of the issues with event series. In principle, the ``date_from`` and ``date_to`` attributes of an event series are rarely ever useful. That's why

* in the calendar view, we flatten the hierarchy and display subevents along with regular events. This is hard to do in a list, because it breaks pagination
* in the backend list view, we discard date_from and date_to and instead use the earliest and last contained subevent for filtering/ordering

While the first approach is obviously a bit more user-friendly, we could at least port the second one for now. This should be really easy to contribute, because one can just copy a lot from https://github.com/pretix/pretix/blob/master/src/pretix/control/views/main.py#L38

**Comment by JindalMohit** [comment]
Hi, I want to solve this issue. Can you please help me how to make sub-events of an event. I know how to create an event, but I did not find out any option to make sub-events.

**Comment by raphaelm** [comment]
You need to select "event series" during event creation, subevents are named "dates" in the interface. You can read more here: https://docs.pretix.eu/en/latest/user/events/subevents.html

**Comment by felixrindt** [comment]
![screenshot-2018-1-15 create a new event pretix de](https://user-images.githubusercontent.com/5970076/34958732-6bdb250e-fa33-11e7-9fdf-5c3f96fb5796.png)

Make sure you tick "This is an event series". You will then be able to define multiple dates for a series of events who share most of the attributes.

**Comment by JindalMohit** [comment]
On the organizer page, all the events are not shown. Can you please tell me where is the problem:
![screenshot from 2018-01-16 19-08-37](https://user-images.githubusercontent.com/16673210/34991724-a1b55f10-faf0-11e7-9f3f-e5253e1cbcae.png)
![screenshot from 2018-01-16 19-08-53](https://user-images.githubusercontent.com/16673210/34991726-a422d994-faf0-11e7-9d8b-fd1b4656a3d0.png)

**Comment by felixrindt** [comment]
Do you have the `public` option enabled for all of them?

![screenshot-2018-1-16 painting workshop pretix de](https://user-images.githubusercontent.com/5970076/34992749-70133e0e-face-11e7-975c-6f93c9357f48.png)

**Comment by JindalMohit** [comment]
I have done the changes in [https://github.com/pretix/pretix/blob/master/src/pretix/presale/views/organizer.py](url).

Output:
![screenshot from 2018-01-18 15-59-32](https://user-images.githubusercontent.com/16673210/35093456-71226a9a-fc68-11e7-9314-18382840a33c.png)
![screenshot from 2018-01-18 15-59-45](https://user-images.githubusercontent.com/16673210/35093461-7510845c-fc68-11e7-8a61-c0ea41180073.png)

Here workshop is a series event. Some sub-events are in past and some are upcoming, so it is showing workshop event in both upcoming and past events. Is this approach fine or something else is required.

**Comment by JindalMohit** [comment]
@felixrindt Please review the changes made by me.

**Comment by felixrindt** [comment]
Just did. I also shared my ideas about how the value in the date column could work. 

>  There should be a way for a customer to see that there are multiple dates available.

I don't have a good idea for that, yet.
