### ISSUE TITLE
Control panel: Shop button with custom organizer domain; Site not secure

### ISSUE THREAD

**Issue by LiaraAlis** [pretix/pretix#738]
If a organizer has a custom domain, in the control panel of a organizer event the "Go to shop" button-form points to the `http://`- Domain, so the connection to site is marked as insecure and the button is no longer working.

**Comment by raphaelm** [comment]
That must be a problem with your setup. Either SITE_URL in your pretix.cfg does not have HTTPS protocol or your reverse proxy does not set ``X-Forwarded-Proto: https`` correctly.

**Comment by LiaraAlis** [comment]
@raphaelm Oh, you're right. The site url in the `pretix.cfg` file was configured with the `http` protocol.
Thanks for your help!
