### ISSUE TITLE
rendering issue with decade selection in date picker 

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#740]
While trying out the datepicker in the event settings view I saw this.
![screenshot from 2018-01-10 11-26-57](https://user-images.githubusercontent.com/5970076/34768739-0e42831e-f5fc-11e7-929c-03f6ca15a895.png)

As you can see, the year ranges are seperated by a big vertical gap. What I expected to see was this

![screenshot from 2018-01-10 11-36-37](https://user-images.githubusercontent.com/5970076/34768749-16f37324-f5fc-11e7-95c1-feabeb7c1f25.png) 

from https://eonasdan.github.io/bootstrap-datetimepicker/.
I noticed this with a fresh installation of the pretix master branch using firefox-dev 58.

**Comment by raphaelm** [comment]
Maybe a broken line-height or something?

**Comment by prakharcipher** [comment]
I'd like to pick up this issue.

**Comment by raphaelm** [comment]
@prakharcipher It seems @LeonardoChrivi already found a solution
