### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by td00** [pretix/pretix#741]
Migration fails
`django.db.utils.OperationalError: (1050, "Table 'pretixdroid_appconfiguration' already exists")
`
Version 1.11.0

**Comment by td00** [comment]
How to upgrade to a specific version in manual deployment?
Like 1.10?
Want to upgrade an old 1.6 instance.

**Comment by rixx** [comment]
Depends on your installation method ;)
If you use pip, you can install a specific pretix version with `pip install pretix==1.10`.

**Comment by td00** [comment]
Still the same issue in Version 1.10 :/
Any quick fix?

**Comment by raphaelm** [comment]
I believed this is a bug in 1.11 until now. Can you post a full stacktrace?

**Comment by raphaelm** [comment]
https://pretix.eu/about/en/blog/201801014-release-1111/ should fix it

**Comment by raphaelm** [comment]
If you already ran into the bug, you might need to manually drop the pretixdroid_appconfiguration table in the database
