### ISSUE TITLE
Download reminder email uses wrong logging ID

### ISSUE THREAD

**Issue by sylvinus** [pretix/pretix#747]
Not very important but: 
https://github.com/pretix/pretix/blob/master/src/pretix/base/services/orders.py#L649

**Comment by raphaelm** [comment]
Yep, this should be ``pretix.event.order.email.download_reminder_sent`` instead of ``pretix.event.order.email.expire_warning_sent``. Also, https://github.com/pretix/pretix/blob/master/src/pretix/control/logdisplay.py would need a proper human string for that then :)
