### ISSUE TITLE
Markdown Doc underscore italics

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#748]
At https://docs.pretix.eu/en/latest/user/markdown.html, one sees this:

![screenshot-2018-1-16 markdown guide pretix 1 12 0 dev0 documentation](https://user-images.githubusercontent.com/5970076/34996340-9b3ae6d0-fad9-11e7-8daa-7dc5334c714f.png)

As you may see, the underscores didn't emphasize the text.

**Comment by raphaelm** [comment]
Just to be sure, they do in pretix, right? Just the docs sample is wrong?

**Comment by felixrindt** [comment]
It does work in Pretix. Just the docs are misleading ^^

**Comment by felixrindt** [comment]
We could

1. Fake the italics by writing `Please *really* pay your *ticket*.` I don't like this because it could confuse readers of the doc source.
2. Remove the hint about using underscores. I don't like this because the user should now about them. 
3. Fix the markdown rendering. That's a bit harder, but probably the best solution.

**Comment by raphaelm** [comment]
> Fake the italics by writing Please *really* pay your *ticket*. I don't like this because it could confuse readers of the doc source.

That's what I had in mind.

> Remove the hint about using underscores. I don't like this because the user should now about them.

Would also work for me, to be honest.

> Fix the markdown rendering. That's a bit harder, but probably the best solution.
Nope. The docs are not markdown, they are restructured text. This is probably not even a "bug" and we won't ship our own docs renderer.

**Comment by raphaelm** [comment]
Another option: Use raw HTML in the docs. This is probably the best solution ;)

**Comment by felixrindt** [comment]
> Another option: Use raw HTML in the docs. This is probably the best solution ;)
I like that, too. 

> Nope. The docs are not markdown, they are restructured text. 
Right ^^
