### ISSUE TITLE
Error when adding item with no tax rule and custom price to order

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#754]
I have an event series with a single product, for which I did not configure any tax rule. When trying to add a product to an order with a custom price, I get an Error. 

https://github.com/pretix/pretix/blob/fc7bafe3d98b499f9ae2b2fe4f17e79552b62e4c/src/pretix/base/services/orders.py#L777

`item.tax_rule` is `None`, so the function call fails.

**Comment by raphaelm** [comment]
That's bad, OrderChangeManager should respect that. Although I'm thinking about deprecating tax_rule=None at some point, it is too easy to forget setting one and having a tax problem…

**Comment by felixrindt** [comment]
Resolved in #776
