### ISSUE TITLE
Update docs with P3P support

### ISSUE THREAD

**Issue by bobapple** [pretix/pretix#765]
On my website I'm using the Pretix widget to allow users to buy tickets. While testing with Internet Explorer 11 I came across a behaviour where the browser wouldn't accept a cookie from the ticket system. 

It turned out to be an issue with something called `P3P` (which I never heard before). Anyways, I had to set a custom header before IE11 accepted the cookies. Maybe you want this in the docs somewhere:

```
Header set P3P "CP=\"ALL DSP COR CUR ADM TAI OUR IND COM NAV INT\""
```

Reference P3P: https://blogs.msdn.microsoft.com/ieinternals/2013/09/17/a-quick-look-at-p3p/

**Comment by raphaelm** [comment]
Oh wow, I also never heard of this. Does this need to be set on the embedding website or on the widget itself?

I did test the Widget with various IE versions before releasing it and I remember it to work fine.

**Comment by bobapple** [comment]
I had to set this on the server where Pretix is running. I'm using Apache2 as reverse proxy. Maybe it also depends on the security settings of IE, I'm not very familiar with it. I tested with the most restrictive scale of security settings.

Also, I wasn't able to reproduce this with any other browser. Regarding IE, I did not test with versions older then 11. Edge works fine btw.

**Comment by bobapple** [comment]
Related to this: When the Pretix ticket shop is embedded with the widget, the cookies of it are identified as "third-party" cookies if the domain of the shop differs from the website. In this case the iframe that is opened by the widget adds items to the cart, but the cart is not displayed to the user. Third party cookies are sometimes blocked in some environments, either by company policies, adblockers or whatever.

Is it possible to display a link to the shop if the cookie couldn't be set?

**Comment by raphaelm** [comment]
> Is it possible to display a link to the shop if the cookie couldn't be set?

I had a separate request on a similar topic. Unfortunately, we can't really detect that before we open the iframe containing the popup (since the cross-origin requests are always sent without cookies) and after we opened the iframe, we can't decide to open the shop in a new tab any more (any browser's popup blocker would interfere).

Therefore, I don't see a real fix right now and pushed a mechanism that at least *detects* these cases and displays a warning message.

**Comment by bobapple** [comment]
> Therefore, I don't see a real fix right now and pushed a mechanism that at least detects these cases and displays a warning message.

This helps already a lot, thank you. Can the warning message also include a link to the shop? The user could then just open the shop directly and buy the tickets there.

**Comment by raphaelm** [comment]
> This helps already a lot, thank you. Can the warning message also include a link to the shop? The user could then just open the shop directly and buy the tickets there.

It does :)
