### ISSUE TITLE
Find order for specific answer

### ISSUE THREAD

**Issue by rixx** [pretix/pretix#767]
If you have an answer type of text (one-line or multiline) or multiple choice with "other" option, you'll get answers like "Yes, but contact me if this is an issue" or "I'd love to, please tell me about future developments". It's hard to contact that person, and there's no way to find the correct order short of exporting all orders and looking in the export.

What I could imagine to be a feasible solution: provide a special question search, and link every row (or every field in the number column) of the question statistics table to that search, so that you'll find the orders matching that answer.

**Comment by raphaelm** [comment]
Very good point indeed
