### ISSUE TITLE
Checkbox for cost-free tickets in checkout-process nearly transparent

### ISSUE THREAD

**Issue by FeaturedBugs** [pretix/pretix#772]
In Firefox 58.0.2/Android in the checkout-process of the user for a cost-free ticket (its called GRATIS) the checkbox is nearly invisible.  Thus, its hard for the user to continue with the check-out process on the mobile device.
See attached screen from FF58.0.2/android:

![checkbox](https://user-images.githubusercontent.com/36610587/36358265-f7c0e21e-150b-11e8-8982-48f355d3b4ae.jpg)

In Chrome, the checkbox has a grey colored background and everything is fine.
Possible solution: give the checkbox with CSS a darker background-colour and/or increase the size.

**Comment by casdidier** [comment]
Hello dear team, 

Can i take care of this issue :) ?

**Comment by raphaelm** [comment]
Hi @casdidier, you sure can! :)

**Comment by casdidier** [comment]
I am a bit new at this, i got several issue when importing the project on my local : 
I have been struggling with this issue, 
$ python manage.py collectstatic --noinput
Traceback (most recent call last):
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'pretix' has no attribute 'multidomain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\config.py", line 119, in create
    import_module(entry)
  File "C:\Users\cheungd\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  **File "D:\perso\pretix\src\pretix\multidomain\__init__.py", line 2, in <module>
    from django.urls import RegexURLPattern
ModuleNotFoundError: No module named 'django.urls'**

RegexURLPattern seems to not exist anymore in Django 2.0 , i tried to come back with Django 1.8. Can you help me figure out what is happening there ?

**Comment by felixrindt** [comment]
If you havn't checked it out yet, take a look at the [installation guide](https://docs.pretix.eu/en/latest/development/setup.html). Maybe you can resolve your dependency problems by following the guide. Pretix uses Django 1.11 at the moment. :smiley:

**Comment by casdidier** [comment]
Hello again ^^, 
I am quite new to pretix functionnally and technically :D, I managed to setup locally emulator for android/ with right firefox apk on it, and i created a ticket called "Free entrance for child under 12 years old" to Big Event 2019 test data , and added some quotas. I am not very sure of the scenario.

The thing is I am not able to get the GRATIS button, is there some special plugin or option to enable to have this button at the Check-out page ? ;) thanks !

**Comment by felixrindt** [comment]
No worries :smile: There are quite a lot of pretix settings to wrap your head around.

First of all "Gratis" is just German for "Free". 
The reason you probalby don't get the checkbox is that you allow a customer to order more than one of the free product per order, therefore a number input is shown. Try limiting the maximum amount per order for your free product to 1.

**Comment by felixrindt** [comment]
> First of all "Gratis" is just German for "Free".

Be aware that the checkbox also shows for products which aren't free. The condition that it can not be bought more than once per order.

You might also checkout the radio buttons shown to the user when redeeming a voucher with a maximum usage equal to 1.

**Comment by casdidier** [comment]
Got it !!! thanks ! :+1:  Now going to build up this solutions through what was suggested :  

- givethe checkbox with CSS a darker background-colour 
and/or
-  increase the size.

**Comment by raphaelm** [comment]
Great! You can also experiment with a border color instead of a background color, that might look cleaner.

**Comment by casdidier** [comment]
Hello, 

 I am new to web dev :), i found some background color that would fit the solution, but i wanted to attack the hardest way changing that checkbox properties, i got a little issue, new CSS don't apply.
I tried to change the CSS using the following [snippet](https://www.bootply.com/ugwCnanAfm#).  

What i did is replaced in  ..\src\pretix\static\pretixpresale\scss\_event.scss the below code

```
  .item-checkbox-label {
        display: block;
        background-color: #fafafc; 
    }
```

by this

```
 .item-checkbox-label>[type="checkbox"],
    .item-checkbox-label>label {
        margin-bottom: 10px !important;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .item-checkbox-label>[type="checkbox"]:not(:checked)+label,
    .item-checkbox-label>[type="checkbox"]:checked+label {
        position: relative;
        padding-left: 22px;
        cursor: pointer;
    }

    .item-checkbox-label>[type="checkbox"]:not(:checked)+label:before,
    .item-checkbox-label>[type="checkbox"]:checked+label:before {
        content: '';
        position: absolute;
        left: 0;
        top: 50%;
        margin-top: -9px;
        width: 17px;
        height: 17px;
        border: 2px solid rgb(145, 144, 144);
        background: #ffffff;
        border-radius: px;
    }
```
But it seems, it does not apply the CSS, I saw there is same definition of CSS for .item-checkbox-label in ..\pretix\src\pretix\static.dist\pretixpresale\scss\_event.scss, what is the purpose of this one ? I also changed it but my custom CSS don't apply too.

Question : is there something i am missing that disable the apply of my new css settings ?

**Comment by orithena** [comment]
Bumping this issue, as I as a user always overlook all the checkboxes in pretix.
Reading the link @pcopfer provided, it looks to me that the following CSS in the right place should suffice:

```input[type="checkbox"] {
  border-width: medium;
}```

**Comment by raphaelm** [comment]
Apparently fixed in FF for Android by now
