### ISSUE TITLE
Error when logging in as a super user - Please help.

### ISSUE THREAD

**Issue by Duncanio** [pretix/pretix#773]
Hi all,

I hope you can help me.I have just had Pretix installed on my server under cloudlinux.
The issue I have is that when I log in as a super user e.g admin@localhost, I get an Internal Server Error.
If I then use the back button a couple of times, I can get a screen up and view users but can not view organizers or set one up, therefore rendering Pretix unusable as I can't set up my first organiser.
The first thing I did once installed was add an additional user, I can login using this but of course can't add an organiser as it isnt a superuser account.  If I change it to be a superuser account, it behaves the same as the Admin account and cause the Internal Server Error.  I tried deleting the additional user but still behaves the same.  So what is it about a super user?

My host found the following in the log below.  Does anyone have any experience of this or possible areas to look at as I'm on the verge of giving up with Pretix but I'm sure I'm just a step or two away. :-(

Many thanks in advance.
Dunc

```
ERROR 2018-02-19 08:00:55,284 django.request exception Internal Server Error: /control/
Traceback (most recent call last):
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner 
    response = get_response(request)
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)   
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)   
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/pretix/control/views/dashboards.py", line 433, in user_index
     8   
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/pretix/control/views/dashboards.py", line 371, in widgets_for_event_qs
     'organizer': event.organizer.slug   
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/django/urls/base.py", line 91, in reverse
     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))   
File "/home/etixoutdoorcinem/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
     raise NoReverseMatch(msg) django.urls.exceptions.NoReverseMatch: Reverse for 'event.index' with keyword arguments '{'organizer': '', 'event': ''}' not found. 1 pattern(s) tried: ['control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/$'] ?tid=954601&c=O7jTr6fb
```

**Comment by raphaelm** [comment]
Did this really happen right from the beginning?

The weird thing is, this looks like you already created an event, but one with an empty slug (which should not be possible). What database system are you using? Is it feasible to try deleting the database and starting from scratch again?

**Comment by Duncanio** [comment]
Yes though the first thing I did was register a new user (rather than as the documentation says go in as Admin and create an organizer).  It is a mysql database. 
There are rows in pretixbase_event, pretixbase_logentry and pretixbase_organizer (pics attached)
Am I right in thinking that the only rows that should be there initially are the rows in pretixbase_logentry that relate to the Admin login?
Thanks for your help it is greatly appreciated.

![pretixbase_event](https://user-images.githubusercontent.com/36608504/36422320-6af04bc6-1633-11e8-9bbe-a4ed064f8577.PNG)
![pretixbase_logentry](https://user-images.githubusercontent.com/36608504/36422321-6b07715c-1633-11e8-82c1-7c94707f4e1a.PNG)
![pretixbase_organizer](https://user-images.githubusercontent.com/36608504/36422322-6b23262c-1633-11e8-836b-e6cda111df51.PNG)

**Comment by raphaelm** [comment]
> Am I right in thinking that the only rows that should be there initially are the rows in pretixbase_logentry that relate to the Admin login?

Yes. The event and organizer rows should absolutely not be there and I have no idea how that happened. You can try deleting them or just starting again from scratch.

**Comment by Duncanio** [comment]
I've deleted all rows from pretixbase_event and pretixbase_organizer and I can now log in and have created an organizer.    
Fantastic, many thanks Raphael.

**Comment by Duncanio** [comment]
Yes it did.   The only thing I did was register a new user straight away (when the documentation says go in as admin and create an organizer).

 

I’m using a mysql database.  Do you mean delete the entire database or the rows from the tables with the event in?   How would I recreate the DB if I delete it?

 

Thanks, I really appreciate you help.

Duncan
