### ISSUE TITLE
Check-in list include unpaid option in subevent detail view

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#779]
All properties of a check-in list linked to a subevent can be altered in the subevents detail view. The option `include unpaid` is new, but can't be edited there.

This also has the effect that when duplicating a subevent, the attribute value `include unpaid` of the check-in list isn't copied over to the form.

**Comment by raphaelm** [comment]
Good catch! Do you want to submit a PR? :wink:

**Comment by felixrindt** [comment]
Yes :)
