### ISSUE TITLE
Invoice displays wrong event date

### ISSUE THREAD

**Issue by bobapple** [pretix/pretix#780]
The invoice of a subevent displays the date of the "main" event. I would expect it to display the date of the subevent.

References:
https://github.com/pretix/pretix/blob/master/src/pretix/base/invoice.py#L292

https://github.com/pretix/pretix/blob/master/src/pretix/base/models/event.py#L66

**Comment by raphaelm** [comment]
Agreed, at least in the case when all positions on the invoice belong to the same subevent.

**Comment by raphaelm** [comment]
This should be resolved by now
