### ISSUE TITLE
Selection of checkin lists for export cumbersome

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#782]
Pretix often lets the user select a Subevent to filter orders or checkin lists. It uses Select2 to show a searchable select box, which is really handy. 

![screenshot from 2018-02-22 18-15-43](https://user-images.githubusercontent.com/5970076/36553383-771e396a-17fc-11e8-9af0-b4c2a729f836.png)

When trying to export check-in lists though, the user is shown a scrollable radio button list. I used `yyyy-mm-dd` in the checkin list's name so they can be destinguished by their name.
![screenshot from 2018-02-22 17-52-27](https://user-images.githubusercontent.com/5970076/36552842-281f2f5a-17fb-11e8-9b46-e89058c027f6.png)

Here not only the checkin lists need to have distinct names (unlike the checkin list index, which shows the date next to the list's name) to be recogniseable, but they are also in an only partially visible list, which can only be searched using the browser natively. 

This makes exporting and naming a checkin list cumbersome in my opinion.

I could imagine a similar Select2 dropdown select which annotates the checkin lists with their corresponding subevent dates, so the checkin list name can be a simple `<name>` instead of `<name> yyyy-mm-dd` or similar. Also selecting the right list would be easier.

**Comment by raphaelm** [comment]
Good idea! Not only for the export, but also for creating pretixdroid configurations etc.

**Comment by felixrindt** [comment]
These are the two **other** places I found that could benefit from a searchable list.

## Checkin lists when creating a checkin app configuration
![screenshot from 2018-02-23 14-41-35](https://user-images.githubusercontent.com/5970076/36602232-cf976786-18b7-11e8-8388-be61867285e8.png)

## Quotas when creating vouchers
Again, quotas should be annotated with their corresponding date.
![screenshot from 2018-02-23 14-39-13](https://user-images.githubusercontent.com/5970076/36602231-cf7f8eae-18b7-11e8-9b14-bde418da1fd3.png)

**Comment by raphaelm** [comment]
Agreed. Do you want to create a pull request? :wink:

**Comment by felixrindt** [comment]
Well actually, I don't have much time on my hands right now.

**Comment by felixrindt** [comment]
Hmm. It's using select2 now, but e.g. for check-in lists doesn't show additional information to the name, so it's still impossible to distinguish. 

![screenshot from 2018-04-03 16-57-30](https://user-images.githubusercontent.com/5970076/38257470-90c1d42a-3760-11e8-8c79-41b7abc971f6.png)

I suppose showing the starting date of the associated event would be an improvement.

**Comment by raphaelm** [comment]
Yes, you're right

**Comment by felixrindt** [comment]
Thank you very much :)
