### ISSUE TITLE
Cache Clearing ?

### ISSUE THREAD

**Issue by Duncanio** [pretix/pretix#789]
Hi,

Thanks in advance for any help.

I have made an amendment to checkout_confirm.html file and uploaded to my server.  I then amended it a couple times more but now the latest change is not showing at all.  If I click browser refresh (repeatedly) on the Review Order page it cycles through a few old versions but never shows the newest.
I'm guessing there is a cache that needs to be cleared but we have restarted redis and it hasn't helped.

Is there another cache that I should be clearing?

Many thanks
Dunc

**Comment by felixrindt** [comment]
Have you tried `./manage.py rebuild`?

**Comment by Duncanio** [comment]
Hi thanks, I haven't.  I haven't actually got a manage.py.

**Comment by felixrindt** [comment]
How did you install pretix then?

**Comment by Duncanio** [comment]
I didn't actually install it myself, django-admin is there just not manage.py .  What gets rebuilt with ./manage.py rebuild?
Apologies, unfortunately I'm new to python and pretix.

**Comment by felixrindt** [comment]
Maybe you should have a look at the [install guide](https://docs.pretix.eu/en/latest/admin/installation/index.html).

**Comment by Duncanio** [comment]
Thank you, I have but I will try and work it out from there.

**Comment by felixrindt** [comment]
If you're interested in professional support, talk to the team at [pretix.eu](https://pretix.eu/about/en/).

**Comment by raphaelm** [comment]
You probably just need to restart the pretix processes.

for the record, ``manage.py <thing>`` corresponds to ``python -m pretix <thing>`` on most production systems.

**Comment by Duncanio** [comment]
Thank you, the restart worked.
