### ISSUE TITLE
Cannot add tickets "unexpected error"

### ISSUE THREAD

**Issue by ciscllc** [pretix/pretix#791]
Hi,

after following your installation docs on a clean debian 9 with nginx I get the following error on my site:

gunicorn[987]: ERROR 2018-03-02 13:50:51,679 pretix.base.async async Unexpected exception: NotRegistered("'pretix.base.services.cart.add_items_to_cart'",)

and on the frontend:
An unexpected error has occurred.

latest debian, latest nginx, mariabd

Thank you for any help!

**Comment by raphaelm** [comment]
What version of pretix are you running exactly? We haven't heard other reports of this since 1.10.1.

**Comment by ciscllc** [comment]
Thanks for your response. It is the latest, 1.12.1, with python 3.5.
Do you need any other log info? How to enable debug mode? I saw a debug-toolbar somewhere.

Best regards

**Comment by raphaelm** [comment]
There is something wrong with the startup of the software, or more likely with the celery background worker. Does the background worker output any errors on startup?

**Comment by ciscllc** [comment]
I will Check. Have not seen any errors or warnings.

Thanks a lot dir this great piece of Software!

**Comment by ciscllc** [comment]
Hey! It was an IP change I did to the running server and django did not like this ;-)
So a simple restart did it.

Thanks a lot!
