### ISSUE TITLE
Removing cart position after end of subevent presale period

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#795]
I have an item of an event which lies in the past in my cart. When I try to remove it (e.g. by clicking "empty cart"), I get an error message stating that the presale period has ended.

**Comment by raphaelm** [comment]
Well, I agree that that's confusing :D

**Comment by felixrindt** [comment]
We should also check whether checkout is possible with an outdated product in the cart.

**Comment by raphaelm** [comment]
AFAIK it is not

**Comment by felixrindt** [comment]
I was able to start checkout, but didn't try finishing checkout yet.

**Comment by felixrindt** [comment]
Ok. So this might only apply to subevents. I was able to go through the full checkout process, but after clicking on 'buy now' the following error messages appeared:

![screenshot from 2018-03-05 18-03-11](https://user-images.githubusercontent.com/5970076/36988648-aa506ce4-209f-11e8-9aed-e38e1b644761.png)

It would be better if items for past subevents would be automatically removed from the cart, as it is done with stand alone events (from what I've seen).

**Comment by raphaelm** [comment]
This should be fixed by now.
