### ISSUE TITLE
"confirmation required" option for check-in lists

### ISSUE THREAD

**Issue by dennisschuerholz** [pretix/pretix#797]
We would like an additional function/option regarding check-in lists:
Currently we can select if a product "Requires special attention" which get's reflected in pretixdroid and pretixdesk - in our usecase the time a ticket is displayed is not enough because manual action is required.

Therefore we would like an option on check-in lists (may also be on-device-basis but i think it's better located on the list) to "Require check-in confirmation".

In our special usecase we wan't to use a check-in list to hand out merchandise and therefore pretixdroid/pretixdesk should be blocked and display the scanned ticket until the "check-in" gets confirmed by our staff member. Currently we can simulate the confirmation-part with check-in time questions but thats more like a dirty workaround and doesn't solve the "display the scanned ticket until confirmed"-part.

**Comment by Janfred** [comment]
I wouldn't bind it to "require_attention".
For entrance scanning personal it isn't yet possible to "undo" a scan. (This might also be worth another issue to make this at least available for the admins in the webpage)
But if you ask the conference attendees e.g. for their ID card to check if it matches their name on the ticket you want to have the possibility to reject the ticket without invalidating it. But you still might want to have tickets (e.g. for students) which will require "other" special attention.

**Comment by raphaelm** [comment]
This can by now be implemented through a checkin-time question if one wants to :)
