### ISSUE TITLE
Server is running but requests fail

### ISSUE THREAD

**Issue by abrock** [pretix/pretix#80]
I managed to install everything according to the setup documentation but when I run the webserver and try to access it in a browser I get:

(env) alexander@toothless:~/rzl/pretix/src$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 17, 2015 - 22:30:50
Django version 1.8.3, using settings 'pretix.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
WARNING 2015-07-17 22:31:07,704 django.request base Not Found: /
WARNING 2015-07-17 22:31:07,704 django.request base Not Found: /
[17/Jul/2015 22:31:07]"GET / HTTP/1.1" 404 74
WARNING 2015-07-17 22:31:08,293 django.request base Not Found: /favicon.ico
WARNING 2015-07-17 22:31:08,293 django.request base Not Found: /favicon.ico
[17/Jul/2015 22:31:08]"GET /favicon.ico HTTP/1.1" 404 85
WARNING 2015-07-17 22:31:08,309 django.request base Not Found: /favicon.ico
WARNING 2015-07-17 22:31:08,309 django.request base Not Found: /favicon.ico
[17/Jul/2015 22:31:08]"GET /favicon.ico HTTP/1.1" 404 85

**Comment by raphaelm** [comment]
Yes, this is a documentation flaw and will be fixed with my next commit.

**Comment by raphaelm** [comment]
Documentation is updated online: http://docs.pretix.eu/en/latest/development/setup.html#run-the-development-server

**Comment by abrock** [comment]
Now I get a page showing "Server Error (500)" and from the "python manage.py runserver" command the following error output:

    Performing system checks...
    
    System check identified no issues (0 silenced).
    July 19, 2015 - 19:26:02
    Django version 1.8.3, using settings 'pretix.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    [19/Jul/2015 19:26:12]"GET /control/ HTTP/1.1" 302 0
    ERROR 2015-07-19 19:26:12,812 django.request base Internal Server Error: /control/login
    Traceback (most recent call last):
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/alexander/rzl/pretix/src/pretix/control/views/auth.py", line 33, in login
        return render(request, 'pretixcontrol/auth/login.html', ctx)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
        template_name, context, request=request, using=using)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/loader.py", line 99, in render_to_string
        return template.render(context, request)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
        return self.template.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 209, in render
        return self._render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 903, in render
        bit = self.render_node(node, context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
        return node.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
        return compiled_parent._render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 903, in render
        bit = self.render_node(node, context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
        return node.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 149, in render
        return self.render_compressed(context, self.kind, self.mode, forced=forced)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
        cached_offline = self.render_offline(context, forced=forced)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
        'You may need to run "python manage.py compress".' % key)
    compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "dbdbf4fa7168560445df2deb70f28bb0" is missing from offline manifest. You may need to run "python manage.py compress".
    ERROR 2015-07-19 19:26:12,812 django.request base Internal Server Error: /control/login
    Traceback (most recent call last):
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/home/alexander/rzl/pretix/src/pretix/control/views/auth.py", line 33, in login
        return render(request, 'pretixcontrol/auth/login.html', ctx)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
        template_name, context, request=request, using=using)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/loader.py", line 99, in render_to_string
        return template.render(context, request)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
        return self.template.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 209, in render
        return self._render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 903, in render
        bit = self.render_node(node, context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
        return node.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
        return compiled_parent._render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 903, in render
        bit = self.render_node(node, context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
        return node.render(context)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 149, in render
        return self.render_compressed(context, self.kind, self.mode, forced=forced)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 89, in render_compressed
        cached_offline = self.render_offline(context, forced=forced)
      File "/home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/templatetags/compress.py", line 73, in render_offline
        'You may need to run "python manage.py compress".' % key)
    compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "dbdbf4fa7168560445df2deb70f28bb0" is missing from offline manifest. You may need to run "python manage.py compress".
    [19/Jul/2015 19:26:12]"GET /control/login?next=/control/ HTTP/1.1" 500 27
    WARNING 2015-07-19 19:26:13,364 django.request base Not Found: /favicon.ico
    WARNING 2015-07-19 19:26:13,364 django.request base Not Found: /favicon.ico
    [19/Jul/2015 19:26:13]"GET /favicon.ico HTTP/1.1" 404 85
    WARNING 2015-07-19 19:26:13,435 django.request base Not Found: /favicon.ico
    WARNING 2015-07-19 19:26:13,435 django.request base Not Found: /favicon.ico
    [19/Jul/2015 19:26:13]"GET /favicon.ico HTTP/1.1" 404 85


"python manage.py compress" leads to:

    WARNING 2015-07-19 19:27:08,136 py.warnings importlib /usr/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
      return f(*args, **kwds)
    
    WARNING 2015-07-19 19:27:08,140 py.warnings base /home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/django/core/management/base.py:259: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
      RemovedInDjango19Warning)
    
    WARNING 2015-07-19 19:27:08,162 py.warnings datastructures /home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/management/commands/compress.py:169: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      compressor_nodes = SortedDict()
    
    Found 'compress' tags in:
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/order/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/plugins.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/base.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/recover.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/quotas.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/auth/login.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/forgot.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/order/refund.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/properties.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/quota.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/checkout_questions.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/quota_delete.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/order/extend.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/organizers/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/organizers/create.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/organizers/detail.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/index.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/login.html
        /home/alexander/rzl/pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/orders/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/property.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/questions.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/payment.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/categories.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/category_delete.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/order_cancel.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/order_modify.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/restrictions.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/order_pay.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/order_pay_confirm.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/variations_0d.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/settings_base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/order/cancel.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/question_delete.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/order.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/orders.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/variations_1d.html
        /home/alexander/rzl/pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_form.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/dashboard.html
        /home/alexander/rzl/pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_assign.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/property_delete.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/events/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/user/settings.html
        /home/alexander/rzl/pretix/src/pretix/plugins/banktransfer/templates/pretixplugins/banktransfer/import_confirm.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/settings.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/events/start.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/variations_nd.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/orders/overview.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/account.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/tickets.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/item/base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/permissions.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/event/base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/question.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/checkout_payment.html
        /home/alexander/rzl/pretix/src/pretix/plugins/sendmail/templates/pretixplugins/sendmail/send_form.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/events/create.html
        /home/alexander/rzl/pretix/src/pretix/plugins/stripe/templates/pretixplugins/stripe/presale_head.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/account_settings.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/auth/base.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/category.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/items/index.html
        /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/auth/register.html
        /home/alexander/rzl/pretix/src/pretix/presale/templates/pretixpresale/event/checkout_confirm.html
    WARNING 2015-07-19 19:27:08,742 py.warnings datastructures /home/alexander/rzl/pretix/src/env/lib/python3.4/site-packages/compressor/management/commands/compress.py:214: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
      offline_manifest = SortedDict()
    
    CommandError: An error occured during rendering /home/alexander/rzl/pretix/src/pretix/control/templates/pretixcontrol/order/index.html: SyntaxError: expected ')' got 'i' in /home/alexander/rzl/pretix/src/pretix/control/static/pretixcontrol/less/main.less on line 4, column 10:
    3 @fa-font-path: "../../fontawesome/fonts";
    4 @import (inline) "metisMenu.min.css";
    5 @import "variables.less";
    
    Compressing... (env)

**Comment by raphaelm** [comment]
That is bad. Could you try creating a file called ``pretix.cfg`` in the directory you are running the commands from (normally ``src/``) with the following content?

```
[django]
debug = on
```

This should make pretix do the LESS compilation on the fly and therefore making it unnecessary to ever run ``python manage.py compress``. If you now get a (more verbose) error 500 in your browser, I'll look into it further.

If it helps, I'll update the documentation accordingly.

**Comment by abrock** [comment]
> Could you try creating a file called [...]

Sure, [this is what i get fro "curl http://localhost:8000/control/login?next=/control/"](https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-19-server-error-control) and [this is what I get from "curl http://localhost:8000/mrmcd/2015/"](https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-19-server-error-mrmcd-2015)

**Comment by raphaelm** [comment]
Okay, we might be a step further. Could you try ``python manage.py collectstatic --noinput``?
As soon as I know what is going on, I'll be looking for a way to simplify it…

**Comment by abrock** [comment]
https://github.com/abrock/Katzenfutter/tree/master/pretix

**Comment by raphaelm** [comment]
Ah, I think I know what is going on: You didn't use ``git clone --recursive`` to clone the repository, so you need to initialize the submodules manually: 

1. Pull the current master branch, as I just changed some things to make it simpler
2. Delete your ``_static/`` directory that was just created by collectstatic, it should no longer be needed for development
3. Check out the submodules with ``git submodule update --init --recursive``
4. It should work.

I want to get rid of the submodules for quite some time but haven't yet found a solution that doesn't introduce new complicated things.

I have an exam this afternoon, so if it doesn't work, don't expect an answer in the next couple of hours ;)

**Comment by abrock** [comment]
This didn't help, so I deleted the whole pretix directory and cloned it with --recursive.
Then I followed the setup instructions and documented what happened:

1. pip install -r requirements.txt

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-install-requirements-pip

2. python manage.py migrate

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-migrate

3. python make_testdata.py

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-python-make-testdata

4. Server error for control:

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-server-error-control

5. Server error for mrmcd:

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-server-error-mrmcd-2015

6. _static directory: https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-20-static.zip

**Comment by raphaelm** [comment]
I did exactly the same thing, and it worked perfectly fine: https://drop.rami.io/6zSZn/plain
Do you spot a major difference?

**Comment by abrock** [comment]
I did it once again from scratch exactly like you did and now I get the presale site and the admin login site but login using the default admin user and pw fails with an error:

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-29-control-after-login.html

This is my log of the installation, looks exactly like yours:

https://github.com/abrock/Katzenfutter/blob/master/pretix/2015-07-29-installation-log

**Comment by raphaelm** [comment]
Well, it's the same error all over again, but at a different page. Weird. 

The weird thing is, I *know* that my installation steps *should* be sufficient because it works all fine in Docker containers that contain *only* what I instructed them to contain… Maybe I'll need a "real" look into this, see you tomorrow…

**Comment by raphaelm** [comment]
A lot has changed, a lot will change, let's try that again in a few months.

**Comment by laf0rge** [comment]
I'm getting the same 
`compressor.exceptions.OfflineGenerationError:` You have offline compression enabled but key "c0a2acda3c76cefe5aa46a520b92f92a" is missing from offline manifest. You may need to run "python manage.py compress".` all the time. Running the "manage.py compress" command as the pretix user doesn't fix the situation.  The only workaround known so far is to disable COMPRESS_OFFLINE in settings.py.
