### ISSUE TITLE
Allow confirmation of unpaid orders

### ISSUE THREAD

**Issue by pedroarinto** [pretix/pretix#800]
When dealing with national institutions or large companies with complex payment procedures, there is sometimes the need to confirm an order (reserve the seats and inform the client) before the payment is received. Most of the times the payment is received after the event has taken place.
This could be an option in the event configuration to allow confirmation without payment, with a new operation on order management to Confirm the order but flag it as not paid.

**Comment by raphaelm** [comment]
I'm not sure what "confirm" should mean in that case, you can probably get the same effect by extending the payment deadline until after the event. Check-in lists now also support checking in unpaid tickets.

As I'm very much against introducing a new state, I'm closing this for now. Feel free to reopen if I understood incorrectly.

**Comment by pedroarinto** [comment]
The only problem with extending the payment deadline until after the event is that the client always sees his order as "Pending", giving him the wrong impression that he might not be allowed to access the event. But I can see the reasoning behind not introducing a new state and the added complexity that comes with it. 
We will use a combination of extending the payment deadline and adjusting the emails sent to the client (to reflect that a confirmed order might still need to be payed) to get a similar effect and control the real payment outside Pretix.

Thank you.
