### ISSUE TITLE
After update to 1.13, cron gives message about psycopg2 wheel package

### ISSUE THREAD

**Issue by saschafoerster** [pretix/pretix#801]
I am using pretix with docker. The cronjob sends my the following message after every circle:

> /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>  """)

**Comment by felixrindt** [comment]
I think this is fixed in https://github.com/pretix/pretix/commit/2f1ee93e86dc9679c28d4ad746ffb0149070a057, which will be included in the next release.

**Comment by raphaelm** [comment]
Exactly! :)

**Comment by saschafoerster** [comment]
With version 1.13.1, it is still there... just so you know.

**Comment by raphaelm** [comment]
Yeah, we do not change things that are not really bugs between minor versions :) Will go away in 1.14.
