### ISSUE TITLE
Pretix Interface nicht Online

### ISSUE THREAD

**Issue by aquadev90** [pretix/pretix#803]
Ich bekomme die Installation nicht hin, wer ist bereit Pretix gegen aufwandtsentschädigung auf meinen Server zu Installieren?

**Comment by raphaelm** [comment]
Dies ist keine Jobbörse :wink: Mit konkreten Fehlermeldungen kannst du dich hier gerne melden. Für den kommerziellen Support geben wir unter sales@pretix.eu gerne Auskunft.
