### ISSUE TITLE
Simplify reordering of questions

### ISSUE THREAD

**Issue by Janfred** [pretix/pretix#807]
The reordering-process is quite annoying right now because it reloads the page every time I move a question up or down. Especially time consuming is it if you have a lot of questions and you want to move one from the very bottom to the top position.

Possible solutions I have in mind:
* make asynchronous requests and move the question within the web page, making complete reloads unnecessary
* add an number input field (maybe displayed only if a button is clicked) for redefining the order in one step for all questions
* drag-and-drop UI (inplace or in a new view)

**Comment by raphaelm** [comment]
I'm not sure which of the three solutions is the best, so I'm open for more input.

There is an additional challenge, though: If you have more than 25 questions, we currently paginate the list, which makes this even harder.

**Comment by rixx** [comment]
I'd be in favor of dropping pagination (unless you think this will ever be a problem with questions) and using drag'n'drop. UI with number inputs for ordering feel clunky and annoying to me (e.g. Goodreads To Read list interface).
