### ISSUE TITLE
If Attendee Names are not populated it renders the manual search in PretixDroid useless

### ISSUE THREAD

**Issue by Duncanio** [pretix/pretix#819]
The manual search in PretixDroid appears to look up on Order Reference and Attendee Name only.

In the real world if a customer does not have their ticket with them then they will not know the Order Reference.  This leaves the only other look up being Attendee Name but if this was not made a required field when setting up the ticket and it was not filled in, then there is no way of looking up the customer's ticket in the PretixDroid manual search.

**Comment by raphaelm** [comment]
And what exactly is your suggestion?

**Comment by Duncanio** [comment]
:-)  

The simplest (possibly incomplete solution) would be to include email address in the look up.  Isn't this the only real mandatory piece of information that the customer supplies?

When invoice info is included you could default Full Name into them all. 

Or Make Full Name a mandatory field, add it to the section where the email address is and default that.

**Comment by raphaelm** [comment]
> The simplest (possibly incomplete solution) would be to include email address in the look up. Isn't this the only real mandatory piece of information that the customer supplies?

It is, but I thought email information as too sensitive to store it on random Android devices. Happy for more thoughts here.

> When invoice info is included you could default Full Name into them all.

I thought the name from the invoice address is already included in the search -- at least when not using asynchronous mode. But I might be wrong. 

> Or Make Full Name a mandatory field, add it to the section where the email address is and default that.
> I would think a name look up would be preferable.

There is a way to make only the name mandatory and keep the other fields of the invoice address optional, this should suffice.

**Comment by Duncanio** [comment]
Just checked Invoice Name when **not** using Asynchronous mode and yes you are correct the search does look at that (Which is great to know).   But when in Asynchronous mode, it doesn't.

**Comment by raphaelm** [comment]
Should all be better with pretixSCAN soon enough :)
