### ISSUE TITLE
When voucher redeemed - Amending quantities in shopping cart results in item being added with no discount.

### ISSUE THREAD

**Issue by Duncanio** [pretix/pretix#820]
Redeemed a voucher and it put me onto the voucher page, I added the items to my cart and contiued.

![voucher isssue step 1](https://user-images.githubusercontent.com/36608504/37556129-540e33fe-29e9-11e8-9cd1-21826eac86a5.PNG)

Once the new page has been invoked it shows the cart with the items and correct discounts etc.
I then increase the quantity of the highlighted item and it (seemingly incorrectly) adds a new row with the item at the original price rather than the discounted price.

![voucher isssue step 2](https://user-images.githubusercontent.com/36608504/37556139-5b131070-29e9-11e8-8ec3-a06b974d710d.PNG)

Is this the intended behaviour?  If it is, it doesn't seem completely intuitive.

(_Please ignore my change of tax rule to Booking Fee, it's literally a label change_)

**Comment by raphaelm** [comment]
Hmm, it is working as intended, but from a time when every voucher was single-user. For multi-use vouchers, this actually kinda makes sense to improve (i.e. use discounted price if voucher is still valid and full price otherwise).

**Comment by raphaelm** [comment]
Hmm, it is working as intended, but from a time when every voucher was single-user. For multi-use vouchers, this actually kinda makes sense to improve (i.e. use discounted price if voucher is still valid and full price otherwise).
