### ISSUE TITLE
Kontaktinformationen is empty although i gave the email-adress in and arrived one email

### ISSUE THREAD

**Issue by ford42** [pretix/pretix#825]
Hey,

i gave my e-mail adress correct in but the field by Kontaktinformationen is empty ("E-Mail
None").

I arrived an email to these typed in adress.

Thank you and sry for my worse english
Greetings ford

German:
Hey,

ich habe eine E-Mail-Adresse korrekt in das richtige Feld eingetragen, aber in dem Feld Kontaktinformationen bei der Bestellübersicht steht "E-Mail
None"!

Eine E-Mail habe ich zu der eingetragenen Adresse jedoch bekommen!

Vielen Dank
LG ford

**Comment by raphaelm** [comment]
Hi! Which pretix version are you using?

**Comment by raphaelm** [comment]
Or, to make this quicker: THis is fixed in 1.13.1, please reopen if you use that version :wink:
