### ISSUE TITLE
pretix in docker container behind proxy

### ISSUE THREAD

**Issue by fbatschi** [pretix/pretix#826]
I am trying to run pretix as docker container behind an nginx proxy (which does ssl termination).
The pretix docker container (built with the Dockerfile without modifications) does a port forward from 8888 to 80 inside the container.

I configured nginx to use a upstream
```
upstream pretix {
    server localhost:8888;
}
```
and then used it in the location block 
```
        proxy_pass http://pretix;
```

Every requests to the vhost ends in an error 400. the pretix logfile shows a django error 

```
ERROR 2018-03-20 00:01:09,491 django.security.DisallowedHost exception Invalid HTTP_HOST header: 'pretix'. You may need to add 'pretix' to ALLOWED_HOSTS.
```

Apparently the HTTP host header is checked to prevent HTTP HOST header attacks, although there is a wildcard set in `/pretix/src/pretix/settings.py`: 

```
ALLOWED_HOSTS = ['*']
```

A change of ALLOWED_HOSTS to ['pretix'] does not change anything. Besides, the wildcard should work anyways.

If i connect to the container directly at port 8888 i get a normal response, if i use the proxy in front (which send a host header), pretix (or rather django) somehow does not like this.

**Comment by raphaelm** [comment]
You are probably not passing on the Host header. You might want to read [the installation guide](https://docs.pretix.eu/en/latest/admin/installation/docker_smallscale.html#ssl) :wink:

**Comment by fbatschi** [comment]
I am sorry, but I have read the installation guide and I am passing on the host header.
In fact I am using the exact snippet for the proxy configuration from your installation guide.

This is especially the case, as the django error message explicitly references the exact Host header I am sending via nginx. 

The (wildcard) setting in ALLOWED_HOSTS does not seem to work, or rather the ALLOWED_HOSTS setting is not used at all when used behind a proxy. 

I have switched to your official `pretix/standalone` image instead of the self-built one. The error message here is slightly different, but still a HTTP code of 400 (with foo.mydomain.com representing my domain name):

```
ERROR 2018-03-20 10:07:41,666 django.security.DisallowedHost exception Unknown host: 'foo.mydomain.com'
```

Again - I can connect to the container directly via localhost:8345. But using a reverse proxy in front or connecting to foo.mydomain.com:8345 somehow triggers a DisallowedHost exception.

**Comment by raphaelm** [comment]
> I am sorry, but I have read the installation guide and I am passing on the host header.
> In fact I am using the exact snippet for the proxy configuration from your installation guide.

Alright, sorry, that wasn't clear from your description.

> This is especially the case, as the django error message explicitly references the exact Host header I am sending via nginx.

Yeah, the error message seems misleading here. We check host headers differently.

> Again - I can connect to the container directly via localhost:8345. But using a reverse proxy in front or connecting to foo.mydomain.com:8345 somehow triggers a DisallowedHost exception.

Can you check if the ``url=`` setting in your ``pretix.cfg`` config file is correct and the file is read correctly? That is what it checks against.
