### ISSUE TITLE
Autoexpiration of unpaid orders after a 'delay'

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#827]
At the moment you can check this to automatically expire unpaid orders.

![screenshot from 2018-03-20 20-52-32](https://user-images.githubusercontent.com/5970076/37679254-afd31e36-2c80-11e8-9365-df7b5b838f4d.png)

Now here's the problem we encountered: Suppose there is a bank transfer payment for an order that expires on April 1st. That bank transfer arrives on April 1st (in time). We check bank statements (de: Kontoauszüge) every day, but they are always a day behind. That way, we can (at the earliest) mark the order as paid on April 2nd. But by this time, above order has already been autoexpired and new order might have taken it's place in the quota. I think this might be a (rare) problem for others as well.

The best solution I came up with is to replace the "automatically expire" checkbox with an integer field for a delay in days or hours, after which an unpaid order automatically expires. An empty value would mean no expiration and a `0` instant expiration. 

Obviously, an order beeing expired and that order not reserving space in quotas is tied to each other, so we can't change that. Showing a different date to the user might be confusing for (plugin) developers.

What do you think?

**Comment by felixrindt** [comment]
Also, while being at it, one could add a notification type for this automatic expiration. Although again, this might be useful without a delay, as to remind the staff to check on bank statements before the order expires while payment was actually done in time. (Yes, automatic payment detection, we're working on that)

**Comment by raphaelm** [comment]
Uh. I understand the use case and see why this is useful, but it *feels* a bit too much of an edge-case to confuse users even further by making this setting more complicated (non-technical people already have trouble understanding it sometimes). But that's really just a feeling, happy for any other comments.

At the moment, I'm leaning more towards another idea: Just don't check the box in that case, but build a tool for manual bulk-expiry (#134) that supports something like "expire everything with an expiry date before x". This way, you don't couple it to a delay of one day, but you can just manually trigger it after every bank statement import. Feels simpler in terms of settings **and** more failsafe at the same time. What do you think?

**Comment by felixrindt** [comment]
> a tool for manual bulk-expiry

I think that would fit our usecase even better. 
Such a tool could support all kinds of conditions and needs. I'd like to see a detailed writeup at #134 ;-)

**Comment by raphaelm** [comment]
Well, I haven't thought this through any further, so if you want to come up with a proposal before I get around to do a write up, feel free to do so :stuck_out_tongue:
