### ISSUE TITLE
Change "delete event" prerequisite from 0 orders to 0 turnover

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#834]
Thank you for the new option to delete an event if there are no orders (from https://github.com/pretix/pretix/issues/762)
If the prerequisite for deleting an event was changed to a turnover of 0 € ($ or whatever) instead of 0 orders it would become possible to place test orders and experiment with a new installation, while still guaranteeing a strict policy towards financial authorities.

**Comment by raphaelm** [comment]
Nope. Performing an order and then refunding it would be turnover of 0€, but would be problematic to delete from the viewpoint of financial authoritites. Orders must not be deleted under any circumstances.

**Comment by bpcurse** [comment]
Another proposal (although it is probably too complicated): 
If a second prerequisite (0 refunds) was checked along with 0 turnover, would that be acceptable?

**Comment by raphaelm** [comment]
Sorry to be that unwilling to discuss here, but pretix will not be able to delete orders.
