### ISSUE TITLE
Option to delete a user

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#835]
I could not find an option to delete a user from the user overview. If there is none could you support deleting a user in an upcoming release?

Use case: Due to the fact that we are students we have quite a turnover of staff. As personnel changes the user list grows bigger and gets confusing if you cannot delete old users.

**Comment by raphaelm** [comment]
Deleting users is not possible, for reasons of auditability. Every change made somewhere is connected to a user forever. You can disable them and anonymize them, but not delete them, sorry.

**Comment by bpcurse** [comment]
I see the point. What about an archive alternative as it was discussed earlier for whole events? Simply get unused user accounts out of sight and keep the user list clean by moving them to a separate "archived users" list.

**Comment by raphaelm** [comment]
Frankly, I'm not in favour of introducing an additional "archived" field and additional lists, neither for users nor events. There already is an "inactive" field, and I'd happily merge a PR that allows to filter the user list by active/inactive. :)
