### ISSUE TITLE
Getting {"detail":"Authentication credentials were not provided."} when testing the API with Postman

### ISSUE THREAD

**Issue by George-Born-Creative** [pretix/pretix#846]
I apologize if this is not the place to ask for support. I have the pretix app installed on a debian 8 server with Apache and ngnix proxy and the app is running with no issue. I managed to create events, tickets and place test orders but when I tried to test the API with postman I keep getting the {"detail":"Authentication credentials were not provided."} error.
I'm using the authentication token generated from the team's screen in Postman (Bearer Token).

What am I doing wrong?

Appreciate the help in advance.

**Comment by raphaelm** [comment]
I have no idea about postman, so I don't know.

**Comment by George-Born-Creative** [comment]
Thanks, Raphael for responding that quickly. I'm getting the same error even when using javascript fo the request. 

I can see that the API is working https://pretix.icegjobs.com/api/v1/organizers/ICEG/events/gww2017/items/1/

so I'm not sure why I'm getting the authentication error. Any clue?

**Comment by raphaelm** [comment]
Well, you're not sending the token correctly, apparently. You can see the correct Authorization header here: https://docs.pretix.eu/en/latest/api/fundamentals.html#authentication

**Comment by George-Born-Creative** [comment]
Thanks. I found the error and it’s working now
