### ISSUE TITLE
Limit number of characters in one-line-answers (attendee registration)

### ISSUE THREAD

**Issue by Problemkerze** [pretix/pretix#847]
We want to print the company name of the attendee onto our tickets. Sometimes the company name is quite long and the company name won't fit onto the ticket any more.

Thus, it would be great to be able to limit the number of characters in one (or multiline) answers.

**Comment by raphaelm** [comment]
If we do this, I suggest we do it for both one and multiline answers :)

**Comment by felixrindt** [comment]
I think question answer validation could be also done for other types. Think min/max date/time for date/time questions or min/max for number input.

**Comment by raphaelm** [comment]
This has been implemented a while ago
