### ISSUE TITLE
Time limitation does not remove articles from frontend

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#85]
The MRMCD Laufshirt had a time limit set to "02.08.2015 23:59:59" but is still shown in the front end on the 3th of August. How ever, it is not possible to order it, the user is shwon a "out of stock" warning. Shouldn't it be hidden or somehow marked as "unavailable"?

Also: There seem to be some strange dependencies with articles with their limitations/variants. I was not able do disable the MRMCD Laufshirt from the frontend. Even disabling it and removing all variations did not help. There seems to be some issue...

**Comment by raphaelm** [comment]
I pushed several commits that should solve all aspects of the problem. I will deploy them to mrmcd.net soon.
