### ISSUE TITLE
Entry time cannot be set correctly when event starts at 0:00

### ISSUE THREAD

**Issue by d00616** [pretix/pretix#850]
I want to start an event at 0:00. In that case the entry time can only set not earlier than 0:00 at the same day. Creating an entry time earlier is not allowed.

**Comment by d00616** [comment]
I think, [this](https://github.com/pretix/pretix/blob/0ad3ec444c458017e90a0688112f0d563a4eeae6/src/pretix/control/forms/event.py#L239) is the line, which have to be changed.

**Comment by raphaelm** [comment]
Thanks!
