### ISSUE TITLE
Pass database options via configfile

### ISSUE THREAD

**Issue by ni-le** [pretix/pretix#857]
Having installed pretix in a shared hosting environment, I'm not able to change the default storage engine of the mysql instance from MYISAM to INNODB.
Thus I always receive an `_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')` error on migration, when not manually adding `'OPTIONS': {'init_command': 'SET storage_engine=INNODB;'}` to settings.py after updates.

I would love to see a possibility to pass options from pretix.cfg

**Comment by raphaelm** [comment]
I'm not opposed against passing config options in general, but… if your MySQL defaults to MYISAM, you should use a more recent version of MySQL ;) Both MySQL 5.5.5+ and MariaDB 10.2+ default to InnoDB.

**Comment by destruktomatik** [comment]
Sure thing, unfortunately I'm tied to the hosters view on that version dilemma at the moment... ;)
