### ISSUE TITLE
Add event name to admin notification

### ISSUE THREAD

**Issue by jfwiebe** [pretix/pretix#861]
When recieving an admin notification, e.g. when an order is placed, only the order number is displayed in the mail. It would be great to also see the event, right now you have to look it up in the "Detail" button url.

I thought this could be an easy task by adding `n.add_attribute(_('Event'), order.event.name)` to `src/pretix/base/notifications.py`, but unfortunately I was not successful.

Thanks for your work!

**Comment by raphaelm** [comment]
Good point.

What was your problem exactly? Can you try ``n.add_attribute(_('Event'), str(order.event.name))``?

**Comment by jfwiebe** [comment]
I had some caching issues, but they are fixed now.
![grafik](https://user-images.githubusercontent.com/6865786/38527928-9f509bf0-3c5d-11e8-9231-83079a71de29.png)
Have a look at #862. :)
