### ISSUE TITLE
[Improvement]  custom time delta for warning that the order is about to expire

### ISSUE THREAD

**Issue by Speedy1991** [pretix/pretix#867]
My usecase:
- Creating an event for next week (yea we have many/only shorttime events)
- Set payment term in days to 1 day before the event

When creating an event with a really low "Payment term in days" the user get's an order email + an email with the warning that the order is about to expire.
This confuses some of our customers.
It would be great, if I could define a day delta for each event myself (for sending of the expire email)  or switch it off completely if it's set to 0.

**Comment by raphaelm** [comment]
You can switch of reminder emails by setting them to ß
