### ISSUE TITLE
presale: HTML div encapsulating main container and footer

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#871]
I'm experimenting with some simple custom css styling to adhere to some corporate identity rules. I want to have a background image on the left and right side. I therefore want to limit the width of the main container div and the footer. 

It would be much (much!) easier to have both of them in a "content column div" and apply styling to that, especially since I want shadows for the whole column.

As this (as far as I know) wouldn't hurt any existing behavior, I think changing this in Pretix core could be possible.

**Comment by raphaelm** [comment]
I don't see an immediate problem with this either, feel free to create a PR and let's discuss any possible implications there.

**Comment by felixrindt** [comment]
Would be much simpler to move the footer from `body` into the upper level bootstrap `.container`.
