### ISSUE TITLE
Widget: Event series without specifying subevent

### ISSUE THREAD

**Issue by mgrandl** [pretix/pretix#878]
I really want the user the be able to select which subevent they want to attend, which is not possible with the current widget. For some reason if the user doesn't select a ticket, then clicks on buy, he gets the option to select which subevent they want to attend. That's how I imagine the widget for event series without specified subevents should look like.

**Comment by raphaelm** [comment]
You are correct, this is currently not supported by the widget and would be nice to have.

**Comment by mgrandl** [comment]
@raphaelm Ok. I am familiar with vue. If you want I can try and setup a pull request?

**Comment by raphaelm** [comment]
If you want, feel free to go ahead and create a pull request, sure. It probably won't be that easy, though, especially if we (like the non-widget version) want to support a calendar-like view in case of a large number of sub-events. But having a list view would be a good start at least.

**Comment by raphaelm** [comment]
I'm also not sure if there's an API available supplying the required data for this, so we'd probably need a second API view for the widget, similar to ``WidgetAPIProductList`` (but simpler).

**Comment by mgrandl** [comment]
Well apparently some API has to be supplying it right? Since the list of subevents appears as soon as you click buy...

**Comment by mgrandl** [comment]
@raphaelm can you point me to where to code for the widget is maintained?

**Comment by raphaelm** [comment]
> Well apparently some API has to be supplying it right? Since the list of subevents appears as soon as you click buy...

I assume that happens in the iframe that is opened.

> @raphaelm can you point me to where to code for the widget is maintained?

Sure, that is mostly in
* pretix/static/pretixpresale/js/widget/widget.js
* pretix/presale/views/widget.py

**Comment by simonbensoussan** [comment]
hi,
I am student in CS i would like contribute, where i should start ? I  have some knowledge in django, your project seems cool and i would like help.
Thk :)

**Comment by raphaelm** [comment]
Hi @sims34, I think @mgrandl is taking a look at this (also, this requires more Vue knowledge than Django knowledge) :)

**Comment by mgrandl** [comment]
@raphaelm I just used to REST API to achieve a proper frontend for now... To be honest, I am a little confused by the widget code lol. @sims34 If you wanna give it a shot, go for it!

**Comment by sims34** [comment]
Hi,
I forked the project but i didn't find the code of the widget, where is it ? what is the file ?
about Vue i can help.
Thk best regards

**Comment by mgrandl** [comment]
@sims34 

- pretix/static/pretixpresale/js/widget/widget.js
- pretix/presale/views/widget.py

**Comment by sims34** [comment]
hi @mgrandl 
Thk for the links i'm going to take a look, if i can do something 
Bye

**Comment by felixrindt** [comment]
Hey @sims34 @mgrandl are you still working on this?

**Comment by sims34** [comment]
Hi @felixrindt 
Sorry i was busy, i didn't start yet. 
Just for Information if you are some issues about Vue.js in Front i can provide some helps.
thanks

**Comment by raphaelm** [comment]
See #1223
