### ISSUE TITLE
Link in Pretix update reminder E-Mail leads to 404 error

### ISSUE THREAD

**Issue by bpcurse** [pretix/pretix#879]
In the automatically generated pretix update reminder E-Mail the link to the blog presents a 404 error.

"Neuste Informationen über Updates finden Sie immer im pretix.eu-Blog:"
https://pretix.eu/about/de/news/

**Comment by felixrindt** [comment]
I changed the [relevant translation](https://translate.pretix.eu/translate/pretix/pretix/de/?checksum=df4fc3ac4ab25833) to point to `/about/de/blog/` instead of `/about/de/news/`.
