### ISSUE TITLE
Widget does not embed image correctly

### ISSUE THREAD

**Issue by v0tti** [pretix/pretix#887]
If there is an product image, it is not displayed correctly if the widget is embedded on a site with a different base URL.
This issue can be seen here: https://www.fem.tu-ilmenau.de/ressorts-projekte/aktive-projekte/fiwak/fiwak-2018/
The browser tries to get the image at "/media/pub/thumbs/ac2ac7d85b24756d890ab728bfdf1806.60x60c.png" which would expand to "https://fem.tu-ilmenau.de/media/pub/thumbs/ac2ac7d85b24756d890ab728bfdf1806.60x60c.png". The pretix is running at tickets.fem.tu-ilmenau.de, so it should be linking to "https://tickets.fem.tu-ilmenau.de/media/pub/thumbs/ac2ac7d85b24756d890ab728bfdf1806.60x60c.png"

**Comment by raphaelm** [comment]
This appears to be a regression introduced in e7458f30

**Comment by v0tti** [comment]
Thanks for the fast fix! Will there be a new release? We will start to sell tickets tomorrow and it would be nice to have that image working :).
(Running a small scale docker installation)

**Comment by raphaelm** [comment]
Given that 1.15 is scheduled will be released some time towards the end of this week, I don't think I'll be issuing a 1.14.1 for this, sorry!

**Comment by raphaelm** [comment]
You can always use the :latest docker tag, of course, which builds of git master, at your own risk :wink:

**Comment by v0tti** [comment]
Thats ok ;). Thanks!
