### ISSUE TITLE
How do I add a language?

### ISSUE THREAD

**Issue by JoooostB** [pretix/pretix#888]
In the docs you're only referred to https://translate.pretix.eu, where I downloaded the necessary Dutch translation and pasted it in /usr/share/locale/nl/. Unfortunately, the extra language doesn't pop-up in the dropdown menu; only English, German & German-informal are available still. What I've done for a workaround is placing the Dutch language files in the German folder. Unfortunately, this still results in the wrong flag being shown and missing words are still in German (which I would want in English). What am I missing in the process of adding a language?

**Comment by johan12345** [comment]
As shown in the [documentation](https://docs.pretix.eu/en/latest/development/translation/index.html) languages are divided into three categories depending on the current status of the translation. Dutch is currently one of the incubating languages, so it's not shown by default in production mode.

Here is the location where the language categories are configured:
https://github.com/pretix/pretix/blob/ce68f52ca00fe73aed471dcbc24e8b41547d1dd8/src/pretix/settings.py#L362
So if you remove dutch from the incubating languages list, it should show up in the selection.

**Comment by raphaelm** [comment]
Johan is most correct :) nl support for core is currently at 37%, I don't think it's of much use at that point, so we do not expose it in production yet.
