### ISSUE TITLE
Payment due dates at the end of a presale

### ISSUE THREAD

**Issue by abrock** [pretix/pretix#89]
I ordered a bambini ticket for testing (and cancelled it later) (2015RULSE) and the email I got tells me that I have until 08/20/2015 to pay it, but the presale ends on 08/16/2015 and we want the money until 08/18/2015

**Comment by raphaelm** [comment]
Yes, I know (tested at the same time like you), it's a fuckup and I'll call the t-shirt print shop on tuesday (our guy there is in holiday until and including monday) to find a way to resolve it. I also already changed the configuration.
