### ISSUE TITLE
Configurable subevent ordering

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#898]
At the moment, subevent ordering mainly depends on their start date. This is not always the most intuitive, e.g. when there are events in two different locations at various times and people mainly decide which event to attend based on the events location. If the subevents where grouped by in this case location, it would be easier to find the desired subevent in the list on the presale page.

We could

- make the subevent positions configurable in a per subevent basis (like in many other places in pretix, where paginated item list items can be reordered), or
- provide functionality to chose an ordering method (by event start, event name, location->name, ...)

What do you think?

**Comment by raphaelm** [comment]
> make the subevent positions configurable in a per subevent basis

I'm not sure this is a good idea, it seems like it will create unexpected behaviour to most users.

> provide functionality to chose an ordering method (by event start, event name, location->name, ...)

Yes, that sounsd better.

**Comment by felixrindt** [comment]
Ok, lets create a setting that influences the sorting behaviour in subevent lists on the presale page.
Sorting for this happens in this line of a property function called from a template:
https://github.com/pretix/pretix/blob/1ee584c5a1e7b041d94add6b410f5025d7e379bd/src/pretix/base/models/event.py#L536

My plan is to create a setting for this under Eventsettings->Display. I'm not sure where to put the logic for which sorting tuple to use though. (The setting value might be `'name__asc,date_from__asc'`. How and where is this 'translated' to the tuple we can pass as argument to `order_by`.)
