### ISSUE TITLE
Very slow Docker startup on small machines

### ISSUE THREAD

**Issue by v0tti** [pretix/pretix#899]
At default the Docker container spawns 10 gunicorn processes at startup. This seems to significantly slow down machines with only few CPU cores. Therefore this should be configurable or lower at default.

**Comment by raphaelm** [comment]
Hmm, the gunicorn-docs recommend 2-4 times the number of CPUs. Do you think something like the following could make sense?

```
NUM_WORKERS=$((2 * $(nproc --all)))
```

**Comment by raphaelm** [comment]
(I don't see an easy way to make this configurable right now)

**Comment by v0tti** [comment]
I would have to try it, but it seems more reasonable this way.
