### ISSUE TITLE
Make products/orders that are not cancelable

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#91]
May be there are some products which shouldn't be cancelable?

**Comment by raphaelm** [comment]
Orders can only be cancelled before they are paid. So, introducing non-cancelable items only make sense if you're really going to forcefully collect the money for unpaid orders. 
I agree that this makes sense for some events and should be possible.

**Comment by raphaelm** [comment]
To implement this, the following steps are required:

* Add a boolean property as ``allow_cancel`` to the ``Item`` model that defaults to ``True`` and create a migration
* Add this property to the item editing form
* Add an appropriate check to ``Order.can_user_cancel``

If someone wants to tackle this as his or her first issue in the project, do not hesitate to ask me questions if you get stuck!
