### ISSUE TITLE
Send ticket as attachment

### ISSUE THREAD

**Issue by JoooostB** [pretix/pretix#917]
I'm about to go live with a ticketshop when I tested it from start to end and came to the conclusion tickets can only be downloaded through an URL. Is it possible to get the pdf tickets as an attachment in the email?

**Comment by raphaelm** [comment]
Currently not. We know the feature would be good, but it's a problem of timing: The order confirmation and payment mails are both sent before the tickets are generated.

**Comment by hno2** [comment]
I would +1 this.

**Comment by JoooostB** [comment]
Love to see that you guys implement user suggestions, 10/10 would use again!
