### ISSUE TITLE
[My mistake] Organizer calendar show no events

### ISSUE THREAD

**Issue by s33d3r** [pretix/pretix#919]
Events are not showing on organizer calendar neither list view.
Tested on docker installation using auto-install script.

**Comment by raphaelm** [comment]
Is the event both live and marked as "show in public lists" in the event settings?

**Comment by s33d3r** [comment]
I think it's marked but I'll take a look as soon as I get home in a few hours.

**Comment by s33d3r** [comment]
Can't believe I didn't see the option to show in public lists before. Sorry for the inconvenience.
