### ISSUE TITLE
[Question] Security in installation

### ISSUE THREAD

**Issue by s33d3r** [pretix/pretix#920]
In the tutorial script for docker installation it says there are unsafe defaults such insecure hardcoded passwords and other things. What are these unsafe things. And what should be changed to be possible to use this great software in production?

**Comment by raphaelm** [comment]
Hmm, not sure what you're refering to exactly, most likely the security of the redis server? That would require to look into redis setup tutorials ;)

**Comment by s33d3r** [comment]
Talking about this:
https://github.com/pretix/pretix-test-tutorials
It's just the manual instructions implemented right? So the manual instructions for deployment should have the warning too.
It's just the red is config that need edits?
Are the file permissions ok?
