### ISSUE TITLE
Enable searching of tickets by QR-code secret

### ISSUE THREAD

**Issue by b-schweiger** [pretix/pretix#928]
We've had issues, where some participants posted images of their tickets including the QR code on social media. Since they now may be used by anybody, we want to cancel that ticket. If the ticket is part of a multi ticket order, there is no way to identify which ticket to cancel (at least, I didn't find any way). 
So we would propose a search feature for QR code secret, possibly in the check in list section.

**Comment by raphaelm** [comment]
Good idea.

P.S.: You don't even need to cancel it, in the form used to change email addresses you can trigger the generation of a new secret.

**Comment by b-schweiger** [comment]
Addition: The form used to edit products of an order should also show the QR-Secret. That way it would be possible to manipulate a specific ticket. 

The generation of new QR Secrets wouldn't work for our use case: We have large orders with 50+ tickets we give as physical tickets to resellers. Generating new secrets for the whole order would invalidate them all.

**Comment by raphaelm** [comment]
I just pushed a number of changes that should help here :) You can now search, regenerate and see the secrets of single tickets.
