### ISSUE TITLE
Show more details in "order details"

### ISSUE THREAD

**Issue by Unicorn-rzl** [pretix/pretix#93]
There are more information that could be displayed on the order detail page:
-Order date & time (or better a order history, ordered on day x, payed on day z, downloaded day y, etc)
-Account/Emailadress used

**Comment by raphaelm** [comment]
An order history is a nice idea, but would not look that good as it would always be very short, it would mostly consist of "ordered" and "paid". We currently do not track ticket downloads and I don't see a real reason to do so. I will instead introduce a box with general information that will also contain order and payment date.
