### ISSUE TITLE
Trying to run pretix on kube with ingress controller, help pls :)

### ISSUE THREAD

**Issue by sokoow** [pretix/pretix#933]
Hi All,

I don't know if somebody ever ran pretix on kubernetes yet, but here's my challenges trying to do it with ingress controller. So my setup looks as follows : internet -> traefik ingress controller on kube (SSL ACME) -> node/pods (nginx + gunicorn/uwsgi, plain http).

I'm getting a lot of these in logs:

```
ERROR 2018-05-31 00:56:20,802 django.security.DisallowedHost exception Unknown host: 'xxx.yyy.zzz:443'
ERROR 2018-05-31 00:56:20,802 django.security.DisallowedHost exception Unknown host: 'xxx.yyy.zzz:443'
ERROR 2018-05-31 07:31:19,310 django.security.DisallowedHost exception Unknown host: 'xxx.yyy.zzz'
ERROR 2018-05-31 07:31:19,310 django.security.DisallowedHost exception Unknown host: 'xxx.yyy.zzz'
```
I've following set in my config:

```[pretix]
url=https://xxx.yyy.zzz
```

So everything should be ok right ? I've also seen ALLOW_HOSTS = ['*'] in your settings.py. Any ideas how to fix that ?

**Comment by raphaelm** [comment]
You're proxy is probably not passing the Host header correctly.

**Comment by sokoow** [comment]
it was something else - config file wasn't being picked up, even after setting PRETIX_CONFIG_FILE path, strange. I put pretix.cfg into /etc/pretix folder and it started working
