### ISSUE TITLE
Date of the Event in one line

### ISSUE THREAD

**Issue by HDValentin** [pretix/pretix#934]
The beginning and end date of the event is shown in five lines:
"22.–23. September 2018
Beginn: 09:00
Ende: 17:30
Einlass: 08:00
Zum Kalender hinzufügen"

Is ist possible to show it in one line? Like this:
"22.–23. September 2018 | Beginn: 09:00 Uhr | Ende: 17:30 Uhr | Einlass: 08:00 Uhr | Zum Kalender hinzufügen

There could be a switch in the configuration "compact date" and "normal date"

**Comment by raphaelm** [comment]
I'm not sure it would actually be more readable, but it might be worth trying it out. Either way, we'll not have a configuration flag for this, there will be one way going forward :)

**Comment by HDValentin** [comment]
the date would not be better readable. But it would save four lines of space. This would give the products more weight (viewability and usability).

**Comment by strudra** [comment]
Can I take a shot on this one? First contribution, though.

**Comment by raphaelm** [comment]
@strudra  Very much so, go ahead, if you're still  interested! Sorry for the late reply, I was still travelling.

Keep in mind that we've been still discussing if this is a good idea, so please be prepared that we might say we don't want to make the change after all when we see the result, but seeing the result would certainly be useful and it shouldn't be too much effort to prepare it.

**Comment by HDValentin** [comment]
@raphaelm @strudra probably an option in the settings would be nice. Like "compact view" "extended view"

**Comment by raphaelm** [comment]
No, I'm against a settings option for this. It is trivial, and we have way to many settings options already, it just gets ever more confusing to newcomers :)

**Comment by raphaelm** [comment]
I don't think we'll change this. Too complex with the many different variations possible.
