### ISSUE TITLE
Heading of Tickets have different sizes

### ISSUE THREAD

**Issue by HDValentin** [pretix/pretix#935]
The text size and weight is different for tickets with variants compared to the tickets without variants.

Please change size and weight at the tickets with variants.

Example is attached.
![screenshot 2018-05-31 23 55 21](https://user-images.githubusercontent.com/1276955/40810539-5c4f8128-652e-11e8-9bab-fe1fe777f119.jpg)

**Comment by raphaelm** [comment]
It's just the weight, the size is the same (14px). The margin above the text below "Aktuell verfügbar" is intended, as this is a different kind of information than a product description. We'll fix the weight :)
