### ISSUE TITLE
“Paid tickets per quota” does not show paid orders count for unlimited quota

### ISSUE THREAD

**Issue by rimi-itk** [pretix/pretix#940]
In the Event overview (/control/events/), the “Paid tickets per quota” column shows the “pending orders“ count rather than the “paid orders“ count for quotas with unlimited total capacity.

The pending orders count is assigned to the quota's `cached_availability_paid_orders` property in https://github.com/pretix/pretix/blob/master/src/pretix/base/models/items.py#L1014, but it's not clear to me if this is a typo or deliberately.

Is the pending orders count used by design or by mistake?

Best regards,
Mikkel

**Comment by raphaelm** [comment]
This looks a lot like a typo to me.
