### ISSUE TITLE
Internet explorer: frontpage styling needs word-wrapping

### ISSUE THREAD

**Issue by perthaarhus** [pretix/pretix#941]
Hi 

The word wrapping when logged in on the front page (https://billet.aarhus.dk/control/) doesn't make the line-shift proberly in Internet explorer 11. It is seen with both the 2 colloum and 4 collum window size, if the window is smaller.

I'm not sure where this should be fixed and if it effects other pages. I haven't found errors other places though.

/Pernille

**Comment by raphaelm** [comment]
Could you maybe supply a screenshot of the behaviour? :)

**Comment by perthaarhus** [comment]
Here is an example where you can see it in word wrapping is not when we have very long texts 
![image](https://user-images.githubusercontent.com/13046592/41154786-8f9dd032-6b1b-11e8-9093-b00458d2170c.png)

**Comment by raphaelm** [comment]
We're no longer fixing backend bugs in IE11, so we don't need to keep this open
