### ISSUE TITLE
Voucher handling

### ISSUE THREAD

**Issue by steviehs** [pretix/pretix#946]
Maybe it is just my wrong understanding how to use vouchers: I generate a list with let's say 20 entries and want to send one voucher to every VIP I would like to invite to my party. Right now, I see no alternative than to hold a list aside from pretix, which VIP got which voucher... Wouldn't the control of such a list not be a nice part of pretix?

BR
 Steve

**Comment by raphaelm** [comment]
You can of course put in in the comments/tags of the vouchers, but no, there's no perfect way for that yet. Happy for ideas on how to approach this.

**Comment by raphaelm** [comment]
possible by now
