### ISSUE TITLE
[question] Export check-in-lists without e-mails

### ISSUE THREAD

**Issue by perthaarhus** [pretix/pretix#947]
Is it intended that the registered e-mail is not a selection on the check-in list on "Event => Orders => Check-in list (CSV)" and "Event => Orders => Check-in list (PDF)"

Could it maybe be possible to make it a selection if the user would like to export e-mails as well?

The question rises as our check in managers would like to eg compare e-mails and t-shirt sizes, as we do not plan to ask for attendee names on every order. Order-number is a bit harder for the customer to know of by heart.

**Comment by raphaelm** [comment]
Currently, the column is included if (and only if) email addresses are collected per attendee, not per order. We'll look into this.

**Comment by raphaelm** [comment]
I was wrong, it will be included always with 1.17.
