### ISSUE TITLE
Restrict payment method to countries

### ISSUE THREAD

**Issue by Problemkerze** [pretix/pretix#954]
Bank transfers are difficult to handle and we'd like to restrict payment by bank transfer / invoice to certain countries.

We really want to use the bank transfers (at least within Schengen) because usually we don't have to pay any fees other than when we work with Stripe or PayPal.
Two (real) examples of the disadvantages of bank transfers:
A person from Nigeria registers and gets an invoice. He uses the invoice as invitation letter to get a visa. We never see the money nor do we see him.
A company from abroad pays its invoice but deducts the bank charges.

**Comment by raphaelm** [comment]
Sure, those are real inconveniences. We're currently changing the way payments work technically alltogether, so we're not touching other payment-related things at the moment to avoid conflicts, but later, this might be an interesting addition.

**Comment by raphaelm** [comment]
Fixed by now :)
