### ISSUE TITLE
Wrong count of orders on dashboard

### ISSUE THREAD

**Issue by bobapple** [pretix/pretix#955]
The dashboard of an event may show `0 Attendees (ordered)` and `0 Attendees (paid)` even though there are paid orders. I noticed this after the upgrade to `1.16.0` and only on one certain event. I don't know what info to provide so this can be debugged. Please let me know how I can help.

**Comment by raphaelm** [comment]
We need to differentiate:

* Orders
* Order positions, which can by multiple per order
* Attendees, which are the subset of order positions using products which have the "allows admission" flag

I agree that this is not perfectly clear, but I'm not sure how to make it clearer. Having "1000 Attendees" on the dashboard even though you sold 500 tickets and 500 t-shirts would be just as confusing.

Please feel free to reopen if this does not explain your observation and if you think there's a real error in counting :)

**Comment by bobapple** [comment]
I re-checked the event and it was indeed the `is an admission ticket` flag that was missing. Thank you!
