### ISSUE TITLE
Centralize all payments

### ISSUE THREAD

**Issue by pedrohills** [pretix/pretix#956]
Is there any way to centralize all payments into a single Stripe account?

**Comment by raphaelm** [comment]
Sure, you can enter the same stripe account for all events :)

**Comment by pedrohills** [comment]
@raphaelm thanks for answering
How can I remove this option so that it can not be modified?

My goal is to receive all payments and then make the transfer to the event organizer.

**Comment by raphaelm** [comment]
Sorry, you can't, except by writing your own payment provider.

**Comment by pedrohills** [comment]
Could you recommend someone or some company that could do this service?

I always try to contact the pretix team directly by email sales@pretix.eu, but there is an immense delay to get a response...

**Comment by pedrohills** [comment]
Thanks for the answer.

I'll send a message by e-mail with details.

**Comment by pedrohills** [comment]
The message was sent a few hours ago ...

**Comment by raphaelm** [comment]
Yeah, I got it. I'm not sure how you're expecting us to answer mails within a few hours on a Friday night.
