### ISSUE TITLE
EPC-QR-Code / Girocode

### ISSUE THREAD

**Issue by 0xErnie** [pretix/pretix#957]
Girocode enables the user to copy all transaction details into their banking app via a QR Code.

This could make paying by wire transfer much easier, for some.

https://de.wikipedia.org/wiki/EPC-QR-Code

**Comment by johan12345** [comment]
Good idea!

There seem to be two competing, incompatible standards here: The EPC QR Code that you linked and [BezahlCode](http://www.bezahlcode.de/). Maybe one would need to support both...

**Comment by raphaelm** [comment]
Yup! Downside: Currently, the banking details are entered as free text by the organizer, so we don't know what the IBAN is and what the BIC is etc. This is for reasons of internationalization, banking just works differently everywhere. Still a very valid proposal, but therefore not as easy as it looks.
