### ISSUE TITLE
PDF password encryption

### ISSUE THREAD

**Issue by enyachoke** [pretix/pretix#958]
Hi thanks for the good work. While working with pretix I had a request to protect the ticket with a password and I had to modify the ticket out put plugin to encrypt the pdf and send the password via email. Could it be possible to add this as an option so someone does not have  to modify the core or make a new plugin just to support this.

**Comment by raphaelm** [comment]
Hi! Thanks for the idea. Out of curiosity: Why would you want to do that?

**Comment by enyachoke** [comment]
@raphaelm  Am deploying pretix for an Event organizer and I had to add customization for them  so they raised an issue that someone could get access to the links for the ticket download and steal the tickets. Not a major issue to me but the seem really intent of having so I kinda just modified the ticket out plugin to support it.

**Comment by raphaelm** [comment]
CLosing this for now, as I think it belongs in its own plugin instead of core
