### ISSUE TITLE
Payment proceed not possible if credit card was selected

### ISSUE THREAD

**Issue by thomic** [pretix/pretix#963]
At this instance:
https://presale.mrmcd.net/mrmcd/2018/checkout/payment/

stripe is used as CreditCard provider and wants to load some JavaScript even if you click on "Credit card" payment by accident.

As soon as you clicked on the "Credit Card" as payment method, the "Proceed payment" button is greyed out - if you than answer the question with "Ok, bank transfer" you still cannot proceed with payment as button stays greyed out and disabled - so you need to go back and forth to get the payment proceeded.

(Javascript of stripe was disabled for this test via NoScript)

**Comment by raphaelm** [comment]
Hi,

thanks for reporting!

I moved this over to the respective repository: https://github.com/metarheinmain/pretix-reluctant-stripe/issues/1

I'm not sure how much attention I want to give to *partially-disabled* JavaScript, but if it's an easy fix, I'll do it :)
