### ISSUE TITLE
Show invoice address name in check-in list export

### ISSUE THREAD

**Issue by Pokerkoffer** [pretix/pretix#966]
Hi there,
the name of the person who bought a ticket is missing in the check in list, exported via Orders -> Export -> Check in list (CSV).

The option "Sort after names" is checked.

I deactivated the "Ask for attendees name" field, the name is only required for the billing, because i only want a name per Order, not per ticket and this option is missing. It there a possibility to use the Billing name?

Additionally, maybe you can add a feature that requires only one name per order, regardless of how many tickets have been ordered.

Thank you!

**Comment by raphaelm** [comment]
> I deactivated the "Ask for attendees name" field, the name is only required for the billing, because i only want a name per Order, not per ticket and this option is missing. It there a possibility to use the Billing name?

Well, in that case the name is associated to the order, not the attendee, and is therefore not listed there. We could fall back on invoice address names here, true.

> Additionally, maybe you can add a feature that requires only one name per order, regardless of how many tickets have been ordered.

That's exactly what happens if you require invoice names but not addresses in the invoice settings.

**Comment by Pokerkoffer** [comment]
> Well, in that case the name is associated to the order, not the attendee, and is therefore not listed there. We could fall back on invoice address names here, true.

That would be a great feature :)

> That's exactly what happens if you require invoice names but not addresses in the invoice settings.

Yes thats true, but as said above, the name is missing in the check in lists and others.

Thanks for the feedback!

**Comment by raphaelm** [comment]
Fixed by now
