### ISSUE TITLE
Using PostGis

### ISSUE THREAD

**Issue by enyachoke** [pretix/pretix#967]
So am writing a custom plugin that listen for changes to the events model especially the location field and geocodes it to a location with actual gis points. I want to create a custom location model with geodjango and link it to an event this will give me the ability query for events within a given radius. I had to switch the database engine to django.contrib.gis.db.backends.postgis and ran the migration and created sample data just okay. Could this be added as an option when configuring  the database or is it too specific to benefit the community?

**Comment by raphaelm** [comment]
I think I would merge a PR that allows to specify generic database backends, i.e. ones that are not inside ``django.db.backends.*``. Maybe we could just check if the backend given in the configuration file contains a ``.`` and if so, treat it as a fully qualified module.

**Comment by raphaelm** [comment]
Also: Are you planning on releasing that plugin? Sounds pretty interesting :)

**Comment by enyachoke** [comment]
Am thinking of handling this similar to the way you have handled galera since it will needs addition of  django.contrib.gis to installed apps for it work anyway what do you think ? . Also just out of curiosity the way you discover and register plugins, is something django does or you wrote some custom code to make it possible. It is very cool.

**Comment by raphaelm** [comment]
> Am thinking of handling this similar to the way you have handled galera since it will needs addition of django.contrib.gis to installed apps for it work anyway what do you think ?

Hmm, well, in that case we'd need a special case here. I don't like it, but I guess I'm okay with it. Note however that you can also use your own settings.py in production, e.g. we have a file called ``production_settings.py`` in our deployment that looks like

```
from pretix.settings import *

MIDDLEWARE += [
    'pretixeu.middleware.ProductionMiddleware'
]
```

and then start pretix with ``DJANGO_SETTINGS_MODULE=production_settings``. So this might be another way to avoid cluttering the settings.py with special cases for unpublished plugins ;)

> Also just out of curiosity the way you discover and register plugins, is something django does or you wrote some custom code to make it possible. It is very cool.

That is custom :) You can watch me explain it here: https://www.youtube.com/watch?v=5NxRdzLTFik

**Comment by enyachoke** [comment]
Thanks @raphaelm  for this. I really wanted to be able to avoid touching the core when customizing the application this will really help.
