### ISSUE TITLE
Error message should default to language of the script

### ISSUE THREAD

**Issue by flourish86** [pretix/pretix#976]
https://osmc.de

We is the widget on our site. The max no of tickets is set to 10.

If you enter a > 10 Tickets to purchase, you expectedly get an error message. The problem is, that it's in German.

We integrated the English version of the script, and all other text is in English as is defined in the event settings.

![screen shot 2018-07-30 at 12 58 57](https://user-
images.githubusercontent.com/6977434/43393720-564df4fa-93f8-11e8-9219-84255e2f8bbf.png)

![screen shot 2018-07-30 at 12 33 18](https://user-images.githubusercontent.com/6977434/43393469-8cad8f02-93f7-11e8-8441-19299efe78c1.png)

**Comment by R9295** [comment]
@raphaelm I can take this up.

**Comment by raphaelm** [comment]
should be fixed by now
