### ISSUE TITLE
Invoice date: today

### ISSUE THREAD

**Issue by johnjohndoe** [pretix/pretix#984]
I just clicked on `Request invoice` to generate an invoice for a conference (MRMCD 2017) which took place a year ago. In the generated PDF the `Rechnungsdatum` shows today's date. I would have expected the date when I actually paid the ticket. Putting today's date might be misleading or even wrong when the invoice is used for a tax report.

**Comment by raphaelm** [comment]
This is intended behaviour. The issuing date of an invoice is the day the invoice is written, not the day of payment.

> Putting today's date might be misleading or even wrong when the invoice is used for a tax report.

On the contrary. It would be wrong to create an invoice with a date of 2017 today, since it wouldn't be included in the 2017 tax documents that have already been filed.

**Comment by johnjohndoe** [comment]
Offtopic: Do you know if is still legal to add the in 2018 generated invoice to the tax report for 2017 since the event and payment took place at that year?

**Comment by raphaelm** [comment]
I'm not a tax lawyer, I have no idea. In Germany, I'd say that it at least depends a lot on the type of tax report you are filing. As a small company like ours, income tax is to be paid in the timeframe of the payment, while sales tax is to be paid in the timeframe of the execution of services or the invoice, depending on whatever. ;)

**Comment by johnjohndoe** [comment]
🤯
