### ISSUE TITLE
python3.7 async keyword breaks module name

### ISSUE THREAD

**Issue by felixrindt** [pretix/pretix#993]
When trying to import the file `pretix/src/pretix/base/services/async.py`, a syntax error is thrown when using python 3.7 (which is supported as per [Python 3.4 or newer](https://docs.pretix.eu/en/latest/development/setup.html))

      File "/home/felix/projects/pretix/src/pretix/base/services/invoices.py", line 24
        from pretix.base.services.async import TransactionAwareTask
                                      ^
    SyntaxError: invalid syntax

I guess changing the module name should fix it.

**Comment by felixrindt** [comment]
I renamed all these occurrences of "async" to tasks. I can submit a PR if you want.

**Comment by raphaelm** [comment]
Yeah, that would be great! :)

**Comment by felixrindt** [comment]
As we are breaking compatibility anyway, we could also remove https://github.com/pretix/pretix/blob/master/src/pretix/presale/views/async.py right? Or is there still a reason this exists in the presale app?
